<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AppTranslation;

class AppLanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $englishTranslations = [
            "about_app" => "About App",
            "ai_setup" => "AI Setup",
            "app_preferences" => "App Preferences",
            "blog" => "Blog",
            "business" => "Business",
            "catalogue_setting" => "Catalogue Setting",
            "category" => "Category",
            "category_posts" => "Category Posts",
            "choose_plan" => "Choose Plan",
            "custom" => "Custom",
            "days_left" => "Days Left",
            "downloads" => "Downloads",
            "edit" => "Edit",
            "faqs" => "FAQs",
            "festival" => "Festival",
            "frames" => "Frames",
            "free" => "Free",
            "help_support" => "Help & Support",
            "home" => "Home",
            "more" => "More",
            "my_businesses" => "My Businesses",
            "new_custom_posts" => "New Custom Posts",
            "new_posts" => "New Posts",
            "news_updates" => "News & Updates",
            "no_categories_found" => "No Categories Found",
            "no_festivals_found" => "No Festivals Found",
            "no_templates_yet" => "No Templates Yet",
            "notifications" => "Notifications",
            "partner_dashboard" => "Partner Dashboard",
            "partner_program" => "Partner Program",
            "preferred_languages" => "Preferred Languages",
            "privacy_policy" => "Privacy Policy",
            "products" => "Products",
            "quick_start" => "Quick Start",
            "refund_policy" => "Refund Policy",
            "report_problem" => "Report a Problem",
            "search_categories_festivals" => "Search Categories & Festivals...",
            "search_templates_categories" => "Search Templates & Categories...",
            "select_language" => "Select Language",
            "settings" => "Settings",
            "story" => "Story",
            "templates" => "Templates",
            "terms_conditions" => "Terms & Conditions",
            "update_business" => "Update Business",
            "upgrade_plan" => "Upgrade Plan",
            "usage_this_month" => "Usage This Month",
            "view_all" => "View All",
            "view_earnings" => "View Earnings",
            "view_plans" => "View Plans",
            "upcoming_festivals" => "Upcoming Festivals"
        ];

        AppTranslation::updateOrCreate(['language_code' => 'en'], [
            'title' => 'English',
            'status' => 1,
            'translations' => $englishTranslations
        ]);

        $hindiTranslations = [
            "about_app" => "ऐप के बारे में",
            "ai_setup" => "एआई सेटअप",
            "app_preferences" => "ऐप प्राथमिकताएं",
            "blog" => "ब्लॉग",
            "business" => "व्यापार",
            "catalogue_setting" => "कैटलॉग सेटिंग",
            "category" => "श्रेणी",
            "category_posts" => "श्रेणी पोस्ट",
            "choose_plan" => "प्लान चुनें",
            "custom" => "कस्टम",
            "days_left" => "दिन बाकी",
            "downloads" => "डाउनलोड",
            "edit" => "संपादित करें",
            "faqs" => "सामान्य प्रश्न",
            "festival" => "त्यौहार",
            "frames" => "फ्रेम्स",
            "free" => "मुफ़्त",
            "help_support" => "मदद और सहायता",
            "home" => "होम",
            "more" => "अधिक",
            "my_businesses" => "मेरे व्यापार",
            "new_custom_posts" => "नई कस्टम पोस्ट",
            "new_posts" => "नई पोस्ट",
            "news_updates" => "समाचार और अपडेट",
            "no_categories_found" => "कोई श्रेणी नहीं मिली",
            "no_festivals_found" => "कोई त्यौहार नहीं मिला",
            "no_templates_yet" => "अभी तक कोई टेम्प्लेट नहीं",
            "notifications" => "सूचनाएं",
            "partner_dashboard" => "पार्टनर डैशबोर्ड",
            "partner_program" => "पार्टनर प्रोग्राम",
            "preferred_languages" => "पसंदीदा भाषाएं",
            "privacy_policy" => "गोपनीयता नीति",
            "products" => "उत्पाद",
            "quick_start" => "त्वरित शुरुआत",
            "refund_policy" => "रिफंड नीति",
            "report_problem" => "समस्या की रिपोर्ट करें",
            "search_categories_festivals" => "श्रेणियां और त्यौहार खोजें...",
            "search_templates_categories" => "टेम्प्लेट और श्रेणियां खोजें...",
            "select_language" => "भाषा चुनें",
            "settings" => "सेटिंग्स",
            "story" => "कहानी",
            "templates" => "टेम्प्लेट",
            "terms_conditions" => "नियम और शर्तें",
            "update_business" => "व्यापार अपडेट करें",
            "upgrade_plan" => "प्लान अपग्रेड करें",
            "usage_this_month" => "इस महीने का उपयोग",
            "view_all" => "सभी देखें",
            "view_earnings" => "कमाई देखें",
            "view_plans" => "प्लान देखें",
            "upcoming_festivals" => "आगामी त्यौहार"
        ];

        AppTranslation::updateOrCreate(['language_code' => 'hi'], [
            'title' => 'Hindi (हिंदी)',
            'status' => 1,
            'translations' => $hindiTranslations
        ]);

        AppTranslation::updateOrCreate(['language_code' => 'ha'], [
            'title' => 'Hindi (ha)',
            'status' => 1,
            'translations' => $hindiTranslations
        ]);

        $gujaratiTranslations = [
            "about_app" => "એપ વિશે",
            "ai_setup" => "AI સેટઅપ",
            "app_preferences" => "એપ પસંદગીઓ",
            "blog" => "બ્લોગ",
            "business" => "વ્યવસાય",
            "catalogue_setting" => "કેટલોગ સેટિંગ",
            "category" => "શ્રેણી",
            "category_posts" => "શ્રેણી પોસ્ટ્સ",
            "choose_plan" => "પ્લાન પસંદ કરો",
            "custom" => "કસ્ટમ",
            "days_left" => "દિવસો બાકી",
            "downloads" => "ડાઉનલોડ્સ",
            "edit" => "સંપાદિત કરો",
            "faqs" => "વારંવાર પૂછાતા પ્રશ્નો",
            "festival" => "તહેવાર",
            "frames" => "ફ્રેમ્સ",
            "free" => "મફત",
            "help_support" => "મદદ અને આધાર",
            "home" => "હોમ",
            "more" => "વધુ",
            "my_businesses" => "મારા વ્યવસાયો",
            "new_custom_posts" => "નવી કસ્ટમ પોસ્ટ્સ",
            "new_posts" => "નવી પોસ્ટ્સ",
            "news_updates" => "સમાચાર અને અપડેટ્સ",
            "no_categories_found" => "કોઈ શ્રેણીઓ મળી નથી",
            "no_festivals_found" => "કોઈ તહેવારો મળ્યા નથી",
            "no_templates_yet" => "હજુ સુધી કોઈ ટેમ્પ્લેટ્સ નથી",
            "notifications" => "સૂચનાઓ",
            "partner_dashboard" => "ભાગીદાર ડેશબોર્ડ",
            "partner_program" => "ભાગીદાર પ્રોગ્રામ",
            "preferred_languages" => "પસંદીદા ભાષાઓ",
            "privacy_policy" => "ગોપનીયતા નીતિ",
            "products" => "ઉત્પાદનો",
            "quick_start" => "ઝડપી શરૂઆત",
            "refund_policy" => "રિફંડ નીતિ",
            "report_problem" => "સમસ્યાની જાણ કરો",
            "search_categories_festivals" => "શ્રેણીઓ અને તહેવારો શોધો...",
            "search_templates_categories" => "ટેમ્પ્લેટ્સ અને શ્રેણીઓ શોધો...",
            "select_language" => "ભાષા પસંદ કરો",
            "settings" => "સેટિંગ્સ",
            "story" => "વાર્તા",
            "templates" => "ટેમ્પ્લેટ્સ",
            "terms_conditions" => "નિયમો અને શરતો",
            "update_business" => "વ્યવસાય અપડેટ કરો",
            "upgrade_plan" => "પ્લાન અપગ્રેડ કરો",
            "usage_this_month" => "આ મહિનાનો ઉપયોગ",
            "view_all" => "બધા જુઓ",
            "view_earnings" => "કમાણી જુઓ",
            "view_plans" => "પ્લાન જુઓ",
            "upcoming_festivals" => "આગામી તહેવારો"
        ];

        AppTranslation::updateOrCreate(['language_code' => 'gu'], [
            'title' => 'Gujarati (ગુજરાતી)',
            'status' => 1,
            'translations' => $gujaratiTranslations
        ]);

        $marathiTranslations = [
            "about_app" => "अॅप बद्दल",
            "ai_setup" => "AI सेटअप",
            "app_preferences" => "अॅप प्राधान्ये",
            "blog" => "ब्लॉग",
            "business" => "व्यवसाय",
            "catalogue_setting" => "कॅटलॉग सेटिंग",
            "category" => "श्रेणी",
            "category_posts" => "श्रेणी पोस्ट",
            "choose_plan" => "प्लॅन निवडा",
            "custom" => "कस्टम",
            "days_left" => "दिवस शिल्लक",
            "downloads" => "डाउनलोड",
            "edit" => "संपादित करा",
            "faqs" => "सामान्य प्रश्न",
            "festival" => "सण",
            "frames" => "फ्रेम्स",
            "free" => "मोफत",
            "help_support" => "मदत आणि सपोर्ट",
            "home" => "होम",
            "more" => "अधिक",
            "my_businesses" => "माझे व्यवसाय",
            "new_custom_posts" => "नवीन कस्टम पोस्ट",
            "new_posts" => "नवीन पोस्ट",
            "news_updates" => "बातम्या आणि अपडेट्स",
            "no_categories_found" => "कोणतीही श्रेणी आढळली नाही",
            "no_festivals_found" => "कोणताही सण आढळला नाही",
            "no_templates_yet" => "अद्याप कोणतेही टेम्प्लेट्स नाहीत",
            "notifications" => "सूचना",
            "partner_dashboard" => "पार्टनर डॅशबोर्ड",
            "partner_program" => "पार्टनर प्रोग्राम",
            "preferred_languages" => "प्राधान्य भाषा",
            "privacy_policy" => "गोपनीयता धोरण",
            "products" => "उत्पादने",
            "quick_start" => "त्वरित सुरुवात",
            "refund_policy" => "रिफंड धोरण",
            "report_problem" => "समस्येची तक्रार करा",
            "search_categories_festivals" => "श्रेणी आणि सण शोधा...",
            "search_templates_categories" => "टेम्प्लेट्स आणि श्रेणी शोधा...",
            "select_language" => "भाषा निवडा",
            "settings" => "सेटिंग्ज",
            "story" => "कथा",
            "templates" => "टेम्प्लेट्स",
            "terms_conditions" => "अटी आणि शर्ती",
            "update_business" => "व्यवसाय अपडेट करा",
            "upgrade_plan" => "प्लॅन अपग्रेड करा",
            "usage_this_month" => "या महिन्याचा वापर",
            "view_all" => "सर्व पहा",
            "view_earnings" => "कमाई पहा",
            "view_plans" => "प्लॅन्स पहा",
            "upcoming_festivals" => "आगामी सण"
        ];

        AppTranslation::updateOrCreate(['language_code' => 'mr'], [
            'title' => 'Marathi (मराठी)',
            'status' => 1,
            'translations' => $marathiTranslations
        ]);

        $tamilTranslations = [
            "about_app" => "செயலி பற்றி",
            "ai_setup" => "AI அமைப்பு",
            "app_preferences" => "செயலி விருப்பங்கள்",
            "blog" => "வலைப்பதிவு",
            "business" => "வணிகம்",
            "catalogue_setting" => "பட்டியல் அமைப்பு",
            "category" => "வகை",
            "category_posts" => "வகை பதிவுகள்",
            "choose_plan" => "திட்டத்தை தேர்வு செய்க",
            "custom" => "தனிப்பயன்",
            "days_left" => "மீதமுள்ள நாட்கள்",
            "downloads" => "பதிவிறக்கங்கள்",
            "edit" => "திருத்து",
            "faqs" => "கேள்விகள்",
            "festival" => "பண்டிகை",
            "frames" => "சட்டங்கள்",
            "free" => "இலவசம்",
            "help_support" => "உதவி மற்றும் ஆதரவு",
            "home" => "முகப்பு",
            "more" => "மேலும்",
            "my_businesses" => "எனது வணிகங்கள்",
            "new_custom_posts" => "புதிய தனிப்பயன் பதிவுகள்",
            "new_posts" => "புதிய பதிவுகள்",
            "news_updates" => "செய்திகள் மற்றும் புதுப்பிப்புகள்",
            "no_categories_found" => "வகைகள் எதுவும் காணப்படவில்லை",
            "no_festivals_found" => "பண்டிகைகள் எதுவும் காணப்படவில்லை",
            "no_templates_yet" => "இன்னும் வார்ப்புருக்கள் இல்லை",
            "notifications" => "அறிவிப்புகள்",
            "partner_dashboard" => "கூட்டாளர் டாஷ்போர்டு",
            "partner_program" => "கூட்டாளர் திட்டம்",
            "preferred_languages" => "விருப்பமான மொழிகள்",
            "privacy_policy" => "தனியுரிமைக் கொள்கை",
            "products" => "தயாரிப்புகள்",
            "quick_start" => "விரைவான தொடக்கம்",
            "refund_policy" => "பணம் திரும்பப்பெறும் கொள்கை",
            "report_problem" => "சிக்கலை புகாரளி",
            "search_categories_festivals" => "வகைகள் மற்றும் பண்டிகைகளைத் தேடுக...",
            "search_templates_categories" => "வார்ப்புருக்கள் மற்றும் வகைகளைத் தேடுக...",
            "select_language" => "மொழியைத் தேர்வு செய்க",
            "settings" => "அமைப்புகள்",
            "story" => "கதை",
            "templates" => "வார்ப்புருக்கள்",
            "terms_conditions" => "விதிமுறைகள் மற்றும் நிபந்தனைகள்",
            "update_business" => "வணிகத்தை புதுப்பிக்கவும்",
            "upgrade_plan" => "திட்டத்தை மேம்படுத்துக",
            "usage_this_month" => "இந்த மாத பயன்பாடு",
            "view_all" => "அனைத்தையும் காண்க",
            "view_earnings" => "வருவாயைக் காண்க",
            "view_plans" => "திட்டங்களைக் காண்க",
            "upcoming_festivals" => "வரவிருக்கும் பண்டிகைகள்"
        ];

        AppTranslation::updateOrCreate(['language_code' => 'ta'], [
            'title' => 'Tamil (தமிழ்)',
            'status' => 1,
            'translations' => $tamilTranslations
        ]);
    }
}
