<?php

namespace App\Services;

use App\Models\StorageSetting;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

/**
 * Applies the Festival AI business header/footer to the completed image.
 * It is intentionally separate from the template editor and frame renderer.
 */
class FestivalAiBrandComposer
{
    public function compose(string $imageBinary, array $business, array $chrome): string
    {
        if (empty($chrome) || empty($business) || !function_exists('imagecreatefromstring')) {
            return $imageBinary;
        }

        $canvas = @imagecreatefromstring($imageBinary);
        if (!$canvas) {
            Log::warning('Festival AI branding skipped because the returned image could not be decoded.');
            return $imageBinary;
        }

        try {
            imagealphablending($canvas, true);
            imagesavealpha($canvas, true);

            $width = imagesx($canvas);
            $height = imagesy($canvas);
            if ($width < 80 || $height < 80) {
                return $imageBinary;
            }

            $headerHeight = max(56, (int) round($height * 0.16));
            $footerHeight = max(58, (int) round($height * 0.18));
            $this->drawPanels($canvas, $width, $height, $headerHeight, $footerHeight);

            $padding = max(12, (int) round($width * 0.035));
            $nameX = $padding;
            $logo = $this->logoImage($business['logo_path'] ?? null);
            if ($logo) {
                $nameX = $this->drawLogo($canvas, $logo, $padding, $headerHeight, $width);
                imagedestroy($logo);
            }

            $font = $this->fontPath();
            $name = trim((string) ($business['name'] ?? ''));
            if ($name !== '') {
                $this->drawText(
                    $canvas,
                    $name,
                    $nameX,
                    max(20, (int) round($headerHeight * 0.62)),
                    max(30, $width - $nameX - $padding),
                    max(13, min(40, (int) round($width * 0.035))),
                    $font,
                    [255, 255, 255]
                );
            }

            $contacts = $this->contacts($business);
            if ($contacts !== []) {
                $this->drawText(
                    $canvas,
                    implode('   •   ', $contacts),
                    $padding,
                    $height - $footerHeight + max(18, (int) round($footerHeight * 0.34)),
                    max(30, $width - ($padding * 2)),
                    max(10, min(24, (int) round($width * 0.020))),
                    $font,
                    [247, 249, 252]
                );
            }

            ob_start();
            imagepng($canvas, null, 6);
            return (string) ob_get_clean();
        } catch (\Throwable $exception) {
            Log::warning('Festival AI business branding could not be composed.', [
                'message' => $exception->getMessage(),
            ]);

            return $imageBinary;
        } finally {
            imagedestroy($canvas);
        }
    }

    private function drawPanels($canvas, int $width, int $height, int $headerHeight, int $footerHeight): void
    {
        // A consistent translucent surface keeps real business information
        // readable regardless of the festival art generated by the provider.
        $top = imagecolorallocatealpha($canvas, 10, 18, 36, 38);
        $bottom = imagecolorallocatealpha($canvas, 10, 18, 36, 28);
        imagefilledrectangle($canvas, 0, 0, $width, $headerHeight, $top);
        imagefilledrectangle($canvas, 0, $height - $footerHeight, $width, $height, $bottom);
    }

    private function drawLogo($canvas, $logo, int $padding, int $headerHeight, int $canvasWidth): int
    {
        $sourceWidth = imagesx($logo);
        $sourceHeight = imagesy($logo);
        if ($sourceWidth < 1 || $sourceHeight < 1) {
            return $padding;
        }

        $maxHeight = max(26, (int) round($headerHeight * 0.68));
        $maxWidth = max(36, (int) round($canvasWidth * 0.18));
        $scale = min($maxWidth / $sourceWidth, $maxHeight / $sourceHeight);
        $targetWidth = max(1, (int) round($sourceWidth * $scale));
        $targetHeight = max(1, (int) round($sourceHeight * $scale));
        $targetY = max(0, (int) round(($headerHeight - $targetHeight) / 2));

        imagecopyresampled($canvas, $logo, $padding, $targetY, 0, 0, $targetWidth, $targetHeight, $sourceWidth, $sourceHeight);

        return $padding + $targetWidth + max(10, (int) round($canvasWidth * 0.02));
    }

    private function drawText($canvas, string $text, int $x, int $baseline, int $maxWidth, int $fontSize, ?string $font, array $rgb): void
    {
        $color = imagecolorallocate($canvas, $rgb[0], $rgb[1], $rgb[2]);
        $lineHeight = max(13, (int) round($fontSize * 1.35));
        $lines = $this->wrapText($text, $maxWidth, $fontSize, $font);

        foreach ($lines as $index => $line) {
            $y = $baseline + ($index * $lineHeight);
            if ($font && function_exists('imagettftext')) {
                imagettftext($canvas, $fontSize, 0, $x, $y, $color, $font, $line);
            } else {
                imagestring($canvas, 3, $x, $y - 12, $line, $color);
            }
        }
    }

    private function wrapText(string $text, int $maxWidth, int $fontSize, ?string $font): array
    {
        $words = preg_split('/\s+/u', trim($text)) ?: [];
        $lines = [];
        $line = '';

        foreach ($words as $word) {
            $candidate = $line === '' ? $word : $line . ' ' . $word;
            if ($line !== '' && $this->textWidth($candidate, $fontSize, $font) > $maxWidth) {
                $lines[] = $line;
                $line = $word;
                continue;
            }
            $line = $candidate;
        }

        if ($line !== '') {
            $lines[] = $line;
        }

        return array_slice($lines, 0, 3);
    }

    private function textWidth(string $text, int $fontSize, ?string $font): int
    {
        if ($font && function_exists('imagettfbbox')) {
            $box = imagettfbbox($fontSize, 0, $font, $text);
            if (is_array($box)) {
                return abs($box[2] - $box[0]);
            }
        }

        return imagefontwidth(3) * strlen($text);
    }

    private function contacts(array $business): array
    {
        return collect([
            ...(array) ($business['phones'] ?? []),
            ...(array) ($business['emails'] ?? []),
            ...(array) ($business['websites'] ?? []),
            ...(array) ($business['addresses'] ?? []),
        ])
            ->filter(fn ($value) => is_string($value) && trim($value) !== '')
            ->map(fn (string $value) => trim($value))
            ->unique()
            ->values()
            ->all();
    }

    private function logoImage(?string $path)
    {
        if (!$path) {
            return null;
        }

        $contents = $this->imageContents($path);
        return $contents ? @imagecreatefromstring($contents) : null;
    }

    private function imageContents(string $image): ?string
    {
        if (filter_var($image, FILTER_VALIDATE_URL)) {
            $response = Http::timeout(20)->get($image);
            return $response->successful() ? $response->body() : null;
        }

        $relativePath = ltrim(str_replace('uploads/', '', $image), '/\\');
        foreach ([public_path('uploads/' . $relativePath), base_path('uploads/' . $relativePath)] as $path) {
            if (is_file($path)) {
                return file_get_contents($path) ?: null;
            }
        }

        if (StorageSetting::getStorageSetting('storage') === 'DigitalOcean') {
            $remotePath = 'uploads/' . $relativePath;
            if (Storage::disk('spaces')->exists($remotePath)) {
                return Storage::disk('spaces')->get($remotePath);
            }
        }

        return null;
    }

    private function fontPath(): ?string
    {
        $candidates = array_filter([
            env('FESTIVAL_AI_BRAND_FONT'),
            'C:\\Windows\\Fonts\\Nirmala.ttf',
            'C:\\Windows\\Fonts\\arial.ttf',
            '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
        ]);

        foreach ($candidates as $path) {
            if (is_file($path)) {
                return $path;
            }
        }

        return null;
    }
}
