<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Agriculture & Farming',
        'sub_category' => 'Greenhouse & Polyhouse Supplier',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Polyhouse Structure', 'type' => 'Physical Product', 'brands' => 'Agriplast'],
            ['name' => 'Greenhouse Structure', 'type' => 'Physical Product', 'brands' => 'Netafim'],
            ['name' => 'Shade Net House', 'type' => 'Physical Product', 'brands' => 'Garware'],
            ['name' => 'Insect Net', 'type' => 'Physical Product', 'brands' => 'Garware'],
            ['name' => 'Shade Net', 'type' => 'Physical Product', 'brands' => 'Garware'],
            ['name' => 'Greenhouse Film', 'type' => 'Physical Product', 'brands' => 'Agriplast'],
            ['name' => 'Poly Film', 'type' => 'Physical Product', 'brands' => 'Agriplast'],
            ['name' => 'Mulching Film', 'type' => 'Physical Product', 'brands' => 'Garware'],
            ['name' => 'Drip Irrigation System', 'type' => 'Physical Product', 'brands' => 'Jain Irrigation'],
            ['name' => 'Fogging System', 'type' => 'Physical Product', 'brands' => 'Netafim'],
            ['name' => 'Misting System', 'type' => 'Physical Product', 'brands' => 'Netafim'],
            ['name' => 'Ventilation System', 'type' => 'Physical Product', 'brands' => 'Supplier'],
            ['name' => 'Cooling Pad System', 'type' => 'Physical Product', 'brands' => 'Supplier'],
            ['name' => 'Exhaust Fan', 'type' => 'Physical Product', 'brands' => 'Crompton'],
            ['name' => 'Greenhouse Controller', 'type' => 'Physical Product', 'brands' => 'Netafim'],
            ['name' => 'Climate Control System', 'type' => 'Physical Product', 'brands' => 'Netafim'],
            ['name' => 'Hydroponic System', 'type' => 'Physical Product', 'brands' => 'Future Farms'],
            ['name' => 'Vertical Farming System', 'type' => 'Physical Product', 'brands' => 'Future Farms'],
            ['name' => 'Nursery Trays', 'type' => 'Physical Product', 'brands' => 'Agriplast'],
            ['name' => 'Cocopeat', 'type' => 'Physical Product', 'brands' => 'FibreDust'],
            ['name' => 'Grow Bags', 'type' => 'Physical Product', 'brands' => 'Agriplast'],
            ['name' => 'Greenhouse Installation', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Site Survey', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Farm Design', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Structural Fabrication', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Government Subsidy Assistance', 'type' => 'Service', 'brands' => 'NHB'],
            ['name' => 'Repair & Maintenance', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Annual Maintenance Contract', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Crop Planning', 'type' => 'Service', 'brands' => 'Agronomist'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Farmer Training', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Online Quotation', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Home Delivery', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Bulk Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Export Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Soil Testing', 'type' => 'Service', 'brands' => 'Agri Lab'],
            ['name' => 'Water Testing', 'type' => 'Service', 'brands' => 'Agri Lab'],
            ['name' => 'Farm Visit', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Supplier'],
        ]
    ],
    [
        'category' => 'Agriculture & Farming',
        'sub_category' => 'Hydroponic Farm',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Hydroponic Lettuce', 'type' => 'Physical Product', 'brands' => 'Hydro Farm'],
            ['name' => 'Hydroponic Spinach', 'type' => 'Physical Product', 'brands' => 'Hydro Farm'],
            ['name' => 'Hydroponic Kale', 'type' => 'Physical Product', 'brands' => 'Hydro Farm'],
            ['name' => 'Hydroponic Herbs', 'type' => 'Physical Product', 'brands' => 'Hydro Farm'],
            ['name' => 'Hydroponic Tomatoes', 'type' => 'Physical Product', 'brands' => 'Hydro Farm'],
            ['name' => 'Hydroponic Cucumbers', 'type' => 'Physical Product', 'brands' => 'Hydro Farm'],
            ['name' => 'Hydroponic Strawberries', 'type' => 'Physical Product', 'brands' => 'Hydro Farm'],
            ['name' => 'Hydroponic Microgreens', 'type' => 'Physical Product', 'brands' => 'Hydro Farm'],
            ['name' => 'Hydroponic Nutrients', 'type' => 'Physical Product', 'brands' => 'General Hydroponics'],
            ['name' => 'Grow Media', 'type' => 'Physical Product', 'brands' => 'FibreDust'],
            ['name' => 'Cocopeat', 'type' => 'Physical Product', 'brands' => 'FibreDust'],
            ['name' => 'Rockwool Cubes', 'type' => 'Physical Product', 'brands' => 'Grodan'],
            ['name' => 'NFT System', 'type' => 'Physical Product', 'brands' => 'Future Farms'],
            ['name' => 'DWC System', 'type' => 'Physical Product', 'brands' => 'Future Farms'],
            ['name' => 'Vertical Hydroponic System', 'type' => 'Physical Product', 'brands' => 'Future Farms'],
            ['name' => 'Grow Lights', 'type' => 'Physical Product', 'brands' => 'Philips'],
            ['name' => 'Water Pump', 'type' => 'Physical Product', 'brands' => 'Kirloskar'],
            ['name' => 'pH Meter', 'type' => 'Physical Product', 'brands' => 'Hanna Instruments'],
            ['name' => 'EC Meter', 'type' => 'Physical Product', 'brands' => 'Hanna Instruments'],
            ['name' => 'Water Filtration System', 'type' => 'Physical Product', 'brands' => 'Kent'],
            ['name' => 'Hydroponic Farm Setup', 'type' => 'Service', 'brands' => 'Hydroponic Consultant'],
            ['name' => 'Farm Design', 'type' => 'Service', 'brands' => 'Hydroponic Consultant'],
            ['name' => 'Installation', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Farm Maintenance', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Nutrient Management', 'type' => 'Service', 'brands' => 'Hydroponic Expert'],
            ['name' => 'Crop Planning', 'type' => 'Service', 'brands' => 'Hydroponic Expert'],
            ['name' => 'Farm Monitoring', 'type' => 'Service', 'brands' => 'Hydroponic Expert'],
            ['name' => 'Training Program', 'type' => 'Service', 'brands' => 'Hydroponic Farm'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Hydroponic Consultant'],
            ['name' => 'Farm Visit', 'type' => 'Service', 'brands' => 'Hydroponic Consultant'],
            ['name' => 'Subscription Produce Box', 'type' => 'Service', 'brands' => 'Hydroponic Farm'],
            ['name' => 'Wholesale Supply', 'type' => 'Service', 'brands' => 'Hydroponic Farm'],
            ['name' => 'Retail Supply', 'type' => 'Service', 'brands' => 'Hydroponic Farm'],
            ['name' => 'Restaurant Supply', 'type' => 'Service', 'brands' => 'Hydroponic Farm'],
            ['name' => 'Government Subsidy Guidance', 'type' => 'Service', 'brands' => 'NHB'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Online Ordering', 'type' => 'Service', 'brands' => 'Hydroponic Farm'],
            ['name' => 'Export Quality Produce', 'type' => 'Physical Product', 'brands' => 'Hydroponic Farm'],
            ['name' => 'Farm Membership', 'type' => 'Service', 'brands' => 'Hydroponic Farm'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Hydroponic Farm'],
        ]
    ],
    [
        'category' => 'Agriculture & Farming',
        'sub_category' => 'Plant Nursery',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Flower Plants', 'type' => 'Physical Product', 'brands' => 'Ugaoo'],
            ['name' => 'Indoor Plants', 'type' => 'Physical Product', 'brands' => 'Ugaoo'],
            ['name' => 'Outdoor Plants', 'type' => 'Physical Product', 'brands' => 'Ugaoo'],
            ['name' => 'Fruit Plants', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Vegetable Seedlings', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Ornamental Plants', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Medicinal Plants', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Bonsai Plants', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Succulent Plants', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Cactus Plants', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Palm Plants', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Shade Trees', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Avenue Trees', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Lawn Grass', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Plant Seeds', 'type' => 'Physical Product', 'brands' => 'Bioseed'],
            ['name' => 'Seedlings', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Cocopeat', 'type' => 'Physical Product', 'brands' => 'FibreDust'],
            ['name' => 'Potting Mix', 'type' => 'Physical Product', 'brands' => 'Ugaoo'],
            ['name' => 'Organic Fertilizer', 'type' => 'Physical Product', 'brands' => 'Organic India'],
            ['name' => 'Plant Pots', 'type' => 'Physical Product', 'brands' => 'Nilkamal'],
            ['name' => 'Ceramic Pots', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Plastic Pots', 'type' => 'Physical Product', 'brands' => 'Nilkamal'],
            ['name' => 'Hanging Pots', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Garden Tools', 'type' => 'Physical Product', 'brands' => 'Falcon'],
            ['name' => 'Watering Can', 'type' => 'Physical Product', 'brands' => 'Gardena'],
            ['name' => 'Drip Irrigation Kit', 'type' => 'Physical Product', 'brands' => 'Jain Irrigation'],
            ['name' => 'Landscape Plants', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Plant Rental', 'type' => 'Service', 'brands' => 'Nursery'],
            ['name' => 'Garden Design', 'type' => 'Service', 'brands' => 'Landscape Expert'],
            ['name' => 'Landscaping', 'type' => 'Service', 'brands' => 'Landscape Expert'],
            ['name' => 'Garden Maintenance', 'type' => 'Service', 'brands' => 'Nursery'],
            ['name' => 'Plant Care Consultation', 'type' => 'Service', 'brands' => 'Nursery'],
            ['name' => 'Home Delivery', 'type' => 'Service', 'brands' => 'Nursery'],
            ['name' => 'Online Plant Store', 'type' => 'Service', 'brands' => 'Nursery'],
            ['name' => 'Wholesale Supply', 'type' => 'Service', 'brands' => 'Nursery'],
            ['name' => 'Retail Supply', 'type' => 'Service', 'brands' => 'Nursery'],
            ['name' => 'Corporate Plant Solutions', 'type' => 'Service', 'brands' => 'Nursery'],
            ['name' => 'Planting Service', 'type' => 'Service', 'brands' => 'Nursery'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Nursery'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Nursery'],
        ]
    ],
    [
        'category' => 'Agriculture & Farming',
        'sub_category' => 'Landscape Gardening Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Landscape Design', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Garden Design', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Lawn Installation', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Vertical Garden', 'type' => 'Service', 'brands' => 'Ugaoo'],
            ['name' => 'Terrace Garden', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Rooftop Garden', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Indoor Landscaping', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Outdoor Landscaping', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Water Fountain Installation', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Artificial Waterfall', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Rock Garden', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Zen Garden', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Plant Supply', 'type' => 'Physical Product', 'brands' => 'Ugaoo'],
            ['name' => 'Indoor Plants', 'type' => 'Physical Product', 'brands' => 'Ugaoo'],
            ['name' => 'Outdoor Plants', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Palm Trees', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Flowering Plants', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Turf Grass', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Irrigation System Installation', 'type' => 'Service', 'brands' => 'Jain Irrigation'],
            ['name' => 'Garden Lighting', 'type' => 'Service', 'brands' => 'Philips'],
            ['name' => 'Garden Furniture', 'type' => 'Physical Product', 'brands' => 'Nilkamal'],
            ['name' => 'Decorative Pots', 'type' => 'Physical Product', 'brands' => 'Nursery'],
            ['name' => 'Garden Accessories', 'type' => 'Physical Product', 'brands' => 'Gardena'],
            ['name' => 'Drip Irrigation', 'type' => 'Service', 'brands' => 'Jain Irrigation'],
            ['name' => 'Garden Maintenance', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Lawn Mowing', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Tree Pruning', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Tree Plantation', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Organic Garden Care', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Pest Control', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Residential Landscaping', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Commercial Landscaping', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Farm Landscaping', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Resort Landscaping', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Garden Renovation', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Annual Maintenance Contract', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Site Visit', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Landscape Company'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Landscape Company'],
        ]
    ],
    [
        'category' => 'Agriculture & Farming',
        'sub_category' => 'Beekeeping Farm',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Raw Honey', 'type' => 'Physical Product', 'brands' => 'Dabur'],
            ['name' => 'Organic Honey', 'type' => 'Physical Product', 'brands' => 'Organic India'],
            ['name' => 'Wild Forest Honey', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Multifloral Honey', 'type' => 'Physical Product', 'brands' => 'Nature\'s Nectar'],
            ['name' => 'Monofloral Honey', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Honeycomb', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Beeswax', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Beeswax Candles', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Bee Pollen', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Royal Jelly', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Propolis', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Queen Bees', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Bee Colonies', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Bee Boxes', 'type' => 'Physical Product', 'brands' => 'Beekeeping Equipment'],
            ['name' => 'Bee Frames', 'type' => 'Physical Product', 'brands' => 'Beekeeping Equipment'],
            ['name' => 'Honey Extractor', 'type' => 'Physical Product', 'brands' => 'Beekeeping Equipment'],
            ['name' => 'Protective Bee Suit', 'type' => 'Physical Product', 'brands' => 'Beekeeping Equipment'],
            ['name' => 'Smoker', 'type' => 'Physical Product', 'brands' => 'Beekeeping Equipment'],
            ['name' => 'Hive Tool', 'type' => 'Physical Product', 'brands' => 'Beekeeping Equipment'],
            ['name' => 'Pollination Services', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Honey Processing', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Honey Packaging', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Bulk Honey Supply', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Retail Honey Supply', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Export Quality Honey', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Beekeeping Training', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Farm Setup Consultation', 'type' => 'Service', 'brands' => 'Beekeeping Expert'],
            ['name' => 'Hive Management', 'type' => 'Service', 'brands' => 'Beekeeping Expert'],
            ['name' => 'Disease Management', 'type' => 'Service', 'brands' => 'Beekeeping Expert'],
            ['name' => 'Queen Bee Breeding', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Apiary Inspection', 'type' => 'Service', 'brands' => 'Beekeeping Expert'],
            ['name' => 'Government Scheme Guidance', 'type' => 'Service', 'brands' => 'NABARD'],
            ['name' => 'Organic Certification Guidance', 'type' => 'Service', 'brands' => 'APEDA'],
            ['name' => 'Online Orders', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Home Delivery', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Farm Visit', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Subscription Honey Box', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
            ['name' => 'Corporate Gift Packs', 'type' => 'Physical Product', 'brands' => 'Beekeeping Farm'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Beekeeping Farm'],
        ]
    ],
    [
        'category' => 'Agriculture & Farming',
        'sub_category' => 'Mushroom Farm',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Button Mushroom', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Oyster Mushroom', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Milky Mushroom', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Shiitake Mushroom', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Portobello Mushroom', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Enoki Mushroom', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Fresh Mushrooms', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Dried Mushrooms', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Mushroom Powder', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Mushroom Pickle', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Mushroom Soup Mix', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Mushroom Spawn', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Spawn Bags', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Compost Bags', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Mushroom Growing Kit', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Poly Bags', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Humidity Controller', 'type' => 'Physical Product', 'brands' => 'Mushroom Equipment'],
            ['name' => 'Temperature Controller', 'type' => 'Physical Product', 'brands' => 'Mushroom Equipment'],
            ['name' => 'Mushroom Dryer', 'type' => 'Physical Product', 'brands' => 'Mushroom Equipment'],
            ['name' => 'Mushroom Packaging', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Bulk Mushroom Supply', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Retail Mushroom Supply', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Restaurant Supply', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Export Quality Mushrooms', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Mushroom Farm Setup', 'type' => 'Service', 'brands' => 'Mushroom Consultant'],
            ['name' => 'Mushroom Cultivation Training', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Technical Consultation', 'type' => 'Service', 'brands' => 'Mushroom Expert'],
            ['name' => 'Compost Preparation Training', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Farm Visit', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Government Subsidy Guidance', 'type' => 'Service', 'brands' => 'NABARD'],
            ['name' => 'Organic Certification', 'type' => 'Service', 'brands' => 'APEDA'],
            ['name' => 'Online Orders', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Home Delivery', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Subscription Produce Box', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Wholesale Supply', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Retail Store Supply', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Value Added Products', 'type' => 'Physical Product', 'brands' => 'Mushroom Farm'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
            ['name' => 'Farm Management Consulting', 'type' => 'Service', 'brands' => 'Mushroom Expert'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Mushroom Farm'],
        ]
    ],
    [
        'category' => 'Agriculture & Farming',
        'sub_category' => 'Vermicompost Producer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Vermicompost', 'type' => 'Physical Product', 'brands' => 'VermiGold'],
            ['name' => 'Organic Compost', 'type' => 'Physical Product', 'brands' => 'Organic India'],
            ['name' => 'Earthworms', 'type' => 'Physical Product', 'brands' => 'Vermicompost Producer'],
            ['name' => 'Red Wiggler Worms', 'type' => 'Physical Product', 'brands' => 'Vermicompost Producer'],
            ['name' => 'Vermiwash', 'type' => 'Physical Product', 'brands' => 'Vermicompost Producer'],
            ['name' => 'Liquid Organic Fertilizer', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Bio Fertilizer', 'type' => 'Physical Product', 'brands' => 'T. Stanes'],
            ['name' => 'Compost Bags', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Organic Potting Mix', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Cocopeat Mix', 'type' => 'Physical Product', 'brands' => 'FibreDust'],
            ['name' => 'Soil Conditioner', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Garden Compost', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Farm Compost', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Organic Manure', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Compost Starter Culture', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Compost Bin', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Vermicompost Unit Kit', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Compost Bed', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Compost Sieve', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Packaging Bags', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Bulk Compost Supply', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Retail Supply', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Home Delivery', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Organic Farming Consultation', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Vermicomposting Training', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Farm Setup Consultation', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Compost Unit Installation', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Waste Management Consultation', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Soil Health Testing', 'type' => 'Service', 'brands' => 'Agri Lab'],
            ['name' => 'Crop Nutrition Planning', 'type' => 'Service', 'brands' => 'Agronomist'],
            ['name' => 'Organic Certification Support', 'type' => 'Service', 'brands' => 'APEDA'],
            ['name' => 'Farmer Workshops', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'School Awareness Programs', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Online Orders', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Wholesale Distribution', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Export Quality Compost', 'type' => 'Physical Product', 'brands' => 'Producer'],
            ['name' => 'Government Subsidy Guidance', 'type' => 'Service', 'brands' => 'NABARD'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => 'Farm Visit', 'type' => 'Service', 'brands' => 'Producer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Producer'],
        ]
    ],
    [
        'category' => 'Agriculture & Farming',
        'sub_category' => 'AgriTech Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Farm Management Software', 'type' => 'Software', 'brands' => 'CropIn'],
            ['name' => 'Precision Farming Platform', 'type' => 'Software', 'brands' => 'Fasal'],
            ['name' => 'Smart Irrigation System', 'type' => 'Physical Product', 'brands' => 'Jain Irrigation'],
            ['name' => 'IoT Farm Sensors', 'type' => 'Physical Product', 'brands' => 'Fasal'],
            ['name' => 'Soil Moisture Sensor', 'type' => 'Physical Product', 'brands' => 'Netafim'],
            ['name' => 'Weather Monitoring Station', 'type' => 'Physical Product', 'brands' => 'Davis Instruments'],
            ['name' => 'Crop Monitoring App', 'type' => 'Software', 'brands' => 'DeHaat'],
            ['name' => 'Satellite Crop Monitoring', 'type' => 'Service', 'brands' => 'CropIn'],
            ['name' => 'Drone Crop Survey', 'type' => 'Service', 'brands' => 'Garuda Aerospace'],
            ['name' => 'Drone Spraying Service', 'type' => 'Service', 'brands' => 'Garuda Aerospace'],
            ['name' => 'AI Crop Advisory', 'type' => 'Software', 'brands' => 'Fasal'],
            ['name' => 'Pest Detection AI', 'type' => 'Software', 'brands' => 'AgriTech Company'],
            ['name' => 'Yield Prediction', 'type' => 'Software', 'brands' => 'CropIn'],
            ['name' => 'Farm Analytics Dashboard', 'type' => 'Software', 'brands' => 'CropIn'],
            ['name' => 'Digital Farm Records', 'type' => 'Software', 'brands' => 'AgriTech Company'],
            ['name' => 'Farmer Mobile App', 'type' => 'Software', 'brands' => 'DeHaat'],
            ['name' => 'eCommerce for Farmers', 'type' => 'Software', 'brands' => 'DeHaat'],
            ['name' => 'Online Input Marketplace', 'type' => 'Software', 'brands' => 'AgriBazaar'],
            ['name' => 'Produce Marketplace', 'type' => 'Software', 'brands' => 'Ninjacart'],
            ['name' => 'Agri Loan Assistance', 'type' => 'Service', 'brands' => 'NABARD'],
            ['name' => 'Crop Insurance Assistance', 'type' => 'Service', 'brands' => 'PMFBY'],
            ['name' => 'Soil Testing', 'type' => 'Service', 'brands' => 'Agri Lab'],
            ['name' => 'Water Testing', 'type' => 'Service', 'brands' => 'Agri Lab'],
            ['name' => 'Farm Advisory', 'type' => 'Service', 'brands' => 'Agri Expert'],
            ['name' => 'Agronomist Consultation', 'type' => 'Service', 'brands' => 'AgriTech Company'],
            ['name' => 'Farm Mapping', 'type' => 'Service', 'brands' => 'AgriTech Company'],
            ['name' => 'GPS Field Survey', 'type' => 'Service', 'brands' => 'AgriTech Company'],
            ['name' => 'Farm Automation', 'type' => 'Service', 'brands' => 'AgriTech Company'],
            ['name' => 'Greenhouse Automation', 'type' => 'Service', 'brands' => 'AgriTech Company'],
            ['name' => 'Smart Irrigation Automation', 'type' => 'Service', 'brands' => 'Netafim'],
            ['name' => 'Farmer Training', 'type' => 'Service', 'brands' => 'AgriTech Company'],
            ['name' => 'API Integration', 'type' => 'Software', 'brands' => 'AgriTech Platform'],
            ['name' => 'ERP for Farms', 'type' => 'Software', 'brands' => 'AgriTech Company'],
            ['name' => 'Supply Chain Management', 'type' => 'Software', 'brands' => 'Ninjacart'],
            ['name' => 'Warehouse Management', 'type' => 'Software', 'brands' => 'AgriTech Company'],
            ['name' => 'Export Assistance', 'type' => 'Service', 'brands' => 'APEDA'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'AgriTech Company'],
            ['name' => 'Subscription Plans', 'type' => 'Service', 'brands' => 'AgriTech Company'],
            ['name' => 'Enterprise Solutions', 'type' => 'Service', 'brands' => 'AgriTech Company'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'AgriTech Company'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Agriculture & Farming Sub Categories 33.13 to 33.20.\n";
