<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Construction Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Residential Construction', 'type' => 'Service', 'brands' => 'L&T Construction'],
            ['name' => 'Commercial Construction', 'type' => 'Service', 'brands' => 'Shapoorji Pallonji'],
            ['name' => 'Industrial Construction', 'type' => 'Service', 'brands' => 'Tata Projects'],
            ['name' => 'Infrastructure Construction', 'type' => 'Service', 'brands' => 'NCC Limited'],
            ['name' => 'Turnkey Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Villa Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Apartment Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Bungalow Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Office Building Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Warehouse Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Factory Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Hospital Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'School Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Hotel Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Mall Construction', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'RCC Work', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Civil Contracting', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Structural Work', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Interior Fit-Out', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Renovation & Remodeling', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Demolition Work', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Site Development', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Quantity Surveying', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Estimation & Costing', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Labor Contract', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Material Procurement', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'EPC Contract', 'type' => 'Service', 'brands' => 'Tata Projects'],
            ['name' => 'Green Building Construction', 'type' => 'Service', 'brands' => 'IGBC'],
            ['name' => 'Smart Building Solutions', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Construction Consultancy', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Building Approval Assistance', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Structural Audit', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Safety Management', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Quality Inspection', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'BIM Services', 'type' => 'Service', 'brands' => 'Autodesk'],
            ['name' => 'Online Project Tracking', 'type' => 'Software', 'brands' => 'Procore'],
            ['name' => 'AMC Services', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Construction Company'],
            ['name' => '24×7 Project Support', 'type' => 'Service', 'brands' => 'Construction Company'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Civil Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Civil Construction', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Foundation Work', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Excavation Work', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Earthwork', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'RCC Construction', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Brick Masonry', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Block Work', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Plastering', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Flooring Work', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Tiling Work', 'type' => 'Service', 'brands' => 'Kajaria'],
            ['name' => 'Waterproofing', 'type' => 'Service', 'brands' => 'Dr. Fixit'],
            ['name' => 'Roofing Work', 'type' => 'Service', 'brands' => 'Tata BlueScope'],
            ['name' => 'Boundary Wall Construction', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Compound Wall Construction', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Road Construction', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Drainage Construction', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Sewage Line Work', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Storm Water Drain', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Retaining Wall', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Industrial Civil Work', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Commercial Civil Work', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Residential Civil Work', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Site Survey', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Land Development', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Construction Estimation', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Quantity Survey', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Labor Supply', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Material Supply', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Project Supervision', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Safety Compliance', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Structural Repair', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Concrete Cutting', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Core Cutting', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Demolition Work', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Construction Equipment Rental', 'type' => 'Service', 'brands' => 'JCB'],
            ['name' => 'Quality Testing', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Government Tender Work', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'AMC Services', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Civil Contractor'],
            ['name' => '24×7 Site Support', 'type' => 'Service', 'brands' => 'Civil Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Architect',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Residential Architecture', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Commercial Architecture', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Industrial Architecture', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Villa Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Bungalow Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Apartment Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Office Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Retail Store Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Hotel Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Hospital Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'School Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Restaurant Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Master Planning', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Floor Plan Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Elevation Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => '3D Elevation', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => '3D Rendering', 'type' => 'Service', 'brands' => 'Lumion'],
            ['name' => 'Interior Space Planning', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Landscape Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Sustainable Building Design', 'type' => 'Service', 'brands' => 'IGBC'],
            ['name' => 'Green Building Consultancy', 'type' => 'Service', 'brands' => 'IGBC'],
            ['name' => 'Vastu Consultation', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Building Approval Drawings', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Working Drawings', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Structural Coordination', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'MEP Coordination', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'BIM Modeling', 'type' => 'Service', 'brands' => 'Autodesk Revit'],
            ['name' => 'Site Supervision', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Project Consultation', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Renovation Design', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Heritage Restoration', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Urban Planning', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Interior Architecture', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Material Selection', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Cost Estimation', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Virtual Design Review', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Construction Documentation', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Architect'],
            ['name' => '24×7 Client Support', 'type' => 'Service', 'brands' => 'Architect'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Structural Engineer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Structural Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'RCC Structural Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Steel Structure Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Pre-Engineered Building (PEB) Design', 'type' => 'Service', 'brands' => 'Kirby Building Systems'],
            ['name' => 'Foundation Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Column Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Beam Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Slab Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Retaining Wall Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Industrial Structure Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Residential Structure Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Commercial Structure Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'High-Rise Structural Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Bridge Structure Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Earthquake Resistant Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Wind Load Analysis', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Structural Analysis', 'type' => 'Service', 'brands' => 'ETABS'],
            ['name' => 'Finite Element Analysis', 'type' => 'Service', 'brands' => 'STAAD.Pro'],
            ['name' => 'BIM Structural Modeling', 'type' => 'Service', 'brands' => 'Autodesk Revit'],
            ['name' => 'Structural Drawings', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Shop Drawings', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Structural Audit', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Building Stability Certificate', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Structural Inspection', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Concrete Testing', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Steel Testing', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Site Supervision', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Construction Consultation', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Quantity Estimation', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'BOQ Preparation', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Retrofit Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Rehabilitation Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Temporary Structure Design', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Value Engineering', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Tender Documentation', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Technical Reports', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Expert Witness Services', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => '24×7 Client Support', 'type' => 'Service', 'brands' => 'Structural Engineer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Interior Designer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Residential Interior Design', 'type' => 'Service', 'brands' => 'Livspace'],
            ['name' => 'Modular Kitchen Design', 'type' => 'Service', 'brands' => 'Sleek Kitchens'],
            ['name' => 'Bedroom Interior Design', 'type' => 'Service', 'brands' => 'HomeLane'],
            ['name' => 'Living Room Design', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Dining Room Design', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Bathroom Interior Design', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Office Interior Design', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Commercial Interior Design', 'type' => 'Service', 'brands' => 'Livspace'],
            ['name' => 'Retail Store Interior', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Restaurant Interior', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Hotel Interior Design', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Hospital Interior', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'False Ceiling Design', 'type' => 'Service', 'brands' => 'Gyproc'],
            ['name' => 'Wall Panel Design', 'type' => 'Service', 'brands' => 'Greenlam'],
            ['name' => 'Wallpaper Installation', 'type' => 'Service', 'brands' => 'Marshalls'],
            ['name' => 'Wooden Flooring', 'type' => 'Physical Product', 'brands' => 'Pergo'],
            ['name' => 'Vinyl Flooring', 'type' => 'Physical Product', 'brands' => 'Responsive Industries'],
            ['name' => 'Lighting Design', 'type' => 'Service', 'brands' => 'Philips Lighting'],
            ['name' => 'Furniture Layout', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Space Planning', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => '2D Layout', 'type' => 'Service', 'brands' => 'AutoCAD'],
            ['name' => '3D Interior Rendering', 'type' => 'Service', 'brands' => 'Lumion'],
            ['name' => 'Walkthrough Animation', 'type' => 'Service', 'brands' => 'Twinmotion'],
            ['name' => 'Material Selection', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Color Consultation', 'type' => 'Service', 'brands' => 'Asian Paints'],
            ['name' => 'Custom Furniture Design', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Turnkey Interior Execution', 'type' => 'Service', 'brands' => 'HomeLane'],
            ['name' => 'Site Supervision', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Renovation Services', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Smart Home Integration', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Home Automation Planning', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Vastu Interior Consultation', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'BOQ Preparation', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Budget Planning', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Virtual Design Review', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => 'After Sales Service', 'type' => 'Service', 'brands' => 'Interior Designer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Interior Designer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Building Material Supplier',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Cement', 'type' => 'Physical Product', 'brands' => 'UltraTech Cement'],
            ['name' => 'Ready Mix Concrete (RMC)', 'type' => 'Physical Product', 'brands' => 'UltraTech RMC'],
            ['name' => 'TMT Bars', 'type' => 'Physical Product', 'brands' => 'Tata Tiscon'],
            ['name' => 'Structural Steel', 'type' => 'Physical Product', 'brands' => 'JSW Steel'],
            ['name' => 'Bricks', 'type' => 'Physical Product', 'brands' => 'Wienerberger'],
            ['name' => 'AAC Blocks', 'type' => 'Physical Product', 'brands' => 'Magicrete'],
            ['name' => 'Fly Ash Bricks', 'type' => 'Physical Product', 'brands' => 'Local Manufacturer'],
            ['name' => 'Sand', 'type' => 'Physical Product', 'brands' => 'Supplier'],
            ['name' => 'Crushed Stone Aggregate', 'type' => 'Physical Product', 'brands' => 'Supplier'],
            ['name' => 'Gravel', 'type' => 'Physical Product', 'brands' => 'Supplier'],
            ['name' => 'Lime', 'type' => 'Physical Product', 'brands' => 'Supplier'],
            ['name' => 'Gypsum', 'type' => 'Physical Product', 'brands' => 'Saint-Gobain Gyproc'],
            ['name' => 'Waterproofing Chemicals', 'type' => 'Physical Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Construction Chemicals', 'type' => 'Physical Product', 'brands' => 'Fosroc'],
            ['name' => 'Tile Adhesive', 'type' => 'Physical Product', 'brands' => 'MYK LATICRETE'],
            ['name' => 'Wall Putty', 'type' => 'Physical Product', 'brands' => 'Birla White'],
            ['name' => 'POP', 'type' => 'Physical Product', 'brands' => 'JK Lakshmi'],
            ['name' => 'Roofing Sheets', 'type' => 'Physical Product', 'brands' => 'Tata BlueScope'],
            ['name' => 'PVC Pipes', 'type' => 'Physical Product', 'brands' => 'Astral'],
            ['name' => 'CPVC Pipes', 'type' => 'Physical Product', 'brands' => 'Ashirvad'],
            ['name' => 'UPVC Pipes', 'type' => 'Physical Product', 'brands' => 'Supreme'],
            ['name' => 'Electrical Conduits', 'type' => 'Physical Product', 'brands' => 'Finolex'],
            ['name' => 'Paints', 'type' => 'Physical Product', 'brands' => 'Asian Paints'],
            ['name' => 'Primer', 'type' => 'Physical Product', 'brands' => 'Berger Paints'],
            ['name' => 'Hardware Materials', 'type' => 'Physical Product', 'brands' => 'Supplier'],
            ['name' => 'Fasteners', 'type' => 'Physical Product', 'brands' => 'Hilti'],
            ['name' => 'Scaffolding Material', 'type' => 'Physical Product', 'brands' => 'Supplier'],
            ['name' => 'Construction Tools', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Bulk Material Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Site Delivery', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Material Estimation', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Contractor Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Project Supply Contract', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Online Ordering', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Inventory Management', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Credit Facility', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Technical Consultation', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Quality Certification', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'After Sales Support', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Supplier'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Cement Dealer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'OPC Cement', 'type' => 'Physical Product', 'brands' => 'UltraTech Cement'],
            ['name' => 'PPC Cement', 'type' => 'Physical Product', 'brands' => 'ACC Cement'],
            ['name' => 'PSC Cement', 'type' => 'Physical Product', 'brands' => 'Dalmia Cement'],
            ['name' => 'White Cement', 'type' => 'Physical Product', 'brands' => 'Birla White'],
            ['name' => 'Rapid Hardening Cement', 'type' => 'Physical Product', 'brands' => 'JK Cement'],
            ['name' => 'Sulphate Resistant Cement', 'type' => 'Physical Product', 'brands' => 'UltraTech Cement'],
            ['name' => 'Low Heat Cement', 'type' => 'Physical Product', 'brands' => 'ACC Cement'],
            ['name' => 'Masonry Cement', 'type' => 'Physical Product', 'brands' => 'JK Lakshmi Cement'],
            ['name' => 'Ready Mix Concrete', 'type' => 'Physical Product', 'brands' => 'UltraTech RMC'],
            ['name' => 'Cement Bags', 'type' => 'Physical Product', 'brands' => 'UltraTech Cement'],
            ['name' => 'Bulk Cement', 'type' => 'Physical Product', 'brands' => 'ACC Cement'],
            ['name' => 'Waterproof Cement', 'type' => 'Physical Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Tile Adhesive', 'type' => 'Physical Product', 'brands' => 'MYK LATICRETE'],
            ['name' => 'Wall Putty', 'type' => 'Physical Product', 'brands' => 'Birla White'],
            ['name' => 'Construction Chemicals', 'type' => 'Physical Product', 'brands' => 'Fosroc'],
            ['name' => 'Concrete Admixture', 'type' => 'Physical Product', 'brands' => 'Sika'],
            ['name' => 'Grout Material', 'type' => 'Physical Product', 'brands' => 'Fosroc'],
            ['name' => 'Cement Primer', 'type' => 'Physical Product', 'brands' => 'Asian Paints'],
            ['name' => 'Sand', 'type' => 'Physical Product', 'brands' => 'Dealer'],
            ['name' => 'Aggregate', 'type' => 'Physical Product', 'brands' => 'Dealer'],
            ['name' => 'Bulk Cement Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Site Delivery', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Contractor Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Builder Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Government Project Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Material Estimation', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Quantity Calculation', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Credit Facility', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Online Ordering', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Wholesale Distribution', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Retail Sales', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Loading & Unloading', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Material Transportation', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Dealer Network Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Product Consultation', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Technical Guidance', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'After Sales Support', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Emergency Delivery', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Dealer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Steel & TMT Bar Dealer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'TMT Bars', 'type' => 'Physical Product', 'brands' => 'Tata Tiscon'],
            ['name' => 'Fe500 TMT Bars', 'type' => 'Physical Product', 'brands' => 'Kamdhenu'],
            ['name' => 'Fe550 TMT Bars', 'type' => 'Physical Product', 'brands' => 'JSW Neosteel'],
            ['name' => 'Fe600 TMT Bars', 'type' => 'Physical Product', 'brands' => 'Shyam Steel'],
            ['name' => 'Structural Steel', 'type' => 'Physical Product', 'brands' => 'JSW Steel'],
            ['name' => 'Mild Steel Rods', 'type' => 'Physical Product', 'brands' => 'SAIL'],
            ['name' => 'Steel Angles', 'type' => 'Physical Product', 'brands' => 'Tata Steel'],
            ['name' => 'Steel Channels', 'type' => 'Physical Product', 'brands' => 'Tata Steel'],
            ['name' => 'Steel Beams', 'type' => 'Physical Product', 'brands' => 'JSW Steel'],
            ['name' => 'Steel Plates', 'type' => 'Physical Product', 'brands' => 'SAIL'],
            ['name' => 'Steel Sheets', 'type' => 'Physical Product', 'brands' => 'Tata Steel'],
            ['name' => 'GI Sheets', 'type' => 'Physical Product', 'brands' => 'Jindal'],
            ['name' => 'Binding Wire', 'type' => 'Physical Product', 'brands' => 'Dealer'],
            ['name' => 'Weld Mesh', 'type' => 'Physical Product', 'brands' => 'Tata Wiron'],
            ['name' => 'Roofing Steel', 'type' => 'Physical Product', 'brands' => 'Tata BlueScope'],
            ['name' => 'Fabricated Steel', 'type' => 'Physical Product', 'brands' => 'Dealer'],
            ['name' => 'Stainless Steel Bars', 'type' => 'Physical Product', 'brands' => 'Jindal Stainless'],
            ['name' => 'Steel Pipes', 'type' => 'Physical Product', 'brands' => 'Jindal Pipes'],
            ['name' => 'MS Pipes', 'type' => 'Physical Product', 'brands' => 'APL Apollo'],
            ['name' => 'Hollow Sections', 'type' => 'Physical Product', 'brands' => 'APL Apollo'],
            ['name' => 'Bulk Steel Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Site Delivery', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Contractor Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Builder Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Steel Cutting', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Steel Bending', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Custom Fabrication', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Quantity Estimation', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Material Consultation', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Wholesale Distribution', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Retail Sales', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Credit Facility', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Online Ordering', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Transportation', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Loading & Unloading', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Material Testing Certificate', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Emergency Delivery', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Dealer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Brick & Block Manufacturer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Clay Bricks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Fly Ash Bricks', 'type' => 'Physical Product', 'brands' => 'Magicrete'],
            ['name' => 'AAC Blocks', 'type' => 'Physical Product', 'brands' => 'Magicrete'],
            ['name' => 'Solid Concrete Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Hollow Concrete Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Interlocking Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Paver Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Kerb Stones', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Cement Bricks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Lightweight Blocks', 'type' => 'Physical Product', 'brands' => 'Magicrete'],
            ['name' => 'Fire Bricks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Refractory Bricks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Partition Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Boundary Wall Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'U-Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Lintel Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Decorative Concrete Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Designer Bricks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Ready Masonry Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Building Blocks', 'type' => 'Physical Product', 'brands' => 'Manufacturer'],
            ['name' => 'Bulk Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Contractor Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Builder Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Project Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Wholesale Distribution', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Retail Sales', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Site Delivery', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Custom Block Manufacturing', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Color Block Manufacturing', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Product Testing', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'ISI Quality Certification', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Material Consultation', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Quantity Estimation', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Online Orders', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Transportation', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Loading & Unloading', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Dealer Network Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'After Sales Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Construction & Infrastructure Sub Categories 34.1 to 34.9.\n";
