<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Ready Mix Concrete (RMC) Supplier',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'M10 Ready Mix Concrete', 'type' => 'Product', 'brands' => 'UltraTech RMC'],
            ['name' => 'M15 Ready Mix Concrete', 'type' => 'Product', 'brands' => 'UltraTech RMC'],
            ['name' => 'M20 Ready Mix Concrete', 'type' => 'Product', 'brands' => 'ACC Ready Mix'],
            ['name' => 'M25 Ready Mix Concrete', 'type' => 'Product', 'brands' => 'Prism RMC'],
            ['name' => 'M30 Ready Mix Concrete', 'type' => 'Product', 'brands' => 'Nuvoco RMC'],
            ['name' => 'M35 Ready Mix Concrete', 'type' => 'Product', 'brands' => 'UltraTech RMC'],
            ['name' => 'M40 Ready Mix Concrete', 'type' => 'Product', 'brands' => 'ACC Ready Mix'],
            ['name' => 'High Strength Concrete', 'type' => 'Product', 'brands' => 'Prism RMC'],
            ['name' => 'Self Compacting Concrete', 'type' => 'Product', 'brands' => 'UltraTech RMC'],
            ['name' => 'Fiber Reinforced Concrete', 'type' => 'Product', 'brands' => 'Master Builders Solutions'],
            ['name' => 'Lightweight Concrete', 'type' => 'Product', 'brands' => 'Nuvoco RMC'],
            ['name' => 'Pumpable Concrete', 'type' => 'Product', 'brands' => 'ACC Ready Mix'],
            ['name' => 'Waterproof Concrete', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Decorative Concrete', 'type' => 'Product', 'brands' => 'Prism RMC'],
            ['name' => 'Pavement Concrete', 'type' => 'Product', 'brands' => 'UltraTech RMC'],
            ['name' => 'Transit Mixer Supply', 'type' => 'Service', 'brands' => 'Schwing Stetter'],
            ['name' => 'Concrete Pump Service', 'type' => 'Service', 'brands' => 'Putzmeister'],
            ['name' => 'Boom Pump Service', 'type' => 'Service', 'brands' => 'Schwing Stetter'],
            ['name' => 'Site Concrete Delivery', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Cube Testing', 'type' => 'Service', 'brands' => 'NABL Laboratory'],
            ['name' => 'Slump Testing', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Mix Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Concrete Admixtures', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Plasticizers', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Superplasticizers', 'type' => 'Product', 'brands' => 'Master Builders Solutions'],
            ['name' => 'Retarding Admixtures', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Accelerating Admixtures', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Concrete Technical Support', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Site Engineer Support', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Bulk Concrete Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Mega Project Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Annual Supply Contract', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Emergency Concrete Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => '24×7 Concrete Delivery', 'type' => 'Service', 'brands' => 'Supplier'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Civil Engineering Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Civil Engineering Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Site Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Feasibility Study', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'DPR Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Site Survey', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'Topographic Survey', 'type' => 'Service', 'brands' => 'Topcon'],
            ['name' => 'Land Development Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Infrastructure Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Road Design', 'type' => 'Service', 'brands' => 'Civil 3D'],
            ['name' => 'Drainage Design', 'type' => 'Service', 'brands' => 'Bentley OpenFlows'],
            ['name' => 'Water Supply Design', 'type' => 'Service', 'brands' => 'Bentley WaterGEMS'],
            ['name' => 'Sewerage Design', 'type' => 'Service', 'brands' => 'Bentley SewerGEMS'],
            ['name' => 'Storm Water Design', 'type' => 'Service', 'brands' => 'Bentley OpenFlows'],
            ['name' => 'Earthwork Calculation', 'type' => 'Service', 'brands' => 'Civil 3D'],
            ['name' => 'Quantity Estimation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'BOQ Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Cost Estimation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Tender Documentation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Construction Supervision', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Quality Control', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Structural Coordination', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Utility Coordination', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Value Engineering', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Monitoring', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Risk Assessment', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Environmental Compliance', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Technical Due Diligence', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Third Party Inspection', 'type' => 'Service', 'brands' => 'Bureau Veritas'],
            ['name' => 'Project Reporting', 'type' => 'Software', 'brands' => 'Microsoft Project'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Expert Opinion', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'After Project Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Remote Consultation', 'type' => 'Service', 'brands' => 'Microsoft Teams'],
            ['name' => '24×7 Technical Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Construction Material Supplier',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Ordinary Portland Cement (OPC)', 'type' => 'Product', 'brands' => 'UltraTech Cement'],
            ['name' => 'Portland Pozzolana Cement (PPC)', 'type' => 'Product', 'brands' => 'ACC Cement'],
            ['name' => 'Portland Slag Cement (PSC)', 'type' => 'Product', 'brands' => 'Ambuja Cement'],
            ['name' => 'TMT Steel Bars', 'type' => 'Product', 'brands' => 'Tata Tiscon'],
            ['name' => 'Structural Steel', 'type' => 'Product', 'brands' => 'JSW Steel'],
            ['name' => 'Binding Wire', 'type' => 'Product', 'brands' => 'Tata Steel'],
            ['name' => 'River Sand', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'M-Sand', 'type' => 'Product', 'brands' => 'RoboSand'],
            ['name' => 'Crushed Stone Aggregate', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'Fly Ash Bricks', 'type' => 'Product', 'brands' => 'Magicrete'],
            ['name' => 'AAC Blocks', 'type' => 'Product', 'brands' => 'Magicrete'],
            ['name' => 'Concrete Blocks', 'type' => 'Product', 'brands' => 'UltraTech Building Solutions'],
            ['name' => 'Red Clay Bricks', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'Paver Blocks', 'type' => 'Product', 'brands' => 'UltraTech Building Products'],
            ['name' => 'Kerb Stones', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'RCC Pipes', 'type' => 'Product', 'brands' => 'Hume Pipe'],
            ['name' => 'HDPE Pipes', 'type' => 'Product', 'brands' => 'Supreme Industries'],
            ['name' => 'PVC Pipes', 'type' => 'Product', 'brands' => 'Astral Pipes'],
            ['name' => 'CPVC Pipes', 'type' => 'Product', 'brands' => 'Ashirvad Pipes'],
            ['name' => 'Water Storage Tanks', 'type' => 'Product', 'brands' => 'Sintex'],
            ['name' => 'Waterproofing Chemicals', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Construction Chemicals', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Tile Adhesive', 'type' => 'Product', 'brands' => 'MYK LATICRETE'],
            ['name' => 'Wall Putty', 'type' => 'Product', 'brands' => 'Birla White'],
            ['name' => 'Ready Mix Plaster', 'type' => 'Product', 'brands' => 'Saint-Gobain Weber'],
            ['name' => 'Gypsum Powder', 'type' => 'Product', 'brands' => 'Saint-Gobain Gyproc'],
            ['name' => 'Roofing Sheets', 'type' => 'Product', 'brands' => 'Tata BlueScope Steel'],
            ['name' => 'Barbed Wire', 'type' => 'Product', 'brands' => 'Tata Wiron'],
            ['name' => 'Weld Mesh', 'type' => 'Product', 'brands' => 'Bekaert'],
            ['name' => 'Safety Equipment', 'type' => 'Product', 'brands' => 'KARAM'],
            ['name' => 'Bulk Material Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Site Delivery', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Material Consultation', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Credit Supply Facility', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => '24×7 Material Supply', 'type' => 'Service', 'brands' => 'Supplier'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Construction Chemical Supplier',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Concrete Admixtures', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Superplasticizer', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Plasticizer', 'type' => 'Product', 'brands' => 'Master Builders Solutions'],
            ['name' => 'Waterproofing Compound', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Integral Waterproofing Compound', 'type' => 'Product', 'brands' => 'MYK Arment'],
            ['name' => 'Bonding Agent', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Epoxy Resin', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Epoxy Grout', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Non-Shrink Grout', 'type' => 'Product', 'brands' => 'Master Builders Solutions'],
            ['name' => 'Tile Adhesive', 'type' => 'Product', 'brands' => 'MYK LATICRETE'],
            ['name' => 'Tile Grout', 'type' => 'Product', 'brands' => 'Roff'],
            ['name' => 'Crack Repair Mortar', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Repair Mortar', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Micro Concrete', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Floor Hardener', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Epoxy Flooring System', 'type' => 'Product', 'brands' => 'Flowcrete'],
            ['name' => 'PU Flooring', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Protective Coating', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Anti-Carbonation Coating', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Concrete Curing Compound', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Release Agent', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Anchoring Chemical', 'type' => 'Product', 'brands' => 'Hilti'],
            ['name' => 'Injection Grout', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Joint Sealant', 'type' => 'Product', 'brands' => 'Dow'],
            ['name' => 'Silicone Sealant', 'type' => 'Product', 'brands' => 'Dow'],
            ['name' => 'Fire Stop Sealant', 'type' => 'Product', 'brands' => 'Hilti'],
            ['name' => 'Waterproof Membrane', 'type' => 'Product', 'brands' => 'STP Limited'],
            ['name' => 'Concrete Repair System', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Industrial Flooring Solution', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Technical Site Visit', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Product Demonstration', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Material Recommendation', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Contractor Training', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Bulk Chemical Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => '24×7 Technical Support', 'type' => 'Service', 'brands' => 'Supplier'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Surveying & Mapping Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Land Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Topographic Survey', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'DGPS Survey', 'type' => 'Service', 'brands' => 'Trimble'],
            ['name' => 'Total Station Survey', 'type' => 'Product', 'brands' => 'Topcon'],
            ['name' => 'GPS Survey', 'type' => 'Product', 'brands' => 'Trimble'],
            ['name' => 'Boundary Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Contour Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Route Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Alignment Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Construction Layout Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Building Setting Out', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Road Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Railway Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Canal Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Pipeline Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Utility Mapping', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Underground Utility Detection', 'type' => 'Product', 'brands' => 'Leica Geosystems'],
            ['name' => 'GIS Mapping', 'type' => 'Software', 'brands' => 'ArcGIS'],
            ['name' => 'Drone Survey', 'type' => 'Service', 'brands' => 'DJI Enterprise'],
            ['name' => 'UAV Mapping', 'type' => 'Product', 'brands' => 'DJI Enterprise'],
            ['name' => 'LiDAR Survey', 'type' => 'Product', 'brands' => 'Leica Geosystems'],
            ['name' => 'Hydrographic Survey', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Volume Calculation', 'type' => 'Software', 'brands' => 'Civil 3D'],
            ['name' => 'Earthwork Measurement', 'type' => 'Software', 'brands' => 'Civil 3D'],
            ['name' => 'Digital Terrain Model (DTM)', 'type' => 'Software', 'brands' => 'Bentley OpenRoads'],
            ['name' => 'Point Cloud Processing', 'type' => 'Software', 'brands' => 'Autodesk Recap'],
            ['name' => 'CAD Mapping', 'type' => 'Software', 'brands' => 'AutoCAD'],
            ['name' => 'Survey Report', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Land Record Verification', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Survey Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Site Monitoring', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Survey Data Processing', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Remote Survey Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '24×7 Survey Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Construction Safety Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Construction Safety Audit', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Site Safety Inspection', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'HSE Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Safety Risk Assessment', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Job Safety Analysis (JSA)', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Method Statement Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Permit to Work System', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Safety Training', 'type' => 'Service', 'brands' => 'NEBOSH'],
            ['name' => 'Toolbox Talk', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Emergency Response Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Fire Safety Audit', 'type' => 'Service', 'brands' => 'Honeywell'],
            ['name' => 'Fire Evacuation Plan', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Scaffolding Safety Inspection', 'type' => 'Service', 'brands' => 'Layher'],
            ['name' => 'Lifting Plan', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Crane Safety Inspection', 'type' => 'Service', 'brands' => 'Liebherr'],
            ['name' => 'Electrical Safety Audit', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'PPE Consultation', 'type' => 'Product', 'brands' => 'KARAM'],
            ['name' => 'Fall Protection System', 'type' => 'Product', 'brands' => '3M Protecta'],
            ['name' => 'Confined Space Safety', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Work at Height Safety', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Excavation Safety', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Temporary Structure Safety', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Environmental Health & Safety', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Incident Investigation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Safety Documentation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'ISO 45001 Consultancy', 'type' => 'Service', 'brands' => 'BSI'],
            ['name' => 'Safety Compliance Audit', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Third Party Safety Inspection', 'type' => 'Service', 'brands' => 'Bureau Veritas'],
            ['name' => 'Site Safety Officer Deployment', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Safety Signage Supply', 'type' => 'Product', 'brands' => 'Brady'],
            ['name' => 'Monthly Safety Review', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Annual Safety Contract', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Online Safety Training', 'type' => 'Service', 'brands' => 'Microsoft Teams'],
            ['name' => 'Emergency Safety Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '24×7 HSE Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Elevator & Escalator Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Passenger Elevator', 'type' => 'Product', 'brands' => 'Otis'],
            ['name' => 'Hospital Elevator', 'type' => 'Product', 'brands' => 'KONE'],
            ['name' => 'Home Elevator', 'type' => 'Product', 'brands' => 'Schindler'],
            ['name' => 'Goods Lift', 'type' => 'Product', 'brands' => 'Johnson Lifts'],
            ['name' => 'Freight Elevator', 'type' => 'Product', 'brands' => 'Otis'],
            ['name' => 'Capsule Elevator', 'type' => 'Product', 'brands' => 'Mitsubishi Electric'],
            ['name' => 'Machine Room Less (MRL) Lift', 'type' => 'Product', 'brands' => 'KONE'],
            ['name' => 'Hydraulic Lift', 'type' => 'Product', 'brands' => 'GMV'],
            ['name' => 'Dumbwaiter Lift', 'type' => 'Product', 'brands' => 'Johnson Lifts'],
            ['name' => 'Escalator', 'type' => 'Product', 'brands' => 'Schindler'],
            ['name' => 'Moving Walkway', 'type' => 'Product', 'brands' => 'Otis'],
            ['name' => 'Car Lift', 'type' => 'Product', 'brands' => 'Hyundai Elevator'],
            ['name' => 'Automobile Elevator', 'type' => 'Product', 'brands' => 'KONE'],
            ['name' => 'Lift Modernization', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Elevator Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Escalator Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Lift Commissioning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Lift AMC', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Preventive Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Breakdown Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Lift Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Spare Parts Supply', 'type' => 'Product', 'brands' => 'Otis'],
            ['name' => 'Elevator Controller Upgrade', 'type' => 'Product', 'brands' => 'Mitsubishi Electric'],
            ['name' => 'VVVF Drive Upgrade', 'type' => 'Product', 'brands' => 'Fuji Electric'],
            ['name' => 'Lift Cabin Interior', 'type' => 'Product', 'brands' => 'Contractor'],
            ['name' => 'Lift Door Operator', 'type' => 'Product', 'brands' => 'Fermator'],
            ['name' => 'Landing Doors', 'type' => 'Product', 'brands' => 'Otis'],
            ['name' => 'Safety Inspection', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Elevator Safety Audit', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Third Party Lift Inspection', 'type' => 'Service', 'brands' => 'TÜV SÜD'],
            ['name' => 'Annual Safety Certification', 'type' => 'Service', 'brands' => 'TÜV Rheinland'],
            ['name' => 'Remote Monitoring', 'type' => 'Software', 'brands' => 'KONE 24/7 Connected Services'],
            ['name' => 'IoT Lift Monitoring', 'type' => 'Software', 'brands' => 'Otis ONE'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Emergency Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Prefabricated Building Manufacturer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Prefabricated House', 'type' => 'Product', 'brands' => 'EPACK Prefab'],
            ['name' => 'Portable Cabin', 'type' => 'Product', 'brands' => 'Everest Industries'],
            ['name' => 'Portable Office', 'type' => 'Product', 'brands' => 'EPACK Prefab'],
            ['name' => 'Site Office Cabin', 'type' => 'Product', 'brands' => 'BMarko Structures'],
            ['name' => 'Security Cabin', 'type' => 'Product', 'brands' => 'EPACK Prefab'],
            ['name' => 'Portable Toilet', 'type' => 'Product', 'brands' => 'Sintex'],
            ['name' => 'Labour Accommodation Cabin', 'type' => 'Product', 'brands' => 'EPACK Prefab'],
            ['name' => 'Modular Classroom', 'type' => 'Product', 'brands' => 'Everest Industries'],
            ['name' => 'Prefabricated School Building', 'type' => 'Product', 'brands' => 'EPACK Prefab'],
            ['name' => 'Modular Hospital Building', 'type' => 'Product', 'brands' => 'EPACK Prefab'],
            ['name' => 'Prefabricated Warehouse', 'type' => 'Product', 'brands' => 'Interarch'],
            ['name' => 'Modular Office Building', 'type' => 'Product', 'brands' => 'Kirby Building Systems'],
            ['name' => 'Portable Container Office', 'type' => 'Product', 'brands' => 'BMarko Structures'],
            ['name' => 'Shipping Container Office', 'type' => 'Product', 'brands' => 'BMarko Structures'],
            ['name' => 'Modular Kitchen Unit', 'type' => 'Product', 'brands' => 'Manufacturer'],
            ['name' => 'Prefab Bathroom Unit', 'type' => 'Product', 'brands' => 'Manufacturer'],
            ['name' => 'Sandwich Panel', 'type' => 'Product', 'brands' => 'Kingspan'],
            ['name' => 'PUF Panel', 'type' => 'Product', 'brands' => 'Metecno'],
            ['name' => 'Rockwool Panel', 'type' => 'Product', 'brands' => 'Tata BlueScope Steel'],
            ['name' => 'EPS Panel', 'type' => 'Product', 'brands' => 'EPACK Prefab'],
            ['name' => 'Steel Frame Structure', 'type' => 'Product', 'brands' => 'Tata Steel'],
            ['name' => 'Turnkey Prefab Solution', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Design & Engineering', 'type' => 'Service', 'brands' => 'AutoCAD'],
            ['name' => 'Fabrication', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Transportation', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Installation', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Foundation Coordination', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Electrical Integration', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Plumbing Integration', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'HVAC Integration', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'AMC Service', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Expansion & Relocation', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Building Demolition & Recycling Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Building Demolition', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Industrial Demolition', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Selective Demolition', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Interior Strip-Out', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Concrete Crushing', 'type' => 'Service', 'brands' => 'Metso'],
            ['name' => 'Concrete Recycling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Asphalt Recycling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Steel Scrap Recovery', 'type' => 'Service', 'brands' => 'Tata Steel'],
            ['name' => 'Scrap Metal Recycling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Construction Waste Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Debris Removal', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Waste Segregation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'C&D Waste Recycling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Mobile Crusher Service', 'type' => 'Product', 'brands' => 'Metso'],
            ['name' => 'Mobile Screening Plant', 'type' => 'Product', 'brands' => 'Sandvik'],
            ['name' => 'Hydraulic Breaker', 'type' => 'Product', 'brands' => 'Epiroc'],
            ['name' => 'Excavator Demolition', 'type' => 'Product', 'brands' => 'Caterpillar'],
            ['name' => 'Dust Suppression System', 'type' => 'Product', 'brands' => 'BOSSTEK'],
            ['name' => 'Noise Control System', 'type' => 'Product', 'brands' => 'Contractor'],
            ['name' => 'Hazardous Material Handling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Site Clearance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Land Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Material Salvaging', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Structural Dismantling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'RCC Structure Removal', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Bridge Demolition', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Chimney Demolition', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Controlled Blasting Coordination', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Environmental Compliance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Recycling Consultation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Sustainability Reporting', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Site Safety Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Demolition Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Site Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Infrastructure Development Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Smart City Projects', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Urban Infrastructure Development', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Township Development', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Industrial Infrastructure', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'SEZ Development', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Road Infrastructure', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Bridge Infrastructure', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Metro Infrastructure', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Airport Infrastructure', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Railway Infrastructure', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Water Supply Infrastructure', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Sewerage Infrastructure', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Storm Water Drainage', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Underground Utility Works', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Utility Corridor Development', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Smart Utility Network', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Public Infrastructure Projects', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'EPC Infrastructure Projects', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Civil Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Earthwork & Excavation', 'type' => 'Service', 'brands' => 'Caterpillar'],
            ['name' => 'Project Planning', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'BIM Coordination', 'type' => 'Service', 'brands' => 'Autodesk Revit'],
            ['name' => 'Construction Supervision', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Quality Control', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Safety Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Environmental Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Procurement Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Vendor Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Contract Administration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Monitoring', 'type' => 'Software', 'brands' => 'Microsoft Project'],
            ['name' => 'Digital Progress Dashboard', 'type' => 'Software', 'brands' => 'Procore'],
            ['name' => 'Turnkey Infrastructure Solution', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Maintenance Support', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Project Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Road Marking & Traffic Safety Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Thermoplastic Road Marking', 'type' => 'Product', 'brands' => '3M'],
            ['name' => 'Cold Paint Road Marking', 'type' => 'Product', 'brands' => 'Asian Paints PPG'],
            ['name' => 'Reflective Road Marking', 'type' => 'Product', 'brands' => '3M'],
            ['name' => 'Lane Marking', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Zebra Crossing Marking', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Stop Line Marking', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Directional Arrow Marking', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Parking Line Marking', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Airport Runway Marking', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Road Stud Installation', 'type' => 'Product', 'brands' => '3M'],
            ['name' => 'Solar Road Stud', 'type' => 'Product', 'brands' => 'Tata Power Solar'],
            ['name' => 'Cat Eye Reflectors', 'type' => 'Product', 'brands' => '3M'],
            ['name' => 'Delineators', 'type' => 'Product', 'brands' => '3M'],
            ['name' => 'Crash Barrier Installation', 'type' => 'Product', 'brands' => 'Tata Steel'],
            ['name' => 'W Beam Crash Barrier', 'type' => 'Product', 'brands' => 'Tata Steel'],
            ['name' => 'Guard Rail Installation', 'type' => 'Product', 'brands' => 'Tata Steel'],
            ['name' => 'Traffic Sign Boards', 'type' => 'Product', 'brands' => '3M'],
            ['name' => 'Retro Reflective Signage', 'type' => 'Product', 'brands' => 'Avery Dennison'],
            ['name' => 'Convex Safety Mirror', 'type' => 'Product', 'brands' => 'KARAM'],
            ['name' => 'Speed Breaker Installation', 'type' => 'Product', 'brands' => 'Sintex'],
            ['name' => 'Rubber Speed Hump', 'type' => 'Product', 'brands' => 'Sintex'],
            ['name' => 'Bollards', 'type' => 'Product', 'brands' => 'Tata Steel'],
            ['name' => 'Traffic Cones', 'type' => 'Product', 'brands' => 'KARAM'],
            ['name' => 'Safety Barricades', 'type' => 'Product', 'brands' => 'Tata Steel'],
            ['name' => 'Road Safety Audit', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Traffic Management Plan', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Work Zone Safety', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Highway Safety Solutions', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'School Zone Safety', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Industrial Traffic Safety', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Road Marking Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Road Safety Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'On-Site Inspection', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Traffic Safety Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Tunnel Construction Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Highway Tunnel Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Railway Tunnel Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Metro Tunnel Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Water Tunnel Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Utility Tunnel Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'TBM Excavation', 'type' => 'Product', 'brands' => 'Herrenknecht'],
            ['name' => 'Drill & Blast Tunneling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'NATM Tunneling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Tunnel Lining', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Segment Lining', 'type' => 'Product', 'brands' => 'Contractor'],
            ['name' => 'Rock Bolting', 'type' => 'Product', 'brands' => 'DSI Underground'],
            ['name' => 'Shotcrete Application', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Tunnel Waterproofing', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Ground Support System', 'type' => 'Product', 'brands' => 'DSI Underground'],
            ['name' => 'Ventilation System', 'type' => 'Product', 'brands' => 'Systemair'],
            ['name' => 'Tunnel Lighting', 'type' => 'Product', 'brands' => 'Philips'],
            ['name' => 'Drainage System', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Dewatering System', 'type' => 'Product', 'brands' => 'Xylem'],
            ['name' => 'Geotechnical Monitoring', 'type' => 'Service', 'brands' => 'Sisgeo'],
            ['name' => 'Survey & Alignment', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'Tunnel Instrumentation', 'type' => 'Product', 'brands' => 'Sisgeo'],
            ['name' => 'Seismic Monitoring', 'type' => 'Product', 'brands' => 'Geosense'],
            ['name' => 'TBM Maintenance', 'type' => 'Service', 'brands' => 'Herrenknecht'],
            ['name' => 'Tunnel MEP Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Fire Protection System', 'type' => 'Product', 'brands' => 'Honeywell'],
            ['name' => 'Emergency Escape System', 'type' => 'Product', 'brands' => 'Contractor'],
            ['name' => 'Tunnel Safety Audit', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Environmental Monitoring', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Quality Control', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Testing & Commissioning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Tunnel Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Tunnel Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Tunnel Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Railway Construction Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Railway Track Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'High-Speed Rail Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Metro Rail Track Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Rail Yard Development', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Railway Station Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Ballast Supply', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'Rail Track Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Rail Welding', 'type' => 'Service', 'brands' => 'Pandrol'],
            ['name' => 'Long Welded Rail (LWR)', 'type' => 'Product', 'brands' => 'SAIL'],
            ['name' => 'Turnout Installation', 'type' => 'Product', 'brands' => 'Vossloh'],
            ['name' => 'Railway Sleepers', 'type' => 'Product', 'brands' => 'Indian Hume Pipe'],
            ['name' => 'PSC Sleepers', 'type' => 'Product', 'brands' => 'Indian Hume Pipe'],
            ['name' => 'Rail Fastening System', 'type' => 'Product', 'brands' => 'Pandrol'],
            ['name' => 'Overhead Electrification (OHE)', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'Traction Substation', 'type' => 'Product', 'brands' => 'ABB'],
            ['name' => 'Signalling & Telecommunication', 'type' => 'Product', 'brands' => 'Alstom'],
            ['name' => 'Automatic Signalling', 'type' => 'Product', 'brands' => 'Siemens'],
            ['name' => 'Railway Bridge Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Railway Tunnel Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Platform Development', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Drainage Works', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Earthwork & Embankment', 'type' => 'Service', 'brands' => 'Caterpillar'],
            ['name' => 'Track Geometry Survey', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'Track Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Rail Grinding', 'type' => 'Service', 'brands' => 'Loram'],
            ['name' => 'Track Inspection', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Safety Compliance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Planning', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Project Monitoring', 'type' => 'Software', 'brands' => 'Microsoft Project'],
            ['name' => 'Testing & Commissioning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Railway Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Track Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Railway Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Airport Construction Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Airport Terminal Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Runway Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Taxiway Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Apron Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Hangar Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Air Traffic Control Tower', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Airport Road Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Passenger Boarding Bridge Installation', 'type' => 'Product', 'brands' => 'TK Elevator'],
            ['name' => 'Baggage Handling System', 'type' => 'Product', 'brands' => 'Siemens Logistics'],
            ['name' => 'Airfield Lighting System', 'type' => 'Product', 'brands' => 'ADB SAFEGATE'],
            ['name' => 'Runway Lighting', 'type' => 'Product', 'brands' => 'ADB SAFEGATE'],
            ['name' => 'Navigational Aid Infrastructure', 'type' => 'Product', 'brands' => 'Honeywell'],
            ['name' => 'Fuel Farm Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Aircraft Parking Bay', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Storm Water Drainage', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Perimeter Security Fence', 'type' => 'Product', 'brands' => 'Bekaert'],
            ['name' => 'Airport Fire Station', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Fire Protection System', 'type' => 'Product', 'brands' => 'Honeywell'],
            ['name' => 'Utility Infrastructure', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'MEP Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Structural Steel Work', 'type' => 'Product', 'brands' => 'Tata Steel'],
            ['name' => 'Glass Facade', 'type' => 'Product', 'brands' => 'Saint-Gobain Glass'],
            ['name' => 'Pavement Quality Concrete', 'type' => 'Product', 'brands' => 'UltraTech Cement'],
            ['name' => 'Asphalt Paving', 'type' => 'Product', 'brands' => 'VG-30 Bitumen'],
            ['name' => 'Geotechnical Investigation', 'type' => 'Service', 'brands' => 'Fugro'],
            ['name' => 'Survey & Mapping', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'BIM Coordination', 'type' => 'Service', 'brands' => 'Autodesk Revit'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Safety Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Environmental Compliance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Testing & Commissioning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Infrastructure Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Airport Project Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Dam & Irrigation Project Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Dam Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Irrigation Canal Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Barrage Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Check Dam Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Reservoir Development', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Spillway Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Canal Lining', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Lift Irrigation Project', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Pump House Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Water Intake Structure', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Sluice Gate Installation', 'type' => 'Product', 'brands' => 'Orbinox'],
            ['name' => 'Radial Gate Installation', 'type' => 'Product', 'brands' => 'Orbinox'],
            ['name' => 'Penstock Fabrication', 'type' => 'Product', 'brands' => 'Tata Steel'],
            ['name' => 'Hydro Mechanical Equipment', 'type' => 'Product', 'brands' => 'Kirloskar Brothers'],
            ['name' => 'Water Control Valves', 'type' => 'Product', 'brands' => 'AVK'],
            ['name' => 'Dewatering System', 'type' => 'Product', 'brands' => 'Xylem'],
            ['name' => 'Earth Dam Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'RCC Dam Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Roller Compacted Concrete (RCC) Dam', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Embankment Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'River Diversion Works', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Soil Stabilization', 'type' => 'Product', 'brands' => 'Keller'],
            ['name' => 'Geotextile Installation', 'type' => 'Product', 'brands' => 'HUESKER'],
            ['name' => 'Survey & Mapping', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'Geotechnical Investigation', 'type' => 'Service', 'brands' => 'Fugro'],
            ['name' => 'Environmental Impact Assessment Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Instrumentation & Monitoring', 'type' => 'Product', 'brands' => 'Sisgeo'],
            ['name' => 'Structural Health Monitoring', 'type' => 'Product', 'brands' => 'Geokon'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Safety Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Planning', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Testing & Commissioning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Dam Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Repair Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Project Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds,
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Construction & Infrastructure Sub Categories 34.48 to 34.68.\n";
