<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Hostel',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Dormitory Bed', 'type' => 'Service', 'brands' => 'Zostel, goSTOPS'],
            ['name' => 'Mixed Dorm', 'type' => 'Service', 'brands' => 'Zostel'],
            ['name' => 'Female Dorm', 'type' => 'Service', 'brands' => 'goSTOPS'],
            ['name' => 'Male Dorm', 'type' => 'Service', 'brands' => 'goSTOPS'],
            ['name' => 'Private Room', 'type' => 'Service', 'brands' => 'Zostel'],
            ['name' => 'Twin Sharing Room', 'type' => 'Service', 'brands' => 'goSTOPS'],
            ['name' => 'Triple Sharing Room', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Family Room', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Monthly Stay', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Long-Term Stay', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Student Accommodation', 'type' => 'Service', 'brands' => 'Stanza Living'],
            ['name' => 'Working Professional Stay', 'type' => 'Service', 'brands' => 'Stanza Living'],
            ['name' => 'Backpacker Stay', 'type' => 'Service', 'brands' => 'Zostel'],
            ['name' => 'Group Booking', 'type' => 'Service', 'brands' => 'Zostel'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'Hostelworld'],
            ['name' => 'Free Wi-Fi', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Air Conditioned Room', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Laundry Service', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Housekeeping', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Shared Kitchen', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Cafeteria', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Common Lounge', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Co-Working Space', 'type' => 'Service', 'brands' => 'Zostel'],
            ['name' => 'Lockers', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Luggage Storage', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'CCTV Security', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => '24×7 Reception', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Biometric Entry', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Parking Facility', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Airport Pickup', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Local Tours', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Bike Rental', 'type' => 'Service', 'brands' => 'Royal Brothers'],
            ['name' => 'Car Rental', 'type' => 'Service', 'brands' => 'Zoomcar'],
            ['name' => 'Community Events', 'type' => 'Service', 'brands' => 'Zostel'],
            ['name' => 'Game Zone', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Rooftop Café', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Travel Desk', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Travel Assistance', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => 'Membership Program', 'type' => 'Service', 'brands' => 'Hostel'],
            ['name' => '24×7 Guest Support', 'type' => 'Service', 'brands' => 'Hostel'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Guest House',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Standard Room', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Deluxe Room', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Family Room', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Executive Room', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Single Occupancy', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Double Occupancy', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Triple Occupancy', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Group Stay', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Daily Stay', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Weekly Stay', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Monthly Stay', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'Booking.com'],
            ['name' => 'Walk-In Booking', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Complimentary Breakfast', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Room Service', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Housekeeping', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Laundry Service', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Free Wi-Fi', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Air Conditioned Rooms', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Parking Facility', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Airport Pickup', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Airport Drop', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Railway Station Pickup', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Local Sightseeing', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Car Rental', 'type' => 'Service', 'brands' => 'Zoomcar'],
            ['name' => 'Taxi Booking', 'type' => 'Service', 'brands' => 'Ola'],
            ['name' => 'Meeting Room', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Small Banquet Hall', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Business Stay Package', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Family Stay Package', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Long Stay Discount', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Corporate Booking', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Event Accommodation', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Travel Desk', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Concierge Service', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Luggage Storage', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => '24×7 Reception', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'CCTV Security', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => 'Personalized Stay Package', 'type' => 'Service', 'brands' => 'Guest House'],
            ['name' => '24×7 Guest Support', 'type' => 'Service', 'brands' => 'Guest House'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Visa & Passport Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Passport Application', 'type' => 'Service', 'brands' => 'Passport Seva'],
            ['name' => 'Passport Renewal', 'type' => 'Service', 'brands' => 'Passport Seva'],
            ['name' => 'Tatkal Passport Assistance', 'type' => 'Service', 'brands' => 'Passport Seva'],
            ['name' => 'Passport Reissue', 'type' => 'Service', 'brands' => 'Passport Seva'],
            ['name' => 'Lost Passport Assistance', 'type' => 'Service', 'brands' => 'Passport Seva'],
            ['name' => 'New Passport Consultation', 'type' => 'Service', 'brands' => 'Passport Consultant'],
            ['name' => 'Visa Consultation', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Tourist Visa', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Business Visa', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Student Visa', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Work Visa', 'type' => 'Service', 'brands' => 'Y-Axis'],
            ['name' => 'Visitor Visa', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Dependent Visa', 'type' => 'Service', 'brands' => 'Y-Axis'],
            ['name' => 'PR Visa Guidance', 'type' => 'Service', 'brands' => 'Y-Axis'],
            ['name' => 'Immigration Consultation', 'type' => 'Service', 'brands' => 'Y-Axis'],
            ['name' => 'Visa Documentation', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Visa Form Filling', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Visa Appointment Booking', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Biometrics Appointment', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Document Verification', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'SOP Preparation', 'type' => 'Service', 'brands' => 'Leverage Edu'],
            ['name' => 'Cover Letter Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Invitation Letter Guidance', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Flight Reservation for Visa', 'type' => 'Service', 'brands' => 'Travel Agency'],
            ['name' => 'Hotel Reservation for Visa', 'type' => 'Service', 'brands' => 'Travel Agency'],
            ['name' => 'Forex Assistance', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'Forex Card', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'Translation Services', 'type' => 'Service', 'brands' => 'Certified Translator'],
            ['name' => 'Notary Assistance', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Apostille Services', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Embassy Appointment', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Visa Tracking', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Passport Tracking', 'type' => 'Service', 'brands' => 'Passport Seva'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Family Visa Assistance', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Corporate Visa Services', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Student Counseling', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'End-to-End Visa Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Car Rental Service',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Self Drive Car Rental', 'type' => 'Service', 'brands' => 'Zoomcar'],
            ['name' => 'Chauffeur Driven Car', 'type' => 'Service', 'brands' => 'Savaari'],
            ['name' => 'Economy Car Rental', 'type' => 'Service', 'brands' => 'Maruti Suzuki'],
            ['name' => 'Sedan Rental', 'type' => 'Service', 'brands' => 'Honda City, Hyundai Verna'],
            ['name' => 'SUV Rental', 'type' => 'Service', 'brands' => 'Toyota Innova, Mahindra XUV700'],
            ['name' => 'Luxury Car Rental', 'type' => 'Service', 'brands' => 'Mercedes-Benz, BMW'],
            ['name' => 'Premium SUV Rental', 'type' => 'Service', 'brands' => 'Toyota Fortuner'],
            ['name' => 'Hatchback Rental', 'type' => 'Service', 'brands' => 'Hyundai i20'],
            ['name' => 'Airport Pickup', 'type' => 'Service', 'brands' => 'Ola Outstation'],
            ['name' => 'Airport Drop', 'type' => 'Service', 'brands' => 'Ola Outstation'],
            ['name' => 'Railway Station Pickup', 'type' => 'Service', 'brands' => 'Car Rental'],
            ['name' => 'Local City Rental', 'type' => 'Service', 'brands' => 'Savaari'],
            ['name' => 'Outstation Taxi', 'type' => 'Service', 'brands' => 'Savaari'],
            ['name' => 'One Way Taxi', 'type' => 'Service', 'brands' => 'Gozo Cabs'],
            ['name' => 'Round Trip Taxi', 'type' => 'Service', 'brands' => 'Savaari'],
            ['name' => 'Corporate Car Rental', 'type' => 'Service', 'brands' => 'Avis India'],
            ['name' => 'Wedding Car Rental', 'type' => 'Service', 'brands' => 'Luxury Ride'],
            ['name' => 'Event Transportation', 'type' => 'Service', 'brands' => 'Car Rental'],
            ['name' => 'Monthly Car Rental', 'type' => 'Service', 'brands' => 'Revv'],
            ['name' => 'Long-Term Leasing', 'type' => 'Service', 'brands' => 'LeasePlan'],
            ['name' => 'Luxury Chauffeur Service', 'type' => 'Service', 'brands' => 'Avis'],
            ['name' => 'Hourly Rental', 'type' => 'Service', 'brands' => 'Revv'],
            ['name' => 'Daily Rental', 'type' => 'Service', 'brands' => 'Zoomcar'],
            ['name' => 'Weekly Rental', 'type' => 'Service', 'brands' => 'Revv'],
            ['name' => 'GPS Navigation', 'type' => 'Service', 'brands' => 'Garmin'],
            ['name' => 'Child Seat Rental', 'type' => 'Service', 'brands' => 'Car Rental'],
            ['name' => 'Wi-Fi Enabled Vehicle', 'type' => 'Service', 'brands' => 'Car Rental'],
            ['name' => 'Driver on Demand', 'type' => 'Service', 'brands' => 'DriveU'],
            ['name' => 'Fuel Included Package', 'type' => 'Service', 'brands' => 'Car Rental'],
            ['name' => 'Unlimited Kilometer Package', 'type' => 'Service', 'brands' => 'Car Rental'],
            ['name' => 'Interstate Permit', 'type' => 'Service', 'brands' => 'Car Rental'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'Zoomcar'],
            ['name' => 'Mobile App Booking', 'type' => 'Service', 'brands' => 'Zoomcar'],
            ['name' => 'Fleet Management', 'type' => 'Service', 'brands' => 'Avis India'],
            ['name' => 'Roadside Assistance', 'type' => 'Service', 'brands' => '24x7 Assistance'],
            ['name' => 'Vehicle Sanitization', 'type' => 'Service', 'brands' => 'Car Rental'],
            ['name' => 'Customized Travel Package', 'type' => 'Service', 'brands' => 'Car Rental'],
            ['name' => 'Corporate Billing', 'type' => 'Service', 'brands' => 'Car Rental'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Car Rental'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Bike Rental Service',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Scooter Rental', 'type' => 'Service', 'brands' => 'Honda Activa, TVS Jupiter'],
            ['name' => 'Motorcycle Rental', 'type' => 'Service', 'brands' => 'Royal Brothers'],
            ['name' => 'Sports Bike Rental', 'type' => 'Service', 'brands' => 'Kawasaki, Yamaha'],
            ['name' => 'Cruiser Bike Rental', 'type' => 'Service', 'brands' => 'Royal Enfield'],
            ['name' => 'Adventure Bike Rental', 'type' => 'Service', 'brands' => 'Royal Enfield Himalayan, KTM Adventure'],
            ['name' => 'Electric Scooter Rental', 'type' => 'Service', 'brands' => 'Ola Electric, Ather'],
            ['name' => 'Electric Bike Rental', 'type' => 'Service', 'brands' => 'Revolt Motors'],
            ['name' => 'Hourly Bike Rental', 'type' => 'Service', 'brands' => 'Royal Brothers'],
            ['name' => 'Daily Bike Rental', 'type' => 'Service', 'brands' => 'Royal Brothers'],
            ['name' => 'Weekly Bike Rental', 'type' => 'Service', 'brands' => 'Royal Brothers'],
            ['name' => 'Monthly Bike Rental', 'type' => 'Service', 'brands' => 'ONN Bikes'],
            ['name' => 'Self Ride Bike Rental', 'type' => 'Service', 'brands' => 'ONN Bikes'],
            ['name' => 'Guided Bike Tour', 'type' => 'Service', 'brands' => 'Royal Enfield Rides'],
            ['name' => 'Group Ride Package', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
            ['name' => 'Ladakh Bike Expedition', 'type' => 'Service', 'brands' => 'Royal Enfield Rides'],
            ['name' => 'Leh–Ladakh Package', 'type' => 'Service', 'brands' => 'Thrillophilia'],
            ['name' => 'Goa Bike Rental', 'type' => 'Service', 'brands' => 'Local Rental Service'],
            ['name' => 'Helmet Rental', 'type' => 'Physical Product', 'brands' => 'Studds, Vega'],
            ['name' => 'Riding Jacket Rental', 'type' => 'Physical Product', 'brands' => 'Rynox'],
            ['name' => 'Riding Gloves Rental', 'type' => 'Physical Product', 'brands' => 'Rynox'],
            ['name' => 'Knee Guard Rental', 'type' => 'Physical Product', 'brands' => 'Rynox'],
            ['name' => 'Saddle Bag Rental', 'type' => 'Physical Product', 'brands' => 'Viaterra'],
            ['name' => 'GPS Navigation', 'type' => 'Service', 'brands' => 'Garmin'],
            ['name' => 'Roadside Assistance', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
            ['name' => 'Pickup & Drop Service', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
            ['name' => 'Airport Delivery', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
            ['name' => 'Hotel Delivery', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
            ['name' => 'Fuel Included Package', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
            ['name' => 'Unlimited Kilometer Package', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
            ['name' => 'One Way Rental', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
            ['name' => 'Corporate Bike Rental', 'type' => 'Service', 'brands' => 'Royal Brothers'],
            ['name' => 'Event Bike Rental', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
            ['name' => 'Bike Tour Planning', 'type' => 'Service', 'brands' => 'Royal Enfield Rides'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'ONN Bikes'],
            ['name' => 'Mobile App Booking', 'type' => 'Service', 'brands' => 'Royal Brothers'],
            ['name' => 'Membership Plan', 'type' => 'Service', 'brands' => 'ONN Bikes'],
            ['name' => 'Subscription Rental', 'type' => 'Service', 'brands' => 'ONN Bikes'],
            ['name' => 'Fleet Rental', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Bike Rental Company'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Camping & Trekking Organizer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Weekend Camping', 'type' => 'Service', 'brands' => 'Thrillophilia'],
            ['name' => 'Luxury Camping', 'type' => 'Service', 'brands' => 'Luxeglamp'],
            ['name' => 'Riverside Camping', 'type' => 'Service', 'brands' => 'Camp Riverside'],
            ['name' => 'Forest Camping', 'type' => 'Service', 'brands' => 'Jungle Camps India'],
            ['name' => 'Desert Camping', 'type' => 'Service', 'brands' => 'Rajasthan Camps'],
            ['name' => 'Beach Camping', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Mountain Camping', 'type' => 'Service', 'brands' => 'Indiahikes'],
            ['name' => 'Snow Camping', 'type' => 'Service', 'brands' => 'Indiahikes'],
            ['name' => 'Family Camping', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Kids Camping', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Corporate Camping', 'type' => 'Service', 'brands' => 'Adventure Nation'],
            ['name' => 'School Camping', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Trekking Expedition', 'type' => 'Service', 'brands' => 'Indiahikes'],
            ['name' => 'Beginner Trek', 'type' => 'Service', 'brands' => 'Indiahikes'],
            ['name' => 'Advanced Trek', 'type' => 'Service', 'brands' => 'Indiahikes'],
            ['name' => 'Himalayan Trek', 'type' => 'Service', 'brands' => 'Indiahikes'],
            ['name' => 'Night Trek', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Sunrise Trek', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Guided Trek', 'type' => 'Service', 'brands' => 'Certified Trek Leader'],
            ['name' => 'Nature Walk', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Wildlife Trek', 'type' => 'Service', 'brands' => 'Jungle Lodges'],
            ['name' => 'Bird Watching Tour', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Campfire Experience', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'BBQ Dinner', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Adventure Activities', 'type' => 'Service', 'brands' => 'Adventure Nation'],
            ['name' => 'Zipline', 'type' => 'Service', 'brands' => 'Flying Fox'],
            ['name' => 'Rock Climbing', 'type' => 'Service', 'brands' => 'Adventure Nation'],
            ['name' => 'Rappelling', 'type' => 'Service', 'brands' => 'Adventure Nation'],
            ['name' => 'Trekking Gear Rental', 'type' => 'Service', 'brands' => 'Decathlon'],
            ['name' => 'Tent Rental', 'type' => 'Physical Product', 'brands' => 'Quechua'],
            ['name' => 'Sleeping Bag Rental', 'type' => 'Physical Product', 'brands' => 'Quechua'],
            ['name' => 'Backpack Rental', 'type' => 'Physical Product', 'brands' => 'Wildcraft'],
            ['name' => 'Trekking Pole Rental', 'type' => 'Physical Product', 'brands' => 'Quechua'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Transportation', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Photography Tour', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'Thrillophilia'],
            ['name' => 'Customized Camping Package', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => 'Group Discount Package', 'type' => 'Service', 'brands' => 'Camp Organizer'],
            ['name' => '24×7 Tour Support', 'type' => 'Service', 'brands' => 'Camp Organizer'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Event & Destination Wedding Planner',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Destination Wedding Planning', 'type' => 'Service', 'brands' => 'Tamarind Global'],
            ['name' => 'Beach Wedding', 'type' => 'Service', 'brands' => 'WeddingSutra'],
            ['name' => 'Palace Wedding', 'type' => 'Service', 'brands' => 'Neemrana Hotels'],
            ['name' => 'Resort Wedding', 'type' => 'Service', 'brands' => 'Club Mahindra'],
            ['name' => 'Hill Station Wedding', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Luxury Wedding Planning', 'type' => 'Service', 'brands' => 'Tamarind Global'],
            ['name' => 'Intimate Wedding', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Wedding Venue Booking', 'type' => 'Service', 'brands' => 'WeddingWire India'],
            ['name' => 'Resort Booking', 'type' => 'Service', 'brands' => 'Booking.com'],
            ['name' => 'Hotel Booking', 'type' => 'Service', 'brands' => 'Marriott'],
            ['name' => 'Guest Accommodation', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Flight Booking', 'type' => 'Service', 'brands' => 'MakeMyTrip'],
            ['name' => 'Train Booking', 'type' => 'Service', 'brands' => 'IRCTC'],
            ['name' => 'Airport Transfers', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Guest Transportation', 'type' => 'Service', 'brands' => 'Savaari'],
            ['name' => 'Wedding Decor', 'type' => 'Service', 'brands' => 'Ferns N Petals'],
            ['name' => 'Floral Decoration', 'type' => 'Service', 'brands' => 'Ferns N Petals'],
            ['name' => 'Stage Decoration', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Wedding Catering', 'type' => 'Service', 'brands' => 'Catering Partner'],
            ['name' => 'Photography', 'type' => 'Service', 'brands' => 'Wedding Photographer'],
            ['name' => 'Cinematography', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Drone Photography', 'type' => 'Service', 'brands' => 'DJI'],
            ['name' => 'Entertainment Booking', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Celebrity Management', 'type' => 'Service', 'brands' => 'Event Management Company'],
            ['name' => 'DJ & Music', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Mehendi Event', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Haldi Ceremony', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Sangeet Night', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Reception Planning', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Invitation Design', 'type' => 'Service', 'brands' => 'Canva'],
            ['name' => 'Digital Invitation', 'type' => 'Service', 'brands' => 'Canva'],
            ['name' => 'Wedding Website', 'type' => 'Service', 'brands' => 'The Knot'],
            ['name' => 'Bridal Makeup Booking', 'type' => 'Service', 'brands' => 'Lakmé Salon'],
            ['name' => 'Groom Styling', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Honeymoon Planning', 'type' => 'Service', 'brands' => 'MakeMyTrip'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Vendor Management', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Budget Planning', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'End-to-End Wedding Management', 'type' => 'Service', 'brands' => 'Tamarind Global'],
            ['name' => '24×7 Event Support', 'type' => 'Service', 'brands' => 'Wedding Planner'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Pilgrimage Tour Operator',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Char Dham Yatra', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Kedarnath Yatra', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Badrinath Yatra', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Amarnath Yatra', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Vaishno Devi Yatra', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Somnath Tour', 'type' => 'Service', 'brands' => 'Gujarat Tourism'],
            ['name' => 'Dwarka Tour', 'type' => 'Service', 'brands' => 'Gujarat Tourism'],
            ['name' => 'Kashi Vishwanath Tour', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Ayodhya Tour', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Tirupati Balaji Tour', 'type' => 'Service', 'brands' => 'TTD'],
            ['name' => 'Shirdi Sai Baba Tour', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Jagannath Puri Tour', 'type' => 'Service', 'brands' => 'Odisha Tourism'],
            ['name' => 'Rameswaram Tour', 'type' => 'Service', 'brands' => 'Tamil Nadu Tourism'],
            ['name' => 'Ujjain Mahakal Tour', 'type' => 'Service', 'brands' => 'Madhya Pradesh Tourism'],
            ['name' => 'Sabarimala Tour', 'type' => 'Service', 'brands' => 'Kerala Tourism'],
            ['name' => 'Buddhist Circuit Tour', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Jain Pilgrimage Tour', 'type' => 'Service', 'brands' => 'Pilgrimage Operator'],
            ['name' => 'Sikh Pilgrimage Tour', 'type' => 'Service', 'brands' => 'Punjab Tourism'],
            ['name' => 'Church Pilgrimage Tour', 'type' => 'Service', 'brands' => 'Pilgrimage Operator'],
            ['name' => 'Hajj Package', 'type' => 'Service', 'brands' => 'Approved Hajj Operator'],
            ['name' => 'Umrah Package', 'type' => 'Service', 'brands' => 'AlHind Tours'],
            ['name' => 'Temple Darshan Booking', 'type' => 'Service', 'brands' => 'Temple Trust'],
            ['name' => 'VIP Darshan Assistance', 'type' => 'Service', 'brands' => 'Temple Trust'],
            ['name' => 'Hotel Booking', 'type' => 'Service', 'brands' => 'Booking.com'],
            ['name' => 'Dharamshala Booking', 'type' => 'Service', 'brands' => 'Pilgrimage Operator'],
            ['name' => 'Flight Booking', 'type' => 'Service', 'brands' => 'MakeMyTrip'],
            ['name' => 'Train Booking', 'type' => 'Service', 'brands' => 'IRCTC'],
            ['name' => 'Bus Booking', 'type' => 'Service', 'brands' => 'redBus'],
            ['name' => 'Local Transportation', 'type' => 'Service', 'brands' => 'Pilgrimage Operator'],
            ['name' => 'Tour Guide', 'type' => 'Service', 'brands' => 'Licensed Guide'],
            ['name' => 'Prasad Arrangement', 'type' => 'Service', 'brands' => 'Temple Trust'],
            ['name' => 'Pooja Booking', 'type' => 'Service', 'brands' => 'Temple Trust'],
            ['name' => 'Group Pilgrimage Tour', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Senior Citizen Pilgrimage', 'type' => 'Service', 'brands' => 'Veena World'],
            ['name' => 'Customized Religious Tour', 'type' => 'Service', 'brands' => 'Pilgrimage Operator'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'EMI Payment Option', 'type' => 'Service', 'brands' => 'Bajaj Finserv'],
            ['name' => 'Spiritual Retreat Package', 'type' => 'Service', 'brands' => 'Pilgrimage Operator'],
            ['name' => '24×7 Tour Support', 'type' => 'Service', 'brands' => 'Pilgrimage Operator'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Travel & Tourism Sub Categories 30.6 to 30.15.\n";
