<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Plumbing Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Residential Plumbing', 'type' => 'Service', 'brands' => 'Plumbing Contractor'],
            ['name' => 'Commercial Plumbing', 'type' => 'Service', 'brands' => 'Plumbing Contractor'],
            ['name' => 'Industrial Plumbing', 'type' => 'Service', 'brands' => 'Plumbing Contractor'],
            ['name' => 'Water Supply Line Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Drainage Line Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Sewer Line Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Rainwater Harvesting System', 'type' => 'Service', 'brands' => 'Supreme Industries'],
            ['name' => 'Borewell Pipeline Installation', 'type' => 'Service', 'brands' => 'Finolex'],
            ['name' => 'UPVC Pipe Installation', 'type' => 'Service', 'brands' => 'Astral'],
            ['name' => 'CPVC Pipe Installation', 'type' => 'Service', 'brands' => 'Ashirvad'],
            ['name' => 'PPR Pipe Installation', 'type' => 'Service', 'brands' => 'Supreme Industries'],
            ['name' => 'GI Pipe Installation', 'type' => 'Service', 'brands' => 'Jindal Pipes'],
            ['name' => 'Bathroom Plumbing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Kitchen Plumbing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Water Tank Installation', 'type' => 'Service', 'brands' => 'Sintex'],
            ['name' => 'Water Pump Installation', 'type' => 'Service', 'brands' => 'Kirloskar'],
            ['name' => 'Pressure Pump Installation', 'type' => 'Service', 'brands' => 'Grundfos'],
            ['name' => 'Solar Water Heater Plumbing', 'type' => 'Service', 'brands' => 'Racold'],
            ['name' => 'Water Filter Plumbing', 'type' => 'Service', 'brands' => 'Kent'],
            ['name' => 'Sanitary Fitting Installation', 'type' => 'Service', 'brands' => 'Jaquar'],
            ['name' => 'Leak Detection', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Pipe Leakage Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Blocked Drain Cleaning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Jetting Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Pipe Replacement', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Valve Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Plumbing Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Maintenance Contract', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Plumbing Inspection', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Water Pressure Testing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Plumbing Design', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'BOQ Preparation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Site Supervision', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Plumbing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Smart Plumbing Solutions', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Material Supply', 'type' => 'Physical Product', 'brands' => 'Astral'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'After Sales Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Emergency Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Electrical Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Residential Electrical Work', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Commercial Electrical Work', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Industrial Electrical Work', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Electrical Wiring', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Rewiring Services', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'HT Electrical Installation', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'LT Electrical Installation', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Electrical Panel Installation', 'type' => 'Service', 'brands' => 'L&T Electrical'],
            ['name' => 'Distribution Board Installation', 'type' => 'Service', 'brands' => 'Havells'],
            ['name' => 'Earthing System', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Lightning Protection System', 'type' => 'Service', 'brands' => 'OBO Bettermann'],
            ['name' => 'Cable Tray Installation', 'type' => 'Service', 'brands' => 'Legrand'],
            ['name' => 'Conduit Installation', 'type' => 'Service', 'brands' => 'Finolex'],
            ['name' => 'Switchgear Installation', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Circuit Breaker Installation', 'type' => 'Service', 'brands' => 'ABB'],
            ['name' => 'Generator Installation', 'type' => 'Service', 'brands' => 'Kirloskar'],
            ['name' => 'DG Synchronization', 'type' => 'Service', 'brands' => 'Cummins'],
            ['name' => 'UPS Installation', 'type' => 'Service', 'brands' => 'APC'],
            ['name' => 'Inverter Installation', 'type' => 'Service', 'brands' => 'Luminous'],
            ['name' => 'Solar Electrical Installation', 'type' => 'Service', 'brands' => 'Tata Power Solar'],
            ['name' => 'EV Charger Installation', 'type' => 'Service', 'brands' => 'Exicom'],
            ['name' => 'Smart Home Electrical System', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Lighting Installation', 'type' => 'Service', 'brands' => 'Philips'],
            ['name' => 'Outdoor Lighting', 'type' => 'Service', 'brands' => 'Wipro Lighting'],
            ['name' => 'Emergency Lighting', 'type' => 'Service', 'brands' => 'Havells'],
            ['name' => 'Electrical Safety Audit', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Thermal Scanning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Energy Audit', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Preventive Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Maintenance Contract', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Load Calculation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Electrical Design', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Site Supervision', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Government Electrical Approval', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Electrical Testing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'After Sales Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Electrical Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'HVAC Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Central Air Conditioning', 'type' => 'Service', 'brands' => 'Daikin'],
            ['name' => 'VRV / VRF System Installation', 'type' => 'Service', 'brands' => 'Mitsubishi Electric'],
            ['name' => 'HVAC Design', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'HVAC Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Chiller Installation', 'type' => 'Service', 'brands' => 'Carrier'],
            ['name' => 'Cooling Tower Installation', 'type' => 'Service', 'brands' => 'BAC'],
            ['name' => 'Air Handling Unit (AHU) Installation', 'type' => 'Service', 'brands' => 'Blue Star'],
            ['name' => 'Fan Coil Unit (FCU) Installation', 'type' => 'Service', 'brands' => 'Blue Star'],
            ['name' => 'Ventilation System', 'type' => 'Service', 'brands' => 'Greenheck'],
            ['name' => 'Exhaust System', 'type' => 'Service', 'brands' => 'Systemair'],
            ['name' => 'Fresh Air System', 'type' => 'Service', 'brands' => 'Systemair'],
            ['name' => 'Duct Fabrication', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'GI Duct Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Insulated Duct Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Clean Room HVAC', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Industrial Ventilation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Kitchen Exhaust System', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Smoke Extraction System', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'HVAC Controls', 'type' => 'Service', 'brands' => 'Honeywell'],
            ['name' => 'Building Management System (BMS)', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'Air Balancing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'HVAC Commissioning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Preventive Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'HVAC AMC', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Filter Replacement', 'type' => 'Service', 'brands' => 'Camfil'],
            ['name' => 'Coil Cleaning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Refrigerant Charging', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Energy Efficiency Audit', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Indoor Air Quality Testing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Cold Room Installation', 'type' => 'Service', 'brands' => 'Blue Star'],
            ['name' => 'Pharma HVAC', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Hospital HVAC', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Data Center Cooling', 'type' => 'Service', 'brands' => 'Vertiv'],
            ['name' => 'Server Room Cooling', 'type' => 'Service', 'brands' => 'Stulz'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Site Survey', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Breakdown Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'After Sales Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 HVAC Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Solar EPC Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Residential Solar EPC', 'type' => 'Service', 'brands' => 'Tata Power Solar'],
            ['name' => 'Commercial Solar EPC', 'type' => 'Service', 'brands' => 'Waaree'],
            ['name' => 'Industrial Solar EPC', 'type' => 'Service', 'brands' => 'Adani Solar'],
            ['name' => 'Rooftop Solar Installation', 'type' => 'Service', 'brands' => 'Tata Power Solar'],
            ['name' => 'Ground Mounted Solar Plant', 'type' => 'Service', 'brands' => 'Waaree'],
            ['name' => 'Solar Farm Development', 'type' => 'Service', 'brands' => 'Adani Green'],
            ['name' => 'Solar Panel Supply', 'type' => 'Physical Product', 'brands' => 'Waaree'],
            ['name' => 'Mono PERC Solar Panels', 'type' => 'Physical Product', 'brands' => 'LONGi'],
            ['name' => 'Bifacial Solar Panels', 'type' => 'Physical Product', 'brands' => 'Trina Solar'],
            ['name' => 'Solar Inverter', 'type' => 'Physical Product', 'brands' => 'Sungrow'],
            ['name' => 'Hybrid Inverter', 'type' => 'Physical Product', 'brands' => 'Growatt'],
            ['name' => 'String Inverter', 'type' => 'Physical Product', 'brands' => 'SMA'],
            ['name' => 'Solar Battery', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Lithium Battery Storage', 'type' => 'Physical Product', 'brands' => 'Luminous'],
            ['name' => 'Solar Structure', 'type' => 'Physical Product', 'brands' => 'EPC Company'],
            ['name' => 'DC Cable', 'type' => 'Physical Product', 'brands' => 'Polycab'],
            ['name' => 'ACDB/DCDB Panel', 'type' => 'Physical Product', 'brands' => 'L&T'],
            ['name' => 'Net Metering Assistance', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Site Survey', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Solar Plant Design', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Shadow Analysis', 'type' => 'Service', 'brands' => 'PVsyst'],
            ['name' => 'Energy Generation Analysis', 'type' => 'Service', 'brands' => 'PVsyst'],
            ['name' => 'Government Subsidy Assistance', 'type' => 'Service', 'brands' => 'MNRE'],
            ['name' => 'DISCOM Approval', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Electrical Installation', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Testing & Commissioning', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'O&M (Operation & Maintenance)', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Annual Maintenance Contract', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Solar Cleaning', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Remote Monitoring', 'type' => 'Software', 'brands' => 'SolarEdge'],
            ['name' => 'Energy Monitoring Dashboard', 'type' => 'Software', 'brands' => 'SolarEdge'],
            ['name' => 'Warranty Support', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Financing Assistance', 'type' => 'Service', 'brands' => 'Tata Capital'],
            ['name' => 'Carbon Credit Consultation', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Industrial Energy Audit', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => 'After Sales Service', 'type' => 'Service', 'brands' => 'EPC Company'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'EPC Company'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Road Construction Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Highway Construction', 'type' => 'Service', 'brands' => 'L&T Construction'],
            ['name' => 'State Highway Construction', 'type' => 'Service', 'brands' => 'NCC Limited'],
            ['name' => 'City Road Construction', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Rural Road Construction', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Concrete Road Construction', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Bitumen Road Construction', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Asphalt Paving', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Road Resurfacing', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Road Widening', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Bridge Approach Road', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Drainage Construction', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Culvert Construction', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Road Marking', 'type' => 'Service', 'brands' => '3M'],
            ['name' => 'Thermoplastic Road Marking', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Crash Barrier Installation', 'type' => 'Service', 'brands' => 'Tata Steel'],
            ['name' => 'Road Sign Installation', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Street Lighting', 'type' => 'Service', 'brands' => 'Philips'],
            ['name' => 'Footpath Construction', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Interlocking Paver Road', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Earthwork', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Soil Stabilization', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'WMM Layer Construction', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'GSB Layer Construction', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Quality Testing', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Asphalt Testing', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Site Survey', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Total Station Survey', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'Project Planning', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'BOQ Preparation', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Tender Documentation', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Equipment Rental', 'type' => 'Service', 'brands' => 'JCB'],
            ['name' => 'Material Supply', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Safety Management', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Environmental Compliance', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Online Project Monitoring', 'type' => 'Software', 'brands' => 'Procore'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Government Project Execution', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'After Project Maintenance', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Road Contractor'],
            ['name' => '24×7 Project Support', 'type' => 'Service', 'brands' => 'Road Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Bridge Construction Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Highway Bridge Construction', 'type' => 'Service', 'brands' => 'L&T Construction'],
            ['name' => 'Railway Bridge Construction', 'type' => 'Service', 'brands' => 'Afcons Infrastructure'],
            ['name' => 'Flyover Construction', 'type' => 'Service', 'brands' => 'Tata Projects'],
            ['name' => 'Metro Bridge Construction', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Cable Stayed Bridge', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Suspension Bridge Construction', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'RCC Bridge Construction', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Steel Bridge Construction', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Box Girder Bridge', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Precast Bridge Components', 'type' => 'Physical Product', 'brands' => 'Bridge Company'],
            ['name' => 'Bridge Foundation', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Pile Foundation', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Pier Construction', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Abutment Construction', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Launching Girder Service', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Structural Steel Fabrication', 'type' => 'Service', 'brands' => 'JSW Steel'],
            ['name' => 'Prestressing Work', 'type' => 'Service', 'brands' => 'Freyssinet'],
            ['name' => 'Expansion Joint Installation', 'type' => 'Service', 'brands' => 'Mageba'],
            ['name' => 'Bridge Bearing Installation', 'type' => 'Service', 'brands' => 'Mageba'],
            ['name' => 'Road Approach Work', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'River Protection Work', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Structural Inspection', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Load Testing', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Non-Destructive Testing (NDT)', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'BIM Modeling', 'type' => 'Service', 'brands' => 'Autodesk Revit'],
            ['name' => 'Site Survey', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'Drone Survey', 'type' => 'Service', 'brands' => 'DJI Enterprise'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Safety Compliance', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Project Planning', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'BOQ Preparation', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Tender Documentation', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Environmental Compliance', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Project Monitoring', 'type' => 'Software', 'brands' => 'Primavera P6'],
            ['name' => 'Government Infrastructure Projects', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Maintenance & Rehabilitation', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Emergency Structural Repair', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Bridge Company'],
            ['name' => '24×7 Project Support', 'type' => 'Service', 'brands' => 'Bridge Company'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Demolition Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Residential Demolition', 'type' => 'Service', 'brands' => 'Demolition Contractor'],
            ['name' => 'Commercial Demolition', 'type' => 'Service', 'brands' => 'Demolition Contractor'],
            ['name' => 'Industrial Demolition', 'type' => 'Service', 'brands' => 'Demolition Contractor'],
            ['name' => 'Building Demolition', 'type' => 'Service', 'brands' => 'Demolition Contractor'],
            ['name' => 'Factory Demolition', 'type' => 'Service', 'brands' => 'Demolition Contractor'],
            ['name' => 'Bridge Demolition', 'type' => 'Service', 'brands' => 'Demolition Contractor'],
            ['name' => 'Chimney Demolition', 'type' => 'Service', 'brands' => 'Demolition Contractor'],
            ['name' => 'Interior Demolition', 'type' => 'Service', 'brands' => 'Demolition Contractor'],
            ['name' => 'Selective Demolition', 'type' => 'Service', 'brands' => 'Demolition Contractor'],
            ['name' => 'Controlled Demolition', 'type' => 'Service', 'brands' => 'Demolition Contractor'],
            ['name' => 'Concrete Breaking', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Rock Breaking', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Core Cutting', 'type' => 'Service', 'brands' => 'Hilti'],
            ['name' => 'Wall Cutting', 'type' => 'Service', 'brands' => 'Hilti'],
            ['name' => 'Slab Cutting', 'type' => 'Service', 'brands' => 'Hilti'],
            ['name' => 'Diamond Wire Saw Cutting', 'type' => 'Service', 'brands' => 'Husqvarna'],
            ['name' => 'Hydraulic Crushing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Excavator Demolition', 'type' => 'Service', 'brands' => 'Caterpillar'],
            ['name' => 'High Reach Demolition', 'type' => 'Service', 'brands' => 'Volvo CE'],
            ['name' => 'Debris Removal', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Construction Waste Disposal', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Scrap Recovery', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Metal Recycling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Site Clearance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Land Preparation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Dust Control', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Environmental Compliance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Structural Assessment', 'type' => 'Service', 'brands' => 'Structural Engineer'],
            ['name' => 'Safety Planning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Government Demolition Permit Assistance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Site Survey', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Drone Survey', 'type' => 'Service', 'brands' => 'DJI Enterprise'],
            ['name' => 'Project Planning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Equipment Rental', 'type' => 'Service', 'brands' => 'JCB'],
            ['name' => 'Labor Supply', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Demolition', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Disaster Recovery Demolition', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Supervision', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Emergency Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Pre-Engineered Building (PEB) Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'PEB Warehouse', 'type' => 'Service', 'brands' => 'Kirby Building Systems'],
            ['name' => 'Industrial Shed', 'type' => 'Service', 'brands' => 'Interarch'],
            ['name' => 'Factory Building', 'type' => 'Service', 'brands' => 'Zamil Steel'],
            ['name' => 'Commercial PEB Building', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Aircraft Hangar', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Logistics Warehouse', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Cold Storage Building', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Multi-Storey Steel Building', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Mezzanine Floor', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Steel Structure Fabrication', 'type' => 'Physical Product', 'brands' => 'JSW Steel'],
            ['name' => 'Primary Steel Structure', 'type' => 'Physical Product', 'brands' => 'PEB Company'],
            ['name' => 'Secondary Steel Structure', 'type' => 'Physical Product', 'brands' => 'PEB Company'],
            ['name' => 'Roof Purlins', 'type' => 'Physical Product', 'brands' => 'Tata BlueScope'],
            ['name' => 'Wall Girts', 'type' => 'Physical Product', 'brands' => 'Tata BlueScope'],
            ['name' => 'Sandwich PUF Panels', 'type' => 'Physical Product', 'brands' => 'Metecno'],
            ['name' => 'Color Coated Roofing Sheets', 'type' => 'Physical Product', 'brands' => 'Tata BlueScope'],
            ['name' => 'Skylight Panels', 'type' => 'Physical Product', 'brands' => 'Lexan'],
            ['name' => 'Turbo Ventilator', 'type' => 'Physical Product', 'brands' => 'Turbovent'],
            ['name' => 'Gutter System', 'type' => 'Physical Product', 'brands' => 'PEB Company'],
            ['name' => 'Down Take Pipes', 'type' => 'Physical Product', 'brands' => 'Supreme'],
            ['name' => 'Building Design', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Structural Analysis', 'type' => 'Service', 'brands' => 'STAAD.Pro'],
            ['name' => 'Shop Drawings', 'type' => 'Service', 'brands' => 'Tekla Structures'],
            ['name' => 'BIM Modeling', 'type' => 'Service', 'brands' => 'Autodesk Revit'],
            ['name' => 'Site Survey', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Fabrication', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Erection & Installation', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Civil Foundation Coordination', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Quality Inspection', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Material Testing', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Maintenance Services', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Expansion Projects', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Online Project Monitoring', 'type' => 'Software', 'brands' => 'Procore'],
            ['name' => 'Warranty Support', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Annual Maintenance Contract', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'After Sales Support', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'PEB Company'],
            ['name' => '24×7 Client Support', 'type' => 'Service', 'brands' => 'PEB Company'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Surveyor & Land Survey Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Land Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Topographic Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Boundary Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'DGPS Survey', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'Total Station Survey', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'GPS Survey', 'type' => 'Service', 'brands' => 'Trimble'],
            ['name' => 'Drone Survey', 'type' => 'Service', 'brands' => 'DJI Enterprise'],
            ['name' => 'UAV Mapping', 'type' => 'Service', 'brands' => 'DJI Enterprise'],
            ['name' => 'Contour Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Construction Layout Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Road Alignment Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Railway Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Canal Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Hydrographic Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Mining Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'GIS Mapping', 'type' => 'Service', 'brands' => 'Esri'],
            ['name' => 'Utility Mapping', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'As-Built Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Volume Calculation', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Earthwork Measurement', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Plot Demarcation', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Property Measurement', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Site Inspection', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Digital Terrain Model (DTM)', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'CAD Drafting', 'type' => 'Service', 'brands' => 'AutoCAD'],
            ['name' => 'BIM Survey Data', 'type' => 'Service', 'brands' => 'Autodesk Revit'],
            ['name' => 'Geotechnical Investigation Coordination', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Land Records Verification', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Government Survey Assistance', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Mutation Survey Support', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Online Survey Reports', 'type' => 'Software', 'brands' => 'Survey Company'],
            ['name' => 'Drone Image Processing', 'type' => 'Software', 'brands' => 'Pix4D'],
            ['name' => 'Project Documentation', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Technical Consultation', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Construction Stakeout', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Site Monitoring', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Equipment Rental', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => 'Emergency Survey', 'type' => 'Service', 'brands' => 'Survey Company'],
            ['name' => '24×7 Survey Support', 'type' => 'Service', 'brands' => 'Survey Company'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Geotechnical Investigation Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Soil Investigation', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Borehole Drilling', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Soil Sampling', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Standard Penetration Test (SPT)', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Cone Penetration Test (CPT)', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Plate Load Test', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'California Bearing Ratio (CBR) Test', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Rock Core Drilling', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Rock Testing', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Groundwater Investigation', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Permeability Test', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Soil Bearing Capacity Test', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Foundation Recommendation', 'type' => 'Service', 'brands' => 'Geotechnical Engineer'],
            ['name' => 'Geophysical Survey', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Seismic Refraction Survey', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Soil Classification', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Laboratory Soil Testing', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Chemical Soil Analysis', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Compaction Test', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Field Density Test', 'type' => 'Service', 'brands' => 'Civil Lab'],
            ['name' => 'Settlement Analysis', 'type' => 'Service', 'brands' => 'Geotechnical Engineer'],
            ['name' => 'Slope Stability Analysis', 'type' => 'Service', 'brands' => 'Geotechnical Engineer'],
            ['name' => 'Earth Retaining Design Support', 'type' => 'Service', 'brands' => 'Geotechnical Engineer'],
            ['name' => 'Pile Foundation Investigation', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Site Investigation Report', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Geotechnical Report', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Construction Site Investigation', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Project Consultation', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Site Survey', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Environmental Soil Assessment', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Ground Improvement Recommendation', 'type' => 'Service', 'brands' => 'Geotechnical Engineer'],
            ['name' => 'Soil Stabilization Consultation', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Technical Documentation', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Government Project Investigation', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Emergency Site Investigation', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'After Project Support', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
            ['name' => '24×7 Technical Support', 'type' => 'Service', 'brands' => 'Geotechnical Company'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Construction Project Management Consultant (PMC)',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Project Planning', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Project Scheduling', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Construction Supervision', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Site Management', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Project Coordination', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Contractor Management', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Cost Management', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Budget Planning', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Quantity Surveying', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'BOQ Preparation', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Tender Documentation', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Bid Evaluation', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Contract Administration', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Risk Management', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Quality Control', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Safety Management', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Environmental Compliance', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Material Inspection', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Vendor Management', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Procurement Management', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Progress Monitoring', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Delay Analysis', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Claim Management', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'BIM Coordination', 'type' => 'Service', 'brands' => 'Autodesk Revit'],
            ['name' => 'Project Reporting', 'type' => 'Software', 'brands' => 'Microsoft Project'],
            ['name' => 'Digital Project Dashboard', 'type' => 'Software', 'brands' => 'Procore'],
            ['name' => 'Drone Progress Monitoring', 'type' => 'Service', 'brands' => 'DJI Enterprise'],
            ['name' => 'Site Audit', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Structural Audit Coordination', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Commissioning Management', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Handover Management', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Facility Management Planning', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Online Project Meetings', 'type' => 'Service', 'brands' => 'Microsoft Teams'],
            ['name' => 'Client Representation', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Value Engineering', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'After Project Support', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'PMC'],
            ['name' => '24×7 Project Support', 'type' => 'Service', 'brands' => 'PMC'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Construction & Infrastructure Sub Categories 34.16 to 34.26.\n";
