<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Building Restoration & Heritage Conservation Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Heritage Building Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Monument Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Historical Structure Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Stone Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Masonry Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Lime Plaster Restoration', 'type' => 'Product', 'brands' => 'Saint-Astier'],
            ['name' => 'Facade Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Structural Strengthening', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Crack Stitching', 'type' => 'Product', 'brands' => 'Helifix'],
            ['name' => 'Carbon Fiber Strengthening', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Epoxy Injection', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Concrete Restoration', 'type' => 'Product', 'brands' => 'Master Builders Solutions'],
            ['name' => 'Stone Cleaning', 'type' => 'Service', 'brands' => 'Kärcher'],
            ['name' => 'Monument Cleaning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Waterproofing Restoration', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Roof Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Timber Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Metal Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Decorative Element Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Structural Assessment', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Heritage Documentation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '3D Laser Scanning', 'type' => 'Product', 'brands' => 'Leica Geosystems'],
            ['name' => 'BIM for Heritage', 'type' => 'Software', 'brands' => 'Autodesk Revit'],
            ['name' => 'Material Analysis', 'type' => 'Service', 'brands' => 'Laboratory'],
            ['name' => 'Conservation Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Government Heritage Compliance', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Site Supervision', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Quality Assurance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Annual Heritage Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Emergency Restoration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Disaster Damage Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Remote Project Review', 'type' => 'Service', 'brands' => 'Microsoft Teams'],
            ['name' => '24×7 Technical Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Waterproofing Material Manufacturer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Liquid Waterproofing Membrane', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Cementitious Waterproofing', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Acrylic Waterproof Coating', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'PU Waterproof Coating', 'type' => 'Product', 'brands' => 'MYK Arment'],
            ['name' => 'Bituminous Membrane', 'type' => 'Product', 'brands' => 'STP Limited'],
            ['name' => 'APP Membrane', 'type' => 'Product', 'brands' => 'STP Limited'],
            ['name' => 'SBS Membrane', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'HDPE Waterproof Membrane', 'type' => 'Product', 'brands' => 'GSE Environmental'],
            ['name' => 'PVC Waterproof Membrane', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Crystalline Waterproofing', 'type' => 'Product', 'brands' => 'Xypex'],
            ['name' => 'Injection Grout', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'PU Injection Resin', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Epoxy Injection Resin', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Joint Sealant', 'type' => 'Product', 'brands' => 'Dow'],
            ['name' => 'Silicone Sealant', 'type' => 'Product', 'brands' => 'Dow'],
            ['name' => 'Expansion Joint System', 'type' => 'Product', 'brands' => 'MIGUA'],
            ['name' => 'Waterstop', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'PVC Water Bar', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Concrete Admixture', 'type' => 'Product', 'brands' => 'Master Builders Solutions'],
            ['name' => 'Protective Coating', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Roof Coating', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Terrace Waterproofing Kit', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Basement Waterproofing System', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Crack Repair Kit', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Tile Adhesive', 'type' => 'Product', 'brands' => 'MYK LATICRETE'],
            ['name' => 'Tile Grout', 'type' => 'Product', 'brands' => 'Roff'],
            ['name' => 'Product Testing', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Technical Demonstration', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Contractor Training', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Site Inspection', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'OEM Manufacturing', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Bulk Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Warranty Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Roofing Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Industrial Roofing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Commercial Roofing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Residential Roofing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'PEB Roofing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Metal Roofing', 'type' => 'Product', 'brands' => 'Tata BlueScope Steel'],
            ['name' => 'Standing Seam Roofing', 'type' => 'Product', 'brands' => 'Kingspan'],
            ['name' => 'Sandwich Panel Roofing', 'type' => 'Product', 'brands' => 'Metecno'],
            ['name' => 'PUF Roofing Panels', 'type' => 'Product', 'brands' => 'Kingspan'],
            ['name' => 'Polycarbonate Roofing', 'type' => 'Product', 'brands' => 'Danpal'],
            ['name' => 'Skylight Installation', 'type' => 'Product', 'brands' => 'Velux'],
            ['name' => 'Roof Insulation', 'type' => 'Product', 'brands' => 'Rockwool'],
            ['name' => 'Roof Ventilator', 'type' => 'Product', 'brands' => 'Lomanco'],
            ['name' => 'Turbo Ventilator', 'type' => 'Product', 'brands' => 'Everest Industries'],
            ['name' => 'Gutter Installation', 'type' => 'Product', 'brands' => 'Lindab'],
            ['name' => 'Downpipe Installation', 'type' => 'Product', 'brands' => 'Supreme Industries'],
            ['name' => 'Roof Waterproofing', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Roof Coating', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Roof Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Roof Leak Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Roof Replacement', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Roof Strengthening', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Solar Roof Integration', 'type' => 'Product', 'brands' => 'Tata Power Solar'],
            ['name' => 'Roof Safety System', 'type' => 'Product', 'brands' => '3M Protecta'],
            ['name' => 'Roof Access Ladder', 'type' => 'Product', 'brands' => 'ZARGES'],
            ['name' => 'Flashing Installation', 'type' => 'Product', 'brands' => 'Tata BlueScope Steel'],
            ['name' => 'Roof Inspection', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Drone Roof Survey', 'type' => 'Service', 'brands' => 'DJI Enterprise'],
            ['name' => 'Thermal Roof Inspection', 'type' => 'Product', 'brands' => 'FLIR'],
            ['name' => 'Preventive Roof Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Roof Maintenance Contract', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Roof Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Storm Damage Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Roofing Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Flooring Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Vitrified Tile Flooring', 'type' => 'Product', 'brands' => 'Kajaria Ceramics'],
            ['name' => 'Ceramic Tile Flooring', 'type' => 'Product', 'brands' => 'Somany Ceramics'],
            ['name' => 'Porcelain Tile Flooring', 'type' => 'Product', 'brands' => 'Johnson Tiles'],
            ['name' => 'Marble Flooring', 'type' => 'Product', 'brands' => 'RK Marble'],
            ['name' => 'Granite Flooring', 'type' => 'Product', 'brands' => 'Pokarna'],
            ['name' => 'Wooden Flooring', 'type' => 'Product', 'brands' => 'Pergo'],
            ['name' => 'Engineered Wood Flooring', 'type' => 'Product', 'brands' => 'Greenlam'],
            ['name' => 'Laminate Flooring', 'type' => 'Product', 'brands' => 'Greenlam'],
            ['name' => 'Vinyl Flooring', 'type' => 'Product', 'brands' => 'Tarkett'],
            ['name' => 'SPC Flooring', 'type' => 'Product', 'brands' => 'Responsive Industries'],
            ['name' => 'WPC Flooring', 'type' => 'Product', 'brands' => 'Responsive Industries'],
            ['name' => 'Carpet Tile Installation', 'type' => 'Product', 'brands' => 'Interface'],
            ['name' => 'Epoxy Flooring', 'type' => 'Product', 'brands' => 'Flowcrete'],
            ['name' => 'PU Flooring', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Concrete Polishing', 'type' => 'Service', 'brands' => 'HTC'],
            ['name' => 'Floor Grinding', 'type' => 'Service', 'brands' => 'Husqvarna'],
            ['name' => 'Floor Leveling', 'type' => 'Product', 'brands' => 'Fosroc'],
            ['name' => 'Self-Leveling Compound', 'type' => 'Product', 'brands' => 'MYK LATICRETE'],
            ['name' => 'Tile Adhesive', 'type' => 'Product', 'brands' => 'MYK LATICRETE'],
            ['name' => 'Tile Grouting', 'type' => 'Product', 'brands' => 'Roff'],
            ['name' => 'Expansion Joint Installation', 'type' => 'Product', 'brands' => 'MIGUA'],
            ['name' => 'Skirting Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Staircase Flooring', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Outdoor Deck Flooring', 'type' => 'Product', 'brands' => 'Trex'],
            ['name' => 'Anti-Skid Flooring', 'type' => 'Product', 'brands' => 'Kajaria Ceramics'],
            ['name' => 'Sports Flooring', 'type' => 'Product', 'brands' => 'Gerflor'],
            ['name' => 'Floor Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Crack Repair', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Waterproof Underlayment', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Floor Inspection', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Floor Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Floor Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Flooring Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'False Ceiling Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Gypsum False Ceiling', 'type' => 'Product', 'brands' => 'Saint-Gobain Gyproc'],
            ['name' => 'POP False Ceiling', 'type' => 'Product', 'brands' => 'JK Lakshmi'],
            ['name' => 'Mineral Fiber Ceiling', 'type' => 'Product', 'brands' => 'Armstrong Ceiling Solutions'],
            ['name' => 'Metal Ceiling', 'type' => 'Product', 'brands' => 'Hunter Douglas'],
            ['name' => 'PVC Ceiling', 'type' => 'Product', 'brands' => 'Dumaplast'],
            ['name' => 'Wooden Ceiling', 'type' => 'Product', 'brands' => 'Greenply'],
            ['name' => 'Acoustic Ceiling', 'type' => 'Product', 'brands' => 'Rockfon'],
            ['name' => 'Baffle Ceiling', 'type' => 'Product', 'brands' => 'Hunter Douglas'],
            ['name' => 'Open Cell Ceiling', 'type' => 'Product', 'brands' => 'Armstrong Ceiling Solutions'],
            ['name' => 'Grid Ceiling', 'type' => 'Product', 'brands' => 'Armstrong Ceiling Solutions'],
            ['name' => 'Linear Ceiling', 'type' => 'Product', 'brands' => 'Hunter Douglas'],
            ['name' => 'Decorative Ceiling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Coffered Ceiling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Stretch Ceiling', 'type' => 'Product', 'brands' => 'Barrisol'],
            ['name' => 'Ceiling Insulation', 'type' => 'Product', 'brands' => 'Rockwool'],
            ['name' => 'Ceiling Lighting Integration', 'type' => 'Product', 'brands' => 'Philips'],
            ['name' => 'Cove Lighting', 'type' => 'Product', 'brands' => 'Signify'],
            ['name' => 'HVAC Ceiling Coordination', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Fire Rated Ceiling', 'type' => 'Product', 'brands' => 'Saint-Gobain Gyproc'],
            ['name' => 'Moisture Resistant Ceiling', 'type' => 'Product', 'brands' => 'Saint-Gobain Gyproc'],
            ['name' => 'Ceiling Access Panels', 'type' => 'Product', 'brands' => 'Knauf'],
            ['name' => 'Ceiling Framing', 'type' => 'Product', 'brands' => 'Gyproc'],
            ['name' => 'Office Ceiling Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Commercial Ceiling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Hospital Ceiling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Clean Room Ceiling', 'type' => 'Product', 'brands' => 'Armstrong'],
            ['name' => 'Ceiling Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Ceiling Replacement', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Site Measurement', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Ceiling Maintenance', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Ceiling Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Installation Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Glass & Aluminium Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Aluminium Windows', 'type' => 'Product', 'brands' => 'Reynaers Aluminium'],
            ['name' => 'Aluminium Doors', 'type' => 'Product', 'brands' => 'Schüco'],
            ['name' => 'Sliding Windows', 'type' => 'Product', 'brands' => 'Fenesta'],
            ['name' => 'Casement Windows', 'type' => 'Product', 'brands' => 'Fenesta'],
            ['name' => 'uPVC Windows', 'type' => 'Product', 'brands' => 'VEKA'],
            ['name' => 'uPVC Doors', 'type' => 'Product', 'brands' => 'Koemmerling'],
            ['name' => 'Toughened Glass', 'type' => 'Product', 'brands' => 'Saint-Gobain Glass'],
            ['name' => 'Laminated Glass', 'type' => 'Product', 'brands' => 'AIS Glass'],
            ['name' => 'Insulated Glass Unit (IGU)', 'type' => 'Product', 'brands' => 'Saint-Gobain Glass'],
            ['name' => 'Structural Glazing', 'type' => 'Product', 'brands' => 'Schüco'],
            ['name' => 'Spider Glazing', 'type' => 'Product', 'brands' => 'Dormakaba'],
            ['name' => 'Curtain Wall', 'type' => 'Product', 'brands' => 'Reynaers Aluminium'],
            ['name' => 'ACP Cladding', 'type' => 'Product', 'brands' => 'Aludecor'],
            ['name' => 'Glass Partition', 'type' => 'Product', 'brands' => 'Saint-Gobain Glass'],
            ['name' => 'Office Glass Cabin', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Shower Enclosure', 'type' => 'Product', 'brands' => 'Jaquar'],
            ['name' => 'Glass Railing', 'type' => 'Product', 'brands' => 'Dormakaba'],
            ['name' => 'Skylight System', 'type' => 'Product', 'brands' => 'Velux'],
            ['name' => 'Glass Canopy', 'type' => 'Product', 'brands' => 'Saint-Gobain Glass'],
            ['name' => 'Automatic Sliding Door', 'type' => 'Product', 'brands' => 'Dormakaba'],
            ['name' => 'Sensor Door', 'type' => 'Product', 'brands' => 'GEZE'],
            ['name' => 'Aluminium Louvers', 'type' => 'Product', 'brands' => 'Hunter Douglas'],
            ['name' => 'Handrail System', 'type' => 'Product', 'brands' => 'Q-railing'],
            ['name' => 'Facade Glazing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Glass Film Installation', 'type' => 'Product', 'brands' => '3M'],
            ['name' => 'Window Hardware', 'type' => 'Product', 'brands' => 'Häfele'],
            ['name' => 'Silicone Glazing', 'type' => 'Product', 'brands' => 'Dow'],
            ['name' => 'Glass Replacement', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Site Measurement', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Installation Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Maintenance Contract', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Emergency Glass Replacement', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Doors & Windows Manufacturer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Wooden Doors', 'type' => 'Product', 'brands' => 'Greenply'],
            ['name' => 'Flush Doors', 'type' => 'Product', 'brands' => 'CenturyPly'],
            ['name' => 'Panel Doors', 'type' => 'Product', 'brands' => 'Greenpanel'],
            ['name' => 'Laminated Doors', 'type' => 'Product', 'brands' => 'CenturyDoors'],
            ['name' => 'Veneer Doors', 'type' => 'Product', 'brands' => 'Greenply'],
            ['name' => 'Fire Rated Doors', 'type' => 'Product', 'brands' => 'Navair'],
            ['name' => 'Steel Doors', 'type' => 'Product', 'brands' => 'TATA Pravesh'],
            ['name' => 'WPC Doors', 'type' => 'Product', 'brands' => 'Ecoste'],
            ['name' => 'PVC Doors', 'type' => 'Product', 'brands' => 'Sintex'],
            ['name' => 'uPVC Windows', 'type' => 'Product', 'brands' => 'Fenesta'],
            ['name' => 'Aluminium Windows', 'type' => 'Product', 'brands' => 'Reynaers Aluminium'],
            ['name' => 'Sliding Windows', 'type' => 'Product', 'brands' => 'VEKA'],
            ['name' => 'Casement Windows', 'type' => 'Product', 'brands' => 'Koemmerling'],
            ['name' => 'French Windows', 'type' => 'Product', 'brands' => 'Fenesta'],
            ['name' => 'Soundproof Windows', 'type' => 'Product', 'brands' => 'Saint-Gobain Glass'],
            ['name' => 'Skylight Windows', 'type' => 'Product', 'brands' => 'Velux'],
            ['name' => 'Door Frames', 'type' => 'Product', 'brands' => 'CenturyPly'],
            ['name' => 'Window Frames', 'type' => 'Product', 'brands' => 'Reynaers Aluminium'],
            ['name' => 'Door Hardware', 'type' => 'Product', 'brands' => 'Häfele'],
            ['name' => 'Smart Door Lock', 'type' => 'Product', 'brands' => 'Yale'],
            ['name' => 'Digital Lock', 'type' => 'Product', 'brands' => 'Godrej Locks'],
            ['name' => 'Door Closer', 'type' => 'Product', 'brands' => 'Dormakaba'],
            ['name' => 'Hinges', 'type' => 'Product', 'brands' => 'Hettich'],
            ['name' => 'Sliding Door System', 'type' => 'Product', 'brands' => 'Häfele'],
            ['name' => 'Mosquito Mesh System', 'type' => 'Product', 'brands' => 'TuffScreen'],
            ['name' => 'Window Glass', 'type' => 'Product', 'brands' => 'AIS Glass'],
            ['name' => 'Toughened Glass', 'type' => 'Product', 'brands' => 'Saint-Gobain Glass'],
            ['name' => 'Custom Manufacturing', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Site Measurement', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Installation Service', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Warranty Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Annual Maintenance', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'OEM Manufacturing', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Stone & Marble Supplier',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Italian Marble', 'type' => 'Product', 'brands' => 'RK Marble'],
            ['name' => 'Indian Marble', 'type' => 'Product', 'brands' => 'RK Marble'],
            ['name' => 'Granite Slabs', 'type' => 'Product', 'brands' => 'Pokarna'],
            ['name' => 'Granite Tiles', 'type' => 'Product', 'brands' => 'Pokarna'],
            ['name' => 'Quartz Stone', 'type' => 'Product', 'brands' => 'Caesarstone'],
            ['name' => 'Engineered Quartz', 'type' => 'Product', 'brands' => 'KalingaStone'],
            ['name' => 'Sandstone', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'Limestone', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'Kota Stone', 'type' => 'Product', 'brands' => 'Kota Stone'],
            ['name' => 'Slate Stone', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'Onyx Marble', 'type' => 'Product', 'brands' => 'Antolini'],
            ['name' => 'Travertine Stone', 'type' => 'Product', 'brands' => 'Antolini'],
            ['name' => 'Stone Veneer', 'type' => 'Product', 'brands' => 'StoneLam'],
            ['name' => 'Exterior Cladding Stone', 'type' => 'Product', 'brands' => 'RK Marble'],
            ['name' => 'Wall Cladding Stone', 'type' => 'Product', 'brands' => 'KalingaStone'],
            ['name' => 'Cobblestone', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'Kerb Stone', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'Paving Stone', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'Monument Stone', 'type' => 'Product', 'brands' => 'Supplier'],
            ['name' => 'Kitchen Countertop', 'type' => 'Product', 'brands' => 'Caesarstone'],
            ['name' => 'Vanity Countertop', 'type' => 'Product', 'brands' => 'KalingaStone'],
            ['name' => 'CNC Stone Cutting', 'type' => 'Service', 'brands' => 'Breton'],
            ['name' => 'Waterjet Stone Cutting', 'type' => 'Service', 'brands' => 'Breton'],
            ['name' => 'Edge Polishing', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Stone Carving', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Book Matching', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Stone Installation', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Stone Restoration', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Surface Polishing', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Bulk Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Export Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Site Inspection', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Annual Maintenance', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => '24×7 Supply Support', 'type' => 'Service', 'brands' => 'Supplier'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Tiles & Sanitaryware Dealer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Vitrified Tiles', 'type' => 'Product', 'brands' => 'Kajaria Ceramics'],
            ['name' => 'Ceramic Tiles', 'type' => 'Product', 'brands' => 'Somany Ceramics'],
            ['name' => 'GVT Tiles', 'type' => 'Product', 'brands' => 'Simpolo Ceramics'],
            ['name' => 'PGVT Tiles', 'type' => 'Product', 'brands' => 'Varmora'],
            ['name' => 'Double Charge Tiles', 'type' => 'Product', 'brands' => 'Nitco'],
            ['name' => 'Parking Tiles', 'type' => 'Product', 'brands' => 'Kajaria Ceramics'],
            ['name' => 'Wall Tiles', 'type' => 'Product', 'brands' => 'Johnson Tiles'],
            ['name' => 'Bathroom Tiles', 'type' => 'Product', 'brands' => 'Cera'],
            ['name' => 'Kitchen Tiles', 'type' => 'Product', 'brands' => 'Somany Ceramics'],
            ['name' => 'Outdoor Tiles', 'type' => 'Product', 'brands' => 'Simpolo Ceramics'],
            ['name' => 'Sanitaryware', 'type' => 'Product', 'brands' => 'Cera'],
            ['name' => 'Water Closet (WC)', 'type' => 'Product', 'brands' => 'Hindware'],
            ['name' => 'Wash Basin', 'type' => 'Product', 'brands' => 'Parryware'],
            ['name' => 'Urinal', 'type' => 'Product', 'brands' => 'Hindware'],
            ['name' => 'Kitchen Sink', 'type' => 'Product', 'brands' => 'Carysil'],
            ['name' => 'Faucets', 'type' => 'Product', 'brands' => 'Jaquar'],
            ['name' => 'Shower System', 'type' => 'Product', 'brands' => 'Jaquar'],
            ['name' => 'Bathroom Accessories', 'type' => 'Product', 'brands' => 'Kohler'],
            ['name' => 'Bathtub', 'type' => 'Product', 'brands' => 'Kohler'],
            ['name' => 'Shower Enclosure', 'type' => 'Product', 'brands' => 'Jaquar'],
            ['name' => 'Concealed Cistern', 'type' => 'Product', 'brands' => 'Geberit'],
            ['name' => 'Flush Plate', 'type' => 'Product', 'brands' => 'Geberit'],
            ['name' => 'Tile Adhesive', 'type' => 'Product', 'brands' => 'MYK LATICRETE'],
            ['name' => 'Tile Grout', 'type' => 'Product', 'brands' => 'Roff'],
            ['name' => 'Tile Spacer', 'type' => 'Product', 'brands' => 'Raimondi'],
            ['name' => 'Tile Leveling System', 'type' => 'Product', 'brands' => 'Rubi'],
            ['name' => 'Tile Cutting Machine', 'type' => 'Product', 'brands' => 'Rubi'],
            ['name' => 'Interior Consultation', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Site Measurement', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Home Delivery', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Installation Support', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Bulk Project Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Warranty Assistance', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Dealer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Plywood, Laminates & Veneer Dealer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Commercial Plywood', 'type' => 'Product', 'brands' => 'Greenply'],
            ['name' => 'Marine Plywood', 'type' => 'Product', 'brands' => 'CenturyPly'],
            ['name' => 'BWP Plywood', 'type' => 'Product', 'brands' => 'Greenply'],
            ['name' => 'BWR Plywood', 'type' => 'Product', 'brands' => 'Kitply'],
            ['name' => 'Block Board', 'type' => 'Product', 'brands' => 'CenturyPly'],
            ['name' => 'MDF Board', 'type' => 'Product', 'brands' => 'Greenpanel'],
            ['name' => 'HDHMR Board', 'type' => 'Product', 'brands' => 'Action TESA'],
            ['name' => 'Particle Board', 'type' => 'Product', 'brands' => 'Greenpanel'],
            ['name' => 'Decorative Laminates', 'type' => 'Product', 'brands' => 'Greenlam'],
            ['name' => 'High Gloss Laminates', 'type' => 'Product', 'brands' => 'Merino'],
            ['name' => 'Acrylic Laminates', 'type' => 'Product', 'brands' => 'Royale Touche'],
            ['name' => 'Exterior Laminates', 'type' => 'Product', 'brands' => 'Greenlam'],
            ['name' => 'Veneer Sheets', 'type' => 'Product', 'brands' => 'Century Veneers'],
            ['name' => 'Natural Veneer', 'type' => 'Product', 'brands' => 'Greenply'],
            ['name' => 'Engineered Veneer', 'type' => 'Product', 'brands' => 'Decowood'],
            ['name' => 'PVC Laminates', 'type' => 'Product', 'brands' => 'Merino'],
            ['name' => 'Edge Band Tape', 'type' => 'Product', 'brands' => 'Rehau'],
            ['name' => 'Decorative Panels', 'type' => 'Product', 'brands' => 'Greenpanel'],
            ['name' => 'Charcoal Panels', 'type' => 'Product', 'brands' => 'Advance Decorative Laminates'],
            ['name' => 'WPC Boards', 'type' => 'Product', 'brands' => 'Ecoste'],
            ['name' => 'PVC Boards', 'type' => 'Product', 'brands' => 'Alstone'],
            ['name' => 'Wooden Flooring', 'type' => 'Product', 'brands' => 'Pergo'],
            ['name' => 'Adhesives', 'type' => 'Product', 'brands' => 'Fevicol'],
            ['name' => 'Wood Polish', 'type' => 'Product', 'brands' => 'ICA'],
            ['name' => 'Hardware Accessories', 'type' => 'Product', 'brands' => 'Häfele'],
            ['name' => 'CNC Cutting', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Edge Banding', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Home Delivery', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Project Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Interior Material Consultation', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Site Measurement', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Bulk Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'OEM Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Dealer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Paint & Coating Dealer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Interior Emulsion Paint', 'type' => 'Product', 'brands' => 'Asian Paints'],
            ['name' => 'Exterior Emulsion Paint', 'type' => 'Product', 'brands' => 'Berger Paints'],
            ['name' => 'Premium Emulsion', 'type' => 'Product', 'brands' => 'Nerolac'],
            ['name' => 'Texture Paint', 'type' => 'Product', 'brands' => 'Dulux'],
            ['name' => 'Distemper', 'type' => 'Product', 'brands' => 'Indigo Paints'],
            ['name' => 'Primer', 'type' => 'Product', 'brands' => 'Asian Paints'],
            ['name' => 'Wall Putty', 'type' => 'Product', 'brands' => 'Birla White'],
            ['name' => 'Waterproof Coating', 'type' => 'Product', 'brands' => 'Dr. Fixit'],
            ['name' => 'Wood Coating', 'type' => 'Product', 'brands' => 'ICA'],
            ['name' => 'PU Wood Finish', 'type' => 'Product', 'brands' => 'ICA'],
            ['name' => 'Melamine Polish', 'type' => 'Product', 'brands' => 'Asian Paints'],
            ['name' => 'Enamel Paint', 'type' => 'Product', 'brands' => 'Berger Paints'],
            ['name' => 'Metal Primer', 'type' => 'Product', 'brands' => 'Jotun'],
            ['name' => 'Industrial Coating', 'type' => 'Product', 'brands' => 'Jotun'],
            ['name' => 'Epoxy Coating', 'type' => 'Product', 'brands' => 'Sika'],
            ['name' => 'Floor Coating', 'type' => 'Product', 'brands' => 'Flowcrete'],
            ['name' => 'Heat Resistant Paint', 'type' => 'Product', 'brands' => 'Jotun'],
            ['name' => 'Road Marking Paint', 'type' => 'Product', 'brands' => 'Asian Paints PPG'],
            ['name' => 'Spray Paint', 'type' => 'Product', 'brands' => 'Rust-Oleum'],
            ['name' => 'Decorative Finish', 'type' => 'Product', 'brands' => 'Royale Play'],
            ['name' => 'Painter Tools', 'type' => 'Product', 'brands' => 'Stanley'],
            ['name' => 'Paint Roller', 'type' => 'Product', 'brands' => 'Asian Paints'],
            ['name' => 'Paint Brush', 'type' => 'Product', 'brands' => 'Stanley'],
            ['name' => 'Masking Tape', 'type' => 'Product', 'brands' => '3M'],
            ['name' => 'Abrasives', 'type' => 'Product', 'brands' => 'Norton'],
            ['name' => 'Colour Matching', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Paint Mixing', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Shade Consultation', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Home Delivery', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Contractor Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Bulk Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Site Visit', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Warranty Assistance', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Dealer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Construction Hardware & Fasteners Supplier',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Anchor Fasteners', 'type' => 'Product', 'brands' => 'Hilti'],
            ['name' => 'Chemical Anchors', 'type' => 'Product', 'brands' => 'Fischer'],
            ['name' => 'Wedge Anchors', 'type' => 'Product', 'brands' => 'Hilti'],
            ['name' => 'Through Bolts', 'type' => 'Product', 'brands' => 'Fischer'],
            ['name' => 'Hex Bolts', 'type' => 'Product', 'brands' => 'Unbrako'],
            ['name' => 'High Tensile Bolts', 'type' => 'Product', 'brands' => 'TVS Fasteners'],
            ['name' => 'Stainless Steel Fasteners', 'type' => 'Product', 'brands' => 'Unbrako'],
            ['name' => 'Foundation Bolts', 'type' => 'Product', 'brands' => 'TVS Fasteners'],
            ['name' => 'Threaded Rods', 'type' => 'Product', 'brands' => 'Hilti'],
            ['name' => 'Nuts & Washers', 'type' => 'Product', 'brands' => 'Unbrako'],
            ['name' => 'Self Drilling Screws', 'type' => 'Product', 'brands' => 'EJOT'],
            ['name' => 'Drywall Screws', 'type' => 'Product', 'brands' => 'Gyproc'],
            ['name' => 'Roofing Screws', 'type' => 'Product', 'brands' => 'SFS'],
            ['name' => 'Rivets', 'type' => 'Product', 'brands' => 'POP Avdel'],
            ['name' => 'Toggle Bolts', 'type' => 'Product', 'brands' => 'Fischer'],
            ['name' => 'Expansion Bolts', 'type' => 'Product', 'brands' => 'Hilti'],
            ['name' => 'Door Hardware', 'type' => 'Product', 'brands' => 'Häfele'],
            ['name' => 'Cabinet Hardware', 'type' => 'Product', 'brands' => 'Hettich'],
            ['name' => 'Drawer Channels', 'type' => 'Product', 'brands' => 'Hettich'],
            ['name' => 'Hinges', 'type' => 'Product', 'brands' => 'Blum'],
            ['name' => 'Drawer Systems', 'type' => 'Product', 'brands' => 'Blum'],
            ['name' => 'Sliding Door Hardware', 'type' => 'Product', 'brands' => 'Häfele'],
            ['name' => 'Glass Hardware', 'type' => 'Product', 'brands' => 'Dormakaba'],
            ['name' => 'Silicone Sealant', 'type' => 'Product', 'brands' => 'Dow'],
            ['name' => 'Construction Adhesive', 'type' => 'Product', 'brands' => 'Fevicol'],
            ['name' => 'Cutting Tools', 'type' => 'Product', 'brands' => 'Bosch'],
            ['name' => 'Power Tool Accessories', 'type' => 'Product', 'brands' => 'Bosch'],
            ['name' => 'Industrial Hardware Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Bulk Fastener Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'OEM Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Site Delivery', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Technical Consultation', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Inventory Management', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Emergency Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => '24×7 Supply Support', 'type' => 'Service', 'brands' => 'Supplier'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Cement Manufacturer & Supplier',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Ordinary Portland Cement (OPC)', 'type' => 'Product', 'brands' => 'UltraTech Cement'],
            ['name' => 'Portland Pozzolana Cement (PPC)', 'type' => 'Product', 'brands' => 'ACC Cement'],
            ['name' => 'Portland Slag Cement (PSC)', 'type' => 'Product', 'brands' => 'Ambuja Cement'],
            ['name' => 'Rapid Hardening Cement', 'type' => 'Product', 'brands' => 'UltraTech Cement'],
            ['name' => 'Sulphate Resistant Cement', 'type' => 'Product', 'brands' => 'Dalmia Cement'],
            ['name' => 'White Cement', 'type' => 'Product', 'brands' => 'JK Cement'],
            ['name' => 'Ready Mix Cement', 'type' => 'Product', 'brands' => 'UltraTech RMC'],
            ['name' => 'Bulk Cement Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Bagged Cement Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Fly Ash Cement', 'type' => 'Product', 'brands' => 'ACC Cement'],
            ['name' => 'Low Heat Cement', 'type' => 'Product', 'brands' => 'Ultratech Cement'],
            ['name' => 'High Strength Cement', 'type' => 'Product', 'brands' => 'Ambuja Cement'],
            ['name' => 'Masonry Cement', 'type' => 'Product', 'brands' => 'ACC Cement'],
            ['name' => 'Construction Cement Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Industrial Cement Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Infrastructure Project Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Government Project Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Export Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Quality Testing', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Lab Certification', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Technical Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Mix Design Assistance', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Site Visit Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Dealer Network Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Logistics & Delivery', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => '24×7 Supply Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Electrical Goods & Wiring Material Supplier',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Electrical Wires', 'type' => 'Product', 'brands' => 'Polycab'],
            ['name' => 'House Wiring Cable', 'type' => 'Product', 'brands' => 'Havells'],
            ['name' => 'Industrial Cable', 'type' => 'Product', 'brands' => 'KEI Industries'],
            ['name' => 'Armoured Cable', 'type' => 'Product', 'brands' => 'Polycab'],
            ['name' => 'Flexible Cable', 'type' => 'Product', 'brands' => 'Finolex'],
            ['name' => 'Switches', 'type' => 'Product', 'brands' => 'Legrand'],
            ['name' => 'Modular Switches', 'type' => 'Product', 'brands' => 'Schneider Electric'],
            ['name' => 'MCB', 'type' => 'Product', 'brands' => 'L&T Electrical'],
            ['name' => 'RCCB', 'type' => 'Product', 'brands' => 'Siemens'],
            ['name' => 'MCCB', 'type' => 'Product', 'brands' => 'ABB'],
            ['name' => 'Distribution Board', 'type' => 'Product', 'brands' => 'Schneider Electric'],
            ['name' => 'Electrical Panel', 'type' => 'Product', 'brands' => 'L&T Electrical'],
            ['name' => 'LED Bulbs', 'type' => 'Product', 'brands' => 'Philips'],
            ['name' => 'LED Panels', 'type' => 'Product', 'brands' => 'Crompton'],
            ['name' => 'Tube Lights', 'type' => 'Product', 'brands' => 'Bajaj Electricals'],
            ['name' => 'Fans', 'type' => 'Product', 'brands' => 'Havells'],
            ['name' => 'Exhaust Fans', 'type' => 'Product', 'brands' => 'Usha'],
            ['name' => 'Junction Box', 'type' => 'Product', 'brands' => 'Anchor'],
            ['name' => 'Conduit Pipe', 'type' => 'Product', 'brands' => 'Polycab'],
            ['name' => 'PVC Pipe for Wiring', 'type' => 'Product', 'brands' => 'Supreme Industries'],
            ['name' => 'Cable Tray', 'type' => 'Product', 'brands' => 'Legrand'],
            ['name' => 'Earthing Materials', 'type' => 'Product', 'brands' => 'OBO Bettermann'],
            ['name' => 'Lightning Arrester', 'type' => 'Product', 'brands' => 'DEHN'],
            ['name' => 'Voltage Stabilizer', 'type' => 'Product', 'brands' => 'V-Guard'],
            ['name' => 'Inverter System', 'type' => 'Product', 'brands' => 'Luminous'],
            ['name' => 'Solar Accessories', 'type' => 'Product', 'brands' => 'Tata Power Solar'],
            ['name' => 'Electrical Accessories', 'type' => 'Product', 'brands' => 'Anchor'],
            ['name' => 'Industrial Lighting', 'type' => 'Product', 'brands' => 'Syska'],
            ['name' => 'Smart Switch System', 'type' => 'Product', 'brands' => 'Schneider Electric'],
            ['name' => 'Home Automation Wiring', 'type' => 'Product', 'brands' => 'Legrand'],
            ['name' => 'Bulk Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Project Supply', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Site Delivery', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Supplier'],
            ['name' => '24×7 Supply Support', 'type' => 'Service', 'brands' => 'Supplier'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Sanitaryware Manufacturing & Distribution',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Water Closet (WC)', 'type' => 'Product', 'brands' => 'Hindware'],
            ['name' => 'Wall Hung WC', 'type' => 'Product', 'brands' => 'Jaquar'],
            ['name' => 'One Piece Toilet', 'type' => 'Product', 'brands' => 'Cera'],
            ['name' => 'Two Piece Toilet', 'type' => 'Product', 'brands' => 'Parryware'],
            ['name' => 'Wash Basin', 'type' => 'Product', 'brands' => 'Cera'],
            ['name' => 'Pedestal Basin', 'type' => 'Product', 'brands' => 'Jaquar'],
            ['name' => 'Table Top Basin', 'type' => 'Product', 'brands' => 'Kohler'],
            ['name' => 'Urinals', 'type' => 'Product', 'brands' => 'Hindware'],
            ['name' => 'Bathroom Faucet', 'type' => 'Product', 'brands' => 'Jaquar'],
            ['name' => 'Shower System', 'type' => 'Product', 'brands' => 'Jaquar'],
            ['name' => 'Rain Shower', 'type' => 'Product', 'brands' => 'Kohler'],
            ['name' => 'Bathtub', 'type' => 'Product', 'brands' => 'Kohler'],
            ['name' => 'Bathroom Accessories', 'type' => 'Product', 'brands' => 'Cera'],
            ['name' => 'Concealed Cistern', 'type' => 'Product', 'brands' => 'Geberit'],
            ['name' => 'Flush Plate', 'type' => 'Product', 'brands' => 'Geberit'],
            ['name' => 'Kitchen Sink', 'type' => 'Product', 'brands' => 'Carysil'],
            ['name' => 'SS Sink', 'type' => 'Product', 'brands' => 'Nirali'],
            ['name' => 'Health Faucet', 'type' => 'Product', 'brands' => 'Jaquar'],
            ['name' => 'Bathroom Cabinet', 'type' => 'Product', 'brands' => 'Jaquar'],
            ['name' => 'Mirror Cabinet', 'type' => 'Product', 'brands' => 'Cera'],
            ['name' => 'Sanitary Fittings', 'type' => 'Product', 'brands' => 'Parryware'],
            ['name' => 'Ceramic Tiles', 'type' => 'Product', 'brands' => 'Kajaria Ceramics'],
            ['name' => 'Installation Service', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Plumbing Integration', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Project Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Bulk Dealer Supply', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Showroom Distribution', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Warranty Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Site Measurement', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Steel Structure Manufacturer & Supplier',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Structural Steel Fabrication', 'type' => 'Service', 'brands' => 'Tata Steel'],
            ['name' => 'Steel Beams', 'type' => 'Product', 'brands' => 'JSW Steel'],
            ['name' => 'Steel Columns', 'type' => 'Product', 'brands' => 'Tata Structura'],
            ['name' => 'Steel Channels', 'type' => 'Product', 'brands' => 'SAIL'],
            ['name' => 'Steel Angles', 'type' => 'Product', 'brands' => 'Jindal Steel'],
            ['name' => 'Steel Plates', 'type' => 'Product', 'brands' => 'JSW Steel'],
            ['name' => 'MS Plates', 'type' => 'Product', 'brands' => 'SAIL'],
            ['name' => 'TMT Bars', 'type' => 'Product', 'brands' => 'Tata Tiscon'],
            ['name' => 'Binding Wire', 'type' => 'Product', 'brands' => 'Tata Wiron'],
            ['name' => 'Steel Trusses', 'type' => 'Product', 'brands' => 'Kirby Building Systems'],
            ['name' => 'Industrial Shed Structure', 'type' => 'Product', 'brands' => 'Interarch'],
            ['name' => 'PEB Structure', 'type' => 'Product', 'brands' => 'Zamil Steel'],
            ['name' => 'Warehouse Steel Structure', 'type' => 'Product', 'brands' => 'Tata BlueScope Steel'],
            ['name' => 'Roof Truss System', 'type' => 'Product', 'brands' => 'Kirby Building Systems'],
            ['name' => 'Mezzanine Structure', 'type' => 'Product', 'brands' => 'Jindal Steel'],
            ['name' => 'Staircase Fabrication', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Handrail Fabrication', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Welding Services', 'type' => 'Service', 'brands' => 'Lincoln Electric'],
            ['name' => 'Cutting & Bending', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Sand Blasting', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Shot Blasting', 'type' => 'Service', 'brands' => 'Wheelabrator'],
            ['name' => 'Hot Dip Galvanizing', 'type' => 'Service', 'brands' => 'Valmont'],
            ['name' => 'Powder Coating', 'type' => 'Service', 'brands' => 'AkzoNobel'],
            ['name' => 'Structural Erection', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Site Installation', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Industrial Painting', 'type' => 'Product', 'brands' => 'Asian Paints'],
            ['name' => 'Design & Engineering', 'type' => 'Service', 'brands' => 'Tekla Structures'],
            ['name' => 'Structural Detailing', 'type' => 'Service', 'brands' => 'Tekla Structures'],
            ['name' => 'Quality Inspection', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Load Testing', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => 'Maintenance Service', 'type' => 'Service', 'brands' => 'Manufacturer'],
            ['name' => '24×7 Technical Support', 'type' => 'Service', 'brands' => 'Manufacturer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Building Automation & Energy Management Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Building Energy Audit', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Energy Management System', 'type' => 'Software', 'brands' => 'Siemens Desigo'],
            ['name' => 'Smart Building Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'BMS Design', 'type' => 'Service', 'brands' => 'Honeywell'],
            ['name' => 'HVAC Optimization', 'type' => 'Service', 'brands' => 'Daikin'],
            ['name' => 'Lighting Optimization', 'type' => 'Service', 'brands' => 'Philips'],
            ['name' => 'IoT Integration', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'Smart Meter Integration', 'type' => 'Product', 'brands' => 'Schneider Electric'],
            ['name' => 'Power Monitoring System', 'type' => 'Software', 'brands' => 'ABB'],
            ['name' => 'SCADA System Design', 'type' => 'Software', 'brands' => 'AVEVA'],
            ['name' => 'Digital Twin Building Model', 'type' => 'Software', 'brands' => 'Autodesk Revit'],
            ['name' => 'Predictive Maintenance', 'type' => 'Software', 'brands' => 'IBM Maximo'],
            ['name' => 'Occupancy Analytics', 'type' => 'Software', 'brands' => 'Siemens'],
            ['name' => 'Air Quality Monitoring', 'type' => 'Product', 'brands' => 'Honeywell'],
            ['name' => 'Smart Sensor Deployment', 'type' => 'Product', 'brands' => 'Bosch'],
            ['name' => 'Automation Strategy Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Retrofit Automation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Energy Saving Consultancy', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Carbon Footprint Analysis', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Renewable Integration Planning', 'type' => 'Service', 'brands' => 'Tata Power Solar'],
            ['name' => 'Solar + BMS Integration', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Building Efficiency Audit', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Facility Optimization', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Cost Reduction Analysis', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Technical Design Review', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'System Commissioning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'AMC Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Remote Monitoring Setup', 'type' => 'Software', 'brands' => 'Siemens'],
            ['name' => 'Dashboard Development', 'type' => 'Software', 'brands' => 'Power BI'],
            ['name' => 'KPI Reporting', 'type' => 'Software', 'brands' => 'Microsoft'],
            ['name' => 'Technical Training', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '24×7 Monitoring Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Heavy Machinery & Construction Equipment Dealer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Excavator', 'type' => 'Product', 'brands' => 'JCB'],
            ['name' => 'Mini Excavator', 'type' => 'Product', 'brands' => 'Kubota'],
            ['name' => 'Backhoe Loader', 'type' => 'Product', 'brands' => 'JCB'],
            ['name' => 'Bulldozer', 'type' => 'Product', 'brands' => 'Caterpillar'],
            ['name' => 'Wheel Loader', 'type' => 'Product', 'brands' => 'Volvo CE'],
            ['name' => 'Motor Grader', 'type' => 'Product', 'brands' => 'Caterpillar'],
            ['name' => 'Compactor Roller', 'type' => 'Product', 'brands' => 'BOMAG'],
            ['name' => 'Asphalt Paver', 'type' => 'Product', 'brands' => 'Volvo CE'],
            ['name' => 'Crane', 'type' => 'Product', 'brands' => 'Liebherr'],
            ['name' => 'Tower Crane', 'type' => 'Product', 'brands' => 'Potain'],
            ['name' => 'Mobile Crane', 'type' => 'Product', 'brands' => 'Tadano'],
            ['name' => 'Forklift', 'type' => 'Product', 'brands' => 'Toyota Material Handling'],
            ['name' => 'Telehandler', 'type' => 'Product', 'brands' => 'JCB'],
            ['name' => 'Boom Lift', 'type' => 'Product', 'brands' => 'Genie'],
            ['name' => 'Scissor Lift', 'type' => 'Product', 'brands' => 'JLG'],
            ['name' => 'Concrete Mixer Machine', 'type' => 'Product', 'brands' => 'Ajax Engineering'],
            ['name' => 'Transit Mixer', 'type' => 'Product', 'brands' => 'Schwing Stetter'],
            ['name' => 'Concrete Pump', 'type' => 'Product', 'brands' => 'Putzmeister'],
            ['name' => 'Air Compressor', 'type' => 'Product', 'brands' => 'Atlas Copco'],
            ['name' => 'DG Set', 'type' => 'Product', 'brands' => 'Cummins'],
            ['name' => 'Welding Machine', 'type' => 'Product', 'brands' => 'Lincoln Electric'],
            ['name' => 'Earthmoving Equipment Rental', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Machinery Leasing', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Spare Parts Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'AMC Service', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Operator Supply', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'On-site Maintenance', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Equipment Financing Support', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Fleet Management', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Breakdown Repair', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Technical Training', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => 'Project Equipment Planning', 'type' => 'Service', 'brands' => 'Dealer'],
            ['name' => '24×7 Machinery Support', 'type' => 'Service', 'brands' => 'Dealer'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Road & Highway Engineering Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Highway Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Expressway Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Urban Road Design', 'type' => 'Service', 'brands' => 'Civil 3D'],
            ['name' => 'Rural Road Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Road Alignment Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Geometric Design', 'type' => 'Service', 'brands' => 'Autodesk Civil 3D'],
            ['name' => 'Pavement Design', 'type' => 'Service', 'brands' => 'AASHTO'],
            ['name' => 'Flexible Pavement Design', 'type' => 'Service', 'brands' => 'IRC Guidelines'],
            ['name' => 'Rigid Pavement Design', 'type' => 'Service', 'brands' => 'IRC Guidelines'],
            ['name' => 'Traffic Engineering Study', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Traffic Impact Assessment', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Road Safety Audit', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Intersection Design', 'type' => 'Service', 'brands' => 'Civil 3D'],
            ['name' => 'Flyover Design', 'type' => 'Service', 'brands' => 'STAAD.Pro'],
            ['name' => 'Underpass Design', 'type' => 'Service', 'brands' => 'STAAD.Pro'],
            ['name' => 'Drainage Design', 'type' => 'Service', 'brands' => 'Bentley OpenFlows'],
            ['name' => 'Storm Water Design', 'type' => 'Service', 'brands' => 'Bentley'],
            ['name' => 'Road Survey', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'Topographic Survey', 'type' => 'Service', 'brands' => 'Trimble'],
            ['name' => 'Drone Survey', 'type' => 'Service', 'brands' => 'DJI Enterprise'],
            ['name' => 'Geotechnical Input', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Soil Investigation', 'type' => 'Service', 'brands' => 'Fugro'],
            ['name' => 'BOQ Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Cost Estimation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'DPR Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Tender Documentation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Construction Supervision', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Quality Control', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Value Engineering', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Environmental Impact Study', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Utility Coordination', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'GIS Mapping', 'type' => 'Software', 'brands' => 'ArcGIS'],
            ['name' => '3D Road Modeling', 'type' => 'Software', 'brands' => 'Civil 3D'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '24×7 Project Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Smart City Infrastructure Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Smart City Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Urban Infrastructure Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Integrated Command Center (ICC)', 'type' => 'Service', 'brands' => 'Cisco'],
            ['name' => 'Smart Traffic Management', 'type' => 'Service', 'brands' => 'Siemens Mobility'],
            ['name' => 'Intelligent Transportation System', 'type' => 'Service', 'brands' => 'Kapsch'],
            ['name' => 'Smart Lighting System', 'type' => 'Product', 'brands' => 'Philips'],
            ['name' => 'Smart Street Lighting', 'type' => 'Product', 'brands' => 'Signify'],
            ['name' => 'IoT Sensor Deployment', 'type' => 'Product', 'brands' => 'Bosch'],
            ['name' => 'Smart Water Management', 'type' => 'Software', 'brands' => 'Siemens'],
            ['name' => 'Smart Waste Management', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Digital Utility Mapping', 'type' => 'Software', 'brands' => 'ArcGIS'],
            ['name' => 'GIS-Based Planning', 'type' => 'Software', 'brands' => 'Esri'],
            ['name' => 'CCTV Surveillance Network', 'type' => 'Product', 'brands' => 'Hikvision'],
            ['name' => 'Public Safety System', 'type' => 'Product', 'brands' => 'Honeywell'],
            ['name' => 'Emergency Response System', 'type' => 'Software', 'brands' => 'Motorola Solutions'],
            ['name' => 'Environmental Monitoring', 'type' => 'Product', 'brands' => 'Siemens'],
            ['name' => 'Air Quality Monitoring', 'type' => 'Product', 'brands' => 'Honeywell'],
            ['name' => 'Smart Parking System', 'type' => 'Software', 'brands' => 'ParkPlus'],
            ['name' => 'Smart Metering', 'type' => 'Product', 'brands' => 'Schneider Electric'],
            ['name' => 'Energy Management System', 'type' => 'Software', 'brands' => 'ABB Ability'],
            ['name' => 'Data Analytics Dashboard', 'type' => 'Software', 'brands' => 'Power BI'],
            ['name' => 'City Digital Twin', 'type' => 'Software', 'brands' => 'Bentley iTwin'],
            ['name' => 'SCADA Integration', 'type' => 'Software', 'brands' => 'AVEVA'],
            ['name' => 'Fiber Network Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '5G Infrastructure Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Drone Surveillance', 'type' => 'Product', 'brands' => 'DJI Enterprise'],
            ['name' => 'Infrastructure Monitoring', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'DPR Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'PPP Model Advisory', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Funding Strategy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Policy Compliance', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '24×7 Smart City Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Environmental Engineering Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Environmental Impact Assessment (EIA)', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Environmental Clearance Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Air Quality Monitoring', 'type' => 'Product', 'brands' => 'Thermo Fisher'],
            ['name' => 'Water Quality Analysis', 'type' => 'Service', 'brands' => 'Laboratory'],
            ['name' => 'Soil Contamination Study', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Noise Pollution Study', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Waste Management Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Solid Waste Management', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Hazardous Waste Management', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Industrial Pollution Control', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Effluent Treatment Planning', 'type' => 'Service', 'brands' => 'Thermax'],
            ['name' => 'Sewage Treatment Design', 'type' => 'Service', 'brands' => 'Thermax'],
            ['name' => 'Carbon Footprint Assessment', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Sustainability Reporting', 'type' => 'Service', 'brands' => 'GRI Standards'],
            ['name' => 'Green Building Certification', 'type' => 'Service', 'brands' => 'LEED'],
            ['name' => 'IGBC Certification Support', 'type' => 'Service', 'brands' => 'IGBC'],
            ['name' => 'Energy Audit', 'type' => 'Service', 'brands' => 'Schneider Electric'],
            ['name' => 'Renewable Integration Study', 'type' => 'Service', 'brands' => 'Tata Power Solar'],
            ['name' => 'Water Resource Management', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Rainwater Harvesting Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Ecological Impact Study', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Environmental Monitoring System', 'type' => 'Product', 'brands' => 'Siemens'],
            ['name' => 'GIS Environmental Mapping', 'type' => 'Software', 'brands' => 'ArcGIS'],
            ['name' => 'Drone Environmental Survey', 'type' => 'Product', 'brands' => 'DJI Enterprise'],
            ['name' => 'Climate Risk Assessment', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Compliance Reporting', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Regulatory Approval Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Industrial Emission Control', 'type' => 'Product', 'brands' => 'Donaldson'],
            ['name' => 'Air Pollution Control System', 'type' => 'Product', 'brands' => 'Camfil'],
            ['name' => 'Environmental Lab Testing', 'type' => 'Service', 'brands' => 'NABL Lab'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Site Inspection', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '24×7 Environmental Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Urban Planning Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Urban Development Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'City Master Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Regional Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Smart Urban Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Land Use Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Zoning Plan Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Township Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Infrastructure Master Plan', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Transportation Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Transit Oriented Development (TOD)', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Housing Development Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Commercial Zone Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Industrial Zone Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'GIS Mapping', 'type' => 'Software', 'brands' => 'ArcGIS'],
            ['name' => 'Satellite Mapping Analysis', 'type' => 'Software', 'brands' => 'ESRI'],
            ['name' => 'Drone Survey Mapping', 'type' => 'Product', 'brands' => 'DJI Enterprise'],
            ['name' => 'Topographic Survey', 'type' => 'Service', 'brands' => 'Leica Geosystems'],
            ['name' => 'Traffic Impact Analysis', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Environmental Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Water Supply Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Sewerage Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Storm Water Planning', 'type' => 'Service', 'brands' => 'Bentley OpenFlows'],
            ['name' => 'Public Space Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Urban Landscaping', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Infrastructure Design Coordination', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Policy & Regulatory Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'DPR Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Feasibility Study', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Cost Estimation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Smart City Integration', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Utility Mapping', 'type' => 'Software', 'brands' => 'ArcGIS'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Stakeholder Coordination', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '24×7 Planning Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Real Estate Development Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Real Estate Project Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Residential Project Development', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Commercial Project Development', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Township Development Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Land Acquisition Strategy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Feasibility Study', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Market Research', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Investment Advisory', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Structuring', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Financial Modeling', 'type' => 'Service', 'brands' => 'Excel'],
            ['name' => 'DPR Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Zoning Approval Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'RERA Compliance', 'type' => 'Service', 'brands' => 'RERA Authority'],
            ['name' => 'Legal Documentation Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Architectural Coordination', 'type' => 'Service', 'brands' => 'AutoCAD'],
            ['name' => 'Structural Coordination', 'type' => 'Service', 'brands' => 'STAAD.Pro'],
            ['name' => 'MEP Coordination', 'type' => 'Service', 'brands' => 'Revit MEP'],
            ['name' => 'BIM Coordination', 'type' => 'Service', 'brands' => 'Autodesk Revit'],
            ['name' => 'Construction Planning', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Cost Estimation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'BOQ Preparation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Sales Strategy Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Marketing Strategy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'CRM Integration', 'type' => 'Software', 'brands' => 'Salesforce'],
            ['name' => 'Project Branding', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Channel Partner Network', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Site Execution Monitoring', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Quality Control', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Risk Management', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Handover Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Facility Management Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '24×7 Project Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Infrastructure Financing & Project Advisory Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Infrastructure Financing Advisory', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Finance Structuring', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Debt Syndication', 'type' => 'Service', 'brands' => 'Banks'],
            ['name' => 'Equity Structuring', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'PPP Project Advisory', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Viability Gap Funding (VGF) Support', 'type' => 'Service', 'brands' => 'Government'],
            ['name' => 'Bank Loan Assistance', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Credit Appraisal Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'DPR Financial Modeling', 'type' => 'Service', 'brands' => 'Excel'],
            ['name' => 'Feasibility Study', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Risk Assessment', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Investment Analysis', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Cash Flow Modeling', 'type' => 'Service', 'brands' => 'Excel'],
            ['name' => 'IRR Analysis', 'type' => 'Service', 'brands' => 'Excel'],
            ['name' => 'NPV Analysis', 'type' => 'Service', 'brands' => 'Excel'],
            ['name' => 'Cost-Benefit Analysis', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Valuation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Government Scheme Advisory', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Tender Participation Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Contract Negotiation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Regulatory Compliance', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Funding Strategy Planning', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Infrastructure Bond Advisory', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'ESG Financing Advisory', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Green Project Funding', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Structuring', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Due Diligence', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Financial Audit Support', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Insurance Advisory', 'type' => 'Service', 'brands' => 'LIC'],
            ['name' => 'Loan Documentation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Monitoring', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Reporting Dashboard', 'type' => 'Software', 'brands' => 'Power BI'],
            ['name' => 'Stakeholder Management', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => '24×7 Advisory Support', 'type' => 'Service', 'brands' => 'Consultant'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Industrial Automation & Instrumentation Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Industrial Automation System', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'PLC Programming & Integration', 'type' => 'Software', 'brands' => 'Siemens PLC'],
            ['name' => 'SCADA System Integration', 'type' => 'Software', 'brands' => 'AVEVA'],
            ['name' => 'DCS System Setup', 'type' => 'Software', 'brands' => 'Honeywell'],
            ['name' => 'HMI Development', 'type' => 'Software', 'brands' => 'Schneider Electric'],
            ['name' => 'Instrumentation Installation', 'type' => 'Service', 'brands' => 'Endress+Hauser'],
            ['name' => 'Flow Meter Installation', 'type' => 'Product', 'brands' => 'Siemens'],
            ['name' => 'Pressure Transmitter', 'type' => 'Product', 'brands' => 'Yokogawa'],
            ['name' => 'Level Sensor', 'type' => 'Product', 'brands' => 'Vega'],
            ['name' => 'Temperature Sensor', 'type' => 'Product', 'brands' => 'WIKA'],
            ['name' => 'Control Panel Design', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'MCC Panel Installation', 'type' => 'Product', 'brands' => 'ABB'],
            ['name' => 'PCC Panel Installation', 'type' => 'Product', 'brands' => 'L&T Electrical'],
            ['name' => 'VFD Drive Installation', 'type' => 'Product', 'brands' => 'ABB'],
            ['name' => 'Servo System Integration', 'type' => 'Product', 'brands' => 'Yaskawa'],
            ['name' => 'Industrial Robotics Integration', 'type' => 'Product', 'brands' => 'FANUC'],
            ['name' => 'Machine Automation', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'Process Automation', 'type' => 'Service', 'brands' => 'Honeywell'],
            ['name' => 'Factory Automation', 'type' => 'Service', 'brands' => 'Rockwell Automation'],
            ['name' => 'IoT Integration', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'Smart Factory Setup', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Energy Monitoring System', 'type' => 'Software', 'brands' => 'Schneider Electric'],
            ['name' => 'Data Acquisition System', 'type' => 'Software', 'brands' => 'NI (National Instruments)'],
            ['name' => 'Industrial Networking', 'type' => 'Product', 'brands' => 'Cisco'],
            ['name' => 'Control Valve Automation', 'type' => 'Product', 'brands' => 'Emerson'],
            ['name' => 'Pneumatic System Setup', 'type' => 'Product', 'brands' => 'Festo'],
            ['name' => 'Hydraulic System Integration', 'type' => 'Product', 'brands' => 'Bosch Rexroth'],
            ['name' => 'Calibration Services', 'type' => 'Service', 'brands' => 'Fluke'],
            ['name' => 'Loop Checking', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Commissioning Support', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Maintenance Services', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Annual Maintenance Contract', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Training', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Remote Monitoring', 'type' => 'Software', 'brands' => 'Siemens MindSphere'],
            ['name' => '24×7 Automation Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Cold Storage & Refrigeration Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Cold Storage Construction', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Frozen Storage Facility', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Walk-in Cold Room', 'type' => 'Product', 'brands' => 'Blue Star'],
            ['name' => 'Deep Freezer Room', 'type' => 'Product', 'brands' => 'Voltas'],
            ['name' => 'Multi-Temperature Cold Storage', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Food Cold Storage', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Pharma Cold Storage', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Dairy Cold Storage', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Industrial Refrigeration System', 'type' => 'Product', 'brands' => 'Carrier'],
            ['name' => 'Ammonia Refrigeration System', 'type' => 'Product', 'brands' => 'Kirloskar'],
            ['name' => 'Freon Refrigeration System', 'type' => 'Product', 'brands' => 'Danfoss'],
            ['name' => 'Compressor Unit', 'type' => 'Product', 'brands' => 'Bitzer'],
            ['name' => 'Condensing Unit', 'type' => 'Product', 'brands' => 'Emerson'],
            ['name' => 'Evaporator Coil', 'type' => 'Product', 'brands' => 'Carel'],
            ['name' => 'Insulated PUF Panel', 'type' => 'Product', 'brands' => 'Metecno'],
            ['name' => 'Cold Room Door', 'type' => 'Product', 'brands' => 'Sintex'],
            ['name' => 'Temperature Control System', 'type' => 'Software', 'brands' => 'Danfoss'],
            ['name' => 'Humidity Control System', 'type' => 'Product', 'brands' => 'Honeywell'],
            ['name' => 'Data Logger System', 'type' => 'Product', 'brands' => 'Testo'],
            ['name' => 'Cold Chain Logistics Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Warehouse Automation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Racking System', 'type' => 'Product', 'brands' => 'Godrej Storage Solutions'],
            ['name' => 'Forklift Integration', 'type' => 'Product', 'brands' => 'Toyota Material Handling'],
            ['name' => 'Energy Efficient Cooling', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Installation & Commissioning', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Maintenance Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Breakdown Repair', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Refrigerant Gas Supply', 'type' => 'Product', 'brands' => 'Honeywell'],
            ['name' => 'Thermal Insulation Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Temperature Monitoring App', 'type' => 'Software', 'brands' => 'IoT Platform'],
            ['name' => 'Remote Monitoring System', 'type' => 'Software', 'brands' => 'Siemens'],
            ['name' => 'AMC Service', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Technical Consultancy', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Cold Storage Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ],
    [
        'category' => 'Construction & Infrastructure',
        'sub_category' => 'Waste Management & Recycling Contractor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Solid Waste Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Municipal Waste Collection', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Industrial Waste Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Construction Waste Recycling', 'type' => 'Service', 'brands' => 'Metso'],
            ['name' => 'C&D Waste Processing', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Plastic Waste Recycling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'E-Waste Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Hazardous Waste Disposal', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Biomedical Waste Treatment', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Composting Plant Setup', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Bio-Methanation Plant', 'type' => 'Product', 'brands' => 'Praj Industries'],
            ['name' => 'Waste Sorting Facility', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Material Recovery Facility (MRF)', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Incineration Plant', 'type' => 'Product', 'brands' => 'Hitachi Zosen'],
            ['name' => 'Waste Shredder Machine', 'type' => 'Product', 'brands' => 'Metso'],
            ['name' => 'Balers & Compressors', 'type' => 'Product', 'brands' => 'Bramidan'],
            ['name' => 'Conveyor Systems', 'type' => 'Product', 'brands' => 'Siemens'],
            ['name' => 'Waste Segregation System', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Recycling Plant Design', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Landfill Management', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Leachate Treatment', 'type' => 'Service', 'brands' => 'Thermax'],
            ['name' => 'Waste Transportation Fleet', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'GPS Tracking System', 'type' => 'Software', 'brands' => 'Fleet Management'],
            ['name' => 'Environmental Monitoring', 'type' => 'Product', 'brands' => 'Siemens'],
            ['name' => 'Compost Quality Testing', 'type' => 'Service', 'brands' => 'Laboratory'],
            ['name' => 'Plastic Pelletization Plant', 'type' => 'Product', 'brands' => 'Extrusion Systems'],
            ['name' => 'RDF Plant Setup', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => 'Zero Waste Consultancy', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Sustainability Reporting', 'type' => 'Service', 'brands' => 'GRI Standards'],
            ['name' => 'Carbon Credit Advisory', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Project Management', 'type' => 'Service', 'brands' => 'Primavera P6'],
            ['name' => 'Regulatory Compliance', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Municipal Contract Handling', 'type' => 'Service', 'brands' => 'Contractor'],
            ['name' => '24×7 Waste Management Support', 'type' => 'Service', 'brands' => 'Contractor'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds,
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Construction & Infrastructure Sub Categories 34.78 to 34.104.\n";
