<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Education',
        'sub_category' => 'Language Institute',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Spoken English Course', 'type' => 'Service', 'brands' => 'British Council, Cambridge English'],
            ['name' => 'English Grammar Course', 'type' => 'Service', 'brands' => 'British Council'],
            ['name' => 'IELTS Coaching', 'type' => 'Service', 'brands' => 'IDP, British Council'],
            ['name' => 'TOEFL Coaching', 'type' => 'Service', 'brands' => 'ETS'],
            ['name' => 'PTE Coaching', 'type' => 'Service', 'brands' => 'Pearson'],
            ['name' => 'OET Coaching', 'type' => 'Service', 'brands' => 'OET'],
            ['name' => 'French Language Course', 'type' => 'Service', 'brands' => 'Alliance Française'],
            ['name' => 'German Language Course', 'type' => 'Service', 'brands' => 'Goethe-Institut'],
            ['name' => 'Spanish Language Course', 'type' => 'Service', 'brands' => 'Instituto Cervantes'],
            ['name' => 'Japanese Language Course', 'type' => 'Service', 'brands' => 'Japan Foundation'],
            ['name' => 'Korean Language Course', 'type' => 'Service', 'brands' => 'King Sejong Institute'],
            ['name' => 'Chinese (Mandarin) Course', 'type' => 'Service', 'brands' => 'Confucius Institute'],
            ['name' => 'Arabic Language Course', 'type' => 'Service', 'brands' => 'Local Language Institute'],
            ['name' => 'Russian Language Course', 'type' => 'Service', 'brands' => 'Russian Cultural Centre'],
            ['name' => 'Italian Language Course', 'type' => 'Service', 'brands' => 'Società Dante Alighieri'],
            ['name' => 'Portuguese Language Course', 'type' => 'Service', 'brands' => 'Camões Institute'],
            ['name' => 'Gujarati Language Course', 'type' => 'Service', 'brands' => 'Local Institute'],
            ['name' => 'Hindi Language Course', 'type' => 'Service', 'brands' => 'Local Institute'],
            ['name' => 'Sanskrit Language Course', 'type' => 'Service', 'brands' => 'Sanskrit Bharati'],
            ['name' => 'Public Speaking', 'type' => 'Service', 'brands' => 'Toastmasters'],
            ['name' => 'Business English', 'type' => 'Service', 'brands' => 'British Council'],
            ['name' => 'Accent Training', 'type' => 'Service', 'brands' => 'British Council'],
            ['name' => 'Soft Skills Training', 'type' => 'Service', 'brands' => 'Dale Carnegie'],
            ['name' => 'Interview Preparation', 'type' => 'Service', 'brands' => 'British Council'],
            ['name' => 'Corporate Language Training', 'type' => 'Service', 'brands' => 'British Council'],
            ['name' => 'Translation Training', 'type' => 'Service', 'brands' => 'Local Institute'],
            ['name' => 'Interpreter Training', 'type' => 'Service', 'brands' => 'Local Institute'],
            ['name' => 'Language Certification', 'type' => 'Service', 'brands' => 'Cambridge English'],
            ['name' => 'DELF Preparation', 'type' => 'Service', 'brands' => 'Alliance Française'],
            ['name' => 'Goethe Exam Preparation', 'type' => 'Service', 'brands' => 'Goethe-Institut'],
            ['name' => 'JLPT Preparation', 'type' => 'Service', 'brands' => 'Japan Foundation'],
            ['name' => 'TOPIK Preparation', 'type' => 'Service', 'brands' => 'King Sejong Institute'],
            ['name' => 'HSK Preparation', 'type' => 'Service', 'brands' => 'Confucius Institute'],
            ['name' => 'Online Language Classes', 'type' => 'Service', 'brands' => 'Duolingo, British Council'],
            ['name' => 'Kids Language Program', 'type' => 'Service', 'brands' => 'British Council'],
            ['name' => 'Adult Language Program', 'type' => 'Service', 'brands' => 'British Council'],
            ['name' => 'Weekend Language Classes', 'type' => 'Service', 'brands' => 'Local Institute'],
            ['name' => 'Crash Course', 'type' => 'Service', 'brands' => 'Local Institute'],
            ['name' => 'Study Abroad Language Preparation', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Admission Counseling', 'type' => 'Service', 'brands' => 'Language Institute'],
        ]
    ],
    [
        'category' => 'Education',
        'sub_category' => 'Abacus & Mental Math Institute',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Abacus Beginner Course', 'type' => 'Service', 'brands' => 'UCMAS, SIP Abacus'],
            ['name' => 'Abacus Intermediate Course', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Abacus Advanced Course', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Mental Math Course', 'type' => 'Service', 'brands' => 'SIP Abacus'],
            ['name' => 'Speed Math Training', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Arithmetic Skills Development', 'type' => 'Service', 'brands' => 'SIP Abacus'],
            ['name' => 'Brain Development Program', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Memory Enhancement Program', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Concentration Improvement', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'IQ Development Program', 'type' => 'Service', 'brands' => 'SIP Abacus'],
            ['name' => 'Visual Calculation Training', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Auditory Learning Program', 'type' => 'Service', 'brands' => 'SIP Abacus'],
            ['name' => 'Left & Right Brain Development', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Vedic Mathematics', 'type' => 'Service', 'brands' => 'Vedic Maths Forum India'],
            ['name' => 'Speed Calculation Techniques', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Olympiad Math Preparation', 'type' => 'Service', 'brands' => 'SOF'],
            ['name' => 'Logical Reasoning Classes', 'type' => 'Service', 'brands' => 'SIP Abacus'],
            ['name' => 'Analytical Thinking Program', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Problem Solving Skills', 'type' => 'Service', 'brands' => 'SIP Abacus'],
            ['name' => 'Creative Thinking Program', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Kids Cognitive Development', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Preschool Brain Gym', 'type' => 'Service', 'brands' => 'SIP Abacus'],
            ['name' => 'Number Sense Development', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Multiplication Speed Training', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Competitive Math Skills', 'type' => 'Service', 'brands' => 'SOF'],
            ['name' => 'Online Abacus Classes', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Live Interactive Classes', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Practice Workbook', 'type' => 'Physical Product', 'brands' => 'UCMAS'],
            ['name' => 'Abacus Kit', 'type' => 'Physical Product', 'brands' => 'UCMAS, SIP Abacus'],
            ['name' => 'Finger Calculation Training', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Teacher Training Program', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Student Assessment', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Monthly Progress Report', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'National Competition Preparation', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'International Competition Preparation', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Summer Camp', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Certificate Program', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Parent Counseling', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Trial Class', 'type' => 'Service', 'brands' => 'UCMAS'],
            ['name' => 'Admission Counseling', 'type' => 'Service', 'brands' => 'UCMAS'],
        ]
    ],
    [
        'category' => 'Education',
        'sub_category' => 'Library & Study Center',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Reading Hall', 'type' => 'Service', 'brands' => 'Local Library'],
            ['name' => 'Individual Study Cabin', 'type' => 'Service', 'brands' => 'Local Study Center'],
            ['name' => 'Silent Study Zone', 'type' => 'Service', 'brands' => 'Local Study Center'],
            ['name' => 'AC Study Room', 'type' => 'Service', 'brands' => 'Local Study Center'],
            ['name' => '24x7 Study Facility', 'type' => 'Service', 'brands' => 'Local Study Center'],
            ['name' => 'Library Membership', 'type' => 'Service', 'brands' => 'Local Library'],
            ['name' => 'Daily Study Pass', 'type' => 'Service', 'brands' => 'Local Study Center'],
            ['name' => 'Monthly Study Pass', 'type' => 'Service', 'brands' => 'Local Study Center'],
            ['name' => 'Annual Membership', 'type' => 'Service', 'brands' => 'Local Library'],
            ['name' => 'Digital Library Access', 'type' => 'Service', 'brands' => 'National Digital Library of India'],
            ['name' => 'E-Books Access', 'type' => 'Service', 'brands' => 'Kindle, Google Books'],
            ['name' => 'Competitive Exam Books', 'type' => 'Physical Product', 'brands' => 'Arihant, Disha Publications'],
            ['name' => 'School Textbooks', 'type' => 'Physical Product', 'brands' => 'NCERT'],
            ['name' => 'College Reference Books', 'type' => 'Physical Product', 'brands' => 'Pearson Education'],
            ['name' => 'Newspapers', 'type' => 'Physical Product', 'brands' => 'The Hindu, Indian Express'],
            ['name' => 'Magazines', 'type' => 'Physical Product', 'brands' => 'Competition Success Review'],
            ['name' => 'Research Journals', 'type' => 'Service', 'brands' => 'JSTOR'],
            ['name' => 'Wi-Fi Facility', 'type' => 'Service', 'brands' => 'Library Facility'],
            ['name' => 'Computer Access', 'type' => 'Service', 'brands' => 'Library Facility'],
            ['name' => 'Printing Service', 'type' => 'Service', 'brands' => 'Study Center'],
            ['name' => 'Photocopy Service', 'type' => 'Service', 'brands' => 'Study Center'],
            ['name' => 'Scanning Service', 'type' => 'Service', 'brands' => 'Study Center'],
            ['name' => 'Locker Facility', 'type' => 'Service', 'brands' => 'Study Center'],
            ['name' => 'Drinking Water', 'type' => 'Service', 'brands' => 'Study Center'],
            ['name' => 'Cafeteria', 'type' => 'Service', 'brands' => 'Study Center'],
            ['name' => 'Group Study Room', 'type' => 'Service', 'brands' => 'Study Center'],
            ['name' => 'Discussion Room', 'type' => 'Service', 'brands' => 'Study Center'],
            ['name' => 'Online Reservation', 'type' => 'Service', 'brands' => 'Library Management System'],
            ['name' => 'Book Reservation', 'type' => 'Service', 'brands' => 'Library Management System'],
            ['name' => 'Book Issue & Return', 'type' => 'Service', 'brands' => 'Library Management System'],
            ['name' => 'Book Bank Facility', 'type' => 'Service', 'brands' => 'Library'],
            ['name' => 'Career Guidance Books', 'type' => 'Physical Product', 'brands' => 'Arihant Publications'],
            ['name' => 'UPSC Study Material', 'type' => 'Physical Product', 'brands' => 'McGraw Hill'],
            ['name' => 'NEET/JEE Study Material', 'type' => 'Physical Product', 'brands' => 'Allen, Aakash'],
            ['name' => 'Mock Test Facility', 'type' => 'Service', 'brands' => 'Study Center'],
            ['name' => 'Seminar Hall', 'type' => 'Service', 'brands' => 'Library'],
            ['name' => 'Educational Workshops', 'type' => 'Service', 'brands' => 'Library'],
            ['name' => 'Membership Renewal', 'type' => 'Service', 'brands' => 'Library'],
            ['name' => 'Student Counseling', 'type' => 'Service', 'brands' => 'Study Center'],
            ['name' => 'Study Planning Support', 'type' => 'Service', 'brands' => 'Study Center'],
        ]
    ],
    [
        'category' => 'Education',
        'sub_category' => 'Skill Development Institute',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Digital Marketing Course', 'type' => 'Service', 'brands' => 'Google Digital Garage'],
            ['name' => 'Graphic Design Course', 'type' => 'Service', 'brands' => 'Adobe'],
            ['name' => 'UI/UX Design Course', 'type' => 'Service', 'brands' => 'Google UX'],
            ['name' => 'Web Development Course', 'type' => 'Service', 'brands' => 'Coding Ninjas'],
            ['name' => 'App Development Course', 'type' => 'Service', 'brands' => 'Google Android'],
            ['name' => 'Full Stack Development', 'type' => 'Service', 'brands' => 'Coding Ninjas'],
            ['name' => 'Data Science Course', 'type' => 'Service', 'brands' => 'IBM SkillsBuild'],
            ['name' => 'Artificial Intelligence Course', 'type' => 'Service', 'brands' => 'Microsoft Learn'],
            ['name' => 'Machine Learning Course', 'type' => 'Service', 'brands' => 'IBM SkillsBuild'],
            ['name' => 'Cyber Security Course', 'type' => 'Service', 'brands' => 'EC-Council'],
            ['name' => 'Ethical Hacking Course', 'type' => 'Service', 'brands' => 'EC-Council'],
            ['name' => 'Cloud Computing Course', 'type' => 'Service', 'brands' => 'AWS Academy'],
            ['name' => 'AWS Certification Training', 'type' => 'Service', 'brands' => 'AWS Academy'],
            ['name' => 'Microsoft Azure Training', 'type' => 'Service', 'brands' => 'Microsoft Learn'],
            ['name' => 'DevOps Training', 'type' => 'Service', 'brands' => 'Red Hat'],
            ['name' => 'AutoCAD Course', 'type' => 'Service', 'brands' => 'Autodesk'],
            ['name' => 'Revit Training', 'type' => 'Service', 'brands' => 'Autodesk'],
            ['name' => 'SolidWorks Training', 'type' => 'Service', 'brands' => 'Dassault Systèmes'],
            ['name' => 'CNC Programming', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'PLC & Automation Training', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'Electrician Course', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Plumbing Course', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Welding Course', 'type' => 'Service', 'brands' => 'Lincoln Electric'],
            ['name' => 'Fashion Designing Course', 'type' => 'Service', 'brands' => 'NIFT'],
            ['name' => 'Interior Designing Course', 'type' => 'Service', 'brands' => 'CADD Centre'],
            ['name' => 'Beauty & Makeup Course', 'type' => 'Service', 'brands' => 'Lakmé Academy'],
            ['name' => 'Hair Styling Course', 'type' => 'Service', 'brands' => 'L\'Oréal Professionnel'],
            ['name' => 'Baking Course', 'type' => 'Service', 'brands' => 'Lavonne Academy'],
            ['name' => 'Hotel Management Training', 'type' => 'Service', 'brands' => 'IIHM'],
            ['name' => 'Retail Sales Training', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Spoken English', 'type' => 'Service', 'brands' => 'British Council'],
            ['name' => 'Personality Development', 'type' => 'Service', 'brands' => 'Dale Carnegie'],
            ['name' => 'Interview Skills', 'type' => 'Service', 'brands' => 'Dale Carnegie'],
            ['name' => 'Entrepreneurship Development', 'type' => 'Service', 'brands' => 'Startup India'],
            ['name' => 'Soft Skills Training', 'type' => 'Service', 'brands' => 'NIIT'],
            ['name' => 'Internship Program', 'type' => 'Service', 'brands' => 'Institute Program'],
            ['name' => 'Placement Assistance', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Industry Certification', 'type' => 'Service', 'brands' => 'Microsoft, Adobe'],
            ['name' => 'Online Learning', 'type' => 'Service', 'brands' => 'Coursera'],
            ['name' => 'Career Counseling', 'type' => 'Service', 'brands' => 'Institute'],
        ]
    ],
    [
        'category' => 'Education',
        'sub_category' => 'Preschool / Kindergarten',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Playgroup Admission', 'type' => 'Service', 'brands' => 'EuroKids, Kidzee'],
            ['name' => 'Nursery Admission', 'type' => 'Service', 'brands' => 'EuroKids, Bachpan'],
            ['name' => 'Junior KG', 'type' => 'Service', 'brands' => 'EuroKids'],
            ['name' => 'Senior KG', 'type' => 'Service', 'brands' => 'Kidzee'],
            ['name' => 'Early Childhood Education', 'type' => 'Service', 'brands' => 'EuroKids'],
            ['name' => 'Montessori Program', 'type' => 'Service', 'brands' => 'Montessori Method'],
            ['name' => 'Daycare', 'type' => 'Service', 'brands' => 'KLAY, EuroKids'],
            ['name' => 'Half Day Program', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Full Day Program', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Toddler Program', 'type' => 'Service', 'brands' => 'Hello Kids'],
            ['name' => 'Activity-Based Learning', 'type' => 'Service', 'brands' => 'LEAD School'],
            ['name' => 'Smart Classroom', 'type' => 'Service', 'brands' => 'Next Education'],
            ['name' => 'Storytelling Sessions', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Phonics Classes', 'type' => 'Service', 'brands' => 'Jolly Phonics'],
            ['name' => 'English Speaking Activities', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Mathematics Readiness', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Art & Craft', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Drawing Classes', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Music & Singing', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Dance Classes', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Yoga for Kids', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Indoor Games', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Outdoor Play Area', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Sensory Activities', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'STEM Activities', 'type' => 'Service', 'brands' => 'LEGO Education'],
            ['name' => 'Robotics for Kids', 'type' => 'Service', 'brands' => 'LEGO Education'],
            ['name' => 'Personality Development', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Parent-Teacher Meeting', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Child Progress Report', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'School Transport', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Healthy Meal Program', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Summer Camp', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Holiday Camp', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Birthday Celebration', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Annual Function', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Educational Excursions', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Online Parent Portal', 'type' => 'Service', 'brands' => 'School ERP'],
            ['name' => 'Live Parent Updates', 'type' => 'Service', 'brands' => 'Preschool App'],
            ['name' => 'Admission Counseling', 'type' => 'Service', 'brands' => 'Preschool'],
            ['name' => 'Trial Class', 'type' => 'Service', 'brands' => 'Preschool'],
        ]
    ],
    [
        'category' => 'Education',
        'sub_category' => 'Special Education Center',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Special Education Assessment', 'type' => 'Service', 'brands' => 'NIEPID'],
            ['name' => 'Learning Disability Assessment', 'type' => 'Service', 'brands' => 'Certified Specialists'],
            ['name' => 'Autism Support Program', 'type' => 'Service', 'brands' => 'Action For Autism'],
            ['name' => 'ADHD Support Program', 'type' => 'Service', 'brands' => 'Certified Specialists'],
            ['name' => 'Dyslexia Intervention', 'type' => 'Service', 'brands' => 'Certified Specialists'],
            ['name' => 'Speech Therapy', 'type' => 'Service', 'brands' => 'Certified Speech Therapists'],
            ['name' => 'Occupational Therapy', 'type' => 'Service', 'brands' => 'Certified Therapists'],
            ['name' => 'Behavioral Therapy', 'type' => 'Service', 'brands' => 'Certified Therapists'],
            ['name' => 'Sensory Integration Therapy', 'type' => 'Service', 'brands' => 'Certified Therapists'],
            ['name' => 'Early Intervention Program', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Individual Education Plan (IEP)', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Inclusive Education Support', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Shadow Teacher Support', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Remedial Education', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Cognitive Skill Development', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Social Skills Training', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Communication Skills Training', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Parent Counseling', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Family Guidance Program', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Psychological Assessment', 'type' => 'Service', 'brands' => 'Certified Psychologists'],
            ['name' => 'IQ Assessment', 'type' => 'Service', 'brands' => 'Certified Psychologists'],
            ['name' => 'Developmental Screening', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Physiotherapy', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Fine Motor Skill Training', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Gross Motor Skill Training', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Life Skills Training', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Vocational Training', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Assistive Technology Training', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Braille Education', 'type' => 'Service', 'brands' => 'National Institute for the Empowerment of Persons with Visual Disabilities'],
            ['name' => 'Sign Language Training', 'type' => 'Service', 'brands' => 'Indian Sign Language Research & Training Centre'],
            ['name' => 'Online Therapy', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Tele Counseling', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Home-Based Intervention', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Group Therapy', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Child Progress Evaluation', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Teacher Training Program', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Inclusive Classroom Support', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'School Readiness Program', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Admission Counseling', 'type' => 'Service', 'brands' => 'Special Education Center'],
            ['name' => 'Follow-up Assessment', 'type' => 'Service', 'brands' => 'Special Education Center'],
        ]
    ],
    [
        'category' => 'Education',
        'sub_category' => 'Vocational Training Institute',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Electrician Training', 'type' => 'Service', 'brands' => 'NSDC, ITI'],
            ['name' => 'Wireman Course', 'type' => 'Service', 'brands' => 'ITI'],
            ['name' => 'Fitter Course', 'type' => 'Service', 'brands' => 'ITI'],
            ['name' => 'Turner Course', 'type' => 'Service', 'brands' => 'ITI'],
            ['name' => 'Welder Training', 'type' => 'Service', 'brands' => 'Lincoln Electric'],
            ['name' => 'CNC Operator Training', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'CNC Programming', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'PLC & Automation', 'type' => 'Service', 'brands' => 'Siemens'],
            ['name' => 'Mechanical Technician Course', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Automobile Technician Course', 'type' => 'Service', 'brands' => 'ASDC'],
            ['name' => 'Two-Wheeler Mechanic Course', 'type' => 'Service', 'brands' => 'Hero MotoCorp'],
            ['name' => 'Four-Wheeler Mechanic Course', 'type' => 'Service', 'brands' => 'Maruti Suzuki'],
            ['name' => 'AC & Refrigeration Technician', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Plumbing Course', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Carpenter Training', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Mason Training', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Painter Training', 'type' => 'Service', 'brands' => 'Asian Paints Academy'],
            ['name' => 'Tailoring Course', 'type' => 'Service', 'brands' => 'Usha'],
            ['name' => 'Fashion Designing', 'type' => 'Service', 'brands' => 'NIFT'],
            ['name' => 'Beauty Therapist Course', 'type' => 'Service', 'brands' => 'Lakmé Academy'],
            ['name' => 'Hair Stylist Course', 'type' => 'Service', 'brands' => 'L\'Oréal Professionnel'],
            ['name' => 'Makeup Artist Course', 'type' => 'Service', 'brands' => 'Lakmé Academy'],
            ['name' => 'Spa Therapist Course', 'type' => 'Service', 'brands' => 'VLCC Institute'],
            ['name' => 'Hospitality Training', 'type' => 'Service', 'brands' => 'IIHM'],
            ['name' => 'Hotel Management Skills', 'type' => 'Service', 'brands' => 'IIHM'],
            ['name' => 'Housekeeping Training', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Retail Sales Associate', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Data Entry Operator', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Office Assistant Course', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Tally & GST Training', 'type' => 'Service', 'brands' => 'Tally Education'],
            ['name' => 'Computer Hardware Course', 'type' => 'Service', 'brands' => 'Jetking'],
            ['name' => 'Networking Course', 'type' => 'Service', 'brands' => 'Cisco Networking Academy'],
            ['name' => 'CCTV Installation Course', 'type' => 'Service', 'brands' => 'Hikvision'],
            ['name' => 'Mobile Repairing Course', 'type' => 'Service', 'brands' => 'MI Academy'],
            ['name' => 'Solar Technician Course', 'type' => 'Service', 'brands' => 'Skill Council for Green Jobs'],
            ['name' => 'Entrepreneurship Development', 'type' => 'Service', 'brands' => 'Startup India'],
            ['name' => 'Apprenticeship Program', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Placement Assistance', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Skill Certification', 'type' => 'Service', 'brands' => 'NSDC'],
            ['name' => 'Career Counseling', 'type' => 'Service', 'brands' => 'Institute'],
        ]
    ],
    [
        'category' => 'Education',
        'sub_category' => 'Study Abroad Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Study Abroad Counseling', 'type' => 'Service', 'brands' => 'IDP Education, KC Overseas'],
            ['name' => 'University Selection', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Course Selection Guidance', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Career Counseling', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Country Selection', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Admission Assistance', 'type' => 'Service', 'brands' => 'KC Overseas'],
            ['name' => 'University Application', 'type' => 'Service', 'brands' => 'ApplyBoard'],
            ['name' => 'SOP Writing', 'type' => 'Service', 'brands' => 'Leverage Edu'],
            ['name' => 'LOR Guidance', 'type' => 'Service', 'brands' => 'Leverage Edu'],
            ['name' => 'Resume Preparation', 'type' => 'Service', 'brands' => 'Leverage Edu'],
            ['name' => 'IELTS Coaching', 'type' => 'Service', 'brands' => 'IDP, British Council'],
            ['name' => 'TOEFL Coaching', 'type' => 'Service', 'brands' => 'ETS'],
            ['name' => 'PTE Coaching', 'type' => 'Service', 'brands' => 'Pearson'],
            ['name' => 'GRE Coaching', 'type' => 'Service', 'brands' => 'Manya'],
            ['name' => 'GMAT Coaching', 'type' => 'Service', 'brands' => 'Jamboree'],
            ['name' => 'SAT Coaching', 'type' => 'Service', 'brands' => 'Princeton Review'],
            ['name' => 'Visa Counseling', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Student Visa Processing', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Visa Documentation', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Interview Preparation', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Education Loan Assistance', 'type' => 'Service', 'brands' => 'HDFC Credila, Avanse'],
            ['name' => 'Scholarship Guidance', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Financial Documentation', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Forex Assistance', 'type' => 'Service', 'brands' => 'BookMyForex'],
            ['name' => 'Overseas Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Accommodation Assistance', 'type' => 'Service', 'brands' => 'University Living'],
            ['name' => 'Airport Pickup Assistance', 'type' => 'Service', 'brands' => 'University Living'],
            ['name' => 'Pre-Departure Orientation', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Forex Card', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'International SIM Card', 'type' => 'Service', 'brands' => 'Matrix'],
            ['name' => 'Travel Assistance', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'Internship Guidance', 'type' => 'Service', 'brands' => 'Leverage Edu'],
            ['name' => 'Post-Study Work Visa Guidance', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'PR Guidance', 'type' => 'Service', 'brands' => 'Y-Axis'],
            ['name' => 'Application Tracking', 'type' => 'Service', 'brands' => 'ApplyBoard'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Document Verification', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'University Admission Updates', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Offer Letter Assistance', 'type' => 'Service', 'brands' => 'Consultant'],
            ['name' => 'Admission Counseling', 'type' => 'Service', 'brands' => 'IDP Education'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Education Sub Categories 29.7 to 29.14.\n";
