<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Automotive',
        'sub_category' => 'Bicycle Store',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Mountain Bike (MTB)', 'type' => 'Physical Product', 'brands' => 'Hero Cycles, Firefox, Montra'],
            ['name' => 'Road Bike', 'type' => 'Physical Product', 'brands' => 'Trek, Giant, Scott'],
            ['name' => 'Hybrid Bicycle', 'type' => 'Physical Product', 'brands' => 'Firefox, Montra'],
            ['name' => 'City Bicycle', 'type' => 'Physical Product', 'brands' => 'Hero Cycles, Atlas'],
            ['name' => 'Kids Bicycle', 'type' => 'Physical Product', 'brands' => 'Hero Cycles, BSA, Hercules'],
            ['name' => 'BMX Bicycle', 'type' => 'Physical Product', 'brands' => 'Mongoose, Firefox'],
            ['name' => 'Folding Bicycle', 'type' => 'Physical Product', 'brands' => 'Schnell, Firefox'],
            ['name' => 'Electric Bicycle (E-Bike)', 'type' => 'Physical Product', 'brands' => 'EMotorad, Hero Lectro'],
            ['name' => 'Fat Bike', 'type' => 'Physical Product', 'brands' => 'Montra'],
            ['name' => 'Touring Bicycle', 'type' => 'Physical Product', 'brands' => 'Trek, Giant'],
            ['name' => 'Racing Bicycle', 'type' => 'Physical Product', 'brands' => 'Trek, Scott'],
            ['name' => 'Ladies Bicycle', 'type' => 'Physical Product', 'brands' => 'Ladybird, BSA'],
            ['name' => 'Bicycle Frame', 'type' => 'Physical Product', 'brands' => 'Hero Cycles, Firefox'],
            ['name' => 'Bicycle Fork', 'type' => 'Physical Product', 'brands' => 'SR Suntour'],
            ['name' => 'Bicycle Handlebar', 'type' => 'Physical Product', 'brands' => 'Zoom, UNO'],
            ['name' => 'Bicycle Stem', 'type' => 'Physical Product', 'brands' => 'UNO'],
            ['name' => 'Bicycle Saddle', 'type' => 'Physical Product', 'brands' => 'Selle Royal, Btwin'],
            ['name' => 'Bicycle Seat Cover', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Pedals', 'type' => 'Physical Product', 'brands' => 'Shimano'],
            ['name' => 'Crankset', 'type' => 'Physical Product', 'brands' => 'Shimano'],
            ['name' => 'Chain', 'type' => 'Physical Product', 'brands' => 'KMC, Shimano'],
            ['name' => 'Cassette', 'type' => 'Physical Product', 'brands' => 'Shimano'],
            ['name' => 'Freewheel', 'type' => 'Physical Product', 'brands' => 'Shimano'],
            ['name' => 'Derailleur', 'type' => 'Physical Product', 'brands' => 'Shimano'],
            ['name' => 'Gear Shifter', 'type' => 'Physical Product', 'brands' => 'Shimano'],
            ['name' => 'Brake Set', 'type' => 'Physical Product', 'brands' => 'Shimano, Tektro'],
            ['name' => 'Disc Brake', 'type' => 'Physical Product', 'brands' => 'Shimano'],
            ['name' => 'Brake Pads', 'type' => 'Physical Product', 'brands' => 'Shimano'],
            ['name' => 'Wheel Set', 'type' => 'Physical Product', 'brands' => 'Shimano'],
            ['name' => 'Bicycle Tyres', 'type' => 'Physical Product', 'brands' => 'Michelin, Maxxis, Ralson'],
            ['name' => 'Bicycle Tubes', 'type' => 'Physical Product', 'brands' => 'Ralson, Michelin'],
            ['name' => 'Mudguards', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Water Bottle Cage', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Bicycle Water Bottle', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Cycle Bell', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Bicycle Lock', 'type' => 'Physical Product', 'brands' => 'Godrej, Btwin'],
            ['name' => 'Front Light', 'type' => 'Physical Product', 'brands' => 'Cateye, Btwin'],
            ['name' => 'Rear Light', 'type' => 'Physical Product', 'brands' => 'Cateye'],
            ['name' => 'Reflectors', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Helmet', 'type' => 'Physical Product', 'brands' => 'Btwin, Giro'],
            ['name' => 'Cycling Gloves', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Cycling Jersey', 'type' => 'Physical Product', 'brands' => 'Rockrider'],
            ['name' => 'Cycling Shorts', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Cycling Shoes', 'type' => 'Physical Product', 'brands' => 'Shimano'],
            ['name' => 'Bike Pump', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'CO₂ Inflator', 'type' => 'Physical Product', 'brands' => 'Topeak'],
            ['name' => 'Puncture Repair Kit', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Multi Tool', 'type' => 'Physical Product', 'brands' => 'Topeak'],
            ['name' => 'Chain Lubricant', 'type' => 'Physical Product', 'brands' => 'Finish Line, Motul'],
            ['name' => 'Bike Cleaning Kit', 'type' => 'Physical Product', 'brands' => 'Muc-Off, Motul'],
            ['name' => 'Bicycle Stand', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Bike Trainer', 'type' => 'Physical Product', 'brands' => 'Wahoo'],
            ['name' => 'Bike Carrier Rack', 'type' => 'Physical Product', 'brands' => 'Thule'],
            ['name' => 'Child Bicycle Seat', 'type' => 'Physical Product', 'brands' => 'Thule'],
            ['name' => 'Saddle Bag', 'type' => 'Physical Product', 'brands' => 'Topeak'],
            ['name' => 'Handlebar Bag', 'type' => 'Physical Product', 'brands' => 'Topeak'],
            ['name' => 'Rear Carrier', 'type' => 'Physical Product', 'brands' => 'Btwin'],
            ['name' => 'Cycling Computer', 'type' => 'Physical Product', 'brands' => 'Garmin'],
            ['name' => 'GPS Bike Computer', 'type' => 'Physical Product', 'brands' => 'Garmin, Wahoo'],
            ['name' => 'Heart Rate Monitor', 'type' => 'Physical Product', 'brands' => 'Garmin'],
            ['name' => 'Smart Trainer', 'type' => 'Physical Product', 'brands' => 'Wahoo'],
            ['name' => 'Bicycle Tool Kit', 'type' => 'Physical Product', 'brands' => 'Super B'],
            ['name' => 'Bicycle Care Combo', 'type' => 'Physical Product', 'brands' => 'Muc-Off, Motul'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'Auto Parts Store',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Engine Oil', 'type' => 'Physical Product', 'brands' => 'Castrol, Shell, Mobil, Motul'],
            ['name' => 'Gear Oil', 'type' => 'Physical Product', 'brands' => 'Castrol, Motul'],
            ['name' => 'Brake Oil', 'type' => 'Physical Product', 'brands' => 'Bosch, Castrol'],
            ['name' => 'Coolant', 'type' => 'Physical Product', 'brands' => 'Prestone, Castrol'],
            ['name' => 'Radiator Coolant', 'type' => 'Physical Product', 'brands' => 'Prestone'],
            ['name' => 'Car Battery', 'type' => 'Physical Product', 'brands' => 'Exide, Amaron, SF Sonic'],
            ['name' => 'Spark Plug', 'type' => 'Physical Product', 'brands' => 'NGK, Bosch'],
            ['name' => 'Air Filter', 'type' => 'Physical Product', 'brands' => 'Bosch, MANN'],
            ['name' => 'Oil Filter', 'type' => 'Physical Product', 'brands' => 'Bosch, MANN'],
            ['name' => 'Fuel Filter', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Cabin Air Filter', 'type' => 'Physical Product', 'brands' => 'MANN'],
            ['name' => 'Timing Belt', 'type' => 'Physical Product', 'brands' => 'Gates, Contitech'],
            ['name' => 'Fan Belt', 'type' => 'Physical Product', 'brands' => 'Gates'],
            ['name' => 'Clutch Kit', 'type' => 'Physical Product', 'brands' => 'Valeo, Luk'],
            ['name' => 'Clutch Plate', 'type' => 'Physical Product', 'brands' => 'Valeo'],
            ['name' => 'Brake Pads', 'type' => 'Physical Product', 'brands' => 'Bosch, Brembo'],
            ['name' => 'Brake Disc', 'type' => 'Physical Product', 'brands' => 'Brembo'],
            ['name' => 'Brake Shoes', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Shock Absorber', 'type' => 'Physical Product', 'brands' => 'Monroe, Gabriel'],
            ['name' => 'Suspension Kit', 'type' => 'Physical Product', 'brands' => 'Monroe'],
            ['name' => 'Steering Rack', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Wheel Bearing', 'type' => 'Physical Product', 'brands' => 'SKF, FAG'],
            ['name' => 'CV Joint', 'type' => 'Physical Product', 'brands' => 'GSP'],
            ['name' => 'Axle Shaft', 'type' => 'Physical Product', 'brands' => 'GSP'],
            ['name' => 'Tyres', 'type' => 'Physical Product', 'brands' => 'MRF, CEAT, Apollo, Michelin'],
            ['name' => 'Alloy Wheels', 'type' => 'Physical Product', 'brands' => 'Neo Wheels'],
            ['name' => 'Wheel Cap', 'type' => 'Physical Product', 'brands' => 'OEM, Local Brands'],
            ['name' => 'Wiper Blades', 'type' => 'Physical Product', 'brands' => 'Bosch, Michelin'],
            ['name' => 'Headlight Bulb', 'type' => 'Physical Product', 'brands' => 'Philips, Osram'],
            ['name' => 'LED Headlight', 'type' => 'Physical Product', 'brands' => 'Philips, Osram'],
            ['name' => 'Tail Light', 'type' => 'Physical Product', 'brands' => 'OEM'],
            ['name' => 'Fog Lamp', 'type' => 'Physical Product', 'brands' => 'Hella'],
            ['name' => 'Horn', 'type' => 'Physical Product', 'brands' => 'Bosch, Roots'],
            ['name' => 'Fuse', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Relay', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Alternator', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Starter Motor', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Car Stereo', 'type' => 'Physical Product', 'brands' => 'Sony, Pioneer'],
            ['name' => 'Android Stereo', 'type' => 'Physical Product', 'brands' => 'Blaupunkt'],
            ['name' => 'Reverse Camera', 'type' => 'Physical Product', 'brands' => 'Sony, Blaupunkt'],
            ['name' => 'Dash Camera', 'type' => 'Physical Product', 'brands' => 'DDPAI, 70mai'],
            ['name' => 'GPS Tracker', 'type' => 'Physical Product', 'brands' => 'Ajjas'],
            ['name' => 'Seat Cover', 'type' => 'Physical Product', 'brands' => 'Autofurnish'],
            ['name' => 'Floor Mat', 'type' => 'Physical Product', 'brands' => '3D Mats'],
            ['name' => 'Steering Cover', 'type' => 'Physical Product', 'brands' => 'Autofurnish'],
            ['name' => 'Car Cover', 'type' => 'Physical Product', 'brands' => 'Polco'],
            ['name' => 'Car Perfume', 'type' => 'Physical Product', 'brands' => 'Areon, Ambi Pur'],
            ['name' => 'Car Polish', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Car Wax', 'type' => 'Physical Product', 'brands' => 'Meguiar\'s'],
            ['name' => 'Ceramic Coating', 'type' => 'Physical Product', 'brands' => 'Turtle Wax'],
            ['name' => 'Cleaning Shampoo', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Microfiber Cloth', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Pressure Washer', 'type' => 'Physical Product', 'brands' => 'Bosch, Kärcher'],
            ['name' => 'Jack', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Jack Stand', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Tyre Inflator', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Jump Starter', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Tow Rope', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Emergency Tool Kit', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'OBD Scanner', 'type' => 'Physical Product', 'brands' => 'Launch, Bosch'],
            ['name' => 'Auto Parts Combo Kit', 'type' => 'Physical Product', 'brands' => 'Bosch, 3M'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'Tyre Shop',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Car Tyres', 'type' => 'Physical Product', 'brands' => 'MRF, CEAT, Apollo, Michelin'],
            ['name' => 'SUV Tyres', 'type' => 'Physical Product', 'brands' => 'Bridgestone, Michelin'],
            ['name' => 'Luxury Car Tyres', 'type' => 'Physical Product', 'brands' => 'Pirelli, Continental'],
            ['name' => 'Performance Tyres', 'type' => 'Physical Product', 'brands' => 'Michelin Pilot Sport, Pirelli P Zero'],
            ['name' => 'EV Tyres', 'type' => 'Physical Product', 'brands' => 'Michelin, Bridgestone'],
            ['name' => 'Motorcycle Tyres', 'type' => 'Physical Product', 'brands' => 'MRF, CEAT, TVS Eurogrip'],
            ['name' => 'Scooter Tyres', 'type' => 'Physical Product', 'brands' => 'CEAT, MRF'],
            ['name' => 'Bicycle Tyres', 'type' => 'Physical Product', 'brands' => 'Michelin, Maxxis, Ralson'],
            ['name' => 'Truck Tyres', 'type' => 'Physical Product', 'brands' => 'JK Tyre, Apollo'],
            ['name' => 'Bus Tyres', 'type' => 'Physical Product', 'brands' => 'Apollo, Bridgestone'],
            ['name' => 'Tractor Tyres', 'type' => 'Physical Product', 'brands' => 'BKT, MRF'],
            ['name' => 'OTR Tyres', 'type' => 'Physical Product', 'brands' => 'BKT, JK Tyre'],
            ['name' => 'Radial Tyres', 'type' => 'Physical Product', 'brands' => 'Michelin, Apollo'],
            ['name' => 'Tubeless Tyres', 'type' => 'Physical Product', 'brands' => 'MRF, CEAT'],
            ['name' => 'Tube Tyres', 'type' => 'Physical Product', 'brands' => 'Ralson'],
            ['name' => 'Tyre Tube', 'type' => 'Physical Product', 'brands' => 'MRF, Ralson'],
            ['name' => 'Alloy Wheels', 'type' => 'Physical Product', 'brands' => 'Neo Wheels, Plati'],
            ['name' => 'Steel Wheels', 'type' => 'Physical Product', 'brands' => 'OEM'],
            ['name' => 'Wheel Rim', 'type' => 'Physical Product', 'brands' => 'Neo Wheels'],
            ['name' => 'Wheel Cap', 'type' => 'Physical Product', 'brands' => 'OEM'],
            ['name' => 'Wheel Nuts', 'type' => 'Physical Product', 'brands' => 'OEM'],
            ['name' => 'Wheel Bolts', 'type' => 'Physical Product', 'brands' => 'OEM'],
            ['name' => 'Wheel Spacers', 'type' => 'Physical Product', 'brands' => 'H&R'],
            ['name' => 'Valve Stem', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Tyre Valve Cap', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Nitrogen Valve', 'type' => 'Physical Product', 'brands' => 'Local Brands'],
            ['name' => 'TPMS Sensor', 'type' => 'Physical Product', 'brands' => 'Bosch, Schrader'],
            ['name' => 'Tyre Pressure Gauge', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Digital Tyre Gauge', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Tyre Inflator', 'type' => 'Physical Product', 'brands' => 'Michelin, Bergmann'],
            ['name' => 'Portable Air Compressor', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Wheel Balancing Weights', 'type' => 'Physical Product', 'brands' => 'Wurth'],
            ['name' => 'Tyre Repair Kit', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Tubeless Puncture Kit', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Tyre Sealant', 'type' => 'Physical Product', 'brands' => 'Slime'],
            ['name' => 'Tyre Lever', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Tyre Changer Machine', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Wheel Balancing Machine', 'type' => 'Physical Product', 'brands' => 'Bosch, Launch'],
            ['name' => 'Wheel Alignment Machine', 'type' => 'Physical Product', 'brands' => 'Launch, Bosch'],
            ['name' => 'Hydraulic Jack', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Trolley Jack', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Jack Stand', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Torque Wrench', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'Cross Wheel Spanner', 'type' => 'Physical Product', 'brands' => 'Taparia'],
            ['name' => 'Tyre Shine', 'type' => 'Physical Product', 'brands' => '3M, Wavex'],
            ['name' => 'Tyre Cleaner', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Wheel Cleaner', 'type' => 'Physical Product', 'brands' => 'Sonax'],
            ['name' => 'Alloy Wheel Cleaner', 'type' => 'Physical Product', 'brands' => 'Sonax'],
            ['name' => 'Wheel Brush', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Microfiber Cloth', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Tyre Cover', 'type' => 'Physical Product', 'brands' => 'Polco'],
            ['name' => 'Spare Wheel Cover', 'type' => 'Physical Product', 'brands' => 'Polco'],
            ['name' => 'Tyre Storage Rack', 'type' => 'Physical Product', 'brands' => 'Local Brands'],
            ['name' => 'Emergency Tyre Kit', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Tyre Care Combo', 'type' => 'Physical Product', 'brands' => '3M, Michelin'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'Car Accessories Store',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Seat Covers', 'type' => 'Physical Product', 'brands' => 'Autofurnish, Elegant, AutoForm'],
            ['name' => 'Floor Mats', 'type' => 'Physical Product', 'brands' => '3D Mats, Autofurnish'],
            ['name' => 'Steering Wheel Cover', 'type' => 'Physical Product', 'brands' => 'AutoForm, Autofurnish'],
            ['name' => 'Dashboard Cover', 'type' => 'Physical Product', 'brands' => 'Elegant'],
            ['name' => 'Car Cover', 'type' => 'Physical Product', 'brands' => 'Polco, Autofurnish'],
            ['name' => 'Sun Shades', 'type' => 'Physical Product', 'brands' => 'AutoSun, Autofurnish'],
            ['name' => 'Window Curtains', 'type' => 'Physical Product', 'brands' => 'AutoForm'],
            ['name' => 'Neck Pillow', 'type' => 'Physical Product', 'brands' => 'AutoForm'],
            ['name' => 'Seat Cushion', 'type' => 'Physical Product', 'brands' => 'AutoForm'],
            ['name' => 'Lumbar Support Cushion', 'type' => 'Physical Product', 'brands' => 'AutoForm'],
            ['name' => 'Car Organizer', 'type' => 'Physical Product', 'brands' => 'Autofurnish'],
            ['name' => 'Trunk Organizer', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Boot Mat', 'type' => 'Physical Product', 'brands' => '3D Mats'],
            ['name' => 'Door Visor', 'type' => 'Physical Product', 'brands' => 'Galio'],
            ['name' => 'Mud Flaps', 'type' => 'Physical Product', 'brands' => 'Galio'],
            ['name' => 'Chrome Garnish', 'type' => 'Physical Product', 'brands' => 'Galio'],
            ['name' => 'Body Side Moulding', 'type' => 'Physical Product', 'brands' => 'Galio'],
            ['name' => 'Bumper Protector', 'type' => 'Physical Product', 'brands' => 'Galio'],
            ['name' => 'Door Edge Guard', 'type' => 'Physical Product', 'brands' => 'Galio'],
            ['name' => 'Door Sill Plate', 'type' => 'Physical Product', 'brands' => 'Galio'],
            ['name' => 'Car Perfume', 'type' => 'Physical Product', 'brands' => 'Areon, Ambi Pur'],
            ['name' => 'Air Freshener', 'type' => 'Physical Product', 'brands' => 'Ambi Pur, Areon'],
            ['name' => 'Mobile Holder', 'type' => 'Physical Product', 'brands' => 'Portronics, Spigen'],
            ['name' => 'Car Charger', 'type' => 'Physical Product', 'brands' => 'Portronics, Ambrane'],
            ['name' => 'USB Car Charger', 'type' => 'Physical Product', 'brands' => 'Belkin'],
            ['name' => 'Wireless Car Charger', 'type' => 'Physical Product', 'brands' => 'Spigen'],
            ['name' => 'Android Infotainment System', 'type' => 'Physical Product', 'brands' => 'Sony, Blaupunkt'],
            ['name' => 'Car Stereo', 'type' => 'Physical Product', 'brands' => 'Pioneer, Sony'],
            ['name' => 'Speakers', 'type' => 'Physical Product', 'brands' => 'JBL, Pioneer'],
            ['name' => 'Tweeters', 'type' => 'Physical Product', 'brands' => 'JBL'],
            ['name' => 'Subwoofer', 'type' => 'Physical Product', 'brands' => 'JBL, Pioneer'],
            ['name' => 'Amplifier', 'type' => 'Physical Product', 'brands' => 'Pioneer'],
            ['name' => 'Reverse Camera', 'type' => 'Physical Product', 'brands' => 'Blaupunkt, Sony'],
            ['name' => '360° Camera System', 'type' => 'Physical Product', 'brands' => 'Blaupunkt'],
            ['name' => 'Dash Camera', 'type' => 'Physical Product', 'brands' => '70mai, DDPAI'],
            ['name' => 'Parking Sensors', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'GPS Tracker', 'type' => 'Physical Product', 'brands' => 'Ajjas, Onelap'],
            ['name' => 'TPMS', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'LED Headlights', 'type' => 'Physical Product', 'brands' => 'Philips, Osram'],
            ['name' => 'Fog Lights', 'type' => 'Physical Product', 'brands' => 'Hella'],
            ['name' => 'DRL Lights', 'type' => 'Physical Product', 'brands' => 'Philips'],
            ['name' => 'Interior LED Lights', 'type' => 'Physical Product', 'brands' => 'Philips'],
            ['name' => 'Ambient Lighting Kit', 'type' => 'Physical Product', 'brands' => 'Philips'],
            ['name' => 'Car Vacuum Cleaner', 'type' => 'Physical Product', 'brands' => 'Black+Decker'],
            ['name' => 'Car Cleaning Kit', 'type' => 'Physical Product', 'brands' => '3M, Wavex'],
            ['name' => 'Microfiber Cloth', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Glass Cleaner', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Dashboard Polish', 'type' => 'Physical Product', 'brands' => 'Formula 1'],
            ['name' => 'Car Shampoo', 'type' => 'Physical Product', 'brands' => '3M, Wavex'],
            ['name' => 'Car Wax', 'type' => 'Physical Product', 'brands' => 'Meguiar\'s'],
            ['name' => 'Ceramic Coating Kit', 'type' => 'Physical Product', 'brands' => 'Turtle Wax'],
            ['name' => 'Pressure Washer', 'type' => 'Physical Product', 'brands' => 'Kärcher'],
            ['name' => 'Jump Starter', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Tyre Inflator', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Emergency Tool Kit', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'First Aid Kit', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Fire Extinguisher', 'type' => 'Physical Product', 'brands' => 'Ceasefire'],
            ['name' => 'Tow Rope', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Roof Carrier', 'type' => 'Physical Product', 'brands' => 'Thule'],
            ['name' => 'Roof Box', 'type' => 'Physical Product', 'brands' => 'Thule'],
            ['name' => 'Bicycle Carrier', 'type' => 'Physical Product', 'brands' => 'Thule'],
            ['name' => 'Car Refrigerator', 'type' => 'Physical Product', 'brands' => 'WAECO, Dometic'],
            ['name' => 'Travel Accessories Kit', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Car Accessories Combo', 'type' => 'Physical Product', 'brands' => '3M, Autofurnish'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'Battery Store',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Car Battery', 'type' => 'Physical Product', 'brands' => 'Exide, Amaron, SF Sonic'],
            ['name' => 'SUV Battery', 'type' => 'Physical Product', 'brands' => 'Exide, Amaron'],
            ['name' => 'Truck Battery', 'type' => 'Physical Product', 'brands' => 'Exide, Amaron'],
            ['name' => 'Bus Battery', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Tractor Battery', 'type' => 'Physical Product', 'brands' => 'Exide, Amaron'],
            ['name' => 'Commercial Vehicle Battery', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Motorcycle Battery', 'type' => 'Physical Product', 'brands' => 'Exide, Amaron'],
            ['name' => 'Scooter Battery', 'type' => 'Physical Product', 'brands' => 'Exide, Amaron'],
            ['name' => 'Electric Scooter Battery', 'type' => 'Physical Product', 'brands' => 'Ola Electric, Ather'],
            ['name' => 'Electric Bike Battery', 'type' => 'Physical Product', 'brands' => 'Revolt'],
            ['name' => 'Inverter Battery', 'type' => 'Physical Product', 'brands' => 'Exide, Luminous, Amaron'],
            ['name' => 'Tubular Battery', 'type' => 'Physical Product', 'brands' => 'Luminous, Exide'],
            ['name' => 'Flat Plate Battery', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'UPS Battery', 'type' => 'Physical Product', 'brands' => 'APC, Exide'],
            ['name' => 'Solar Battery', 'type' => 'Physical Product', 'brands' => 'Luminous, Exide'],
            ['name' => 'SMF Battery', 'type' => 'Physical Product', 'brands' => 'Amaron, Exide'],
            ['name' => 'Lead Acid Battery', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'AGM Battery', 'type' => 'Physical Product', 'brands' => 'Bosch, Exide'],
            ['name' => 'Lithium-Ion Battery', 'type' => 'Physical Product', 'brands' => 'Exide, Livguard'],
            ['name' => 'Battery Charger', 'type' => 'Physical Product', 'brands' => 'Bosch, CTEK'],
            ['name' => 'Smart Battery Charger', 'type' => 'Physical Product', 'brands' => 'CTEK'],
            ['name' => 'Portable Battery Charger', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Jump Starter', 'type' => 'Physical Product', 'brands' => 'Michelin, NOCO'],
            ['name' => 'Battery Booster Pack', 'type' => 'Physical Product', 'brands' => 'NOCO'],
            ['name' => 'Battery Tester', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Digital Battery Analyzer', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Battery Terminal', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Battery Clamp', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Battery Cable', 'type' => 'Physical Product', 'brands' => 'Finolex'],
            ['name' => 'Battery Connector', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Battery Box', 'type' => 'Physical Product', 'brands' => 'Luminous'],
            ['name' => 'Battery Water', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Distilled Water', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Battery Hydrometer', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Battery Terminal Cleaner', 'type' => 'Physical Product', 'brands' => 'Wurth'],
            ['name' => 'Battery Grease', 'type' => 'Physical Product', 'brands' => 'Wurth'],
            ['name' => 'Terminal Protector Spray', 'type' => 'Physical Product', 'brands' => 'Wurth'],
            ['name' => 'Battery Hold Down Kit', 'type' => 'Physical Product', 'brands' => 'Local Brands'],
            ['name' => 'Battery Tray', 'type' => 'Physical Product', 'brands' => 'Local Brands'],
            ['name' => 'Fuse Holder', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Battery Isolator Switch', 'type' => 'Physical Product', 'brands' => 'Blue Sea Systems'],
            ['name' => 'Battery Monitor', 'type' => 'Physical Product', 'brands' => 'Victron Energy'],
            ['name' => 'Battery Management System (BMS)', 'type' => 'Physical Product', 'brands' => 'Daly, Victron Energy'],
            ['name' => 'Power Bank', 'type' => 'Physical Product', 'brands' => 'Ambrane, Mi'],
            ['name' => 'Emergency Power Pack', 'type' => 'Physical Product', 'brands' => 'NOCO'],
            ['name' => 'Solar Charge Controller', 'type' => 'Physical Product', 'brands' => 'Luminous'],
            ['name' => 'DC Converter', 'type' => 'Physical Product', 'brands' => 'Victron Energy'],
            ['name' => 'Battery Rack', 'type' => 'Physical Product', 'brands' => 'Local Brands'],
            ['name' => 'Battery Carry Handle', 'type' => 'Physical Product', 'brands' => 'Local Brands'],
            ['name' => 'Battery Installation Kit', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Battery Maintenance Kit', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Battery Recycling Bin', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Battery Safety Gloves', 'type' => 'Physical Product', 'brands' => 'Honeywell'],
            ['name' => 'Battery Safety Goggles', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Industrial Battery', 'type' => 'Physical Product', 'brands' => 'Exide Industrial'],
            ['name' => 'Forklift Battery', 'type' => 'Physical Product', 'brands' => 'Exide Industrial'],
            ['name' => 'Golf Cart Battery', 'type' => 'Physical Product', 'brands' => 'Trojan'],
            ['name' => 'Marine Battery', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Deep Cycle Battery', 'type' => 'Physical Product', 'brands' => 'Trojan'],
            ['name' => 'RV Battery', 'type' => 'Physical Product', 'brands' => 'Exide'],
            ['name' => 'Battery Care Combo', 'type' => 'Physical Product', 'brands' => 'Exide, Bosch'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Bicycle Store, Auto Parts Store, Tyre Shop, Car Accessories Store, and Battery Store.\n";
