<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Events & Entertainment',
        'sub_category' => 'Fireworks & Special Effects Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Wedding Fireworks Show', 'type' => 'Service', 'brands' => 'Standard Fireworks'],
            ['name' => 'Musical Fireworks Display', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Synchronized Fireworks', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Cold Pyro Effects', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'Indoor Cold Fireworks', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'Spark Fountain Effects', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'CO₂ Jet Effects', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'Confetti Blast', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'Streamer Cannon', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'Smoke Effects', 'type' => 'Service', 'brands' => 'Chauvet DJ'],
            ['name' => 'Low Fog Effect', 'type' => 'Service', 'brands' => 'Antari'],
            ['name' => 'Haze Machine', 'type' => 'Service', 'brands' => 'Antari'],
            ['name' => 'Bubble Machine', 'type' => 'Service', 'brands' => 'Chauvet DJ'],
            ['name' => 'Snow Machine', 'type' => 'Service', 'brands' => 'Chauvet DJ'],
            ['name' => 'Flame Machine', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'Laser Show', 'type' => 'Service', 'brands' => 'Laserworld'],
            ['name' => 'Pixel LED Effects', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Intelligent Lighting Effects', 'type' => 'Service', 'brands' => 'Chauvet Professional'],
            ['name' => 'Stage Special Effects', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Concert Pyrotechnics', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Corporate Event Effects', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Product Launch Effects', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Grand Entry Effects', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Bride & Groom Entry Effects', 'type' => 'Service', 'brands' => 'Wedding FX'],
            ['name' => 'Birthday Special Effects', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Festival Fireworks', 'type' => 'Service', 'brands' => 'Standard Fireworks'],
            ['name' => 'New Year Fireworks', 'type' => 'Service', 'brands' => 'Standard Fireworks'],
            ['name' => 'Sports Event Effects', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Safety Inspection', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Fire Safety Compliance', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Licensed Pyrotechnician', 'type' => 'Service', 'brands' => 'Certified Operator'],
            ['name' => 'Event Risk Assessment', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Setup & Dismantling', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Remote Firing System', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Customized FX Package', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Venue Inspection', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Technical Rehearsal', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Event Coordination', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'Event FX Company'],
            ['name' => '24×7 Technical Support', 'type' => 'Service', 'brands' => 'Event FX Company'],
        ]
    ],
    [
        'category' => 'Events & Entertainment',
        'sub_category' => 'Event Ticketing Platform',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Online Ticket Booking', 'type' => 'Software', 'brands' => 'BookMyShow'],
            ['name' => 'Event Ticket Sales', 'type' => 'Software', 'brands' => 'District by Zomato'],
            ['name' => 'Concert Ticket Booking', 'type' => 'Service', 'brands' => 'BookMyShow'],
            ['name' => 'Movie Ticket Booking', 'type' => 'Service', 'brands' => 'BookMyShow'],
            ['name' => 'Sports Event Ticketing', 'type' => 'Service', 'brands' => 'BookMyShow'],
            ['name' => 'Theatre Show Ticketing', 'type' => 'Service', 'brands' => 'BookMyShow'],
            ['name' => 'Stand-up Comedy Ticketing', 'type' => 'Service', 'brands' => 'BookMyShow'],
            ['name' => 'Festival Ticket Booking', 'type' => 'Service', 'brands' => 'BookMyShow'],
            ['name' => 'Exhibition Ticket Booking', 'type' => 'Service', 'brands' => 'BookMyShow'],
            ['name' => 'Conference Registration', 'type' => 'Service', 'brands' => 'Eventbrite'],
            ['name' => 'Workshop Registration', 'type' => 'Service', 'brands' => 'Eventbrite'],
            ['name' => 'Webinar Registration', 'type' => 'Service', 'brands' => 'Eventbrite'],
            ['name' => 'QR Code Ticket', 'type' => 'Software', 'brands' => 'Eventbrite'],
            ['name' => 'E-Ticket Generation', 'type' => 'Software', 'brands' => 'BookMyShow'],
            ['name' => 'Digital Entry Pass', 'type' => 'Software', 'brands' => 'Ticketing Platform'],
            ['name' => 'Seat Selection', 'type' => 'Software', 'brands' => 'BookMyShow'],
            ['name' => 'Reserved Seating', 'type' => 'Software', 'brands' => 'Ticketing Platform'],
            ['name' => 'VIP Pass Management', 'type' => 'Software', 'brands' => 'Ticketing Platform'],
            ['name' => 'Early Bird Tickets', 'type' => 'Service', 'brands' => 'Ticketing Platform'],
            ['name' => 'Group Booking', 'type' => 'Service', 'brands' => 'Ticketing Platform'],
            ['name' => 'Membership Pass', 'type' => 'Service', 'brands' => 'Ticketing Platform'],
            ['name' => 'Season Pass', 'type' => 'Service', 'brands' => 'Ticketing Platform'],
            ['name' => 'Promo Code Management', 'type' => 'Software', 'brands' => 'Ticketing Platform'],
            ['name' => 'Discount Coupon', 'type' => 'Service', 'brands' => 'Ticketing Platform'],
            ['name' => 'Payment Gateway Integration', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'UPI Payment', 'type' => 'Service', 'brands' => 'PhonePe'],
            ['name' => 'Refund Management', 'type' => 'Service', 'brands' => 'Ticketing Platform'],
            ['name' => 'Ticket Cancellation', 'type' => 'Service', 'brands' => 'Ticketing Platform'],
            ['name' => 'Attendee Check-In', 'type' => 'Software', 'brands' => 'Eventbrite'],
            ['name' => 'QR Scanner App', 'type' => 'Software', 'brands' => 'Ticketing Platform'],
            ['name' => 'Live Attendance Dashboard', 'type' => 'Software', 'brands' => 'Ticketing Platform'],
            ['name' => 'Event Analytics', 'type' => 'Software', 'brands' => 'Eventbrite'],
            ['name' => 'Organizer Dashboard', 'type' => 'Software', 'brands' => 'Ticketing Platform'],
            ['name' => 'Customer Notifications', 'type' => 'Software', 'brands' => 'MSG91'],
            ['name' => 'Email Ticket Delivery', 'type' => 'Service', 'brands' => 'Ticketing Platform'],
            ['name' => 'SMS Ticket Confirmation', 'type' => 'Service', 'brands' => 'MSG91'],
            ['name' => 'Mobile App Ticketing', 'type' => 'Software', 'brands' => 'BookMyShow'],
            ['name' => 'API Integration', 'type' => 'Software', 'brands' => 'Ticketing Platform'],
            ['name' => 'White Label Ticketing Solution', 'type' => 'Software', 'brands' => 'Ticketing Platform'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Ticketing Platform'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Bank',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Savings Account', 'type' => 'Service', 'brands' => 'SBI, HDFC Bank, ICICI Bank'],
            ['name' => 'Current Account', 'type' => 'Service', 'brands' => 'HDFC Bank, Axis Bank'],
            ['name' => 'Salary Account', 'type' => 'Service', 'brands' => 'ICICI Bank'],
            ['name' => 'Zero Balance Account', 'type' => 'Service', 'brands' => 'SBI, Kotak Mahindra Bank'],
            ['name' => 'Fixed Deposit (FD)', 'type' => 'Service', 'brands' => 'SBI, HDFC Bank'],
            ['name' => 'Recurring Deposit (RD)', 'type' => 'Service', 'brands' => 'SBI, ICICI Bank'],
            ['name' => 'Personal Loan', 'type' => 'Service', 'brands' => 'HDFC Bank, Axis Bank'],
            ['name' => 'Home Loan', 'type' => 'Service', 'brands' => 'SBI Home Loans'],
            ['name' => 'Car Loan', 'type' => 'Service', 'brands' => 'HDFC Bank'],
            ['name' => 'Two Wheeler Loan', 'type' => 'Service', 'brands' => 'Bajaj Finance'],
            ['name' => 'Education Loan', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Gold Loan', 'type' => 'Service', 'brands' => 'Muthoot Finance'],
            ['name' => 'Business Loan', 'type' => 'Service', 'brands' => 'ICICI Bank'],
            ['name' => 'MSME Loan', 'type' => 'Service', 'brands' => 'SIDBI'],
            ['name' => 'Working Capital Loan', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Credit Card', 'type' => 'Service', 'brands' => 'HDFC Bank'],
            ['name' => 'Debit Card', 'type' => 'Service', 'brands' => 'Visa, Mastercard, RuPay'],
            ['name' => 'Prepaid Card', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Internet Banking', 'type' => 'Software', 'brands' => 'SBI YONO'],
            ['name' => 'Mobile Banking', 'type' => 'Software', 'brands' => 'HDFC Bank App'],
            ['name' => 'UPI Services', 'type' => 'Service', 'brands' => 'BHIM'],
            ['name' => 'IMPS Transfer', 'type' => 'Service', 'brands' => 'NPCI'],
            ['name' => 'NEFT Transfer', 'type' => 'Service', 'brands' => 'RBI'],
            ['name' => 'RTGS Transfer', 'type' => 'Service', 'brands' => 'RBI'],
            ['name' => 'Demand Draft', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Cheque Book', 'type' => 'Physical Product', 'brands' => 'Bank'],
            ['name' => 'Locker Facility', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Forex Services', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'NRI Banking', 'type' => 'Service', 'brands' => 'ICICI Bank'],
            ['name' => 'Mutual Fund Investment', 'type' => 'Service', 'brands' => 'SBI Mutual Fund'],
            ['name' => 'Demat Account', 'type' => 'Service', 'brands' => 'HDFC Sky'],
            ['name' => 'Insurance Services', 'type' => 'Service', 'brands' => 'SBI Life'],
            ['name' => 'Pension Services', 'type' => 'Service', 'brands' => 'NPS'],
            ['name' => 'ATM Services', 'type' => 'Service', 'brands' => 'Bank ATM'],
            ['name' => 'Cash Deposit Machine', 'type' => 'Service', 'brands' => 'Bank'],
            ['name' => 'Passbook Printing', 'type' => 'Service', 'brands' => 'Bank'],
            ['name' => 'SMS Alerts', 'type' => 'Service', 'brands' => 'Bank'],
            ['name' => 'Relationship Manager', 'type' => 'Service', 'brands' => 'Bank'],
            ['name' => 'Corporate Banking', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Wealth Management', 'type' => 'Service', 'brands' => 'ICICI Bank'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Insurance Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Life Insurance', 'type' => 'Service', 'brands' => 'LIC, HDFC Life'],
            ['name' => 'Term Insurance', 'type' => 'Service', 'brands' => 'Max Life'],
            ['name' => 'Health Insurance', 'type' => 'Service', 'brands' => 'Star Health'],
            ['name' => 'Family Floater Insurance', 'type' => 'Service', 'brands' => 'Care Health'],
            ['name' => 'Senior Citizen Insurance', 'type' => 'Service', 'brands' => 'Niva Bupa'],
            ['name' => 'Critical Illness Insurance', 'type' => 'Service', 'brands' => 'HDFC ERGO'],
            ['name' => 'Personal Accident Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Motor Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Car Insurance', 'type' => 'Service', 'brands' => 'ACKO'],
            ['name' => 'Bike Insurance', 'type' => 'Service', 'brands' => 'Digit Insurance'],
            ['name' => 'Commercial Vehicle Insurance', 'type' => 'Service', 'brands' => 'New India Assurance'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Home Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Property Insurance', 'type' => 'Service', 'brands' => 'Bajaj Allianz'],
            ['name' => 'Fire Insurance', 'type' => 'Service', 'brands' => 'Oriental Insurance'],
            ['name' => 'Marine Insurance', 'type' => 'Service', 'brands' => 'New India Assurance'],
            ['name' => 'Shop Insurance', 'type' => 'Service', 'brands' => 'SBI General'],
            ['name' => 'Business Insurance', 'type' => 'Service', 'brands' => 'HDFC ERGO'],
            ['name' => 'Cyber Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Professional Indemnity Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Crop Insurance', 'type' => 'Service', 'brands' => 'Agriculture Insurance Company'],
            ['name' => 'Livestock Insurance', 'type' => 'Service', 'brands' => 'United India Insurance'],
            ['name' => 'Group Insurance', 'type' => 'Service', 'brands' => 'LIC'],
            ['name' => 'Employee Insurance', 'type' => 'Service', 'brands' => 'HDFC Life'],
            ['name' => 'Child Insurance Plan', 'type' => 'Service', 'brands' => 'LIC'],
            ['name' => 'ULIP Plan', 'type' => 'Service', 'brands' => 'SBI Life'],
            ['name' => 'Retirement Plan', 'type' => 'Service', 'brands' => 'LIC'],
            ['name' => 'Pension Plan', 'type' => 'Service', 'brands' => 'HDFC Life'],
            ['name' => 'Claim Assistance', 'type' => 'Service', 'brands' => 'Insurance Company'],
            ['name' => 'Cashless Claim', 'type' => 'Service', 'brands' => 'Star Health'],
            ['name' => 'Policy Renewal', 'type' => 'Service', 'brands' => 'Insurance Company'],
            ['name' => 'Premium Payment', 'type' => 'Service', 'brands' => 'Insurance Company'],
            ['name' => 'Policy Portability', 'type' => 'Service', 'brands' => 'IRDAI'],
            ['name' => 'Insurance Consultation', 'type' => 'Service', 'brands' => 'Policybazaar'],
            ['name' => 'Risk Assessment', 'type' => 'Service', 'brands' => 'Insurance Company'],
            ['name' => 'Online Policy Purchase', 'type' => 'Service', 'brands' => 'Policybazaar'],
            ['name' => 'Digital Policy Download', 'type' => 'Service', 'brands' => 'Insurance Company'],
            ['name' => 'Customer Support', 'type' => 'Service', 'brands' => 'Insurance Company'],
            ['name' => 'Corporate Insurance Solutions', 'type' => 'Service', 'brands' => 'Marsh India'],
            ['name' => 'Wealth Protection Planning', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Insurance Agent / Advisor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Life Insurance Consultation', 'type' => 'Service', 'brands' => 'LIC'],
            ['name' => 'Health Insurance Consultation', 'type' => 'Service', 'brands' => 'Star Health'],
            ['name' => 'Term Insurance Planning', 'type' => 'Service', 'brands' => 'Max Life'],
            ['name' => 'Family Insurance Planning', 'type' => 'Service', 'brands' => 'Care Health'],
            ['name' => 'Child Education Plan', 'type' => 'Service', 'brands' => 'LIC'],
            ['name' => 'Retirement Planning', 'type' => 'Service', 'brands' => 'HDFC Life'],
            ['name' => 'Pension Plan Advisory', 'type' => 'Service', 'brands' => 'SBI Life'],
            ['name' => 'ULIP Consultation', 'type' => 'Service', 'brands' => 'ICICI Prudential Life'],
            ['name' => 'Investment-Linked Insurance', 'type' => 'Service', 'brands' => 'Bajaj Allianz Life'],
            ['name' => 'Motor Insurance', 'type' => 'Service', 'brands' => 'ACKO'],
            ['name' => 'Car Insurance Renewal', 'type' => 'Service', 'brands' => 'Digit Insurance'],
            ['name' => 'Bike Insurance Renewal', 'type' => 'Service', 'brands' => 'Digit Insurance'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Home Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Shop Insurance', 'type' => 'Service', 'brands' => 'SBI General'],
            ['name' => 'Fire Insurance', 'type' => 'Service', 'brands' => 'Oriental Insurance'],
            ['name' => 'Marine Insurance', 'type' => 'Service', 'brands' => 'New India Assurance'],
            ['name' => 'Business Insurance', 'type' => 'Service', 'brands' => 'HDFC ERGO'],
            ['name' => 'Professional Indemnity Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Cyber Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Claim Assistance', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Cashless Claim Support', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Policy Comparison', 'type' => 'Service', 'brands' => 'Policybazaar'],
            ['name' => 'Premium Calculation', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Policy Renewal', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'New Policy Registration', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Nominee Update', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Policy Transfer', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Risk Assessment', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Financial Protection Planning', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Wealth Protection Planning', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Tax Saving Insurance', 'type' => 'Service', 'brands' => 'LIC'],
            ['name' => 'Group Insurance', 'type' => 'Service', 'brands' => 'HDFC Life'],
            ['name' => 'Employee Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Corporate Insurance Advisory', 'type' => 'Service', 'brands' => 'Marsh India'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Doorstep Service', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Annual Policy Review', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => 'Family Financial Planning', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Insurance Advisor'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Loan Consultant',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Personal Loan Assistance', 'type' => 'Service', 'brands' => 'HDFC Bank'],
            ['name' => 'Home Loan Assistance', 'type' => 'Service', 'brands' => 'SBI Home Loans'],
            ['name' => 'Balance Transfer', 'type' => 'Service', 'brands' => 'ICICI Bank'],
            ['name' => 'Home Loan Top-Up', 'type' => 'Service', 'brands' => 'Axis Bank'],
            ['name' => 'Loan Against Property', 'type' => 'Service', 'brands' => 'LIC Housing Finance'],
            ['name' => 'Business Loan', 'type' => 'Service', 'brands' => 'Bajaj Finserv'],
            ['name' => 'MSME Loan', 'type' => 'Service', 'brands' => 'SIDBI'],
            ['name' => 'Startup Loan', 'type' => 'Service', 'brands' => 'Mudra Yojana'],
            ['name' => 'Mudra Loan Assistance', 'type' => 'Service', 'brands' => 'PMMY'],
            ['name' => 'Working Capital Loan', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Machinery Loan', 'type' => 'Service', 'brands' => 'Bank of Baroda'],
            ['name' => 'Equipment Finance', 'type' => 'Service', 'brands' => 'Tata Capital'],
            ['name' => 'Gold Loan', 'type' => 'Service', 'brands' => 'Muthoot Finance'],
            ['name' => 'Vehicle Loan', 'type' => 'Service', 'brands' => 'HDFC Bank'],
            ['name' => 'Car Loan', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Two Wheeler Loan', 'type' => 'Service', 'brands' => 'Bajaj Finance'],
            ['name' => 'Education Loan', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Agriculture Loan', 'type' => 'Service', 'brands' => 'NABARD'],
            ['name' => 'Mortgage Loan', 'type' => 'Service', 'brands' => 'ICICI Bank'],
            ['name' => 'Construction Loan', 'type' => 'Service', 'brands' => 'LIC Housing Finance'],
            ['name' => 'Loan Eligibility Check', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => 'Credit Score Analysis', 'type' => 'Service', 'brands' => 'CIBIL'],
            ['name' => 'Loan Comparison', 'type' => 'Service', 'brands' => 'BankBazaar'],
            ['name' => 'EMI Calculation', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => 'Documentation Assistance', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => 'Loan Application Filing', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => 'Bank Coordination', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => 'NBFC Loan Assistance', 'type' => 'Service', 'brands' => 'Tata Capital'],
            ['name' => 'Loan Refinancing', 'type' => 'Service', 'brands' => 'Bajaj Finserv'],
            ['name' => 'Debt Consolidation', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => 'Overdraft Facility', 'type' => 'Service', 'brands' => 'SBI'],
            ['name' => 'Cash Credit Assistance', 'type' => 'Service', 'brands' => 'Bank of Baroda'],
            ['name' => 'Loan Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Online Loan Consultation', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => 'Doorstep Documentation', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => 'Corporate Loan Advisory', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => 'Project Finance', 'type' => 'Service', 'brands' => 'SIDBI'],
            ['name' => 'Financial Planning', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => 'End-to-End Loan Processing', 'type' => 'Service', 'brands' => 'Loan Consultant'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Loan Consultant'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Mutual Fund Distributor',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Equity Mutual Funds', 'type' => 'Service', 'brands' => 'SBI Mutual Fund'],
            ['name' => 'Debt Mutual Funds', 'type' => 'Service', 'brands' => 'HDFC Mutual Fund'],
            ['name' => 'Hybrid Mutual Funds', 'type' => 'Service', 'brands' => 'ICICI Prudential Mutual Fund'],
            ['name' => 'Index Funds', 'type' => 'Service', 'brands' => 'UTI Mutual Fund'],
            ['name' => 'ELSS Tax Saving Funds', 'type' => 'Service', 'brands' => 'Axis Mutual Fund'],
            ['name' => 'Large Cap Funds', 'type' => 'Service', 'brands' => 'Nippon India Mutual Fund'],
            ['name' => 'Mid Cap Funds', 'type' => 'Service', 'brands' => 'Kotak Mutual Fund'],
            ['name' => 'Small Cap Funds', 'type' => 'Service', 'brands' => 'Quant Mutual Fund'],
            ['name' => 'Flexi Cap Funds', 'type' => 'Service', 'brands' => 'Parag Parikh Mutual Fund'],
            ['name' => 'Multi Cap Funds', 'type' => 'Service', 'brands' => 'Tata Mutual Fund'],
            ['name' => 'International Funds', 'type' => 'Service', 'brands' => 'Motilal Oswal Mutual Fund'],
            ['name' => 'SIP Investment', 'type' => 'Service', 'brands' => 'Groww'],
            ['name' => 'Lumpsum Investment', 'type' => 'Service', 'brands' => 'Groww'],
            ['name' => 'STP (Systematic Transfer Plan)', 'type' => 'Service', 'brands' => 'AMC'],
            ['name' => 'SWP (Systematic Withdrawal Plan)', 'type' => 'Service', 'brands' => 'AMC'],
            ['name' => 'Goal-Based Investment Planning', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Retirement Planning', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Child Education Planning', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Wealth Creation Planning', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Portfolio Review', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Portfolio Rebalancing', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Risk Profiling', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Fund Comparison', 'type' => 'Service', 'brands' => 'Value Research'],
            ['name' => 'NAV Tracking', 'type' => 'Software', 'brands' => 'Groww'],
            ['name' => 'Online Investment', 'type' => 'Software', 'brands' => 'Groww'],
            ['name' => 'KYC Registration', 'type' => 'Service', 'brands' => 'CAMS'],
            ['name' => 'eKYC Verification', 'type' => 'Service', 'brands' => 'KFintech'],
            ['name' => 'Nomination Update', 'type' => 'Service', 'brands' => 'CAMS'],
            ['name' => 'SIP Registration', 'type' => 'Service', 'brands' => 'Groww'],
            ['name' => 'SIP Modification', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'SIP Cancellation', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Capital Gain Report', 'type' => 'Service', 'brands' => 'CAMS'],
            ['name' => 'Tax Saving Consultation', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Family Portfolio Management', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Corporate Investment Advisory', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'NRI Investment Assistance', 'type' => 'Service', 'brands' => 'AMC'],
            ['name' => 'Mobile App Support', 'type' => 'Software', 'brands' => 'Groww'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => 'Annual Portfolio Review', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Mutual Fund Advisor'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Stock Broker',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Demat Account Opening', 'type' => 'Service', 'brands' => 'Zerodha'],
            ['name' => 'Trading Account Opening', 'type' => 'Service', 'brands' => 'Angel One'],
            ['name' => 'Equity Trading', 'type' => 'Service', 'brands' => 'Upstox'],
            ['name' => 'Intraday Trading', 'type' => 'Service', 'brands' => 'Groww'],
            ['name' => 'Delivery Trading', 'type' => 'Service', 'brands' => 'Zerodha'],
            ['name' => 'Futures Trading', 'type' => 'Service', 'brands' => 'Zerodha'],
            ['name' => 'Options Trading', 'type' => 'Service', 'brands' => 'Angel One'],
            ['name' => 'Commodity Trading', 'type' => 'Service', 'brands' => 'Motilal Oswal'],
            ['name' => 'Currency Trading', 'type' => 'Service', 'brands' => 'ICICI Direct'],
            ['name' => 'IPO Investment', 'type' => 'Service', 'brands' => 'Groww'],
            ['name' => 'Mutual Fund Investment', 'type' => 'Service', 'brands' => 'Zerodha Coin'],
            ['name' => 'Bonds Investment', 'type' => 'Service', 'brands' => 'Wint Wealth'],
            ['name' => 'Government Securities', 'type' => 'Service', 'brands' => 'RBI Retail Direct'],
            ['name' => 'Sovereign Gold Bonds', 'type' => 'Service', 'brands' => 'RBI'],
            ['name' => 'ETF Investment', 'type' => 'Service', 'brands' => 'Zerodha'],
            ['name' => 'Portfolio Management', 'type' => 'Service', 'brands' => 'Motilal Oswal'],
            ['name' => 'Stock Advisory', 'type' => 'Service', 'brands' => 'Broker'],
            ['name' => 'Research Reports', 'type' => 'Service', 'brands' => 'ICICI Direct'],
            ['name' => 'Technical Analysis', 'type' => 'Service', 'brands' => 'TradingView'],
            ['name' => 'Fundamental Analysis', 'type' => 'Service', 'brands' => 'Broker'],
            ['name' => 'Margin Trading Facility', 'type' => 'Service', 'brands' => 'Zerodha'],
            ['name' => 'Algo Trading', 'type' => 'Service', 'brands' => 'Quantiply'],
            ['name' => 'API Trading', 'type' => 'Software', 'brands' => 'Zerodha Kite Connect'],
            ['name' => 'Mobile Trading App', 'type' => 'Software', 'brands' => 'Angel One'],
            ['name' => 'Web Trading Platform', 'type' => 'Software', 'brands' => 'Zerodha Kite'],
            ['name' => 'Live Market Data', 'type' => 'Software', 'brands' => 'NSE'],
            ['name' => 'Stock Screener', 'type' => 'Software', 'brands' => 'Screener.in'],
            ['name' => 'Watchlist Management', 'type' => 'Software', 'brands' => 'Broker'],
            ['name' => 'Price Alerts', 'type' => 'Software', 'brands' => 'Broker'],
            ['name' => 'SIP in Stocks', 'type' => 'Service', 'brands' => 'Smallcase'],
            ['name' => 'Smallcase Investment', 'type' => 'Service', 'brands' => 'Smallcase'],
            ['name' => 'NPS Investment', 'type' => 'Service', 'brands' => 'eNPS'],
            ['name' => 'Tax Report', 'type' => 'Service', 'brands' => 'Broker'],
            ['name' => 'Capital Gain Report', 'type' => 'Service', 'brands' => 'Broker'],
            ['name' => 'KYC Assistance', 'type' => 'Service', 'brands' => 'Broker'],
            ['name' => 'Nomination Update', 'type' => 'Service', 'brands' => 'Broker'],
            ['name' => 'Investor Education', 'type' => 'Service', 'brands' => 'NSE Academy'],
            ['name' => 'Online Support', 'type' => 'Service', 'brands' => 'Broker'],
            ['name' => 'Dedicated Relationship Manager', 'type' => 'Service', 'brands' => 'Broker'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Broker'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Events & Entertainment Sub Categories 31.25 to 31.26, and Finance & Insurance 32.1 to 32.6.\n";
