<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Health & Medical',
        'sub_category' => 'Dental Clinic',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Dental Consultation', 'type' => 'Service', 'brands' => 'Clove Dental, Sabka Dentist'],
            ['name' => 'Dental Checkup', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Digital Dental X-Ray', 'type' => 'Service', 'brands' => 'Carestream Dental'],
            ['name' => 'OPG Scan', 'type' => 'Service', 'brands' => 'Carestream Dental'],
            ['name' => 'Dental Cleaning (Scaling)', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Polishing', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Teeth Whitening', 'type' => 'Service', 'brands' => 'Philips Zoom, Clove Dental'],
            ['name' => 'Tooth Filling', 'type' => 'Service', 'brands' => '3M ESPE'],
            ['name' => 'Root Canal Treatment (RCT)', 'type' => 'Service', 'brands' => 'Dentsply Sirona'],
            ['name' => 'Tooth Extraction', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Wisdom Tooth Extraction', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Dental Crown', 'type' => 'Service', 'brands' => '3M ESPE'],
            ['name' => 'Zirconia Crown', 'type' => 'Service', 'brands' => 'Ivoclar'],
            ['name' => 'Metal Ceramic Crown', 'type' => 'Service', 'brands' => 'Ivoclar'],
            ['name' => 'Dental Bridge', 'type' => 'Service', 'brands' => 'Ivoclar'],
            ['name' => 'Dental Implant', 'type' => 'Service', 'brands' => 'Nobel Biocare, Straumann'],
            ['name' => 'Full Mouth Rehabilitation', 'type' => 'Service', 'brands' => 'Straumann'],
            ['name' => 'Dentures', 'type' => 'Service', 'brands' => 'Ivoclar'],
            ['name' => 'Partial Dentures', 'type' => 'Service', 'brands' => 'Ivoclar'],
            ['name' => 'Invisible Aligners', 'type' => 'Service', 'brands' => 'Invisalign, Illusion Aligners'],
            ['name' => 'Metal Braces', 'type' => 'Service', 'brands' => '3M Unitek'],
            ['name' => 'Ceramic Braces', 'type' => 'Service', 'brands' => '3M Unitek'],
            ['name' => 'Lingual Braces', 'type' => 'Service', 'brands' => 'Incognito'],
            ['name' => 'Retainers', 'type' => 'Service', 'brands' => 'Invisalign'],
            ['name' => 'Pediatric Dentistry', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Fluoride Treatment', 'type' => 'Service', 'brands' => 'GC'],
            ['name' => 'Pit & Fissure Sealants', 'type' => 'Service', 'brands' => '3M ESPE'],
            ['name' => 'Gum Treatment', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Laser Dentistry', 'type' => 'Service', 'brands' => 'Biolase'],
            ['name' => 'Oral Surgery', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'TMJ Treatment', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Smile Makeover', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Cosmetic Dentistry', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Veneers', 'type' => 'Service', 'brands' => 'Ivoclar'],
            ['name' => 'Dental Emergency', 'type' => 'Service', 'brands' => 'Clove Dental'],
            ['name' => 'Mouth Guard', 'type' => 'Physical Product', 'brands' => 'Oral-B'],
            ['name' => 'Night Guard', 'type' => 'Physical Product', 'brands' => 'Oral-B'],
            ['name' => 'Oral Hygiene Kit', 'type' => 'Physical Product', 'brands' => 'Oral-B, Colgate'],
            ['name' => 'Follow-up Consultation', 'type' => 'Service', 'brands' => 'Clove Dental'],
        ]
    ],
    [
        'category' => 'Health & Medical',
        'sub_category' => 'Diagnostic Center',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Complete Blood Count (CBC)', 'type' => 'Service', 'brands' => 'Dr. Lal PathLabs, SRL Diagnostics'],
            ['name' => 'Blood Sugar Test', 'type' => 'Service', 'brands' => 'Dr. Lal PathLabs'],
            ['name' => 'HbA1c Test', 'type' => 'Service', 'brands' => 'SRL Diagnostics'],
            ['name' => 'Lipid Profile', 'type' => 'Service', 'brands' => 'Thyrocare'],
            ['name' => 'Liver Function Test (LFT)', 'type' => 'Service', 'brands' => 'Thyrocare'],
            ['name' => 'Kidney Function Test (KFT)', 'type' => 'Service', 'brands' => 'SRL Diagnostics'],
            ['name' => 'Thyroid Profile', 'type' => 'Service', 'brands' => 'Thyrocare'],
            ['name' => 'Vitamin D Test', 'type' => 'Service', 'brands' => 'Dr. Lal PathLabs'],
            ['name' => 'Vitamin B12 Test', 'type' => 'Service', 'brands' => 'Dr. Lal PathLabs'],
            ['name' => 'Urine Routine Test', 'type' => 'Service', 'brands' => 'SRL Diagnostics'],
            ['name' => 'Stool Test', 'type' => 'Service', 'brands' => 'SRL Diagnostics'],
            ['name' => 'Pregnancy Test', 'type' => 'Service', 'brands' => 'Dr. Lal PathLabs'],
            ['name' => 'Allergy Test', 'type' => 'Service', 'brands' => 'SRL Diagnostics'],
            ['name' => 'COVID-19 Test', 'type' => 'Service', 'brands' => 'Metropolis Healthcare'],
            ['name' => 'Dengue Test', 'type' => 'Service', 'brands' => 'Metropolis Healthcare'],
            ['name' => 'Malaria Test', 'type' => 'Service', 'brands' => 'Thyrocare'],
            ['name' => 'ECG', 'type' => 'Service', 'brands' => 'BPL Medical'],
            ['name' => '2D Echo', 'type' => 'Service', 'brands' => 'Philips Healthcare'],
            ['name' => 'TMT Test', 'type' => 'Service', 'brands' => 'GE HealthCare'],
            ['name' => 'Holter Monitoring', 'type' => 'Service', 'brands' => 'Philips Healthcare'],
            ['name' => 'X-Ray', 'type' => 'Service', 'brands' => 'Siemens Healthineers'],
            ['name' => 'Digital X-Ray', 'type' => 'Service', 'brands' => 'Siemens Healthineers'],
            ['name' => 'Ultrasound', 'type' => 'Service', 'brands' => 'GE HealthCare'],
            ['name' => 'Color Doppler', 'type' => 'Service', 'brands' => 'GE HealthCare'],
            ['name' => 'CT Scan', 'type' => 'Service', 'brands' => 'Siemens Healthineers'],
            ['name' => 'MRI Scan', 'type' => 'Service', 'brands' => 'Siemens Healthineers'],
            ['name' => 'Mammography', 'type' => 'Service', 'brands' => 'Hologic'],
            ['name' => 'Bone Density Test (DEXA)', 'type' => 'Service', 'brands' => 'Hologic'],
            ['name' => 'PET-CT Scan', 'type' => 'Service', 'brands' => 'Siemens Healthineers'],
            ['name' => 'PFT (Pulmonary Function Test)', 'type' => 'Service', 'brands' => 'Schiller'],
            ['name' => 'EEG', 'type' => 'Service', 'brands' => 'Nihon Kohden'],
            ['name' => 'EMG', 'type' => 'Service', 'brands' => 'Nihon Kohden'],
            ['name' => 'Home Sample Collection', 'type' => 'Service', 'brands' => 'Dr. Lal PathLabs'],
            ['name' => 'Corporate Health Checkup', 'type' => 'Service', 'brands' => 'Thyrocare'],
            ['name' => 'Full Body Checkup', 'type' => 'Service', 'brands' => 'Metropolis Healthcare'],
            ['name' => 'Preventive Health Package', 'type' => 'Service', 'brands' => 'Dr. Lal PathLabs'],
            ['name' => 'Senior Citizen Health Package', 'type' => 'Service', 'brands' => 'SRL Diagnostics'],
            ['name' => 'Women\'s Health Package', 'type' => 'Service', 'brands' => 'Thyrocare'],
            ['name' => 'Online Report Download', 'type' => 'Service', 'brands' => 'Dr. Lal PathLabs'],
            ['name' => 'Doctor Consultation Referral', 'type' => 'Service', 'brands' => 'SRL Diagnostics'],
        ]
    ],
    [
        'category' => 'Health & Medical',
        'sub_category' => 'Pharmacy / Medical Store',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Prescription Medicines', 'type' => 'Physical Product', 'brands' => 'Sun Pharma, Cipla, Dr. Reddy\'s'],
            ['name' => 'Generic Medicines', 'type' => 'Physical Product', 'brands' => 'Jan Aushadhi, Cipla'],
            ['name' => 'OTC Medicines', 'type' => 'Physical Product', 'brands' => 'Crocin, Disprin'],
            ['name' => 'Pain Relief Medicines', 'type' => 'Physical Product', 'brands' => 'Crocin, Combiflam'],
            ['name' => 'Cold & Cough Medicines', 'type' => 'Physical Product', 'brands' => 'Benadryl, Corex'],
            ['name' => 'Fever Medicines', 'type' => 'Physical Product', 'brands' => 'Crocin, Dolo 650'],
            ['name' => 'Antibiotics', 'type' => 'Physical Product', 'brands' => 'Cipla, Sun Pharma'],
            ['name' => 'Antacids', 'type' => 'Physical Product', 'brands' => 'Digene, Gelusil'],
            ['name' => 'Vitamins & Supplements', 'type' => 'Physical Product', 'brands' => 'Centrum, Supradyn'],
            ['name' => 'Protein Supplements', 'type' => 'Physical Product', 'brands' => 'Ensure, Protinex'],
            ['name' => 'Baby Care Products', 'type' => 'Physical Product', 'brands' => 'Johnson\'s Baby, Himalaya Baby'],
            ['name' => 'Baby Formula', 'type' => 'Physical Product', 'brands' => 'Nestlé NAN, Lactogen'],
            ['name' => 'Adult Diapers', 'type' => 'Physical Product', 'brands' => 'Friends, Dignity'],
            ['name' => 'Baby Diapers', 'type' => 'Physical Product', 'brands' => 'Pampers, Huggies'],
            ['name' => 'Sanitary Pads', 'type' => 'Physical Product', 'brands' => 'Whisper, Stayfree'],
            ['name' => 'Pregnancy Test Kit', 'type' => 'Physical Product', 'brands' => 'Prega News'],
            ['name' => 'Glucometer', 'type' => 'Physical Product', 'brands' => 'Accu-Chek, OneTouch'],
            ['name' => 'Glucometer Strips', 'type' => 'Physical Product', 'brands' => 'Accu-Chek'],
            ['name' => 'BP Monitor', 'type' => 'Physical Product', 'brands' => 'Omron'],
            ['name' => 'Thermometer', 'type' => 'Physical Product', 'brands' => 'Dr. Morepen, Omron'],
            ['name' => 'Pulse Oximeter', 'type' => 'Physical Product', 'brands' => 'Dr. Trust'],
            ['name' => 'Nebulizer', 'type' => 'Physical Product', 'brands' => 'Omron'],
            ['name' => 'Steam Vaporizer', 'type' => 'Physical Product', 'brands' => 'Dr. Trust'],
            ['name' => 'Face Mask', 'type' => 'Physical Product', 'brands' => 'Venus, 3M'],
            ['name' => 'Hand Sanitizer', 'type' => 'Physical Product', 'brands' => 'Dettol, Lifebuoy'],
            ['name' => 'First Aid Kit', 'type' => 'Physical Product', 'brands' => 'Dettol'],
            ['name' => 'Bandages', 'type' => 'Physical Product', 'brands' => 'Hansaplast'],
            ['name' => 'Cotton Roll', 'type' => 'Physical Product', 'brands' => 'Savlon'],
            ['name' => 'Surgical Gloves', 'type' => 'Physical Product', 'brands' => 'Romsons'],
            ['name' => 'Syringes', 'type' => 'Physical Product', 'brands' => 'Dispovan'],
            ['name' => 'Wheelchair', 'type' => 'Physical Product', 'brands' => 'Karma Healthcare'],
            ['name' => 'Walker', 'type' => 'Physical Product', 'brands' => 'Karma Healthcare'],
            ['name' => 'Crutches', 'type' => 'Physical Product', 'brands' => 'Karma Healthcare'],
            ['name' => 'Orthopedic Belt', 'type' => 'Physical Product', 'brands' => 'Tynor, Vissco'],
            ['name' => 'Knee Support', 'type' => 'Physical Product', 'brands' => 'Tynor'],
            ['name' => 'Cervical Collar', 'type' => 'Physical Product', 'brands' => 'Tynor'],
            ['name' => 'Medical Equipment Rental', 'type' => 'Service', 'brands' => 'Local Medical Stores'],
            ['name' => 'Home Medicine Delivery', 'type' => 'Service', 'brands' => 'Apollo Pharmacy, Tata 1mg'],
            ['name' => 'Online Medicine Order', 'type' => 'Service', 'brands' => 'Apollo Pharmacy, Tata 1mg'],
            ['name' => 'Health Consultation', 'type' => 'Service', 'brands' => 'Apollo 24/7'],
        ]
    ],
    [
        'category' => 'Health & Medical',
        'sub_category' => 'Eye Hospital / Eye Clinic',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Eye Consultation', 'type' => 'Service', 'brands' => 'Centre for Sight, Dr. Agarwal\'s Eye Hospital'],
            ['name' => 'Vision Test', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Computerized Eye Checkup', 'type' => 'Service', 'brands' => 'Titan Eye+'],
            ['name' => 'Refraction Test', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Retina Examination', 'type' => 'Service', 'brands' => 'Dr. Agarwal\'s Eye Hospital'],
            ['name' => 'Glaucoma Screening', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Cataract Surgery', 'type' => 'Service', 'brands' => 'Dr. Agarwal\'s Eye Hospital'],
            ['name' => 'LASIK Surgery', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Contoura Vision', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'SMILE Eye Surgery', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Cornea Treatment', 'type' => 'Service', 'brands' => 'Dr. Agarwal\'s'],
            ['name' => 'Retina Surgery', 'type' => 'Service', 'brands' => 'Dr. Agarwal\'s'],
            ['name' => 'Squint Treatment', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Pediatric Eye Care', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Dry Eye Treatment', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Diabetic Eye Checkup', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Contact Lens Fitting', 'type' => 'Service', 'brands' => 'Bausch + Lomb'],
            ['name' => 'Prescription Glasses', 'type' => 'Physical Product', 'brands' => 'Titan Eye+, Lenskart'],
            ['name' => 'Sunglasses', 'type' => 'Physical Product', 'brands' => 'Ray-Ban, Oakley'],
            ['name' => 'Contact Lenses', 'type' => 'Physical Product', 'brands' => 'Bausch + Lomb, Acuvue'],
            ['name' => 'Colored Contact Lenses', 'type' => 'Physical Product', 'brands' => 'FreshLook'],
            ['name' => 'Contact Lens Solution', 'type' => 'Physical Product', 'brands' => 'Bausch + Lomb'],
            ['name' => 'Eye Drops', 'type' => 'Physical Product', 'brands' => 'Refresh, Systane'],
            ['name' => 'Artificial Tears', 'type' => 'Physical Product', 'brands' => 'Refresh'],
            ['name' => 'Optical Coherence Tomography (OCT)', 'type' => 'Service', 'brands' => 'ZEISS'],
            ['name' => 'Fundus Photography', 'type' => 'Service', 'brands' => 'Topcon'],
            ['name' => 'Visual Field Test', 'type' => 'Service', 'brands' => 'Humphrey'],
            ['name' => 'Eye Pressure Test', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Low Vision Clinic', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Ocular Prosthesis', 'type' => 'Service', 'brands' => 'Local Eye Hospital'],
            ['name' => 'Eye Emergency Care', 'type' => 'Service', 'brands' => 'Dr. Agarwal\'s'],
            ['name' => 'Eye Surgery Consultation', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Follow-up Consultation', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Home Eye Care Consultation', 'type' => 'Service', 'brands' => 'Selected Hospitals'],
            ['name' => 'Tele Eye Consultation', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Spectacle Repair', 'type' => 'Service', 'brands' => 'Titan Eye+'],
            ['name' => 'Eye Health Package', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Senior Citizen Eye Checkup', 'type' => 'Service', 'brands' => 'Dr. Agarwal\'s'],
            ['name' => 'Children\'s Eye Checkup', 'type' => 'Service', 'brands' => 'Centre for Sight'],
            ['name' => 'Annual Eye Examination', 'type' => 'Service', 'brands' => 'Titan Eye+'],
        ]
    ],
    [
        'category' => 'Health & Medical',
        'sub_category' => 'Physiotherapy Center',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Physiotherapy Consultation', 'type' => 'Service', 'brands' => 'Physiocare, Portea'],
            ['name' => 'Orthopedic Physiotherapy', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Sports Physiotherapy', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Neurological Physiotherapy', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Pediatric Physiotherapy', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Geriatric Physiotherapy', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Women\'s Health Physiotherapy', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Post-Surgery Rehabilitation', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Post-Fracture Rehabilitation', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Stroke Rehabilitation', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Spine Rehabilitation', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Back Pain Treatment', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Neck Pain Treatment', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Knee Pain Therapy', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Shoulder Pain Therapy', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Arthritis Management', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Joint Mobilization', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Manual Therapy', 'type' => 'Service', 'brands' => 'Mulligan Concept'],
            ['name' => 'Dry Needling', 'type' => 'Service', 'brands' => 'Certified Clinics'],
            ['name' => 'Cupping Therapy', 'type' => 'Service', 'brands' => 'Certified Clinics'],
            ['name' => 'Electrotherapy', 'type' => 'Service', 'brands' => 'BTL'],
            ['name' => 'Ultrasound Therapy', 'type' => 'Service', 'brands' => 'BTL'],
            ['name' => 'IFT Therapy', 'type' => 'Service', 'brands' => 'BTL'],
            ['name' => 'TENS Therapy', 'type' => 'Service', 'brands' => 'Omron'],
            ['name' => 'Laser Therapy', 'type' => 'Service', 'brands' => 'BTL'],
            ['name' => 'Shockwave Therapy', 'type' => 'Service', 'brands' => 'EMS'],
            ['name' => 'Traction Therapy', 'type' => 'Service', 'brands' => 'BTL'],
            ['name' => 'Balance Training', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Gait Training', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Strength Training', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Posture Correction', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Ergonomic Assessment', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Home Physiotherapy', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Home Visit', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Online Physiotherapy Consultation', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Rehabilitation Package', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Fitness Assessment', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Pain Management Program', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Wellness Physiotherapy Package', 'type' => 'Service', 'brands' => 'Physiocare'],
            ['name' => 'Follow-up Physiotherapy Session', 'type' => 'Service', 'brands' => 'Physiocare'],
        ]
    ],
    [
        'category' => 'Health & Medical',
        'sub_category' => 'Psychologist / Mental Health Clinic',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Psychological Consultation', 'type' => 'Service', 'brands' => 'MindPeers, Amaha'],
            ['name' => 'Mental Health Assessment', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Individual Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Couple Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Marriage Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Family Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Child Counseling', 'type' => 'Service', 'brands' => 'MindPeers'],
            ['name' => 'Teen Counseling', 'type' => 'Service', 'brands' => 'MindPeers'],
            ['name' => 'Career Counseling', 'type' => 'Service', 'brands' => 'Mindler'],
            ['name' => 'Stress Management Therapy', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Anxiety Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Depression Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Trauma Therapy', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Grief Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Cognitive Behavioral Therapy (CBT)', 'type' => 'Service', 'brands' => 'Certified Psychologists'],
            ['name' => 'Dialectical Behavior Therapy (DBT)', 'type' => 'Service', 'brands' => 'Certified Psychologists'],
            ['name' => 'Mindfulness Therapy', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Behavioral Therapy', 'type' => 'Service', 'brands' => 'MindPeers'],
            ['name' => 'Anger Management', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Addiction Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Sleep Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'OCD Treatment', 'type' => 'Service', 'brands' => 'Certified Psychologists'],
            ['name' => 'ADHD Assessment', 'type' => 'Service', 'brands' => 'Certified Psychologists'],
            ['name' => 'Autism Assessment', 'type' => 'Service', 'brands' => 'Certified Psychologists'],
            ['name' => 'Learning Disability Assessment', 'type' => 'Service', 'brands' => 'Certified Psychologists'],
            ['name' => 'IQ Assessment', 'type' => 'Service', 'brands' => 'Certified Psychologists'],
            ['name' => 'Personality Assessment', 'type' => 'Service', 'brands' => 'Certified Psychologists'],
            ['name' => 'Psychometric Testing', 'type' => 'Service', 'brands' => 'MindPeers'],
            ['name' => 'Employee Assistance Program (EAP)', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Corporate Wellness Program', 'type' => 'Service', 'brands' => 'MindPeers'],
            ['name' => 'Group Therapy', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Parenting Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Relationship Counseling', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Online Therapy Session', 'type' => 'Service', 'brands' => 'Amaha, MindPeers'],
            ['name' => 'Video Consultation', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Tele Counseling', 'type' => 'Service', 'brands' => 'MindPeers'],
            ['name' => 'Mental Wellness Package', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Follow-up Counseling Session', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Meditation Guidance', 'type' => 'Service', 'brands' => 'Amaha'],
            ['name' => 'Emotional Wellness Coaching', 'type' => 'Service', 'brands' => 'MindPeers'],
        ]
    ],
    [
        'category' => 'Health & Medical',
        'sub_category' => 'Veterinary Clinic',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'General Pet Consultation', 'type' => 'Service', 'brands' => 'Vetic, Crown Vet'],
            ['name' => 'Dog Consultation', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Cat Consultation', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Puppy Health Check', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Kitten Health Check', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Pet Vaccination', 'type' => 'Service', 'brands' => 'Zoetis, MSD Animal Health'],
            ['name' => 'Rabies Vaccination', 'type' => 'Service', 'brands' => 'Zoetis'],
            ['name' => 'Deworming', 'type' => 'Service', 'brands' => 'Bayer Animal Health'],
            ['name' => 'Flea & Tick Treatment', 'type' => 'Service', 'brands' => 'Bravecto, Frontline'],
            ['name' => 'Pet Grooming', 'type' => 'Service', 'brands' => 'Heads Up For Tails'],
            ['name' => 'Nail Trimming', 'type' => 'Service', 'brands' => 'Heads Up For Tails'],
            ['name' => 'Ear Cleaning', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Dental Cleaning', 'type' => 'Service', 'brands' => 'Virbac'],
            ['name' => 'Pet Dental Treatment', 'type' => 'Service', 'brands' => 'Virbac'],
            ['name' => 'Pet Surgery', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Spaying', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Neutering', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Orthopedic Surgery', 'type' => 'Service', 'brands' => 'Crown Vet'],
            ['name' => 'Pet X-Ray', 'type' => 'Service', 'brands' => 'IDEXX'],
            ['name' => 'Pet Ultrasound', 'type' => 'Service', 'brands' => 'GE Healthcare'],
            ['name' => 'Blood Test', 'type' => 'Service', 'brands' => 'IDEXX Laboratories'],
            ['name' => 'Urine Test', 'type' => 'Service', 'brands' => 'IDEXX'],
            ['name' => 'Pet Pharmacy', 'type' => 'Physical Product', 'brands' => 'Virbac, Himalaya Pet Care'],
            ['name' => 'Prescription Medicines', 'type' => 'Physical Product', 'brands' => 'Zoetis, Virbac'],
            ['name' => 'Pet Vitamins', 'type' => 'Physical Product', 'brands' => 'Virbac'],
            ['name' => 'Dog Food', 'type' => 'Physical Product', 'brands' => 'Pedigree, Royal Canin'],
            ['name' => 'Cat Food', 'type' => 'Physical Product', 'brands' => 'Whiskas, Royal Canin'],
            ['name' => 'Prescription Pet Food', 'type' => 'Physical Product', 'brands' => 'Royal Canin, Hill\'s'],
            ['name' => 'Pet Supplements', 'type' => 'Physical Product', 'brands' => 'Himalaya Pet Care'],
            ['name' => 'Pet Skin Treatment', 'type' => 'Service', 'brands' => 'Virbac'],
            ['name' => 'Allergy Treatment', 'type' => 'Service', 'brands' => 'Zoetis'],
            ['name' => 'Emergency Pet Care', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'ICU for Pets', 'type' => 'Service', 'brands' => 'Crown Vet'],
            ['name' => 'Pet Hospitalization', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Pet Microchipping', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Pet Health Certificate', 'type' => 'Service', 'brands' => 'Registered Veterinarian'],
            ['name' => 'Home Veterinary Visit', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Online Vet Consultation', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Pet Wellness Package', 'type' => 'Service', 'brands' => 'Vetic'],
            ['name' => 'Annual Vaccination Package', 'type' => 'Service', 'brands' => 'Zoetis'],
        ]
    ],
    [
        'category' => 'Health & Medical',
        'sub_category' => 'Ayurvedic Clinic',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Ayurvedic Consultation', 'type' => 'Service', 'brands' => 'Patanjali, Kottakkal Arya Vaidya Sala'],
            ['name' => 'Pulse Diagnosis', 'type' => 'Service', 'brands' => 'Ayurvedic Clinics'],
            ['name' => 'Dosha Assessment', 'type' => 'Service', 'brands' => 'Ayurvedic Clinics'],
            ['name' => 'Panchakarma Consultation', 'type' => 'Service', 'brands' => 'Kottakkal Arya Vaidya Sala'],
            ['name' => 'Panchakarma Therapy', 'type' => 'Service', 'brands' => 'Kottakkal Arya Vaidya Sala'],
            ['name' => 'Abhyanga Massage', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Shirodhara Therapy', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Pizhichil Therapy', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Njavarakizhi Therapy', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Kizhi Therapy', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Nasya Therapy', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Vasti Therapy', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Virechana Therapy', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Herbal Steam Therapy', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Stress Management Therapy', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Arthritis Treatment', 'type' => 'Service', 'brands' => 'Patanjali'],
            ['name' => 'Joint Pain Treatment', 'type' => 'Service', 'brands' => 'Patanjali'],
            ['name' => 'Back Pain Treatment', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Weight Management Program', 'type' => 'Service', 'brands' => 'Patanjali'],
            ['name' => 'Skin Care Treatment', 'type' => 'Service', 'brands' => 'Himalaya Wellness'],
            ['name' => 'Hair Care Treatment', 'type' => 'Service', 'brands' => 'Himalaya Wellness'],
            ['name' => 'Digestive Disorder Treatment', 'type' => 'Service', 'brands' => 'Patanjali'],
            ['name' => 'Diabetes Management', 'type' => 'Service', 'brands' => 'Patanjali'],
            ['name' => 'Women\'s Wellness Program', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Fertility Support Therapy', 'type' => 'Service', 'brands' => 'Ayurvedic Clinics'],
            ['name' => 'Immunity Booster Consultation', 'type' => 'Service', 'brands' => 'Patanjali'],
            ['name' => 'Ayurvedic Medicines', 'type' => 'Physical Product', 'brands' => 'Patanjali, Baidyanath, Dabur'],
            ['name' => 'Herbal Supplements', 'type' => 'Physical Product', 'brands' => 'Himalaya Wellness, Dabur'],
            ['name' => 'Chyawanprash', 'type' => 'Physical Product', 'brands' => 'Dabur, Patanjali'],
            ['name' => 'Herbal Oils', 'type' => 'Physical Product', 'brands' => 'Kottakkal, Kerala Ayurveda'],
            ['name' => 'Herbal Powders', 'type' => 'Physical Product', 'brands' => 'Baidyanath'],
            ['name' => 'Herbal Tablets', 'type' => 'Physical Product', 'brands' => 'Himalaya Wellness'],
            ['name' => 'Herbal Juices', 'type' => 'Physical Product', 'brands' => 'Patanjali'],
            ['name' => 'Ayurvedic Diet Consultation', 'type' => 'Service', 'brands' => 'Ayurvedic Clinics'],
            ['name' => 'Yoga Consultation', 'type' => 'Service', 'brands' => 'Patanjali Yogpeeth'],
            ['name' => 'Lifestyle Counseling', 'type' => 'Service', 'brands' => 'Ayurvedic Clinics'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Patanjali'],
            ['name' => 'Home Panchakarma Service', 'type' => 'Service', 'brands' => 'Selected Clinics'],
            ['name' => 'Wellness Package', 'type' => 'Service', 'brands' => 'Kerala Ayurveda'],
            ['name' => 'Follow-up Consultation', 'type' => 'Service', 'brands' => 'Ayurvedic Clinics'],
        ]
    ],
    [
        'category' => 'Health & Medical',
        'sub_category' => 'Home Healthcare Services',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Doctor Home Visit', 'type' => 'Service', 'brands' => 'Apollo HomeCare, Portea'],
            ['name' => 'Nurse Home Visit', 'type' => 'Service', 'brands' => 'Portea, HCAH'],
            ['name' => 'Physiotherapy at Home', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Elder Care at Home', 'type' => 'Service', 'brands' => 'HCAH, Portea'],
            ['name' => 'Attendant / Caregiver Service', 'type' => 'Service', 'brands' => 'HCAH'],
            ['name' => 'ICU Care at Home', 'type' => 'Service', 'brands' => 'Apollo HomeCare'],
            ['name' => 'Post-Surgery Care', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Mother & Baby Care', 'type' => 'Service', 'brands' => 'Apollo HomeCare'],
            ['name' => 'Newborn Care', 'type' => 'Service', 'brands' => 'HCAH'],
            ['name' => 'Palliative Care', 'type' => 'Service', 'brands' => 'HCAH'],
            ['name' => 'Cancer Care at Home', 'type' => 'Service', 'brands' => 'HCAH'],
            ['name' => 'Dementia Care', 'type' => 'Service', 'brands' => 'HCAH'],
            ['name' => 'Alzheimer\'s Care', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Stroke Rehabilitation', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Bedridden Patient Care', 'type' => 'Service', 'brands' => 'HCAH'],
            ['name' => 'Wound Dressing', 'type' => 'Service', 'brands' => 'Apollo HomeCare'],
            ['name' => 'Injection at Home', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'IV Drip at Home', 'type' => 'Service', 'brands' => 'HCAH'],
            ['name' => 'Catheter Care', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Tracheostomy Care', 'type' => 'Service', 'brands' => 'HCAH'],
            ['name' => 'Oxygen Therapy', 'type' => 'Service', 'brands' => 'Philips Respironics'],
            ['name' => 'Oxygen Concentrator Rental', 'type' => 'Physical Product', 'brands' => 'Philips, Oxymed'],
            ['name' => 'BiPAP Rental', 'type' => 'Physical Product', 'brands' => 'ResMed'],
            ['name' => 'CPAP Rental', 'type' => 'Physical Product', 'brands' => 'ResMed'],
            ['name' => 'Hospital Bed Rental', 'type' => 'Physical Product', 'brands' => 'Arcatron Mobility'],
            ['name' => 'Wheelchair Rental', 'type' => 'Physical Product', 'brands' => 'Karma Healthcare'],
            ['name' => 'Walker Rental', 'type' => 'Physical Product', 'brands' => 'Karma Healthcare'],
            ['name' => 'Medical Equipment Rental', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Home Sample Collection', 'type' => 'Service', 'brands' => 'Dr. Lal PathLabs'],
            ['name' => 'ECG at Home', 'type' => 'Service', 'brands' => 'BPL Medical'],
            ['name' => 'Vaccination at Home', 'type' => 'Service', 'brands' => 'Apollo HomeCare'],
            ['name' => 'Medicine Delivery', 'type' => 'Service', 'brands' => 'Apollo Pharmacy, Tata 1mg'],
            ['name' => 'Nutrition Consultation', 'type' => 'Service', 'brands' => 'Apollo HomeCare'],
            ['name' => 'Teleconsultation', 'type' => 'Service', 'brands' => 'Apollo 24/7'],
            ['name' => 'Health Checkup at Home', 'type' => 'Service', 'brands' => 'Portea'],
            ['name' => 'Diabetes Management', 'type' => 'Service', 'brands' => 'Apollo HomeCare'],
            ['name' => 'Home Dialysis Support', 'type' => 'Service', 'brands' => 'NephroPlus'],
            ['name' => 'Home ICU Setup', 'type' => 'Service', 'brands' => 'HCAH'],
            ['name' => 'Medical Transportation', 'type' => 'Service', 'brands' => 'Apollo HomeCare'],
            ['name' => '24x7 Home Care Package', 'type' => 'Service', 'brands' => 'Portea'],
        ]
    ],
    [
        'category' => 'Health & Medical',
        'sub_category' => 'Blood Bank',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Whole Blood', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Packed Red Blood Cells (PRBC)', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Platelet Concentrate', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Single Donor Platelets (SDP)', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Fresh Frozen Plasma (FFP)', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Cryoprecipitate', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Plasma Donation', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Platelet Donation', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Blood Donation Camp', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Voluntary Blood Donation', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Blood Group Testing', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Cross Matching', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Compatibility Testing', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Blood Screening', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Infectious Disease Screening', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Blood Component Separation', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Emergency Blood Supply', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Rare Blood Group Support', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Neonatal Blood Support', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Thalassemia Blood Support', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Cancer Patient Blood Support', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Surgery Blood Support', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Accident Emergency Blood', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Blood Storage Service', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Blood Transportation', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Donor Registration', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Donor Health Checkup', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Hemoglobin Test', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Blood Bank Certificate', 'type' => 'Service', 'brands' => 'Government Licensed Blood Banks'],
            ['name' => 'Blood Availability Inquiry', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Online Blood Request', 'type' => 'Service', 'brands' => 'e-RaktKosh'],
            ['name' => 'Blood Inventory Management', 'type' => 'Service', 'brands' => 'e-RaktKosh'],
            ['name' => 'Plasma Availability', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Platelet Availability', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Blood Reservation', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
            ['name' => 'Mobile Blood Collection Unit', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Corporate Blood Donation Drive', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Community Blood Donation Camp', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => 'Blood Donor Awareness Program', 'type' => 'Service', 'brands' => 'Indian Red Cross Society'],
            ['name' => '24x7 Emergency Blood Support', 'type' => 'Service', 'brands' => 'Government Blood Banks'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Health & Medical Sub Categories 28.3 to 28.12.\n";
