<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Houseboat & Water Tourism',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Houseboat Stay', 'type' => 'Service', 'brands' => 'Kerala Houseboats'],
            ['name' => 'Luxury Houseboat', 'type' => 'Service', 'brands' => 'Xandari Riverscapes'],
            ['name' => 'Premium Houseboat', 'type' => 'Service', 'brands' => 'Spice Routes'],
            ['name' => 'Deluxe Houseboat', 'type' => 'Service', 'brands' => 'Kerala Backwaters'],
            ['name' => 'Day Cruise', 'type' => 'Service', 'brands' => 'Cordelia Cruises'],
            ['name' => 'Sunset Cruise', 'type' => 'Service', 'brands' => 'Houseboat Operator'],
            ['name' => 'Sunrise Cruise', 'type' => 'Service', 'brands' => 'Houseboat Operator'],
            ['name' => 'Dinner Cruise', 'type' => 'Service', 'brands' => 'Cordelia Cruises'],
            ['name' => 'Private Cruise', 'type' => 'Service', 'brands' => 'Houseboat Operator'],
            ['name' => 'Family Houseboat Package', 'type' => 'Service', 'brands' => 'Kerala Houseboats'],
            ['name' => 'Honeymoon Houseboat', 'type' => 'Service', 'brands' => 'Xandari Riverscapes'],
            ['name' => 'Group Houseboat Booking', 'type' => 'Service', 'brands' => 'Houseboat Operator'],
            ['name' => 'Corporate Cruise', 'type' => 'Service', 'brands' => 'Houseboat Operator'],
            ['name' => 'Backwater Tour', 'type' => 'Service', 'brands' => 'Kerala Tourism'],
            ['name' => 'River Cruise', 'type' => 'Service', 'brands' => 'Cordelia Cruises'],
            ['name' => 'Lake Cruise', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Canal Cruise', 'type' => 'Service', 'brands' => 'Houseboat Operator'],
            ['name' => 'Fishing Trip', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Kayaking', 'type' => 'Service', 'brands' => 'Aquaterra Adventures'],
            ['name' => 'Canoeing', 'type' => 'Service', 'brands' => 'Aquaterra Adventures'],
            ['name' => 'Speed Boat Ride', 'type' => 'Service', 'brands' => 'Water Sports Center'],
            ['name' => 'Jet Ski Ride', 'type' => 'Service', 'brands' => 'Water Sports Center'],
            ['name' => 'Banana Boat Ride', 'type' => 'Service', 'brands' => 'Water Sports Center'],
            ['name' => 'Parasailing', 'type' => 'Service', 'brands' => 'Water Sports Center'],
            ['name' => 'Water Scooter Rental', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Floating Restaurant', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Seafood Dining', 'type' => 'Service', 'brands' => 'Houseboat Operator'],
            ['name' => 'Cultural Performance', 'type' => 'Service', 'brands' => 'Kerala Tourism'],
            ['name' => 'Live Music Cruise', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Photography Tour', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Bird Watching Tour', 'type' => 'Service', 'brands' => 'Kerala Tourism'],
            ['name' => 'Village Tour', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Airport Transfer', 'type' => 'Service', 'brands' => 'Houseboat Operator'],
            ['name' => 'Hotel Pickup & Drop', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'Booking.com'],
            ['name' => 'Customized Water Tour', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Weekend Cruise Package', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Tour Guide', 'type' => 'Service', 'brands' => 'Certified Guide'],
            ['name' => '24×7 Guest Support', 'type' => 'Service', 'brands' => 'Tourism Operator'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Eco Tourism Operator',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Eco Tour Package', 'type' => 'Service', 'brands' => 'Kerala Tourism'],
            ['name' => 'Nature Tour', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Forest Safari', 'type' => 'Service', 'brands' => 'Jungle Lodges'],
            ['name' => 'Wildlife Safari', 'type' => 'Service', 'brands' => 'Jungle Lodges'],
            ['name' => 'Bird Watching Tour', 'type' => 'Service', 'brands' => 'BNHS'],
            ['name' => 'Nature Walk', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Jungle Trekking', 'type' => 'Service', 'brands' => 'Indiahikes'],
            ['name' => 'Eco Camping', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Sustainable Tourism Package', 'type' => 'Service', 'brands' => 'Responsible Tourism Mission'],
            ['name' => 'Farm Stay', 'type' => 'Service', 'brands' => 'SaffronStays'],
            ['name' => 'Organic Farm Visit', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Village Experience Tour', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Tribal Culture Tour', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Botanical Garden Tour', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'National Park Tour', 'type' => 'Service', 'brands' => 'Forest Department'],
            ['name' => 'Mangrove Tour', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'Butterfly Park Visit', 'type' => 'Service', 'brands' => 'Tourism Operator'],
            ['name' => 'River Eco Tour', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Cycling Tour', 'type' => 'Service', 'brands' => 'Decathlon'],
            ['name' => 'Hiking Tour', 'type' => 'Service', 'brands' => 'Indiahikes'],
            ['name' => 'Photography Expedition', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Conservation Awareness Program', 'type' => 'Service', 'brands' => 'WWF India'],
            ['name' => 'Environmental Education Tour', 'type' => 'Service', 'brands' => 'WWF India'],
            ['name' => 'Tree Plantation Program', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Volunteer Tourism', 'type' => 'Service', 'brands' => 'WWF India'],
            ['name' => 'Yoga Retreat', 'type' => 'Service', 'brands' => 'Art of Living'],
            ['name' => 'Wellness Retreat', 'type' => 'Service', 'brands' => 'CGH Earth'],
            ['name' => 'Meditation Camp', 'type' => 'Service', 'brands' => 'Isha Foundation'],
            ['name' => 'Eco Resort Booking', 'type' => 'Service', 'brands' => 'CGH Earth'],
            ['name' => 'Homestay Booking', 'type' => 'Service', 'brands' => 'Airbnb'],
            ['name' => 'Local Guide Service', 'type' => 'Service', 'brands' => 'Certified Guide'],
            ['name' => 'Local Cuisine Experience', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Adventure Activities', 'type' => 'Service', 'brands' => 'Adventure Nation'],
            ['name' => 'School Eco Tour', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Corporate Eco Retreat', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'MakeMyTrip'],
            ['name' => 'Customized Eco Tour', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Carbon Neutral Travel Program', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
            ['name' => '24×7 Tour Support', 'type' => 'Service', 'brands' => 'Eco Tourism Operator'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Travel Photography & Videography Services',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Vacation Photography', 'type' => 'Service', 'brands' => 'Local Photography Studio'],
            ['name' => 'Destination Photoshoot', 'type' => 'Service', 'brands' => 'Flytographer'],
            ['name' => 'Couple Photoshoot', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Honeymoon Photoshoot', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Family Photoshoot', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Solo Traveler Photoshoot', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Group Photography', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Drone Photography', 'type' => 'Service', 'brands' => 'DJI'],
            ['name' => 'Drone Videography', 'type' => 'Service', 'brands' => 'DJI'],
            ['name' => 'Cinematic Travel Film', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Travel Vlog Production', 'type' => 'Service', 'brands' => 'Videographer'],
            ['name' => 'Documentary Style Video', 'type' => 'Service', 'brands' => 'Videographer'],
            ['name' => 'Adventure Photography', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Wildlife Photography', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Landscape Photography', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Underwater Photography', 'type' => 'Service', 'brands' => 'GoPro'],
            ['name' => 'Time-Lapse Video', 'type' => 'Service', 'brands' => 'GoPro'],
            ['name' => 'Hyperlapse Video', 'type' => 'Service', 'brands' => 'GoPro'],
            ['name' => 'Reels Creation', 'type' => 'Service', 'brands' => 'Videographer'],
            ['name' => 'Social Media Travel Content', 'type' => 'Service', 'brands' => 'Content Creator'],
            ['name' => '360° Photography', 'type' => 'Service', 'brands' => 'Insta360'],
            ['name' => 'Virtual Tour Creation', 'type' => 'Service', 'brands' => 'Matterport'],
            ['name' => 'Photo Editing', 'type' => 'Service', 'brands' => 'Adobe Lightroom'],
            ['name' => 'Video Editing', 'type' => 'Service', 'brands' => 'Adobe Premiere Pro'],
            ['name' => 'Color Grading', 'type' => 'Service', 'brands' => 'DaVinci Resolve'],
            ['name' => 'RAW Photo Delivery', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Printed Photo Album', 'type' => 'Physical Product', 'brands' => 'Canvera'],
            ['name' => 'Premium Photo Book', 'type' => 'Physical Product', 'brands' => 'Canvera'],
            ['name' => 'Canvas Photo Print', 'type' => 'Physical Product', 'brands' => 'Canvera'],
            ['name' => 'Framed Photo Print', 'type' => 'Physical Product', 'brands' => 'Canvera'],
            ['name' => 'Travel Documentary', 'type' => 'Service', 'brands' => 'Videographer'],
            ['name' => 'Event Coverage', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Destination Wedding Coverage', 'type' => 'Service', 'brands' => 'Wedding Photographer'],
            ['name' => 'Hotel & Resort Photography', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Tourism Promotion Video', 'type' => 'Service', 'brands' => 'Videographer'],
            ['name' => 'Online Gallery', 'type' => 'Service', 'brands' => 'Pixieset'],
            ['name' => 'Same Day Photo Delivery', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => 'Customized Photography Package', 'type' => 'Service', 'brands' => 'Photographer'],
            ['name' => '24×7 Booking Support', 'type' => 'Service', 'brands' => 'Photographer'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Luxury Travel Concierge',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Luxury Holiday Planning', 'type' => 'Service', 'brands' => 'Abercrombie & Kent'],
            ['name' => 'Personalized Itinerary', 'type' => 'Service', 'brands' => 'Luxury Concierge'],
            ['name' => 'VIP Airport Assistance', 'type' => 'Service', 'brands' => 'Plaza Premium'],
            ['name' => 'Fast Track Immigration', 'type' => 'Service', 'brands' => 'Plaza Premium'],
            ['name' => 'Private Jet Booking', 'type' => 'Service', 'brands' => 'JetSetGo'],
            ['name' => 'Helicopter Charter', 'type' => 'Service', 'brands' => 'Blade India'],
            ['name' => 'Yacht Charter', 'type' => 'Service', 'brands' => 'Azimut Yachts'],
            ['name' => 'Luxury Cruise Booking', 'type' => 'Service', 'brands' => 'Celebrity Cruises'],
            ['name' => '5-Star Hotel Booking', 'type' => 'Service', 'brands' => 'Marriott, Taj Hotels'],
            ['name' => 'Luxury Resort Booking', 'type' => 'Service', 'brands' => 'Aman Resorts'],
            ['name' => 'Private Villa Booking', 'type' => 'Service', 'brands' => 'Airbnb Luxe'],
            ['name' => 'Chauffeur Service', 'type' => 'Service', 'brands' => 'Blacklane'],
            ['name' => 'Luxury Car Rental', 'type' => 'Service', 'brands' => 'Mercedes-Benz Rent'],
            ['name' => 'Exotic Car Rental', 'type' => 'Service', 'brands' => 'Lamborghini Rental'],
            ['name' => 'Fine Dining Reservation', 'type' => 'Service', 'brands' => 'Michelin Guide'],
            ['name' => 'Private Chef Booking', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Spa Reservation', 'type' => 'Service', 'brands' => 'Jiva Spa'],
            ['name' => 'Golf Tour Planning', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Adventure Luxury Experience', 'type' => 'Service', 'brands' => 'Luxury Concierge'],
            ['name' => 'Shopping Assistance', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Personal Shopper', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Event Ticket Booking', 'type' => 'Service', 'brands' => 'BookMyShow'],
            ['name' => 'VIP Concert Access', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Luxury Train Booking', 'type' => 'Service', 'brands' => 'Maharajas\' Express'],
            ['name' => 'Heritage Palace Stay', 'type' => 'Service', 'brands' => 'Taj Hotels'],
            ['name' => 'Butler Service', 'type' => 'Service', 'brands' => 'Luxury Hotel'],
            ['name' => 'Travel Security', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Medical Travel Assistance', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Luxury Honeymoon Planning', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Anniversary Travel Planning', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Family Luxury Vacation', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Corporate Executive Travel', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Visa Assistance', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Forex Assistance', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'Private Tour Guide', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => '24×7 Travel Assistance', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Emergency Travel Support', 'type' => 'Service', 'brands' => 'Concierge'],
            ['name' => 'Membership Program', 'type' => 'Service', 'brands' => 'Luxury Concierge'],
            ['name' => 'Dedicated Travel Manager', 'type' => 'Service', 'brands' => 'Concierge'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Travel Membership Club',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Annual Travel Membership', 'type' => 'Membership', 'brands' => 'Club Mahindra'],
            ['name' => 'Lifetime Membership', 'type' => 'Membership', 'brands' => 'Sterling Holidays'],
            ['name' => 'Vacation Ownership', 'type' => 'Membership', 'brands' => 'Club Mahindra'],
            ['name' => 'Holiday Points Program', 'type' => 'Membership', 'brands' => 'Marriott Vacation Club'],
            ['name' => 'Family Membership', 'type' => 'Membership', 'brands' => 'Club Mahindra'],
            ['name' => 'Couple Membership', 'type' => 'Membership', 'brands' => 'Sterling Holidays'],
            ['name' => 'Premium Membership', 'type' => 'Membership', 'brands' => 'RCI'],
            ['name' => 'VIP Membership', 'type' => 'Membership', 'brands' => 'Marriott Vacation Club'],
            ['name' => 'Domestic Holiday Booking', 'type' => 'Service', 'brands' => 'Club Mahindra'],
            ['name' => 'International Holiday Booking', 'type' => 'Service', 'brands' => 'RCI'],
            ['name' => 'Resort Stay Benefits', 'type' => 'Service', 'brands' => 'Club Mahindra'],
            ['name' => 'Hotel Discounts', 'type' => 'Service', 'brands' => 'Agoda VIP'],
            ['name' => 'Flight Discounts', 'type' => 'Service', 'brands' => 'MakeMyTrip'],
            ['name' => 'Cruise Discounts', 'type' => 'Service', 'brands' => 'MSC Cruises'],
            ['name' => 'Car Rental Discounts', 'type' => 'Service', 'brands' => 'Avis'],
            ['name' => 'Airport Lounge Access', 'type' => 'Service', 'brands' => 'Priority Pass'],
            ['name' => 'Dining Benefits', 'type' => 'Service', 'brands' => 'EazyDiner Prime'],
            ['name' => 'Spa Benefits', 'type' => 'Service', 'brands' => 'Jiva Spa'],
            ['name' => 'Adventure Activity Discounts', 'type' => 'Service', 'brands' => 'Thrillophilia'],
            ['name' => 'Travel Insurance Benefits', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Exclusive Holiday Deals', 'type' => 'Service', 'brands' => 'Club Mahindra'],
            ['name' => 'Members Only Offers', 'type' => 'Service', 'brands' => 'Travel Club'],
            ['name' => 'Seasonal Vacation Packages', 'type' => 'Service', 'brands' => 'Club Mahindra'],
            ['name' => 'Flexible Booking', 'type' => 'Service', 'brands' => 'Membership Club'],
            ['name' => 'Holiday Exchange Program', 'type' => 'Service', 'brands' => 'RCI'],
            ['name' => 'Referral Rewards', 'type' => 'Service', 'brands' => 'Travel Club'],
            ['name' => 'Loyalty Reward Points', 'type' => 'Membership', 'brands' => 'Marriott Bonvoy'],
            ['name' => 'Birthday Holiday Benefits', 'type' => 'Service', 'brands' => 'Travel Club'],
            ['name' => 'Anniversary Vacation Offers', 'type' => 'Service', 'brands' => 'Travel Club'],
            ['name' => 'Family Event Packages', 'type' => 'Service', 'brands' => 'Travel Club'],
            ['name' => 'Corporate Membership', 'type' => 'Membership', 'brands' => 'Travel Club'],
            ['name' => 'Business Travel Benefits', 'type' => 'Service', 'brands' => 'American Express GBT'],
            ['name' => 'Concierge Service', 'type' => 'Service', 'brands' => 'Membership Club'],
            ['name' => 'Travel Planning Assistance', 'type' => 'Service', 'brands' => 'Membership Club'],
            ['name' => 'Mobile App Access', 'type' => 'Software', 'brands' => 'Travel Club'],
            ['name' => 'Online Booking Portal', 'type' => 'Software', 'brands' => 'Club Mahindra'],
            ['name' => 'EMI Membership Plans', 'type' => 'Service', 'brands' => 'Bajaj Finserv'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Travel Club'],
            ['name' => 'Dedicated Relationship Manager', 'type' => 'Service', 'brands' => 'Travel Club'],
            ['name' => 'Member Community Events', 'type' => 'Service', 'brands' => 'Travel Club'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Travel Blog / Influencer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Travel Blog Articles', 'type' => 'Digital Service', 'brands' => 'WordPress'],
            ['name' => 'Destination Reviews', 'type' => 'Digital Service', 'brands' => 'TripAdvisor'],
            ['name' => 'Hotel Reviews', 'type' => 'Digital Service', 'brands' => 'Booking.com'],
            ['name' => 'Restaurant Reviews', 'type' => 'Digital Service', 'brands' => 'Zomato'],
            ['name' => 'Travel Vlogs', 'type' => 'Digital Service', 'brands' => 'YouTube'],
            ['name' => 'Instagram Travel Content', 'type' => 'Digital Service', 'brands' => 'Instagram'],
            ['name' => 'Facebook Travel Content', 'type' => 'Digital Service', 'brands' => 'Facebook'],
            ['name' => 'Travel Photography', 'type' => 'Service', 'brands' => 'Canon'],
            ['name' => 'Travel Videography', 'type' => 'Service', 'brands' => 'Sony'],
            ['name' => 'Drone Content Creation', 'type' => 'Service', 'brands' => 'DJI'],
            ['name' => 'Reels Production', 'type' => 'Digital Service', 'brands' => 'Instagram'],
            ['name' => 'Short Video Creation', 'type' => 'Digital Service', 'brands' => 'YouTube Shorts'],
            ['name' => 'Travel Guides', 'type' => 'Digital Product', 'brands' => 'Lonely Planet'],
            ['name' => 'Travel E-Books', 'type' => 'Digital Product', 'brands' => 'Kindle Direct Publishing'],
            ['name' => 'Itinerary Planning', 'type' => 'Digital Service', 'brands' => 'Creator'],
            ['name' => 'Affiliate Travel Booking', 'type' => 'Digital Service', 'brands' => 'MakeMyTrip Affiliate'],
            ['name' => 'Hotel Affiliate Marketing', 'type' => 'Digital Service', 'brands' => 'Booking.com Affiliate'],
            ['name' => 'Brand Collaboration', 'type' => 'Service', 'brands' => 'Travel Brands'],
            ['name' => 'Sponsored Travel Campaign', 'type' => 'Service', 'brands' => 'Tourism Boards'],
            ['name' => 'Tourism Promotion', 'type' => 'Service', 'brands' => 'Incredible India'],
            ['name' => 'Product Reviews', 'type' => 'Service', 'brands' => 'Brand Collaboration'],
            ['name' => 'Destination Marketing', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Social Media Management', 'type' => 'Service', 'brands' => 'Creator'],
            ['name' => 'Content Strategy', 'type' => 'Service', 'brands' => 'Creator'],
            ['name' => 'SEO for Travel Blog', 'type' => 'Service', 'brands' => 'Yoast SEO'],
            ['name' => 'Newsletter', 'type' => 'Digital Service', 'brands' => 'Mailchimp'],
            ['name' => 'Travel Podcast', 'type' => 'Digital Service', 'brands' => 'Spotify'],
            ['name' => 'Live Travel Sessions', 'type' => 'Service', 'brands' => 'YouTube Live'],
            ['name' => 'Online Community', 'type' => 'Digital Service', 'brands' => 'Discord'],
            ['name' => 'Merchandise Sales', 'type' => 'Physical Product', 'brands' => 'Creator Store'],
            ['name' => 'Preset Pack', 'type' => 'Digital Product', 'brands' => 'Adobe Lightroom'],
            ['name' => 'Photography Course', 'type' => 'Digital Service', 'brands' => 'Creator'],
            ['name' => 'Travel Consultation', 'type' => 'Service', 'brands' => 'Creator'],
            ['name' => 'Group Tours', 'type' => 'Service', 'brands' => 'Creator'],
            ['name' => 'Meet & Greet Events', 'type' => 'Service', 'brands' => 'Creator'],
            ['name' => 'Online Workshops', 'type' => 'Service', 'brands' => 'Creator'],
            ['name' => 'Membership Community', 'type' => 'Membership', 'brands' => 'Patreon'],
            ['name' => 'Paid Subscription Content', 'type' => 'Membership', 'brands' => 'Substack'],
            ['name' => 'Brand Media Kit', 'type' => 'Digital Product', 'brands' => 'Canva'],
            ['name' => 'Digital Advertising', 'type' => 'Service', 'brands' => 'Google Ads'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Tourism Board / Tourism Promotion Agency',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Destination Promotion', 'type' => 'Service', 'brands' => 'Incredible India'],
            ['name' => 'Tourism Campaign', 'type' => 'Service', 'brands' => 'Gujarat Tourism'],
            ['name' => 'State Tourism Promotion', 'type' => 'Service', 'brands' => 'Rajasthan Tourism'],
            ['name' => 'International Tourism Promotion', 'type' => 'Service', 'brands' => 'Incredible India'],
            ['name' => 'Travel Information', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Tourist Helpline', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Visitor Information Center', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Tourism Website', 'type' => 'Digital Service', 'brands' => 'Incredible India'],
            ['name' => 'Tourism Mobile App', 'type' => 'Software', 'brands' => 'Incredible India App'],
            ['name' => 'Tourism Brochures', 'type' => 'Physical Product', 'brands' => 'Tourism Board'],
            ['name' => 'Tourist Maps', 'type' => 'Physical Product', 'brands' => 'Tourism Board'],
            ['name' => 'Travel Guide Books', 'type' => 'Physical Product', 'brands' => 'Lonely Planet'],
            ['name' => 'Cultural Festival Promotion', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Heritage Tourism Promotion', 'type' => 'Service', 'brands' => 'ASI'],
            ['name' => 'Eco Tourism Promotion', 'type' => 'Service', 'brands' => 'Kerala Responsible Tourism'],
            ['name' => 'Adventure Tourism Promotion', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Wildlife Tourism Promotion', 'type' => 'Service', 'brands' => 'Forest Department'],
            ['name' => 'Pilgrimage Tourism Promotion', 'type' => 'Service', 'brands' => 'IRCTC Tourism'],
            ['name' => 'Rural Tourism Promotion', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Medical Tourism Promotion', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Film Tourism Promotion', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Tourism Investment Promotion', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Tourism Events', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Travel Expo', 'type' => 'Service', 'brands' => 'SATTE'],
            ['name' => 'Roadshows', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Familiarization (FAM) Trips', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Travel Trade Partnership', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Hotel Registration Support', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Tour Guide Certification', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Homestay Registration', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Tourism Training', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Digital Marketing Campaign', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Social Media Promotion', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Press & Media Relations', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Tourism Research', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Visitor Analytics', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Tourism Grants', 'type' => 'Service', 'brands' => 'Government Tourism Department'],
            ['name' => 'Tourism Awards', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => 'Public Awareness Campaign', 'type' => 'Service', 'brands' => 'Tourism Board'],
            ['name' => '24×7 Tourist Assistance', 'type' => 'Service', 'brands' => 'Tourism Board'],
        ]
    ],
    [
        'category' => 'Travel & Tourism',
        'sub_category' => 'Corporate Travel Management Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Corporate Flight Booking', 'type' => 'Service', 'brands' => 'American Express GBT'],
            ['name' => 'Corporate Hotel Booking', 'type' => 'Service', 'brands' => 'CWT'],
            ['name' => 'Business Travel Planning', 'type' => 'Service', 'brands' => 'BCD Travel'],
            ['name' => 'Executive Travel Management', 'type' => 'Service', 'brands' => 'FCM Travel'],
            ['name' => 'International Business Travel', 'type' => 'Service', 'brands' => 'American Express GBT'],
            ['name' => 'Domestic Business Travel', 'type' => 'Service', 'brands' => 'Thomas Cook India'],
            ['name' => 'Employee Travel Booking', 'type' => 'Service', 'brands' => 'CWT'],
            ['name' => 'Group Business Travel', 'type' => 'Service', 'brands' => 'BCD Travel'],
            ['name' => 'MICE Management', 'type' => 'Service', 'brands' => 'Thomas Cook India'],
            ['name' => 'Corporate Event Travel', 'type' => 'Service', 'brands' => 'FCM Travel'],
            ['name' => 'Conference Travel', 'type' => 'Service', 'brands' => 'CWT'],
            ['name' => 'Incentive Travel', 'type' => 'Service', 'brands' => 'Thomas Cook India'],
            ['name' => 'VIP Executive Travel', 'type' => 'Service', 'brands' => 'American Express GBT'],
            ['name' => 'Airport Meet & Greet', 'type' => 'Service', 'brands' => 'Plaza Premium'],
            ['name' => 'Airport Lounge Access', 'type' => 'Service', 'brands' => 'Priority Pass'],
            ['name' => 'Chauffeur Service', 'type' => 'Service', 'brands' => 'Blacklane'],
            ['name' => 'Car Rental', 'type' => 'Service', 'brands' => 'Avis'],
            ['name' => 'Travel Policy Management', 'type' => 'Service', 'brands' => 'SAP Concur'],
            ['name' => 'Expense Management', 'type' => 'Software', 'brands' => 'SAP Concur'],
            ['name' => 'Travel Approval Workflow', 'type' => 'Software', 'brands' => 'SAP Concur'],
            ['name' => 'Visa Assistance', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'Passport Assistance', 'type' => 'Service', 'brands' => 'Corporate Travel Company'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Forex Management', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'Corporate Forex Card', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'Rail Ticket Booking', 'type' => 'Service', 'brands' => 'IRCTC'],
            ['name' => 'Bus Ticket Booking', 'type' => 'Service', 'brands' => 'redBus'],
            ['name' => 'Cruise Booking', 'type' => 'Service', 'brands' => 'Royal Caribbean'],
            ['name' => 'Emergency Travel Support', 'type' => 'Service', 'brands' => 'Corporate Travel Company'],
            ['name' => 'Risk Management', 'type' => 'Service', 'brands' => 'International SOS'],
            ['name' => 'Duty of Care Services', 'type' => 'Service', 'brands' => 'International SOS'],
            ['name' => 'Online Booking Tool', 'type' => 'Software', 'brands' => 'SAP Concur'],
            ['name' => 'Mobile Travel App', 'type' => 'Software', 'brands' => 'SAP Concur'],
            ['name' => 'MIS & Reporting', 'type' => 'Software', 'brands' => 'SAP Concur'],
            ['name' => 'Invoice Management', 'type' => 'Service', 'brands' => 'Corporate Travel Company'],
            ['name' => 'GST Billing', 'type' => 'Service', 'brands' => 'Corporate Travel Company'],
            ['name' => 'Account Manager', 'type' => 'Service', 'brands' => 'Corporate Travel Company'],
            ['name' => '24×7 Business Travel Support', 'type' => 'Service', 'brands' => 'Corporate Travel Company'],
            ['name' => 'Travel Analytics', 'type' => 'Service', 'brands' => 'SAP Concur'],
            ['name' => 'End-to-End Corporate Travel Management', 'type' => 'Service', 'brands' => 'American Express GBT'],
        ]
    ],
    [
        'category' => 'Events & Entertainment',
        'sub_category' => 'Banquet Hall',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Wedding Hall Booking', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Reception Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Engagement Function Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Birthday Party Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Anniversary Celebration Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Corporate Event Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Conference Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Seminar Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Exhibition Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Kitty Party Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Indoor Banquet', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Outdoor Lawn', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'AC Banquet Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Luxury Banquet Hall', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Stage Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Floral Decoration', 'type' => 'Service', 'brands' => 'Ferns N Petals'],
            ['name' => 'Theme Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'LED Wall Setup', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Sound System', 'type' => 'Service', 'brands' => 'JBL Professional'],
            ['name' => 'Lighting Setup', 'type' => 'Service', 'brands' => 'Philips Entertainment'],
            ['name' => 'DJ Arrangement', 'type' => 'Service', 'brands' => 'Pioneer DJ'],
            ['name' => 'Live Music', 'type' => 'Service', 'brands' => 'Event Organizer'],
            ['name' => 'Catering Service', 'type' => 'Service', 'brands' => 'Catering Partner'],
            ['name' => 'Multi-Cuisine Catering', 'type' => 'Service', 'brands' => 'Catering Partner'],
            ['name' => 'Buffet Arrangement', 'type' => 'Service', 'brands' => 'Catering Partner'],
            ['name' => 'Photography', 'type' => 'Service', 'brands' => 'Canon Professionals'],
            ['name' => 'Videography', 'type' => 'Service', 'brands' => 'Sony'],
            ['name' => 'Drone Coverage', 'type' => 'Service', 'brands' => 'DJI'],
            ['name' => 'Valet Parking', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Guest Accommodation', 'type' => 'Service', 'brands' => 'Hotel Partner'],
            ['name' => 'Bridal Room', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Generator Backup', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Wi-Fi Facility', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Event Coordinator', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Security Service', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Housekeeping', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'WeddingWire India'],
            ['name' => 'Customized Event Package', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => 'Corporate Package', 'type' => 'Service', 'brands' => 'Banquet Hall'],
            ['name' => '24×7 Event Support', 'type' => 'Service', 'brands' => 'Banquet Hall'],
        ]
    ],
    [
        'category' => 'Events & Entertainment',
        'sub_category' => 'Party Plot / Wedding Lawn',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Wedding Lawn Booking', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Reception Lawn', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Engagement Event', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Outdoor Wedding Venue', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Garden Wedding', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Destination Wedding Venue', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Birthday Celebration', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Anniversary Celebration', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Corporate Outdoor Event', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Cultural Program Venue', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Exhibition Ground', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Concert Venue', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Stage Setup', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Luxury Mandap Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Floral Decoration', 'type' => 'Service', 'brands' => 'Ferns N Petals'],
            ['name' => 'Theme Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Lighting Decoration', 'type' => 'Service', 'brands' => 'Philips Entertainment'],
            ['name' => 'LED Wall Setup', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Sound System', 'type' => 'Service', 'brands' => 'JBL Professional'],
            ['name' => 'DJ & Live Music', 'type' => 'Service', 'brands' => 'Pioneer DJ'],
            ['name' => 'Catering Arrangement', 'type' => 'Service', 'brands' => 'Catering Partner'],
            ['name' => 'Buffet Setup', 'type' => 'Service', 'brands' => 'Catering Partner'],
            ['name' => 'Live Food Counter', 'type' => 'Service', 'brands' => 'Catering Partner'],
            ['name' => 'Bridal Entry Setup', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Fireworks Show', 'type' => 'Service', 'brands' => 'Event Planner'],
            ['name' => 'Photography', 'type' => 'Service', 'brands' => 'Canon Professionals'],
            ['name' => 'Videography', 'type' => 'Service', 'brands' => 'Sony'],
            ['name' => 'Drone Coverage', 'type' => 'Service', 'brands' => 'DJI'],
            ['name' => 'Valet Parking', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Generator Backup', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Washroom Facility', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Guest Seating Arrangement', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Kids Play Area', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Security Service', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Event Coordination', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Customized Wedding Package', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Corporate Event Package', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'WeddingWire India'],
            ['name' => 'Venue Visit Appointment', 'type' => 'Service', 'brands' => 'Party Plot'],
            ['name' => '24×7 Event Support', 'type' => 'Service', 'brands' => 'Party Plot'],
        ]
    ],
    [
        'category' => 'Events & Entertainment',
        'sub_category' => 'Catering Service',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Wedding Catering', 'type' => 'Service', 'brands' => 'Sodexo, Compass Group'],
            ['name' => 'Corporate Catering', 'type' => 'Service', 'brands' => 'Sodexo'],
            ['name' => 'Birthday Party Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Anniversary Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Engagement Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Housewarming Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Festival Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Outdoor Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Indoor Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Buffet Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Live Food Counter', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Multi-Cuisine Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'North Indian Menu', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'South Indian Menu', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Gujarati Menu', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Punjabi Menu', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Chinese Menu', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Italian Menu', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Mexican Menu', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Jain Food Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Vegan Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Breakfast Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Lunch Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Dinner Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Hi-Tea Catering', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Dessert Counter', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Sweet Counter', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Mocktail Counter', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Coffee & Tea Station', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Barbecue Counter', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Chaat Counter', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Ice Cream Counter', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Packed Meal Service', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Corporate Tiffin', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Event Staff', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Crockery & Cutlery Rental', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Table Setup', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Customized Menu Planning', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => 'Food Tasting Session', 'type' => 'Service', 'brands' => 'Caterer'],
            ['name' => '24×7 Catering Support', 'type' => 'Service', 'brands' => 'Caterer'],
        ]
    ],
    [
        'category' => 'Events & Entertainment',
        'sub_category' => 'Photography & Videography Studio',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Wedding Photography', 'type' => 'Service', 'brands' => 'Canon Professionals'],
            ['name' => 'Wedding Videography', 'type' => 'Service', 'brands' => 'Sony'],
            ['name' => 'Pre-Wedding Shoot', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Post-Wedding Shoot', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Engagement Photography', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Maternity Photoshoot', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Baby Photoshoot', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Kids Photography', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Family Portrait', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Fashion Photography', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Product Photography', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Food Photography', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Corporate Photography', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Event Photography', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Birthday Photography', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Drone Photography', 'type' => 'Service', 'brands' => 'DJI'],
            ['name' => 'Drone Videography', 'type' => 'Service', 'brands' => 'DJI'],
            ['name' => 'Cinematic Wedding Film', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Live Streaming', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => '360° Photography', 'type' => 'Service', 'brands' => 'Insta360'],
            ['name' => 'Passport Size Photo', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'ID Card Photography', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Photo Editing', 'type' => 'Service', 'brands' => 'Adobe Lightroom'],
            ['name' => 'Video Editing', 'type' => 'Service', 'brands' => 'Adobe Premiere Pro'],
            ['name' => 'Color Grading', 'type' => 'Service', 'brands' => 'DaVinci Resolve'],
            ['name' => 'Album Design', 'type' => 'Service', 'brands' => 'Canvera'],
            ['name' => 'Premium Photo Album', 'type' => 'Physical Product', 'brands' => 'Canvera'],
            ['name' => 'Canvas Print', 'type' => 'Physical Product', 'brands' => 'Canvera'],
            ['name' => 'Photo Frame', 'type' => 'Physical Product', 'brands' => 'Canvera'],
            ['name' => 'Instant Photo Printing', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Green Screen Shoot', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Studio Rental', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Reels & Shorts Creation', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Social Media Content Shoot', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Corporate Ad Shoot', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Real Estate Photography', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'E-commerce Product Shoot', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Online Booking', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => 'Customized Shoot Package', 'type' => 'Service', 'brands' => 'Studio'],
            ['name' => '24×7 Studio Support', 'type' => 'Service', 'brands' => 'Studio'],
        ]
    ],
    [
        'category' => 'Events & Entertainment',
        'sub_category' => 'DJ & Sound System Rental',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'DJ Booking', 'type' => 'Service', 'brands' => 'Pioneer DJ'],
            ['name' => 'Professional DJ', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Wedding DJ', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Birthday Party DJ', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Corporate Event DJ', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Live DJ Performance', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Sound System Rental', 'type' => 'Service', 'brands' => 'JBL Professional'],
            ['name' => 'Line Array Sound System', 'type' => 'Service', 'brands' => 'JBL Professional'],
            ['name' => 'PA System Rental', 'type' => 'Service', 'brands' => 'Bose Professional'],
            ['name' => 'Wireless Microphone', 'type' => 'Service', 'brands' => 'Shure'],
            ['name' => 'Cordless Microphone', 'type' => 'Service', 'brands' => 'Sennheiser'],
            ['name' => 'Mixer Console', 'type' => 'Service', 'brands' => 'Yamaha Pro Audio'],
            ['name' => 'DJ Console Rental', 'type' => 'Service', 'brands' => 'Pioneer DJ'],
            ['name' => 'Subwoofer Rental', 'type' => 'Service', 'brands' => 'JBL Professional'],
            ['name' => 'Stage Monitor', 'type' => 'Service', 'brands' => 'Yamaha'],
            ['name' => 'Karaoke Setup', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'LED Dance Floor', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Smoke Machine', 'type' => 'Service', 'brands' => 'Chauvet DJ'],
            ['name' => 'Bubble Machine', 'type' => 'Service', 'brands' => 'Chauvet DJ'],
            ['name' => 'Snow Machine', 'type' => 'Service', 'brands' => 'Chauvet DJ'],
            ['name' => 'Confetti Machine', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'CO₂ Jet Machine', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'Laser Show', 'type' => 'Service', 'brands' => 'Laserworld'],
            ['name' => 'LED Lighting', 'type' => 'Service', 'brands' => 'Philips Entertainment'],
            ['name' => 'Moving Head Lights', 'type' => 'Service', 'brands' => 'Chauvet Professional'],
            ['name' => 'Stage Lighting', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Truss Setup', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Generator Backup', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Outdoor Sound Setup', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Indoor Sound Setup', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Concert Sound Setup', 'type' => 'Service', 'brands' => 'JBL Professional'],
            ['name' => 'Festival Sound Setup', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Event Audio Engineer', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Live Band Sound Support', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Equipment Transportation', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Sound Testing', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Hourly Rental', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Full-Day Rental', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => 'Customized Event Package', 'type' => 'Service', 'brands' => 'DJ Service'],
            ['name' => '24×7 Technical Support', 'type' => 'Service', 'brands' => 'DJ Service'],
        ]
    ],
    [
        'category' => 'Events & Entertainment',
        'sub_category' => 'Stage & Lighting Decoration',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Wedding Stage Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Reception Stage Setup', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Engagement Stage Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Birthday Stage Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Corporate Stage Setup', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Fashion Show Stage', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Concert Stage Setup', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Exhibition Stage', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Award Ceremony Stage', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Theme Stage Design', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Floral Stage Decoration', 'type' => 'Service', 'brands' => 'Ferns N Petals'],
            ['name' => 'LED Stage Backdrop', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'LED Wall Installation', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Truss Structure', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Stage Platform Rental', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Stage Carpet Setup', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Premium Sofa Setup', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Bride & Groom Stage', 'type' => 'Service', 'brands' => 'Wedding Planner'],
            ['name' => 'Mandap Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Entrance Gate Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Walkway Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Ambient Lighting', 'type' => 'Service', 'brands' => 'Philips Entertainment'],
            ['name' => 'Moving Head Lights', 'type' => 'Service', 'brands' => 'Chauvet Professional'],
            ['name' => 'Laser Lighting', 'type' => 'Service', 'brands' => 'Laserworld'],
            ['name' => 'Pixel LED Lighting', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Fairy Light Decoration', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Outdoor Lighting', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Indoor Lighting', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Spotlight Setup', 'type' => 'Service', 'brands' => 'Philips Entertainment'],
            ['name' => 'Follow Spot Lighting', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Smoke Effects', 'type' => 'Service', 'brands' => 'Chauvet DJ'],
            ['name' => 'Cold Pyro Effects', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'Confetti Effects', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'CO₂ Effects', 'type' => 'Service', 'brands' => 'MagicFX'],
            ['name' => 'Stage Fabrication', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Event Branding Setup', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Customized Stage Theme', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => 'Installation & Dismantling', 'type' => 'Service', 'brands' => 'Event Vendor'],
            ['name' => 'Full Event Decoration Package', 'type' => 'Service', 'brands' => 'Event Decorator'],
            ['name' => '24×7 Event Support', 'type' => 'Service', 'brands' => 'Event Decorator'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Travel & Tourism Sub Categories 30.18 to 30.25, and Events & Entertainment 31.3 to 31.8.\n";
