<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Currency Exchange / Forex Services',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Foreign Currency Exchange', 'type' => 'Service', 'brands' => 'Thomas Cook, BookMyForex'],
            ['name' => 'Currency Buy', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'Currency Sell', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'Forex Card', 'type' => 'Physical Product', 'brands' => 'Thomas Cook Borderless Card'],
            ['name' => 'Reload Forex Card', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'Student Forex Card', 'type' => 'Physical Product', 'brands' => 'BookMyForex'],
            ['name' => 'Travel Forex Card', 'type' => 'Physical Product', 'brands' => 'Thomas Cook'],
            ['name' => 'Multi Currency Card', 'type' => 'Physical Product', 'brands' => 'Axis Bank Forex Card'],
            ['name' => 'International Money Transfer', 'type' => 'Service', 'brands' => 'Wise'],
            ['name' => 'Outward Remittance', 'type' => 'Service', 'brands' => 'Western Union'],
            ['name' => 'Inward Remittance', 'type' => 'Service', 'brands' => 'Western Union'],
            ['name' => 'Wire Transfer', 'type' => 'Service', 'brands' => 'SWIFT'],
            ['name' => 'Western Union Transfer', 'type' => 'Service', 'brands' => 'Western Union'],
            ['name' => 'MoneyGram Transfer', 'type' => 'Service', 'brands' => 'MoneyGram'],
            ['name' => 'Travel Currency Kit', 'type' => 'Physical Product', 'brands' => 'Forex Provider'],
            ['name' => 'Foreign Currency Notes', 'type' => 'Physical Product', 'brands' => 'Forex Provider'],
            ['name' => 'Currency Rate Alert', 'type' => 'Service', 'brands' => 'BookMyForex'],
            ['name' => 'Live Exchange Rates', 'type' => 'Software', 'brands' => 'XE'],
            ['name' => 'Currency Conversion', 'type' => 'Service', 'brands' => 'Forex Provider'],
            ['name' => 'Currency Booking', 'type' => 'Service', 'brands' => 'BookMyForex'],
            ['name' => 'Doorstep Currency Delivery', 'type' => 'Service', 'brands' => 'BookMyForex'],
            ['name' => 'Airport Forex Pickup', 'type' => 'Service', 'brands' => 'Thomas Cook'],
            ['name' => 'Student Forex Assistance', 'type' => 'Service', 'brands' => 'IDP Education'],
            ['name' => 'Business Forex Solutions', 'type' => 'Service', 'brands' => 'Forex Provider'],
            ['name' => 'Export Import Forex', 'type' => 'Service', 'brands' => 'Forex Provider'],
            ['name' => 'NRI Forex Services', 'type' => 'Service', 'brands' => 'ICICI Bank'],
            ['name' => 'Forex Consultation', 'type' => 'Service', 'brands' => 'Forex Provider'],
            ['name' => 'Travel Insurance', 'type' => 'Service', 'brands' => 'Tata AIG'],
            ['name' => 'Visa Assistance', 'type' => 'Service', 'brands' => 'VFS Global'],
            ['name' => 'International SIM Card', 'type' => 'Physical Product', 'brands' => 'Matrix'],
            ['name' => 'Currency Rate Lock', 'type' => 'Service', 'brands' => 'BookMyForex'],
            ['name' => 'Corporate Forex Account', 'type' => 'Service', 'brands' => 'Forex Provider'],
            ['name' => 'Bulk Currency Exchange', 'type' => 'Service', 'brands' => 'Forex Provider'],
            ['name' => 'Online Forex Booking', 'type' => 'Service', 'brands' => 'BookMyForex'],
            ['name' => 'Mobile App Services', 'type' => 'Software', 'brands' => 'Thomas Cook App'],
            ['name' => 'Transaction Tracking', 'type' => 'Software', 'brands' => 'Forex Provider'],
            ['name' => 'RBI Compliance Support', 'type' => 'Service', 'brands' => 'Forex Provider'],
            ['name' => 'KYC Verification', 'type' => 'Service', 'brands' => 'Forex Provider'],
            ['name' => 'Customer Support', 'type' => 'Service', 'brands' => 'Forex Provider'],
            ['name' => '24×7 Forex Assistance', 'type' => 'Service', 'brands' => 'Forex Provider'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Microfinance Institution',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Micro Business Loan', 'type' => 'Service', 'brands' => 'Bandhan Bank'],
            ['name' => 'Women Entrepreneur Loan', 'type' => 'Service', 'brands' => 'Annapurna Finance'],
            ['name' => 'Self Help Group (SHG) Loan', 'type' => 'Service', 'brands' => 'NABARD'],
            ['name' => 'Joint Liability Group Loan', 'type' => 'Service', 'brands' => 'Fusion Finance'],
            ['name' => 'Agriculture Micro Loan', 'type' => 'Service', 'brands' => 'Spandana Sphoorty'],
            ['name' => 'Dairy Loan', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Livestock Loan', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Small Shop Loan', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Street Vendor Loan', 'type' => 'Service', 'brands' => 'PM SVANidhi'],
            ['name' => 'Rural Enterprise Loan', 'type' => 'Service', 'brands' => 'NABARD'],
            ['name' => 'Working Capital Loan', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Emergency Loan', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Education Loan', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Health Loan', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Home Improvement Loan', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Solar Loan', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Water & Sanitation Loan', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Loan Renewal', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'EMI Collection', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Digital Loan Repayment', 'type' => 'Service', 'brands' => 'UPI'],
            ['name' => 'Financial Literacy Program', 'type' => 'Service', 'brands' => 'NABARD'],
            ['name' => 'Savings Program', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Insurance Facilitation', 'type' => 'Service', 'brands' => 'LIC'],
            ['name' => 'Pension Enrollment', 'type' => 'Service', 'brands' => 'Atal Pension Yojana'],
            ['name' => 'PMJDY Assistance', 'type' => 'Service', 'brands' => 'Jan Dhan Yojana'],
            ['name' => 'Mudra Loan Assistance', 'type' => 'Service', 'brands' => 'PMMY'],
            ['name' => 'Credit Counseling', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Group Meeting Facilitation', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Loan Eligibility Assessment', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Document Verification', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'eKYC Verification', 'type' => 'Service', 'brands' => 'Aadhaar eKYC'],
            ['name' => 'Mobile Banking Assistance', 'type' => 'Service', 'brands' => 'Bank'],
            ['name' => 'Doorstep Collection', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Rural Financial Advisory', 'type' => 'Service', 'brands' => 'NABARD'],
            ['name' => 'Digital Financial Inclusion', 'type' => 'Service', 'brands' => 'NPCI'],
            ['name' => 'Business Mentorship', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Loan Monitoring', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Customer Training', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
            ['name' => 'Community Development Programs', 'type' => 'Service', 'brands' => 'NGO Partner'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Microfinance Institution'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'NBFC (Non-Banking Financial Company)',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Personal Loan', 'type' => 'Service', 'brands' => 'Bajaj Finance'],
            ['name' => 'Business Loan', 'type' => 'Service', 'brands' => 'Tata Capital'],
            ['name' => 'MSME Loan', 'type' => 'Service', 'brands' => 'Lendingkart'],
            ['name' => 'Working Capital Loan', 'type' => 'Service', 'brands' => 'Aditya Birla Finance'],
            ['name' => 'Loan Against Property', 'type' => 'Service', 'brands' => 'PNB Housing Finance'],
            ['name' => 'Gold Loan', 'type' => 'Service', 'brands' => 'Muthoot Finance'],
            ['name' => 'Vehicle Loan', 'type' => 'Service', 'brands' => 'Shriram Finance'],
            ['name' => 'Commercial Vehicle Loan', 'type' => 'Service', 'brands' => 'Shriram Finance'],
            ['name' => 'Two Wheeler Loan', 'type' => 'Service', 'brands' => 'Bajaj Finance'],
            ['name' => 'Consumer Durable Loan', 'type' => 'Service', 'brands' => 'Bajaj Finance'],
            ['name' => 'Education Loan', 'type' => 'Service', 'brands' => 'Avanse Financial Services'],
            ['name' => 'Medical Equipment Loan', 'type' => 'Service', 'brands' => 'Tata Capital'],
            ['name' => 'Machinery Loan', 'type' => 'Service', 'brands' => 'Srei Equipment Finance'],
            ['name' => 'Construction Equipment Finance', 'type' => 'Service', 'brands' => 'Tata Capital'],
            ['name' => 'Lease Finance', 'type' => 'Service', 'brands' => 'Tata Capital'],
            ['name' => 'Hire Purchase Finance', 'type' => 'Service', 'brands' => 'Shriram Finance'],
            ['name' => 'Invoice Financing', 'type' => 'Service', 'brands' => 'KredX'],
            ['name' => 'Supply Chain Finance', 'type' => 'Service', 'brands' => 'KredX'],
            ['name' => 'Vendor Financing', 'type' => 'Service', 'brands' => 'Tata Capital'],
            ['name' => 'Dealer Financing', 'type' => 'Service', 'brands' => 'Hero FinCorp'],
            ['name' => 'EMI Card', 'type' => 'Physical Product', 'brands' => 'Bajaj Finserv EMI Network Card'],
            ['name' => 'Credit Line', 'type' => 'Service', 'brands' => 'FlexiLoans'],
            ['name' => 'Loan Top-Up', 'type' => 'Service', 'brands' => 'NBFC'],
            ['name' => 'Loan Balance Transfer', 'type' => 'Service', 'brands' => 'Bajaj Finance'],
            ['name' => 'Credit Assessment', 'type' => 'Service', 'brands' => 'CIBIL'],
            ['name' => 'Loan Eligibility Check', 'type' => 'Service', 'brands' => 'NBFC'],
            ['name' => 'Digital Loan Application', 'type' => 'Software', 'brands' => 'NBFC Portal'],
            ['name' => 'eKYC Verification', 'type' => 'Service', 'brands' => 'Aadhaar eKYC'],
            ['name' => 'Document Verification', 'type' => 'Service', 'brands' => 'NBFC'],
            ['name' => 'Loan Disbursement', 'type' => 'Service', 'brands' => 'NBFC'],
            ['name' => 'EMI Collection', 'type' => 'Service', 'brands' => 'NBFC'],
            ['name' => 'Online EMI Payment', 'type' => 'Service', 'brands' => 'UPI'],
            ['name' => 'Loan Foreclosure', 'type' => 'Service', 'brands' => 'NBFC'],
            ['name' => 'Loan Restructuring', 'type' => 'Service', 'brands' => 'NBFC'],
            ['name' => 'Insurance Cross Sell', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Financial Advisory', 'type' => 'Service', 'brands' => 'NBFC'],
            ['name' => 'Customer Relationship Manager', 'type' => 'Service', 'brands' => 'NBFC'],
            ['name' => 'Mobile Loan App', 'type' => 'Software', 'brands' => 'Bajaj Finserv'],
            ['name' => 'Online Customer Portal', 'type' => 'Software', 'brands' => 'NBFC'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'NBFC'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Credit Cooperative Society',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Savings Account', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Fixed Deposit', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Recurring Deposit', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Member Savings Scheme', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Personal Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Gold Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Agriculture Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Crop Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Business Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Education Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Housing Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Vehicle Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Emergency Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'SHG Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'MSME Loan', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Loan Against Deposit', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Member Registration', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Share Certificate', 'type' => 'Physical Product', 'brands' => 'Cooperative Society'],
            ['name' => 'Dividend Distribution', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Loan Eligibility Assessment', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'KYC Verification', 'type' => 'Service', 'brands' => 'Aadhaar eKYC'],
            ['name' => 'Nominee Registration', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Passbook', 'type' => 'Physical Product', 'brands' => 'Cooperative Society'],
            ['name' => 'Cheque Book', 'type' => 'Physical Product', 'brands' => 'Cooperative Society'],
            ['name' => 'Online Banking', 'type' => 'Software', 'brands' => 'Cooperative Society'],
            ['name' => 'Mobile Banking', 'type' => 'Software', 'brands' => 'Cooperative Society'],
            ['name' => 'UPI Payment', 'type' => 'Service', 'brands' => 'NPCI'],
            ['name' => 'EMI Collection', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Loan Recovery Services', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Financial Literacy Program', 'type' => 'Service', 'brands' => 'NABARD'],
            ['name' => 'Member Welfare Scheme', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Insurance Facilitation', 'type' => 'Service', 'brands' => 'LIC'],
            ['name' => 'Pension Assistance', 'type' => 'Service', 'brands' => 'Atal Pension Yojana'],
            ['name' => 'Scholarship Assistance', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Annual General Meeting', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Audit Compliance', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Member Support Services', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Community Development Program', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => 'Financial Counseling', 'type' => 'Service', 'brands' => 'Cooperative Society'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Cooperative Society'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Pawn Shop / Gold Loan Center',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Gold Loan', 'type' => 'Service', 'brands' => 'Muthoot Finance'],
            ['name' => 'Instant Gold Loan', 'type' => 'Service', 'brands' => 'Manappuram Finance'],
            ['name' => 'Loan Against Gold Jewelry', 'type' => 'Service', 'brands' => 'IIFL Finance'],
            ['name' => 'Gold Valuation', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Gold Purity Testing', 'type' => 'Service', 'brands' => 'Karatmeter'],
            ['name' => 'Gold Coin Loan', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Gold Biscuit Loan', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Ornament Appraisal', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Loan Renewal', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Gold Loan Top-Up', 'type' => 'Service', 'brands' => 'Muthoot Finance'],
            ['name' => 'Gold Loan Balance Transfer', 'type' => 'Service', 'brands' => 'IIFL Finance'],
            ['name' => 'Short Term Gold Loan', 'type' => 'Service', 'brands' => 'Manappuram Finance'],
            ['name' => 'Long Term Gold Loan', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Agricultural Gold Loan', 'type' => 'Service', 'brands' => 'Muthoot Finance'],
            ['name' => 'Business Gold Loan', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Emergency Gold Loan', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Online Gold Loan Application', 'type' => 'Software', 'brands' => 'Muthoot Finance'],
            ['name' => 'Doorstep Gold Evaluation', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'eKYC Verification', 'type' => 'Service', 'brands' => 'Aadhaar eKYC'],
            ['name' => 'Loan Eligibility Assessment', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Instant Loan Approval', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Same Day Loan Disbursement', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'UPI Loan Repayment', 'type' => 'Service', 'brands' => 'NPCI'],
            ['name' => 'Online EMI Payment', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Loan Closure', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Safe Gold Storage', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Gold Release Service', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'SMS Loan Alerts', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Mobile App Services', 'type' => 'Software', 'brands' => 'Muthoot Finance'],
            ['name' => 'Customer Portal', 'type' => 'Software', 'brands' => 'Gold Loan Center'],
            ['name' => 'Interest Calculation', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Loan Statement', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Insurance for Pledged Gold', 'type' => 'Service', 'brands' => 'ICICI Lombard'],
            ['name' => 'Financial Consultation', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Business Loan Against Gold', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Corporate Gold Loan', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Relationship Manager', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => 'Branch Locator', 'type' => 'Software', 'brands' => 'Muthoot Finance'],
            ['name' => 'Customer Care', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'Gold Loan Center'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Money Transfer Service',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Domestic Money Transfer', 'type' => 'Service', 'brands' => 'Western Union'],
            ['name' => 'International Money Transfer', 'type' => 'Service', 'brands' => 'Wise'],
            ['name' => 'Bank Transfer', 'type' => 'Service', 'brands' => 'NEFT'],
            ['name' => 'IMPS Transfer', 'type' => 'Service', 'brands' => 'NPCI'],
            ['name' => 'RTGS Transfer', 'type' => 'Service', 'brands' => 'RBI'],
            ['name' => 'UPI Money Transfer', 'type' => 'Service', 'brands' => 'BHIM'],
            ['name' => 'Aadhaar Enabled Payment', 'type' => 'Service', 'brands' => 'AePS'],
            ['name' => 'Cash Transfer', 'type' => 'Service', 'brands' => 'MoneyGram'],
            ['name' => 'Wallet to Bank Transfer', 'type' => 'Service', 'brands' => 'Paytm'],
            ['name' => 'Mobile Recharge', 'type' => 'Service', 'brands' => 'Paytm'],
            ['name' => 'DTH Recharge', 'type' => 'Service', 'brands' => 'PhonePe'],
            ['name' => 'Utility Bill Payment', 'type' => 'Service', 'brands' => 'Bharat BillPay'],
            ['name' => 'Electricity Bill Payment', 'type' => 'Service', 'brands' => 'Bharat BillPay'],
            ['name' => 'Gas Bill Payment', 'type' => 'Service', 'brands' => 'Bharat BillPay'],
            ['name' => 'Water Bill Payment', 'type' => 'Service', 'brands' => 'Bharat BillPay'],
            ['name' => 'Broadband Bill Payment', 'type' => 'Service', 'brands' => 'Bharat BillPay'],
            ['name' => 'Credit Card Bill Payment', 'type' => 'Service', 'brands' => 'CRED'],
            ['name' => 'Insurance Premium Payment', 'type' => 'Service', 'brands' => 'PhonePe'],
            ['name' => 'FASTag Recharge', 'type' => 'Service', 'brands' => 'Paytm'],
            ['name' => 'Metro Card Recharge', 'type' => 'Service', 'brands' => 'Paytm'],
            ['name' => 'QR Payment Collection', 'type' => 'Service', 'brands' => 'PhonePe'],
            ['name' => 'Merchant Payment Solution', 'type' => 'Service', 'brands' => 'Razorpay'],
            ['name' => 'POS Machine Services', 'type' => 'Service', 'brands' => 'Pine Labs'],
            ['name' => 'Micro ATM Services', 'type' => 'Service', 'brands' => 'Spice Money'],
            ['name' => 'Cash Withdrawal', 'type' => 'Service', 'brands' => 'AePS'],
            ['name' => 'Cash Deposit', 'type' => 'Service', 'brands' => 'Banking Correspondent'],
            ['name' => 'Mini Statement', 'type' => 'Service', 'brands' => 'AePS'],
            ['name' => 'Balance Inquiry', 'type' => 'Service', 'brands' => 'AePS'],
            ['name' => 'Aadhaar Pay', 'type' => 'Service', 'brands' => 'NPCI'],
            ['name' => 'Domestic Remittance', 'type' => 'Service', 'brands' => 'MoneyGram'],
            ['name' => 'International Remittance', 'type' => 'Service', 'brands' => 'Western Union'],
            ['name' => 'Forex Remittance', 'type' => 'Service', 'brands' => 'Wise'],
            ['name' => 'Payment Gateway Integration', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'API Payment Solution', 'type' => 'Software', 'brands' => 'Cashfree'],
            ['name' => 'Online Money Transfer', 'type' => 'Software', 'brands' => 'Wise'],
            ['name' => 'Mobile App Transfer', 'type' => 'Software', 'brands' => 'PhonePe'],
            ['name' => 'Transaction Tracking', 'type' => 'Software', 'brands' => 'Wise'],
            ['name' => 'eKYC Verification', 'type' => 'Service', 'brands' => 'Aadhaar eKYC'],
            ['name' => 'Customer Support', 'type' => 'Service', 'brands' => 'Money Transfer Center'],
            ['name' => '24×7 Transaction Support', 'type' => 'Service', 'brands' => 'Money Transfer Center'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'FinTech Company',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Digital Wallet', 'type' => 'Software', 'brands' => 'Paytm'],
            ['name' => 'UPI Payment App', 'type' => 'Software', 'brands' => 'PhonePe'],
            ['name' => 'QR Payment Solution', 'type' => 'Software', 'brands' => 'BharatPe'],
            ['name' => 'Payment Gateway', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'Merchant Payment Solution', 'type' => 'Software', 'brands' => 'Cashfree'],
            ['name' => 'Subscription Billing', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'Invoice Payment', 'type' => 'Software', 'brands' => 'Zoho Invoice'],
            ['name' => 'Expense Management', 'type' => 'Software', 'brands' => 'Happay'],
            ['name' => 'Personal Finance App', 'type' => 'Software', 'brands' => 'Walnut'],
            ['name' => 'Budget Tracking', 'type' => 'Software', 'brands' => 'Money Manager'],
            ['name' => 'Investment Platform', 'type' => 'Software', 'brands' => 'Groww'],
            ['name' => 'Mutual Fund Investment', 'type' => 'Software', 'brands' => 'Groww'],
            ['name' => 'Stock Trading Platform', 'type' => 'Software', 'brands' => 'Zerodha'],
            ['name' => 'Digital Lending Platform', 'type' => 'Software', 'brands' => 'KreditBee'],
            ['name' => 'BNPL (Buy Now Pay Later)', 'type' => 'Service', 'brands' => 'LazyPay'],
            ['name' => 'Credit Score Monitoring', 'type' => 'Software', 'brands' => 'OneScore'],
            ['name' => 'Loan Marketplace', 'type' => 'Software', 'brands' => 'BankBazaar'],
            ['name' => 'Insurance Marketplace', 'type' => 'Software', 'brands' => 'Policybazaar'],
            ['name' => 'Wealth Management Platform', 'type' => 'Software', 'brands' => 'INDmoney'],
            ['name' => 'Tax Filing Platform', 'type' => 'Software', 'brands' => 'ClearTax'],
            ['name' => 'Payroll Software', 'type' => 'Software', 'brands' => 'GreytHR'],
            ['name' => 'Accounting Software', 'type' => 'Software', 'brands' => 'Zoho Books'],
            ['name' => 'Digital KYC', 'type' => 'Software', 'brands' => 'Signzy'],
            ['name' => 'Aadhaar eKYC', 'type' => 'Service', 'brands' => 'UIDAI'],
            ['name' => 'Video KYC', 'type' => 'Software', 'brands' => 'HyperVerge'],
            ['name' => 'Fraud Detection', 'type' => 'Software', 'brands' => 'Signzy'],
            ['name' => 'AI Risk Assessment', 'type' => 'Software', 'brands' => 'FinTech Platform'],
            ['name' => 'API Banking', 'type' => 'Software', 'brands' => 'Setu'],
            ['name' => 'Open Banking API', 'type' => 'Software', 'brands' => 'Setu'],
            ['name' => 'Embedded Finance', 'type' => 'Software', 'brands' => 'FinTech Platform'],
            ['name' => 'Payment Links', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'Virtual Accounts', 'type' => 'Software', 'brands' => 'Cashfree'],
            ['name' => 'Recurring Payments', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'Expense Cards', 'type' => 'Physical Product', 'brands' => 'Happay'],
            ['name' => 'Merchant Dashboard', 'type' => 'Software', 'brands' => 'BharatPe'],
            ['name' => 'Customer Mobile App', 'type' => 'Software', 'brands' => 'FinTech Platform'],
            ['name' => 'Admin Dashboard', 'type' => 'Software', 'brands' => 'FinTech Platform'],
            ['name' => 'Analytics & Reporting', 'type' => 'Software', 'brands' => 'FinTech Platform'],
            ['name' => 'API Integration', 'type' => 'Software', 'brands' => 'FinTech Platform'],
            ['name' => '24×7 Customer Support', 'type' => 'Service', 'brands' => 'FinTech Company'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Payment Gateway Provider',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Payment Gateway Integration', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'UPI Payment Collection', 'type' => 'Service', 'brands' => 'Razorpay'],
            ['name' => 'Credit Card Payment', 'type' => 'Service', 'brands' => 'Stripe'],
            ['name' => 'Debit Card Payment', 'type' => 'Service', 'brands' => 'PayU'],
            ['name' => 'Net Banking Payment', 'type' => 'Service', 'brands' => 'CCAvenue'],
            ['name' => 'Wallet Payments', 'type' => 'Service', 'brands' => 'Paytm'],
            ['name' => 'EMI Payment', 'type' => 'Service', 'brands' => 'Razorpay'],
            ['name' => 'Buy Now Pay Later (BNPL)', 'type' => 'Service', 'brands' => 'Simpl'],
            ['name' => 'Payment Links', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'Payment Buttons', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'QR Code Payments', 'type' => 'Service', 'brands' => 'BharatPe'],
            ['name' => 'POS Payment Solution', 'type' => 'Service', 'brands' => 'Pine Labs'],
            ['name' => 'Subscription Billing', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'Recurring Payments', 'type' => 'Software', 'brands' => 'Stripe'],
            ['name' => 'Smart Collect', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'Split Payments', 'type' => 'Software', 'brands' => 'Cashfree'],
            ['name' => 'Marketplace Payments', 'type' => 'Software', 'brands' => 'Cashfree'],
            ['name' => 'International Payments', 'type' => 'Service', 'brands' => 'Stripe'],
            ['name' => 'Multi Currency Payments', 'type' => 'Service', 'brands' => 'PayPal'],
            ['name' => 'Payout API', 'type' => 'Software', 'brands' => 'RazorpayX'],
            ['name' => 'Vendor Payouts', 'type' => 'Service', 'brands' => 'Cashfree'],
            ['name' => 'Bulk Payouts', 'type' => 'Service', 'brands' => 'RazorpayX'],
            ['name' => 'Virtual Accounts', 'type' => 'Software', 'brands' => 'Cashfree'],
            ['name' => 'Payment Reconciliation', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'Fraud Detection', 'type' => 'Software', 'brands' => 'Signzy'],
            ['name' => 'Chargeback Management', 'type' => 'Service', 'brands' => 'Payment Gateway'],
            ['name' => 'Refund Management', 'type' => 'Service', 'brands' => 'Razorpay'],
            ['name' => 'Payment Analytics', 'type' => 'Software', 'brands' => 'Payment Gateway'],
            ['name' => 'Merchant Dashboard', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'Customer Checkout Page', 'type' => 'Software', 'brands' => 'Stripe'],
            ['name' => 'Mobile SDK', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'API Documentation', 'type' => 'Software', 'brands' => 'Stripe'],
            ['name' => 'Webhook Integration', 'type' => 'Software', 'brands' => 'Razorpay'],
            ['name' => 'White Label Payment Gateway', 'type' => 'Software', 'brands' => 'Payment Gateway'],
            ['name' => 'PCI DSS Compliance', 'type' => 'Service', 'brands' => 'Payment Gateway'],
            ['name' => 'Tokenization Support', 'type' => 'Service', 'brands' => 'Payment Gateway'],
            ['name' => 'Settlement Reports', 'type' => 'Service', 'brands' => 'Payment Gateway'],
            ['name' => 'Developer Support', 'type' => 'Service', 'brands' => 'Payment Gateway'],
            ['name' => 'Merchant Onboarding', 'type' => 'Service', 'brands' => 'Payment Gateway'],
            ['name' => '24×7 Technical Support', 'type' => 'Service', 'brands' => 'Payment Gateway'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Credit Rating Agency',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Personal Credit Score', 'type' => 'Service', 'brands' => 'CIBIL'],
            ['name' => 'Business Credit Rating', 'type' => 'Service', 'brands' => 'CRISIL'],
            ['name' => 'Corporate Credit Rating', 'type' => 'Service', 'brands' => 'ICRA'],
            ['name' => 'SME Credit Rating', 'type' => 'Service', 'brands' => 'CARE Ratings'],
            ['name' => 'Credit Report', 'type' => 'Service', 'brands' => 'Experian'],
            ['name' => 'Credit History Analysis', 'type' => 'Service', 'brands' => 'Equifax'],
            ['name' => 'Credit Monitoring', 'type' => 'Service', 'brands' => 'CIBIL'],
            ['name' => 'Credit Score Improvement', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Credit Health Report', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Loan Eligibility Assessment', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Financial Risk Assessment', 'type' => 'Service', 'brands' => 'CRISIL'],
            ['name' => 'Credit Risk Analysis', 'type' => 'Service', 'brands' => 'ICRA'],
            ['name' => 'Company Rating', 'type' => 'Service', 'brands' => 'CARE Ratings'],
            ['name' => 'Bond Rating', 'type' => 'Service', 'brands' => 'CRISIL'],
            ['name' => 'Debt Instrument Rating', 'type' => 'Service', 'brands' => 'ICRA'],
            ['name' => 'Bank Loan Rating', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Startup Credit Assessment', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'MSME Credit Assessment', 'type' => 'Service', 'brands' => 'CRISIL'],
            ['name' => 'Vendor Credit Evaluation', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Customer Credit Verification', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Financial Statement Analysis', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Industry Risk Report', 'type' => 'Service', 'brands' => 'CRISIL'],
            ['name' => 'Credit Advisory', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Rating Surveillance', 'type' => 'Service', 'brands' => 'CARE Ratings'],
            ['name' => 'Rating Upgrade Consultation', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'ESG Rating', 'type' => 'Service', 'brands' => 'CRISIL'],
            ['name' => 'Research Reports', 'type' => 'Service', 'brands' => 'CRISIL'],
            ['name' => 'Credit Analytics', 'type' => 'Software', 'brands' => 'Credit Rating Platform'],
            ['name' => 'Rating Dashboard', 'type' => 'Software', 'brands' => 'Credit Rating Platform'],
            ['name' => 'API Credit Verification', 'type' => 'Software', 'brands' => 'Credit Rating Platform'],
            ['name' => 'Online Credit Report', 'type' => 'Software', 'brands' => 'CIBIL'],
            ['name' => 'eKYC Verification', 'type' => 'Service', 'brands' => 'Aadhaar eKYC'],
            ['name' => 'Due Diligence', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Investor Rating Reports', 'type' => 'Service', 'brands' => 'ICRA'],
            ['name' => 'Corporate Governance Assessment', 'type' => 'Service', 'brands' => 'CRISIL'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Enterprise Risk Management', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Rating Certification', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => 'Customer Support', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
            ['name' => '24×7 Client Support', 'type' => 'Service', 'brands' => 'Credit Rating Agency'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Business Valuation Firm',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Startup Valuation', 'type' => 'Service', 'brands' => 'EY'],
            ['name' => 'Business Valuation', 'type' => 'Service', 'brands' => 'KPMG'],
            ['name' => 'Company Valuation', 'type' => 'Service', 'brands' => 'Deloitte'],
            ['name' => 'Equity Valuation', 'type' => 'Service', 'brands' => 'PwC'],
            ['name' => 'Share Valuation', 'type' => 'Service', 'brands' => 'Grant Thornton'],
            ['name' => 'Fair Market Valuation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Intellectual Property Valuation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Brand Valuation', 'type' => 'Service', 'brands' => 'Brand Finance'],
            ['name' => 'Asset Valuation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Machinery Valuation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Property Valuation', 'type' => 'Service', 'brands' => 'Knight Frank'],
            ['name' => 'Inventory Valuation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Financial Modeling', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Discounted Cash Flow (DCF) Analysis', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Comparable Company Analysis', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'M&A Valuation', 'type' => 'Service', 'brands' => 'EY'],
            ['name' => 'Due Diligence', 'type' => 'Service', 'brands' => 'Deloitte'],
            ['name' => 'Fundraising Valuation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Investor Presentation Support', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Startup Pitch Deck Review', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'ESOP Valuation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Purchase Price Allocation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Goodwill Valuation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Impairment Testing', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Litigation Valuation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Financial Advisory', 'type' => 'Service', 'brands' => 'KPMG'],
            ['name' => 'Strategic Advisory', 'type' => 'Service', 'brands' => 'EY'],
            ['name' => 'Risk Assessment', 'type' => 'Service', 'brands' => 'Deloitte'],
            ['name' => 'Industry Benchmarking', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Valuation Report', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Certified Valuation Report', 'type' => 'Service', 'brands' => 'Registered Valuer'],
            ['name' => 'RBI / SEBI Compliance Valuation', 'type' => 'Service', 'brands' => 'Registered Valuer'],
            ['name' => 'Tax Valuation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Business Restructuring Advisory', 'type' => 'Service', 'brands' => 'EY'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Virtual CFO Support', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Annual Business Review', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Investor Readiness Assessment', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => 'Corporate Finance Advisory', 'type' => 'Service', 'brands' => 'Valuation Firm'],
            ['name' => '24×7 Client Support', 'type' => 'Service', 'brands' => 'Valuation Firm'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Debt Recovery Agency',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Consumer Debt Recovery', 'type' => 'Service', 'brands' => 'Debt Recovery Agency'],
            ['name' => 'Commercial Debt Recovery', 'type' => 'Service', 'brands' => 'Debt Recovery Agency'],
            ['name' => 'Business Debt Collection', 'type' => 'Service', 'brands' => 'Debt Recovery Agency'],
            ['name' => 'Invoice Recovery', 'type' => 'Service', 'brands' => 'Debt Recovery Agency'],
            ['name' => 'Outstanding Payment Recovery', 'type' => 'Service', 'brands' => 'Debt Recovery Agency'],
            ['name' => 'Loan Recovery', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'EMI Recovery', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Credit Card Debt Recovery', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Corporate Debt Recovery', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'MSME Debt Recovery', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Legal Notice Drafting', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Settlement Negotiation', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Debt Restructuring Assistance', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Skip Tracing', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Asset Investigation', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Debtor Verification', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Recovery Case Assessment', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Collection Strategy Planning', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Field Recovery Services', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Tele Collection Services', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Digital Payment Collection', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Recovery Documentation', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Arbitration Support', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Litigation Coordination', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Insolvency Advisory', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'NPA Recovery Support', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'SARFAESI Assistance', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Recovery Analytics', 'type' => 'Software', 'brands' => 'Recovery Platform'],
            ['name' => 'Client Dashboard', 'type' => 'Software', 'brands' => 'Recovery Platform'],
            ['name' => 'Payment Tracking', 'type' => 'Software', 'brands' => 'Recovery Platform'],
            ['name' => 'Recovery Reports', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Compliance Monitoring', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Risk Assessment', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Credit Control Advisory', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Corporate Recovery Services', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Online Consultation', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Dedicated Recovery Manager', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'Customer Communication Management', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => 'End-to-End Recovery Solutions', 'type' => 'Service', 'brands' => 'Recovery Agency'],
            ['name' => '24×7 Client Support', 'type' => 'Service', 'brands' => 'Recovery Agency'],
        ]
    ],
    [
        'category' => 'Finance & Insurance',
        'sub_category' => 'Financial Training Institute',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Stock Market Course', 'type' => 'Service', 'brands' => 'NSE Academy'],
            ['name' => 'Mutual Fund Course', 'type' => 'Service', 'brands' => 'NISM'],
            ['name' => 'Investment Planning Course', 'type' => 'Service', 'brands' => 'CFP Board'],
            ['name' => 'Financial Planning Course', 'type' => 'Service', 'brands' => 'CFP'],
            ['name' => 'Technical Analysis Course', 'type' => 'Service', 'brands' => 'NIFM'],
            ['name' => 'Fundamental Analysis Course', 'type' => 'Service', 'brands' => 'NIFM'],
            ['name' => 'Options Trading Course', 'type' => 'Service', 'brands' => 'Elearnmarkets'],
            ['name' => 'Futures Trading Course', 'type' => 'Service', 'brands' => 'Elearnmarkets'],
            ['name' => 'Commodity Trading Course', 'type' => 'Service', 'brands' => 'MCX Institute'],
            ['name' => 'Forex Trading Course', 'type' => 'Service', 'brands' => 'BSE Institute'],
            ['name' => 'Cryptocurrency Awareness Course', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Personal Finance Course', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Tax Planning Course', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'GST Training', 'type' => 'Service', 'brands' => 'ClearTax'],
            ['name' => 'Tally Course', 'type' => 'Service', 'brands' => 'Tally Education'],
            ['name' => 'Accounting Course', 'type' => 'Service', 'brands' => 'Zoho Books'],
            ['name' => 'Payroll Training', 'type' => 'Service', 'brands' => 'GreytHR'],
            ['name' => 'Banking Exam Coaching', 'type' => 'Service', 'brands' => 'Career Power'],
            ['name' => 'NISM Certification Training', 'type' => 'Service', 'brands' => 'NISM'],
            ['name' => 'NCFM Certification Training', 'type' => 'Service', 'brands' => 'NSE'],
            ['name' => 'CFP Certification Training', 'type' => 'Service', 'brands' => 'CFP Board'],
            ['name' => 'Financial Modeling Course', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Excel for Finance', 'type' => 'Service', 'brands' => 'Microsoft'],
            ['name' => 'Risk Management Training', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Wealth Management Course', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Investment Portfolio Workshop', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Corporate Finance Training', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Entrepreneurship Finance', 'type' => 'Service', 'brands' => 'Startup India'],
            ['name' => 'Startup Fundraising Workshop', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Live Trading Sessions', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Mock Trading Platform', 'type' => 'Software', 'brands' => 'TradingView'],
            ['name' => 'Online Classes', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Recorded Courses', 'type' => 'Digital Product', 'brands' => 'Institute'],
            ['name' => 'Study Materials', 'type' => 'Physical Product', 'brands' => 'Institute'],
            ['name' => 'Practice Tests', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Career Counseling', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Placement Assistance', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Internship Program', 'type' => 'Service', 'brands' => 'Institute'],
            ['name' => 'Certification Exams', 'type' => 'Service', 'brands' => 'NISM'],
            ['name' => '24×7 Student Support', 'type' => 'Service', 'brands' => 'Institute'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Finance & Insurance Sub Categories 32.11 to 32.22.\n";
