<?php

require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\BusinessCategory;
use App\Models\BusinessSubCategory;
use App\Models\BusinessProduct;
use App\Models\ProductType;
use App\Models\Brand;
use Illuminate\Support\Str;

$data = [
    [
        'category' => 'Automotive',
        'sub_category' => 'Fuel Station',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Petrol', 'type' => 'Physical Product', 'brands' => 'IndianOil, HP, BPCL'],
            ['name' => 'Diesel', 'type' => 'Physical Product', 'brands' => 'IndianOil, HP, BPCL'],
            ['name' => 'Premium Petrol', 'type' => 'Physical Product', 'brands' => 'IndianOil XP95, Shell V-Power, HP Power'],
            ['name' => 'Premium Diesel', 'type' => 'Physical Product', 'brands' => 'IndianOil XtraGreen, Shell V-Power Diesel'],
            ['name' => 'CNG', 'type' => 'Physical Product', 'brands' => 'Gujarat Gas, Adani Total Gas, MGL'],
            ['name' => 'PNG', 'type' => 'Physical Product', 'brands' => 'Gujarat Gas, Adani Total Gas'],
            ['name' => 'EV Fast Charging', 'type' => 'Service', 'brands' => 'Tata Power EZ Charge, Statiq, ChargeZone'],
            ['name' => 'EV Slow Charging', 'type' => 'Service', 'brands' => 'Tata Power, Jio-bp Pulse'],
            ['name' => 'Engine Oil', 'type' => 'Physical Product', 'brands' => 'Castrol, Shell, Servo'],
            ['name' => 'Lubricants', 'type' => 'Physical Product', 'brands' => 'Castrol, Shell, Mobil'],
            ['name' => 'Coolant', 'type' => 'Physical Product', 'brands' => 'Castrol, Servo'],
            ['name' => 'Brake Fluid', 'type' => 'Physical Product', 'brands' => 'Bosch, Castrol'],
            ['name' => 'AdBlue', 'type' => 'Physical Product', 'brands' => 'IndianOil, HP'],
            ['name' => 'Distilled Water', 'type' => 'Physical Product', 'brands' => 'Servo'],
            ['name' => 'Windshield Washer Fluid', 'type' => 'Physical Product', 'brands' => 'Wurth'],
            ['name' => 'Air Filling', 'type' => 'Service', 'brands' => 'IndianOil, HP'],
            ['name' => 'Nitrogen Air Filling', 'type' => 'Service', 'brands' => 'HP, BPCL'],
            ['name' => 'Tyre Pressure Check', 'type' => 'Service', 'brands' => 'IndianOil'],
            ['name' => 'Windshield Cleaning', 'type' => 'Service', 'brands' => 'IndianOil'],
            ['name' => 'Oil Change', 'type' => 'Service', 'brands' => 'Castrol Bike Point, Servo'],
            ['name' => 'Battery Check', 'type' => 'Service', 'brands' => 'Exide'],
            ['name' => 'Coolant Top-up', 'type' => 'Service', 'brands' => 'Castrol'],
            ['name' => 'Wiper Replacement', 'type' => 'Service', 'brands' => 'Bosch'],
            ['name' => 'Car Vacuum Cleaning', 'type' => 'Service', 'brands' => 'IndianOil'],
            ['name' => 'Bike Wash', 'type' => 'Service', 'brands' => 'Local Fuel Stations'],
            ['name' => 'Car Wash', 'type' => 'Service', 'brands' => 'HP, Shell'],
            ['name' => 'Drinking Water', 'type' => 'Service', 'brands' => 'Fuel Station Service'],
            ['name' => 'Restroom Facility', 'type' => 'Service', 'brands' => 'Fuel Station Service'],
            ['name' => 'Air Pump', 'type' => 'Service', 'brands' => 'IndianOil'],
            ['name' => 'ATM Facility', 'type' => 'Service', 'brands' => 'SBI, HDFC Bank'],
            ['name' => 'Convenience Store', 'type' => 'Physical Product', 'brands' => 'In & Out, HP Store'],
            ['name' => 'Snacks', 'type' => 'Physical Product', 'brands' => 'Lay\'s, Haldiram\'s'],
            ['name' => 'Soft Drinks', 'type' => 'Physical Product', 'brands' => 'Coca-Cola, Pepsi'],
            ['name' => 'Packaged Water', 'type' => 'Physical Product', 'brands' => 'Bisleri, Kinley'],
            ['name' => 'Tea & Coffee', 'type' => 'Physical Product', 'brands' => 'Nescafé, Bru'],
            ['name' => 'Mobile Recharge', 'type' => 'Service', 'brands' => 'Airtel, Jio'],
            ['name' => 'FASTag Recharge', 'type' => 'Service', 'brands' => 'NHAI FASTag'],
            ['name' => 'FASTag Purchase', 'type' => 'Physical Product', 'brands' => 'NHAI FASTag'],
            ['name' => 'Insurance Renewal', 'type' => 'Service', 'brands' => 'Local Partners'],
            ['name' => 'Pollution Check (PUC)', 'type' => 'Service', 'brands' => 'Government Authorized'],
            ['name' => 'Loyalty Card', 'type' => 'Service', 'brands' => 'IndianOil XTRAREWARDS, HP Pay'],
            ['name' => 'Fuel Card', 'type' => 'Service', 'brands' => 'IndianOil, BPCL'],
            ['name' => 'Digital Payment', 'type' => 'Service', 'brands' => 'UPI, Paytm, PhonePe'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'EV Charging Station',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'DC Fast Charging', 'type' => 'Service', 'brands' => 'Tata Power EZ Charge, Statiq'],
            ['name' => 'AC Charging', 'type' => 'Service', 'brands' => 'Tata Power, ChargeZone'],
            ['name' => 'Ultra Fast Charging', 'type' => 'Service', 'brands' => 'Jio-bp Pulse, ChargeZone'],
            ['name' => 'CCS2 Charging', 'type' => 'Service', 'brands' => 'Tata Power'],
            ['name' => 'CHAdeMO Charging', 'type' => 'Service', 'brands' => 'Statiq'],
            ['name' => 'GB/T Charging', 'type' => 'Service', 'brands' => 'ChargeZone'],
            ['name' => 'Type 2 Charging', 'type' => 'Service', 'brands' => 'Tata Power'],
            ['name' => 'Portable EV Charger', 'type' => 'Physical Product', 'brands' => 'Exicom, Delta'],
            ['name' => 'Home EV Charger', 'type' => 'Physical Product', 'brands' => 'Tata Power, ABB'],
            ['name' => 'Wall Mounted Charger', 'type' => 'Physical Product', 'brands' => 'ABB, Siemens'],
            ['name' => 'Smart EV Charger', 'type' => 'Physical Product', 'brands' => 'Exicom'],
            ['name' => 'EV Charging Cable', 'type' => 'Physical Product', 'brands' => 'Exicom'],
            ['name' => 'Type 2 Charging Cable', 'type' => 'Physical Product', 'brands' => 'ABB'],
            ['name' => 'CCS2 Charging Cable', 'type' => 'Physical Product', 'brands' => 'ABB'],
            ['name' => 'Charging Connector', 'type' => 'Physical Product', 'brands' => 'ABB'],
            ['name' => 'EV Adapter', 'type' => 'Physical Product', 'brands' => 'Exicom'],
            ['name' => 'RFID Charging Card', 'type' => 'Physical Product', 'brands' => 'Tata Power'],
            ['name' => 'Charging Membership', 'type' => 'Service', 'brands' => 'Statiq'],
            ['name' => 'Pay Per Use Charging', 'type' => 'Service', 'brands' => 'ChargeZone'],
            ['name' => 'Monthly Charging Plan', 'type' => 'Service', 'brands' => 'Jio-bp Pulse'],
            ['name' => 'Battery Health Check', 'type' => 'Service', 'brands' => 'Tata Power'],
            ['name' => 'Battery Diagnostics', 'type' => 'Service', 'brands' => 'Exicom'],
            ['name' => 'Battery Cooling Check', 'type' => 'Service', 'brands' => 'EV Service Partner'],
            ['name' => 'EV Software Update', 'type' => 'Service', 'brands' => 'Tata Motors, MG Motor'],
            ['name' => 'Charging Port Cleaning', 'type' => 'Service', 'brands' => 'EV Service Partner'],
            ['name' => 'Charging Port Repair', 'type' => 'Service', 'brands' => 'EV Service Partner'],
            ['name' => 'Emergency Charging', 'type' => 'Service', 'brands' => 'Statiq'],
            ['name' => 'Mobile Charging Van', 'type' => 'Service', 'brands' => 'Tata Power'],
            ['name' => 'EV Roadside Assistance', 'type' => 'Service', 'brands' => 'Tata Motors'],
            ['name' => 'Charging Station Locator', 'type' => 'Service', 'brands' => 'PlugShare, Statiq'],
            ['name' => 'EV Parking', 'type' => 'Service', 'brands' => 'ChargeZone'],
            ['name' => 'Reserved Charging Slot', 'type' => 'Service', 'brands' => 'Statiq'],
            ['name' => 'Solar EV Charging', 'type' => 'Service', 'brands' => 'Tata Power Solar'],
            ['name' => 'Green Energy Charging', 'type' => 'Service', 'brands' => 'ChargeZone'],
            ['name' => 'Fleet EV Charging', 'type' => 'Service', 'brands' => 'Jio-bp Pulse'],
            ['name' => 'Commercial EV Charging', 'type' => 'Service', 'brands' => 'Tata Power'],
            ['name' => 'Charging Station Franchise', 'type' => 'Service', 'brands' => 'ChargeZone'],
            ['name' => 'EV Charging Consultation', 'type' => 'Service', 'brands' => 'Tata Power'],
            ['name' => 'Charging Equipment Installation', 'type' => 'Service', 'brands' => 'ABB'],
            ['name' => 'Charging Maintenance', 'type' => 'Service', 'brands' => 'Exicom'],
            ['name' => 'EV Charging App', 'type' => 'Service', 'brands' => 'Statiq, Jio-bp Pulse'],
            ['name' => 'Digital Payment', 'type' => 'Service', 'brands' => 'UPI, Paytm, PhonePe'],
            ['name' => 'GST Invoice', 'type' => 'Service', 'brands' => 'Charging Operator'],
            ['name' => 'Corporate Charging Plan', 'type' => 'Service', 'brands' => 'Tata Power'],
            ['name' => 'Home Installation Package', 'type' => 'Service', 'brands' => 'Tata Power Solar'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'Tractor Dealer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Mini Tractor', 'type' => 'Physical Product', 'brands' => 'Mahindra, Swaraj'],
            ['name' => 'Utility Tractor', 'type' => 'Physical Product', 'brands' => 'Mahindra, Sonalika'],
            ['name' => 'Compact Tractor', 'type' => 'Physical Product', 'brands' => 'Kubota, John Deere'],
            ['name' => 'Orchard Tractor', 'type' => 'Physical Product', 'brands' => 'New Holland, Kubota'],
            ['name' => 'Garden Tractor', 'type' => 'Physical Product', 'brands' => 'John Deere'],
            ['name' => '2WD Tractor', 'type' => 'Physical Product', 'brands' => 'Swaraj, Mahindra'],
            ['name' => '4WD Tractor', 'type' => 'Physical Product', 'brands' => 'John Deere, New Holland'],
            ['name' => 'Electric Tractor', 'type' => 'Physical Product', 'brands' => 'Cellestial E-Mobility, Sonalika Tiger Electric'],
            ['name' => 'Tractor Trailer', 'type' => 'Physical Product', 'brands' => 'Mahindra, Local Manufacturers'],
            ['name' => 'Tractor Trolley', 'type' => 'Physical Product', 'brands' => 'Local Manufacturers'],
            ['name' => 'Front Loader', 'type' => 'Physical Product', 'brands' => 'Mahindra, John Deere'],
            ['name' => 'Backhoe Attachment', 'type' => 'Physical Product', 'brands' => 'Mahindra'],
            ['name' => 'Rotavator', 'type' => 'Physical Product', 'brands' => 'Shaktiman, Fieldking'],
            ['name' => 'Cultivator', 'type' => 'Physical Product', 'brands' => 'Fieldking'],
            ['name' => 'Disc Harrow', 'type' => 'Physical Product', 'brands' => 'Shaktiman'],
            ['name' => 'Seed Drill', 'type' => 'Physical Product', 'brands' => 'Mahindra'],
            ['name' => 'Plough', 'type' => 'Physical Product', 'brands' => 'Fieldking'],
            ['name' => 'Thresher', 'type' => 'Physical Product', 'brands' => 'Mahindra'],
            ['name' => 'Sprayer', 'type' => 'Physical Product', 'brands' => 'ASPEE, Kisankraft'],
            ['name' => 'Tractor Tyres', 'type' => 'Physical Product', 'brands' => 'MRF, BKT, Apollo'],
            ['name' => 'Tractor Tubes', 'type' => 'Physical Product', 'brands' => 'MRF'],
            ['name' => 'Tractor Battery', 'type' => 'Physical Product', 'brands' => 'Exide, Amaron'],
            ['name' => 'Engine Oil', 'type' => 'Physical Product', 'brands' => 'Servo, Castrol CRB'],
            ['name' => 'Hydraulic Oil', 'type' => 'Physical Product', 'brands' => 'Servo'],
            ['name' => 'Coolant', 'type' => 'Physical Product', 'brands' => 'Castrol'],
            ['name' => 'Air Filter', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Fuel Filter', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Oil Filter', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Clutch Plate', 'type' => 'Physical Product', 'brands' => 'Valeo'],
            ['name' => 'Brake Parts', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'LED Work Light', 'type' => 'Physical Product', 'brands' => 'Philips'],
            ['name' => 'GPS Tracking System', 'type' => 'Physical Product', 'brands' => 'Ajjas'],
            ['name' => 'Tractor Seat', 'type' => 'Physical Product', 'brands' => 'Grammer'],
            ['name' => 'PTO Shaft', 'type' => 'Physical Product', 'brands' => 'Mahindra'],
            ['name' => 'Hydraulic Pump', 'type' => 'Physical Product', 'brands' => 'Mahindra'],
            ['name' => 'Drawbar', 'type' => 'Physical Product', 'brands' => 'Mahindra'],
            ['name' => 'Tool Box', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'Safety Triangle', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Tractor Cover', 'type' => 'Physical Product', 'brands' => 'Polco'],
            ['name' => 'Annual Maintenance Package', 'type' => 'Service', 'brands' => 'Mahindra, John Deere'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'Marine & Boat Dealer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Fishing Boat', 'type' => 'Physical Product', 'brands' => 'Yamaha Marine, Mercury Marine'],
            ['name' => 'Speed Boat', 'type' => 'Physical Product', 'brands' => 'Bayliner, Sea Ray'],
            ['name' => 'Motor Boat', 'type' => 'Physical Product', 'brands' => 'Yamaha Marine'],
            ['name' => 'Pontoon Boat', 'type' => 'Physical Product', 'brands' => 'Sun Tracker'],
            ['name' => 'Cabin Cruiser', 'type' => 'Physical Product', 'brands' => 'Bayliner'],
            ['name' => 'Yacht', 'type' => 'Physical Product', 'brands' => 'Azimut, Princess Yachts'],
            ['name' => 'Personal Watercraft (Jet Ski)', 'type' => 'Physical Product', 'brands' => 'Sea-Doo, Yamaha WaveRunner'],
            ['name' => 'Inflatable Boat', 'type' => 'Physical Product', 'brands' => 'Intex, Zodiac'],
            ['name' => 'Kayak', 'type' => 'Physical Product', 'brands' => 'Perception, Decathlon'],
            ['name' => 'Canoe', 'type' => 'Physical Product', 'brands' => 'Pelican'],
            ['name' => 'Row Boat', 'type' => 'Physical Product', 'brands' => 'Local Manufacturers'],
            ['name' => 'Outboard Motor', 'type' => 'Physical Product', 'brands' => 'Yamaha Marine, Mercury Marine'],
            ['name' => 'Inboard Engine', 'type' => 'Physical Product', 'brands' => 'Volvo Penta'],
            ['name' => 'Boat Trailer', 'type' => 'Physical Product', 'brands' => 'EZ Loader'],
            ['name' => 'Boat Battery', 'type' => 'Physical Product', 'brands' => 'Exide Marine, Trojan'],
            ['name' => 'Marine GPS', 'type' => 'Physical Product', 'brands' => 'Garmin Marine'],
            ['name' => 'Fish Finder', 'type' => 'Physical Product', 'brands' => 'Garmin, Lowrance'],
            ['name' => 'Marine Radio', 'type' => 'Physical Product', 'brands' => 'Icom'],
            ['name' => 'Marine Compass', 'type' => 'Physical Product', 'brands' => 'Garmin'],
            ['name' => 'Life Jacket', 'type' => 'Physical Product', 'brands' => 'Lalizas, Decathlon'],
            ['name' => 'Lifebuoy Ring', 'type' => 'Physical Product', 'brands' => 'Lalizas'],
            ['name' => 'Safety Flares', 'type' => 'Physical Product', 'brands' => 'Orion'],
            ['name' => 'Marine Fire Extinguisher', 'type' => 'Physical Product', 'brands' => 'Ceasefire'],
            ['name' => 'Boat Anchor', 'type' => 'Physical Product', 'brands' => 'Lewmar'],
            ['name' => 'Anchor Rope', 'type' => 'Physical Product', 'brands' => 'Local Brands'],
            ['name' => 'Dock Lines', 'type' => 'Physical Product', 'brands' => 'Local Brands'],
            ['name' => 'Boat Cover', 'type' => 'Physical Product', 'brands' => 'Taylor Made'],
            ['name' => 'Bimini Top', 'type' => 'Physical Product', 'brands' => 'Taylor Made'],
            ['name' => 'Boat Seat', 'type' => 'Physical Product', 'brands' => 'Springfield Marine'],
            ['name' => 'Steering Wheel', 'type' => 'Physical Product', 'brands' => 'Ultraflex'],
            ['name' => 'Marine Steering System', 'type' => 'Physical Product', 'brands' => 'SeaStar Solutions'],
            ['name' => 'Bilge Pump', 'type' => 'Physical Product', 'brands' => 'Rule'],
            ['name' => 'Boat Horn', 'type' => 'Physical Product', 'brands' => 'Marinco'],
            ['name' => 'Navigation Lights', 'type' => 'Physical Product', 'brands' => 'Hella Marine'],
            ['name' => 'Marine LED Lights', 'type' => 'Physical Product', 'brands' => 'Hella Marine'],
            ['name' => 'Marine Battery Charger', 'type' => 'Physical Product', 'brands' => 'NOCO'],
            ['name' => 'Boat Cleaning Kit', 'type' => 'Physical Product', 'brands' => 'Star Brite'],
            ['name' => 'Hull Polish', 'type' => 'Physical Product', 'brands' => 'Meguiar\'s Marine'],
            ['name' => 'Boat Maintenance Package', 'type' => 'Service', 'brands' => 'Yamaha Marine'],
            ['name' => 'Annual Marine Service', 'type' => 'Service', 'brands' => 'Mercury Marine'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'Aircraft Dealer / Aviation Services',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Private Jet', 'type' => 'Physical Product', 'brands' => 'Gulfstream, Bombardier, Dassault'],
            ['name' => 'Business Jet', 'type' => 'Physical Product', 'brands' => 'Cessna, Embraer'],
            ['name' => 'Light Aircraft', 'type' => 'Physical Product', 'brands' => 'Cessna, Diamond Aircraft'],
            ['name' => 'Single Engine Aircraft', 'type' => 'Physical Product', 'brands' => 'Cessna'],
            ['name' => 'Twin Engine Aircraft', 'type' => 'Physical Product', 'brands' => 'Beechcraft'],
            ['name' => 'Turboprop Aircraft', 'type' => 'Physical Product', 'brands' => 'ATR, Pilatus'],
            ['name' => 'Helicopter', 'type' => 'Physical Product', 'brands' => 'Airbus Helicopters, Bell'],
            ['name' => 'Charter Aircraft', 'type' => 'Service', 'brands' => 'JetSetGo, Club One Air'],
            ['name' => 'Air Ambulance', 'type' => 'Service', 'brands' => 'AirRescuers'],
            ['name' => 'Aircraft Leasing', 'type' => 'Service', 'brands' => 'Embraer, Bombardier'],
            ['name' => 'Aircraft Sales', 'type' => 'Service', 'brands' => 'Gulfstream'],
            ['name' => 'Aircraft Brokerage', 'type' => 'Service', 'brands' => 'Jetcraft'],
            ['name' => 'Aircraft Management', 'type' => 'Service', 'brands' => 'JetSetGo'],
            ['name' => 'Aircraft Maintenance', 'type' => 'Service', 'brands' => 'Air Works'],
            ['name' => 'Engine Overhaul', 'type' => 'Service', 'brands' => 'Pratt & Whitney, Rolls-Royce'],
            ['name' => 'Avionics Upgrade', 'type' => 'Service', 'brands' => 'Garmin Aviation, Honeywell'],
            ['name' => 'Aircraft Paint Service', 'type' => 'Service', 'brands' => 'Air Works'],
            ['name' => 'Interior Refurbishment', 'type' => 'Service', 'brands' => 'Jet Aviation'],
            ['name' => 'Pilot Training', 'type' => 'Service', 'brands' => 'CAE, Indira Gandhi Institute of Aeronautics'],
            ['name' => 'Flight Simulator Training', 'type' => 'Service', 'brands' => 'CAE'],
            ['name' => 'Ground Handling', 'type' => 'Service', 'brands' => 'Air India SATS'],
            ['name' => 'Aircraft Cleaning', 'type' => 'Service', 'brands' => 'Air Works'],
            ['name' => 'Hangar Rental', 'type' => 'Service', 'brands' => 'GMR Aviation'],
            ['name' => 'Aircraft Parking', 'type' => 'Service', 'brands' => 'GMR Aviation'],
            ['name' => 'Flight Planning', 'type' => 'Service', 'brands' => 'Garmin Aviation'],
            ['name' => 'Aviation Insurance', 'type' => 'Service', 'brands' => 'ICICI Lombard, Tata AIG'],
            ['name' => 'Flight Dispatch', 'type' => 'Service', 'brands' => 'Aviation Partners'],
            ['name' => 'Aviation Fuel', 'type' => 'Physical Product', 'brands' => 'IndianOil Aviation'],
            ['name' => 'Jet A1 Fuel', 'type' => 'Physical Product', 'brands' => 'IndianOil Aviation'],
            ['name' => 'Aviation Lubricants', 'type' => 'Physical Product', 'brands' => 'Shell Aviation'],
            ['name' => 'Aircraft Battery', 'type' => 'Physical Product', 'brands' => 'Concorde Battery'],
            ['name' => 'Aircraft Tyres', 'type' => 'Physical Product', 'brands' => 'Michelin Aircraft'],
            ['name' => 'ELT (Emergency Locator Transmitter)', 'type' => 'Physical Product', 'brands' => 'Kannad Aviation'],
            ['name' => 'Aviation Headset', 'type' => 'Physical Product', 'brands' => 'Bose Aviation, Lightspeed'],
            ['name' => 'Aviation GPS', 'type' => 'Physical Product', 'brands' => 'Garmin Aviation'],
            ['name' => 'Pilot Uniform', 'type' => 'Physical Product', 'brands' => 'Local Brands'],
            ['name' => 'Pilot Logbook', 'type' => 'Physical Product', 'brands' => 'ASA'],
            ['name' => 'Aviation Charts', 'type' => 'Physical Product', 'brands' => 'Jeppesen'],
            ['name' => 'Aircraft Spare Parts', 'type' => 'Physical Product', 'brands' => 'Boeing, Airbus'],
            ['name' => 'Annual Maintenance Contract', 'type' => 'Service', 'brands' => 'Air Works'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'RV / Camper Dealer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Class A Motorhome', 'type' => 'Physical Product', 'brands' => 'Winnebago, Thor Motor Coach'],
            ['name' => 'Class B Camper Van', 'type' => 'Physical Product', 'brands' => 'Winnebago, Hymer'],
            ['name' => 'Class C Motorhome', 'type' => 'Physical Product', 'brands' => 'Jayco, Thor'],
            ['name' => 'Travel Trailer', 'type' => 'Physical Product', 'brands' => 'Airstream, Forest River'],
            ['name' => 'Fifth Wheel Trailer', 'type' => 'Physical Product', 'brands' => 'Keystone RV'],
            ['name' => 'Pop-Up Camper', 'type' => 'Physical Product', 'brands' => 'Forest River'],
            ['name' => 'Camper Van', 'type' => 'Physical Product', 'brands' => 'Hymer'],
            ['name' => 'Off-Road Camper', 'type' => 'Physical Product', 'brands' => 'Bruder'],
            ['name' => 'Caravan', 'type' => 'Physical Product', 'brands' => 'Swift, Bailey'],
            ['name' => 'Tiny Home Trailer', 'type' => 'Physical Product', 'brands' => 'Escape Trailer'],
            ['name' => 'Camper Conversion Kit', 'type' => 'Physical Product', 'brands' => 'Reimo'],
            ['name' => 'RV Solar Panel', 'type' => 'Physical Product', 'brands' => 'Renogy'],
            ['name' => 'Solar Charge Controller', 'type' => 'Physical Product', 'brands' => 'Victron Energy'],
            ['name' => 'RV Battery', 'type' => 'Physical Product', 'brands' => 'Trojan, Exide'],
            ['name' => 'Lithium RV Battery', 'type' => 'Physical Product', 'brands' => 'Battle Born'],
            ['name' => 'RV Inverter', 'type' => 'Physical Product', 'brands' => 'Victron Energy'],
            ['name' => 'Water Tank', 'type' => 'Physical Product', 'brands' => 'Camco'],
            ['name' => 'Grey Water Tank', 'type' => 'Physical Product', 'brands' => 'Camco'],
            ['name' => 'Black Water Tank', 'type' => 'Physical Product', 'brands' => 'Camco'],
            ['name' => 'Portable Toilet', 'type' => 'Physical Product', 'brands' => 'Thetford'],
            ['name' => 'Cassette Toilet', 'type' => 'Physical Product', 'brands' => 'Thetford'],
            ['name' => 'RV Refrigerator', 'type' => 'Physical Product', 'brands' => 'Dometic'],
            ['name' => 'Portable Fridge', 'type' => 'Physical Product', 'brands' => 'Dometic'],
            ['name' => 'RV Air Conditioner', 'type' => 'Physical Product', 'brands' => 'Dometic'],
            ['name' => 'Awning', 'type' => 'Physical Product', 'brands' => 'Fiamma'],
            ['name' => 'Bike Rack', 'type' => 'Physical Product', 'brands' => 'Thule'],
            ['name' => 'Roof Rack', 'type' => 'Physical Product', 'brands' => 'Thule'],
            ['name' => 'Tow Hitch', 'type' => 'Physical Product', 'brands' => 'CURT'],
            ['name' => 'Trailer Hitch Lock', 'type' => 'Physical Product', 'brands' => 'Master Lock'],
            ['name' => 'Levelling Blocks', 'type' => 'Physical Product', 'brands' => 'Camco'],
            ['name' => 'RV Water Hose', 'type' => 'Physical Product', 'brands' => 'Camco'],
            ['name' => 'Sewer Hose Kit', 'type' => 'Physical Product', 'brands' => 'Camco'],
            ['name' => 'Power Cord', 'type' => 'Physical Product', 'brands' => 'Camco'],
            ['name' => 'Surge Protector', 'type' => 'Physical Product', 'brands' => 'Hughes Autoformers'],
            ['name' => 'Camping Chairs', 'type' => 'Physical Product', 'brands' => 'Coleman'],
            ['name' => 'Camping Table', 'type' => 'Physical Product', 'brands' => 'Coleman'],
            ['name' => 'BBQ Grill', 'type' => 'Physical Product', 'brands' => 'Weber'],
            ['name' => 'RV Cleaning Kit', 'type' => 'Physical Product', 'brands' => 'Meguiar\'s'],
            ['name' => 'RV Cover', 'type' => 'Physical Product', 'brands' => 'Classic Accessories'],
            ['name' => 'Annual RV Service', 'type' => 'Service', 'brands' => 'Winnebago Service'],
            ['name' => 'RV Maintenance Package', 'type' => 'Service', 'brands' => 'Thor Motor Coach'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'Golf Cart Dealer',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Electric Golf Cart', 'type' => 'Physical Product', 'brands' => 'Club Car, E-Z-GO, Yamaha Golf Cars'],
            ['name' => 'Petrol Golf Cart', 'type' => 'Physical Product', 'brands' => 'Yamaha Golf Cars'],
            ['name' => 'Lithium Golf Cart', 'type' => 'Physical Product', 'brands' => 'Club Car'],
            ['name' => '2 Seater Golf Cart', 'type' => 'Physical Product', 'brands' => 'Club Car, E-Z-GO'],
            ['name' => '4 Seater Golf Cart', 'type' => 'Physical Product', 'brands' => 'Club Car, Yamaha'],
            ['name' => '6 Seater Golf Cart', 'type' => 'Physical Product', 'brands' => 'E-Z-GO'],
            ['name' => '8 Seater Golf Cart', 'type' => 'Physical Product', 'brands' => 'Club Car'],
            ['name' => 'Utility Golf Cart', 'type' => 'Physical Product', 'brands' => 'Club Car Carryall'],
            ['name' => 'Cargo Golf Cart', 'type' => 'Physical Product', 'brands' => 'Club Car'],
            ['name' => 'Resort Golf Cart', 'type' => 'Physical Product', 'brands' => 'Yamaha Golf Cars'],
            ['name' => 'Hotel Golf Cart', 'type' => 'Physical Product', 'brands' => 'E-Z-GO'],
            ['name' => 'Airport Golf Cart', 'type' => 'Physical Product', 'brands' => 'Club Car'],
            ['name' => 'Industrial Utility Cart', 'type' => 'Physical Product', 'brands' => 'Club Car Carryall'],
            ['name' => 'Golf Cart Battery', 'type' => 'Physical Product', 'brands' => 'Trojan, Exide'],
            ['name' => 'Lithium Battery Pack', 'type' => 'Physical Product', 'brands' => 'RoyPow'],
            ['name' => 'Battery Charger', 'type' => 'Physical Product', 'brands' => 'Delta-Q'],
            ['name' => 'Golf Cart Tyres', 'type' => 'Physical Product', 'brands' => 'Carlisle'],
            ['name' => 'Golf Cart Wheels', 'type' => 'Physical Product', 'brands' => 'MODZ'],
            ['name' => 'Golf Cart Seat', 'type' => 'Physical Product', 'brands' => 'Club Car'],
            ['name' => 'Seat Cover', 'type' => 'Physical Product', 'brands' => 'Club Clean'],
            ['name' => 'Windshield', 'type' => 'Physical Product', 'brands' => 'Club Car'],
            ['name' => 'Roof Canopy', 'type' => 'Physical Product', 'brands' => 'Club Car'],
            ['name' => 'Side Mirror', 'type' => 'Physical Product', 'brands' => 'MODZ'],
            ['name' => 'LED Headlights', 'type' => 'Physical Product', 'brands' => 'MODZ'],
            ['name' => 'Tail Lights', 'type' => 'Physical Product', 'brands' => 'MODZ'],
            ['name' => 'Horn Kit', 'type' => 'Physical Product', 'brands' => 'MODZ'],
            ['name' => 'Turn Signal Kit', 'type' => 'Physical Product', 'brands' => 'MODZ'],
            ['name' => 'Dashboard Kit', 'type' => 'Physical Product', 'brands' => 'MODZ'],
            ['name' => 'USB Charger', 'type' => 'Physical Product', 'brands' => 'MODZ'],
            ['name' => 'Bluetooth Speaker', 'type' => 'Physical Product', 'brands' => 'JBL'],
            ['name' => 'Storage Basket', 'type' => 'Physical Product', 'brands' => 'Club Car'],
            ['name' => 'Rear Seat Kit', 'type' => 'Physical Product', 'brands' => 'MadJax'],
            ['name' => 'Cooler Box', 'type' => 'Physical Product', 'brands' => 'Coleman'],
            ['name' => 'Lift Kit', 'type' => 'Physical Product', 'brands' => 'MadJax'],
            ['name' => 'Suspension Kit', 'type' => 'Physical Product', 'brands' => 'MadJax'],
            ['name' => 'Brake Kit', 'type' => 'Physical Product', 'brands' => 'Club Car'],
            ['name' => 'Steering Wheel', 'type' => 'Physical Product', 'brands' => 'MODZ'],
            ['name' => 'Floor Mat', 'type' => 'Physical Product', 'brands' => 'Club Clean'],
            ['name' => 'Golf Cart Cover', 'type' => 'Physical Product', 'brands' => 'Classic Accessories'],
            ['name' => 'Annual Maintenance Package', 'type' => 'Service', 'brands' => 'Club Car'],
        ]
    ],
    [
        'category' => 'Automotive',
        'sub_category' => 'Automotive Tools & Equipment Store',
        'has_business_type' => 1,
        'products' => [
            ['name' => 'Socket Set', 'type' => 'Physical Product', 'brands' => 'Stanley, Taparia'],
            ['name' => 'Spanner Set', 'type' => 'Physical Product', 'brands' => 'Stanley, Taparia'],
            ['name' => 'Screwdriver Set', 'type' => 'Physical Product', 'brands' => 'Bosch, Stanley'],
            ['name' => 'Torque Wrench', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'Impact Wrench', 'type' => 'Physical Product', 'brands' => 'Bosch, DeWalt'],
            ['name' => 'Hydraulic Jack', 'type' => 'Physical Product', 'brands' => 'Michelin, Blackhawk'],
            ['name' => 'Trolley Jack', 'type' => 'Physical Product', 'brands' => 'Michelin'],
            ['name' => 'Jack Stand', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'Engine Crane', 'type' => 'Physical Product', 'brands' => 'Torin'],
            ['name' => 'Engine Stand', 'type' => 'Physical Product', 'brands' => 'Torin'],
            ['name' => 'Transmission Jack', 'type' => 'Physical Product', 'brands' => 'Torin'],
            ['name' => 'Wheel Balancer', 'type' => 'Physical Product', 'brands' => 'Bosch, Launch'],
            ['name' => 'Wheel Alignment Machine', 'type' => 'Physical Product', 'brands' => 'Bosch, Launch'],
            ['name' => 'Tyre Changer Machine', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Air Compressor', 'type' => 'Physical Product', 'brands' => 'Stanley, Atlas Copco'],
            ['name' => 'Impact Air Gun', 'type' => 'Physical Product', 'brands' => 'Ingersoll Rand'],
            ['name' => 'Spray Paint Gun', 'type' => 'Physical Product', 'brands' => 'Devilbiss'],
            ['name' => 'Pressure Washer', 'type' => 'Physical Product', 'brands' => 'Kärcher, Bosch'],
            ['name' => 'Steam Cleaner', 'type' => 'Physical Product', 'brands' => 'Kärcher'],
            ['name' => 'Vacuum Cleaner', 'type' => 'Physical Product', 'brands' => 'Kärcher'],
            ['name' => 'Battery Charger', 'type' => 'Physical Product', 'brands' => 'Bosch, CTEK'],
            ['name' => 'Jump Starter', 'type' => 'Physical Product', 'brands' => 'NOCO'],
            ['name' => 'Battery Tester', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'OBD Scanner', 'type' => 'Physical Product', 'brands' => 'Launch, Bosch'],
            ['name' => 'Diagnostic Scanner', 'type' => 'Physical Product', 'brands' => 'Autel, Launch'],
            ['name' => 'Multimeter', 'type' => 'Physical Product', 'brands' => 'Fluke'],
            ['name' => 'Timing Light', 'type' => 'Physical Product', 'brands' => 'Innova'],
            ['name' => 'Compression Tester', 'type' => 'Physical Product', 'brands' => 'OTC'],
            ['name' => 'Brake Bleeder Kit', 'type' => 'Physical Product', 'brands' => 'Mityvac'],
            ['name' => 'Oil Drain Pan', 'type' => 'Physical Product', 'brands' => 'Lisle'],
            ['name' => 'Grease Gun', 'type' => 'Physical Product', 'brands' => 'Lincoln'],
            ['name' => 'Torque Angle Gauge', 'type' => 'Physical Product', 'brands' => 'GearWrench'],
            ['name' => 'Bearing Puller', 'type' => 'Physical Product', 'brands' => 'SKF'],
            ['name' => 'Gear Puller', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'Ball Joint Separator', 'type' => 'Physical Product', 'brands' => 'OTC'],
            ['name' => 'Bearing Press Kit', 'type' => 'Physical Product', 'brands' => 'SKF'],
            ['name' => 'Welding Machine', 'type' => 'Physical Product', 'brands' => 'ESAB'],
            ['name' => 'Plasma Cutter', 'type' => 'Physical Product', 'brands' => 'ESAB'],
            ['name' => 'Bench Grinder', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Angle Grinder', 'type' => 'Physical Product', 'brands' => 'Bosch, Makita'],
            ['name' => 'Drill Machine', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Heat Gun', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Rivet Gun', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'Creeper Seat', 'type' => 'Physical Product', 'brands' => 'Torin'],
            ['name' => 'Tool Cabinet', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'Tool Chest', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'Workshop Trolley', 'type' => 'Physical Product', 'brands' => 'Stanley'],
            ['name' => 'Magnetic Parts Tray', 'type' => 'Physical Product', 'brands' => 'GearWrench'],
            ['name' => 'Inspection Light', 'type' => 'Physical Product', 'brands' => 'Philips'],
            ['name' => 'Work Lamp', 'type' => 'Physical Product', 'brands' => 'Philips'],
            ['name' => 'Safety Gloves', 'type' => 'Physical Product', 'brands' => 'Honeywell'],
            ['name' => 'Safety Goggles', 'type' => 'Physical Product', 'brands' => '3M'],
            ['name' => 'Welding Helmet', 'type' => 'Physical Product', 'brands' => 'ESAB'],
            ['name' => 'Mechanic Tool Kit', 'type' => 'Physical Product', 'brands' => 'Bosch, Stanley'],
            ['name' => 'Garage Equipment Package', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Workshop Lift', 'type' => 'Physical Product', 'brands' => 'Rotary Lift'],
            ['name' => 'Two Post Lift', 'type' => 'Physical Product', 'brands' => 'Rotary Lift'],
            ['name' => 'Four Post Lift', 'type' => 'Physical Product', 'brands' => 'Rotary Lift'],
            ['name' => 'Engine Diagnostic Kit', 'type' => 'Physical Product', 'brands' => 'Bosch'],
            ['name' => 'Automotive Workshop Combo', 'type' => 'Physical Product', 'brands' => 'Bosch, Stanley'],
        ]
    ]
];

foreach ($data as $block) {
    // 1. Get/Create Category
    $category = BusinessCategory::firstOrCreate(
        ['name' => $block['category']],
        ['slug' => Str::slug($block['category']), 'status' => 1]
    );

    // 2. Get/Create Sub Category
    $subCategory = BusinessSubCategory::firstOrCreate(
        [
            'name' => $block['sub_category'],
            'business_category_id' => $category->id
        ],
        [
            'slug' => Str::slug($block['sub_category']),
            'has_business_type' => $block['has_business_type'],
            'status' => 1
        ]
    );

    // 3. Insert Products
    foreach ($block['products'] as $p) {
        $productType = ProductType::firstOrCreate(
            ['name' => $p['type']],
            ['slug' => Str::slug($p['type']), 'status' => 1]
        );

        $brandIds = [];
        if (!empty($p['brands']) && $p['brands'] !== 'None') {
            $brandsArr = array_map('trim', explode(',', $p['brands']));
            foreach ($brandsArr as $b) {
                $brandObj = Brand::firstOrCreate(
                    ['name' => $b],
                    ['slug' => Str::slug($b), 'status' => 1]
                );
                $brandIds[] = (string)$brandObj->id;
            }
        }

        BusinessProduct::updateOrCreate(
            [
                'name' => $p['name'],
                'business_category_id' => $category->id,
                'business_sub_category_id' => $subCategory->id,
            ],
            [
                'slug' => Str::slug($p['name']),
                'product_type_id' => $productType->id,
                'brand_id' => $brandIds, // the cast handles array to json automatically!
                'status' => 1,
            ]
        );
    }
}

echo "Successfully seeded Data for Automotive Sub Categories 27.10, 27.11, 27.14, 27.15, 27.16, 27.17, 27.18, and 27.19.\n";
